### ISSUE TITLE
Legacy installation does not work with webpack

### ISSUE THREAD

**Issue by maxkopych** [bootstrap-vue-next/bootstrap-vue-next#1038]
Current version what I have v0.8.4 with webpack. 

I followed [your instruction](https://github.com/bootstrap-vue/bootstrap-vue-next/tree/main/apps/docs/docs/getting-started#legacy-installation)

But getting error on yarn serve:
```
ERROR in ./node_modules/bootstrap-vue-next/dist/bootstrap-vue-next.mjs 6317:17-18
Can't import the named export 'withCtx' from non EcmaScript module (only default export is available)
```

**Comment by VividLemon** [comment]
https://github.com/vuejs/pinia/issues/675#issuecomment-919544784
