### ISSUE TITLE
B-Table: Pre-Sorting

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1061]
in bootstrap vue I used the props: "sortby" and "sortdesc" to presort the table. 
All columns had "sortable: false" set. 
Although the documentation says: "Setting sort-by to a column that is not defined in the fields as sortable will result in the table not being sorted." it worked anyway. 
It no longer works in Bootstrap vue next. 
you really have to set the sorting column to "sortable: true". 
Unfortunately, you can no longer pre-sort the table. That would be great though, because then I can pre-sort the table without making a column sortable. 
Now I have to pre-sort the table myself. 

**Suggested solution: 
the two props "sortby" and "sortdesc" should be used for pre-sorting without making columns sortable. 
This should be relatively quick and easy to install. thanks in advance**

**Comment by VividLemon** [comment]
Given that this is a _bug_ according to the documentation, I am obligated to fix it. You will need to sort it before it reaches BTable. Will be fixed in 0.15
