### ISSUE TITLE
[0.8.6] Collapse closes automatically

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1067]
look at this example. 
https://stackblitz.com/edit/vue-jgaymx?file=src/components/Liste.vue

click on the right blank rectangle->print->alert opens->click ok, alert closes and also the collapse group -that is not correct
print with alert is only for test purpose, in production it is a contextmenu with many items in it.
the behaviour has nothing to do with the alert dialog.
**Important: in version 0.7.3 and also in bootstrap vue works this example**
i tried prevent, prevent.stop - nothing helped

look at the DOM after the alert-dialog closed
a class=card-link has aria-expanded=true set - that is wrong, it should has aria-expanded=false
div id=bodymonth_1 has class=collapse - that is okay

![image](https://user-images.githubusercontent.com/112922199/234184421-5b7d3bcc-89be-48f0-8679-969f8c315486.png)

**Comment by xvaara** [comment]
@VividLemon how should we handle this? BDropdownItem closes the collapse that it's in. That's for the navbar functionality. Should we also provide/inject from the navbar and only close in that case we inside navbar, or should there be an prop closeCollapseOnClick or something like that. Or ignore-collapse maybe?

**Comment by VividLemon** [comment]
> Should we also provide/inject from the navbar and only close in that case we inside navbar

Yes.

**Comment by VividLemon** [comment]
Should be fixed
