### ISSUE TITLE
b-form-select unexpected applied class in select element

### ISSUE THREAD

**Issue by rubebop** [bootstrap-vue-next/bootstrap-vue-next#1071]
One of the nice things about BootstrapVue (w/ Vue 2) is/was its "out of the box" good look.

Moving to bootstrap-vue-next (w/ Vue 3) has resulted in a lot of unexpected differences.

Using the `b-form-select` component  without applying any explicit class looks now rather ugly compared to "before":
![b-form-select](https://user-images.githubusercontent.com/90906012/235177423-e2ade485-e9c9-4077-96cd-8a306c340b22.PNG)

Inspecting the applied class in the `select` element I see that before the `custom-select` class was applied while with BootstrapVue the `form-select` class is applied.
(If I apply the `form-control` Bootstrap class to a `select` element, it looks also good.)

Am I missing something? Is there a way to make it look as it was without having each time to add a class?

**Comment by VividLemon** [comment]
I think you're missing the required css files. You should review the documentation and try again.

**Comment by rubebop** [comment]
Thanks for your answer. I'm still trying to figure this out: I tried to follow each step of the [installation instructions](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html) and I simply don't understand where the problem comes from.

If I compare a `b-form-select` element from the [doc](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-select.html) to such an element in my project I can see that in both cases the `form-select` class is being applied to the `select` element but the corresponding style is missing in my project. Does someone have an idea why that might be?
![BV-form-select](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/90906012/217d981d-2b55-47a2-8ebb-813e65d0a2f1)

**Comment by rubebop** [comment]
I beg your pardon for the confusion, since I did some back-and-forth version installs I forgot to re-update the Boostrap version to 5. That solved the issue.
