### ISSUE TITLE
[0.8.6] BPopover next Problems 

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1072]
### BPopover almost doesn't work at all in version 0.8.6! 
**in version 0.7.3 it worked like in bootstrap-vue. 
in 0.8.6 the props "triggers" and "show" are missing.** 
I use these two methods to show popover automatically with "triggers='hover'" or 
manually with "triggers='manual" and ":show='true'". 
Both don't work at all. 
whether the new library "floatui" was such a good idea ?!

please check that the documentation is working again. 
we cannot and do not want to guess what the individual components can and cannot do. 
By the way, the popularity of the product falls and rises with the documentation! 
Even the best tool is useless if there is no documentation

**Comment by VividLemon** [comment]
Instead of complaining about issues, you could find solutions. You were not forced to use this _pre production_ library. Your insistence on complaining about every aspect of an unfinished library is the reason people hate working on foss. Please consider this a written warning that if you continue to be disrespectful, demanding for help and hating the direction of the library, your posts will be locked and hidden. If you are unsatisfied, you are free to create your own fork of the project. If you are unsatisfied, you can sit on version 0.7. Alternatively, you volunteer your time just like everyone else on the project and create a pull request to fix the issues yourself. Nobody here works on your time, we are all unpaid volunteers that work on our own schedule and have our own jobs and own lives.

**Comment by aki77** [comment]
@susanne99 

You can find the 0.8.6 props definition by reading the source.
https://github.com/bootstrap-vue/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BPopover.vue#L105-L143

It appears that `show` prop has been changed to `v-model` and `triggers='manual'` to `manual`.

**Comment by susanne99** [comment]
thanks four your help.
I found the interface and can read it (I also work as an it trainer at the university and teach typescript - it doesn't matter). 
As I said, I don't want to guess what kind of functionality is behind each prop

**Comment by susanne99** [comment]
I know that, of course I appreciate your commitment. I'm currently converting a relatively large app (over 200 components) and I'm already using a lot of technology. I've known VUE and Bootstrap-Vue since the beginning. Of course I try to analyze all problems and create reproducible examples for you. But that's not so easy, because the components are usually embedded in others, and they could behave differently than when they're detached.

 

Gesendet: Samstag, 29. April 2023 um 07:27 Uhr
Von: "Issayah" ***@***.***>
An: "bootstrap-vue/bootstrap-vue-next" ***@***.***>
Cc: "susanne99" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [bootstrap-vue/bootstrap-vue-next] [0.8.6] BPopover next Problems (Issue #1072)


 

Instead of complaining about issues, you could find solutions. You were not forced to use this pre production library. Your insistence on complaining about every aspect of an unfinished library is the reason people hate working on foss. Please consider this a written warning that if you continue to be disrespectful, demanding for help and hating the direction of the library, your posts will be locked and hidden. If you are unsatisfied, you are free to create your own fork of the project. If you are unsatisfied, you can sit on version 0.7. Alternatively, you volunteer your time just like everyone else on the project and create a pull request to fix the issues yourself. Nobody here works on your time, we are all unpaid volunteers that work on our own schedule and have our own jobs and own lives.

**Comment by VividLemon** [comment]
I really don't recommend converting a large application. Things get broken and things are subject to change from time to time. If you're fine with the extra work, and the application isn't too sensitive, then its fine. But obviously there are issues.
