### ISSUE TITLE
[0.8.6] B-Form-Input: @change event not fired anymore

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1089]
take a look at this example:

https://stackblitz.com/edit/vue-hygehs?file=src/components/testform.vue

**Comment by VividLemon** [comment]
Strange

**Comment by susanne99** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

_The input event is fired every time the value of the element [change](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event)s. This is unlike the change event, which only fires when the value is committed, such as by pressing the enter key, selecting a value from a list of options, and the like._

**Comment by soorajsprakash** [comment]
Here, in either @update or @input, any way to track the previous selected value?

**Comment by VividLemon** [comment]
For my future reference:
It was caused by this diff:
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/52bd6265-19ce-41f8-bf65-2213fc1be19f)

This code seems like a bug. 

Investigate the relationship of change/input/blur & lazy

**Comment by VividLemon** [comment]
I made a change attempting to fix the issue. Be vigilant of my changes, as the code for this is a bit weird, and the original Bootstrap-vue code is no help. It's basically a reverse engineer job by looking at https://bootstrap-vue.org/play and seeing how it behaves.
