### ISSUE TITLE
[0.8.x] BFormRadio Hydration Bug

### ISSUE THREAD

**Issue by brtinney** [bootstrap-vue-next/bootstrap-vue-next#1092]
**Describe the bug.**
A checked radio button will become unchecked during hydration using `BFormRadio` or `BFormRadioGroup`.

**To Reproduce.**
Use SSR (e.g. Nuxt), reload a page with a `BFormRadio` element. Watch as initial SSR render shows item checked, and then it becomes unchecked at the end of the page fully loading (hydration). By comparison, recreating the DOM natively behaves fine.
```vue
          <!-- Checked option will become unchecked after re-rendered during hydration -->
          <b-form-radio-group
            v-model="sortOn"
            :options="options"
            buttons
            button-variant="outline-primary"
          />
          
          <!-- Checked option will remain checked after re-rendered during hydration -->
          <div class="btn-group btn-group-md bv-no-focus-ring">
            <template v-for="item in options" :key="`sortOn-${item.value}`">
              <input
                type="radio"
                :id="`sortOn-${item.value}`"
                :checked="item.value === sortOn"
                class="btn-check"
                :value="item.value"
              />
              <label
                :for="`sortOn-${item.value}`"
                class="btn btn-outline-primary"
                >{{ item.text }}</label
              >
            </template>
          </div>
``` 

**Expected behavior.**
SSR and client-side rendering work fine separately, hydration shouldn't cause the `checked` property to switch to false.

**Environment:**
- OS: Linux
- Package Version: 0.8.8
- Npm/Yarn/Pnpm Version: yarn@3.5.0

**Comment by VividLemon** [comment]
This reproduction isn't fully usable. I'm going to assume it works
