### ISSUE TITLE
b-table sorting not working

### ISSUE THREAD

**Issue by pbriss** [bootstrap-vue-next/bootstrap-vue-next#1099]
**Describe the bug.** Clicking on the table column header does not sort the column as intended

**To Reproduce.** Click on table header

**Expected behavior.** Should sort based on TableFields that have been specified as `sortable`. Note that the data does get sorted based on the sort-by field but I can't toggle from asc to desc using the click event on column header.

**Screenshots.**

<img width="745" alt="image" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/4909345/20c6ea9d-a245-498b-963a-c44831ece167">

![May-15-2023 14-01-34](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/4909345/6702d28a-017b-4eaa-8088-dca72525e07b)
Not apparent on my screenshot but I am trying to click on the header.

**Environment (please complete the following information):**

- OS: MacOS Ventura 13.2.1
- Package Version: ^0.8.11
- Npm/Yarn/Pnpm Version: yarn@1.22.19

**Comment by MoskalenkoM** [comment]
selectable, select-mode not working correctly

**Comment by Alexbrazdasilva** [comment]
The sort-desc property is required for this implementation to work.

```vue
<template>
  <b-table 
    v-model:sort-desc="sortDesc"
    :items="users"
    :fields="fields"
    sort-by="email"
  />
</template>
<script setup lang="ts">
import type { TableField } from 'src/types'
import { ref } from 'vue'

const sortDesc = ref(false)
const users = ref<{email: string}[]>([
  {email: 'a@gmail.com'},
  {email: 'b@gmail.com'},
  {email: 'c@gmail.com'},
])

const fields = ref<TableField[]>([{ key: 'email', label: 'Email', sortable: true }])
</script>

```

**Comment by stevemandl** [comment]
why does this work
```vue
<template>
  <b-table 
    v-model:sort-desc="sortDesc"
    v-model:sort-by="sortBy"
    :items="users"
    :fields="fields"
  />
</template>
<script setup lang="ts">
import type { TableField } from 'src/types'
import { ref } from 'vue'

const sortDesc = ref(false)
const sortBy = ref("email")
const users = ref<{email: string, name: string}[]>([
  {email: 'a@gmail.com', name: 'Anna'},
  {email: 'b@gmail.com', name: 'Fred Bankcroft'},
  {email: 'c@gmail.com', name: 'Edna Crawford'},
])

const fields: TableField[] = [
{ key: 'email', label: 'Email', sortable: true },
{ key: 'name', label: 'Full Name', sortable: true },
]
</script>
```
but this doesn't:
```vue
<template>
  <b-table 
    :sort-desc="sortDesc"
    :sort-by="sortBy"
    :items="users"
    :fields="fields"
  />
</template>
<script setup lang="ts">
import type { TableField } from 'src/types'
import { ref } from 'vue'

const sortDesc = ref(false)
const sortBy = ref("email")
const users = ref<{email: string, name: string}[]>([
  {email: 'a@gmail.com', name: 'Anna'},
  {email: 'b@gmail.com', name: 'Fred Bankcroft'},
  {email: 'c@gmail.com', name: 'Edna Crawford'},
])

const fields: TableField[] = [
{ key: 'email', label: 'Email', sortable: true },
{ key: 'name', label: 'Full Name', sortable: true },
]
</script>
```
I think the latter works in bootstrap-vue

**Comment by VividLemon** [comment]
> why does this work
> 
> ```
> <template>
>   <b-table 
>     v-model:sort-desc="sortDesc"
>     v-model:sort-by="sortBy"
>     :items="users"
>     :fields="fields"
>   />
> </template>
> <script setup lang="ts">
> import type { TableField } from 'src/types'
> import { ref } from 'vue'
> 
> const sortDesc = ref(false)
> const sortBy = ref("email")
> const users = ref<{email: string, name: string}[]>([
>   {email: 'a@gmail.com', name: 'Anna'},
>   {email: 'b@gmail.com', name: 'Fred Bankcroft'},
>   {email: 'c@gmail.com', name: 'Edna Crawford'},
> ])
> 
> const fields: TableField[] = [
> { key: 'email', label: 'Email', sortable: true },
> { key: 'name', label: 'Full Name', sortable: true },
> ]
> </script>
> ```
> 
> but this doesn't:
> 
> ```
> <template>
>   <b-table 
>     :sort-desc="sortDesc"
>     :sort-by="sortBy"
>     :items="users"
>     :fields="fields"
>   />
> </template>
> <script setup lang="ts">
> import type { TableField } from 'src/types'
> import { ref } from 'vue'
> 
> const sortDesc = ref(false)
> const sortBy = ref("email")
> const users = ref<{email: string, name: string}[]>([
>   {email: 'a@gmail.com', name: 'Anna'},
>   {email: 'b@gmail.com', name: 'Fred Bankcroft'},
>   {email: 'c@gmail.com', name: 'Edna Crawford'},
> ])
> 
> const fields: TableField[] = [
> { key: 'email', label: 'Email', sortable: true },
> { key: 'name', label: 'Full Name', sortable: true },
> ]
> </script>
> ```
> 
> I think the latter works in bootstrap-vue

BTable isn't allowed to mutate the sortDesc or sortBy. If they were doing this in the way you describe, it is an antipattern.

Though it was an anti pattern in Vue 2, I don't think you're even allowed to do it in Vue 3. I think it may error on you if you do.

**Comment by VividLemon** [comment]
@stevemandl https://play.vuejs.org/#eNpVkD9vAyEMxb+Ky3KJ1Ib9RCJVXTp268IS5bgTEmAE3C2I7x4D+bv52c+/h8ns2/vDtio2MhEvQfsEUaXVn6TT1mNIkCGoGQrMAS0MZB0eox+0/tY/8CoqicbSXdDFBDYucKzru+FXGYPwj8FMH8NeOsF7GuWQSMp6c06KFICY9NYKEC1gnBGPkhFMMuB9kjPJUpqdd7/gDwr7ZPfX1Lue9EC25qaCNrXza4Lty+KkDEVQUI+ovo5t1RugtV6/CszZLbSdomTNMalZO/UX0EeRiTlCTEG7pZx2+w683c7KFXEOhX0=

**Comment by Alexbrazdasilva** [comment]
It really is an anti pattern. Child components cannot change parent component properties, at least not directly. It is possible to emit an event in the child component and listen to it from the parent component and from there perform the state change. Best way: https://vuejs.org/guide/components/v-model.html#multiple-v-model-bindings

**Comment by VividLemon** [comment]
> The sort-desc property is required for this implementation to work.
> 
> ```
> <template>
>   <b-table 
>     v-model:sort-desc="sortDesc"
>     :items="users"
>     :fields="fields"
>     sort-by="email"
>   />
> </template>
> <script setup lang="ts">
> import type { TableField } from 'src/types'
> import { ref } from 'vue'
> 
> const sortDesc = ref(false)
> const users = ref<{email: string}[]>([
>   {email: 'a@gmail.com'},
>   {email: 'b@gmail.com'},
>   {email: 'c@gmail.com'},
> ])
> 
> const fields = ref<TableField[]>([{ key: 'email', label: 'Email', sortable: true }])
> </script>
> ```

I never realized before, but I can make this optional. This should be included in my next personal release.

**Comment by VividLemon** [comment]
> > The sort-desc property is required for this implementation to work.
> > ```
> > <template>
> >   <b-table 
> >     v-model:sort-desc="sortDesc"
> >     :items="users"
> >     :fields="fields"
> >     sort-by="email"
> >   />
> > </template>
> > <script setup lang="ts">
> > import type { TableField } from 'src/types'
> > import { ref } from 'vue'
> > 
> > const sortDesc = ref(false)
> > const users = ref<{email: string}[]>([
> >   {email: 'a@gmail.com'},
> >   {email: 'b@gmail.com'},
> >   {email: 'c@gmail.com'},
> > ])
> > 
> > const fields = ref<TableField[]>([{ key: 'email', label: 'Email', sortable: true }])
> > </script>
> > ```
> 
> I never realized before, but I can make this optional. This should be included in my next personal release.

At which point I will close this as completed
