### ISSUE TITLE
Invalid prop: type check failed for prop "toggleable"

### ISSUE THREAD

**Issue by StirStudios** [bootstrap-vue-next/bootstrap-vue-next#1114]
This is only a warning but it seems we need to update the prop types to accept strings for "toggleable":

[Vue warn]: Invalid prop: type check failed for prop "toggleable". Expected Boolean | Object, got String with value "xxl". Also it makes sense to add xxl as well for the doc options.

**Comment by VividLemon** [comment]
Out of everything you chose to exclude the component you're expecting this behavior from 🤣

**Comment by StirStudios** [comment]
Ah perhaps the code is incorrect then. This is a migration from bootstrap-vue:

`  <b-navbar
    id="main-navbar"
    toggleable="xxl"
    variant="light"
    class="shadow-lg"
    :container="true"
    :class="{ 'navbar--hidden': !showNavbar }"
  >`

So this works in previous Nuxt 2 setup with bootstrap-vue. Also it does work without issue!

**Comment by VividLemon** [comment]
This code has some issues that are on our end, and some that exist outside of our scope. 

"xxl" was incorrectly not an allowed value. I reviewed the bootstrap documentation, and it has been fixed. 

The issue with the code was the definition 
```ts
toggleable?: boolean | Omit<Breakpoint, 'xxl'> // <- compiler inferred that this was an object. 
```
When it should have been 
```ts
toggleable?: boolean | Exclude<Breakpoint, 'xxl'>
```

**Comment by StirStudios** [comment]
Great thanks for being on it! @VividLemon Thanks also for working so hard.
