### ISSUE TITLE
BToast default options

### ISSUE THREAD

**Issue by tada5hi** [bootstrap-vue-next/bootstrap-vue-next#1118]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

It would be great to define global default options for the BToast component, to set the **pos** to top-center for example.

**Describe the solution you would like.** A clear and concise description of what you want to happen

overrite defaults on plugin installation

**Describe alternatives you have considered.** A clear and concise description of any alternative solutions or features you've considered

**Additional context.** Add any other context or screenshots about the feature request here

**Comment by tada5hi** [comment]
@VividLemon i can create a pr for that if you want ?

**Comment by VividLemon** [comment]
Nothing has defaults, so go ahead and show me your implementation

**Comment by makroxyz** [comment]
@tada5hi I need the same, for example, for BModal:

```vue
app.use(BootstrapVue3, { BModal: { cancelTitle: 'MyLabel' } })
```

**Comment by tada5hi** [comment]
> @tada5hi I need the same, for example, for BModal:
> 
> ```vue
> app.use(BootstrapVue3, { BModal: { cancelTitle: 'MyLabel' } })
> ```

I will try this weekend or early next week to be able to make a first proposal

**Comment by makroxyz** [comment]
@tada5hi Hi! Any news about your proposal?

**Comment by VividLemon** [comment]
Moving this to https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1607
