### ISSUE TITLE
Offcanvas responsive issues

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1153]
While developing the documentation, it became apparent that there is an issue with attempting to use responsive, and model value together can cause hydration issues. Specifically if model value is true, and then you try to use responsive at the same time. 

So, we need to think about some way to fix all problems at once while retaining the model value, and SSR compatibility.

**Comment by phlegx** [comment]
Hi @VividLemon!

I get a Vue warn with `b-offcanvas` in the client console:

```log
[Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM: #text "\n    " (text) 
  at <BaseTransition mode=undefined onBeforeEnter=fn<onBeforeEnter> onAfterEnter=fn<x>  ... > 
  at <Transition mode=undefined css=true name=""  ... > 
  at <BTransition no-fade=true trans-props= 
Object { enterToClass: "showing", enterFromClass: "", leaveToClass: "hiding show", leaveFromClass: "show" }
 onBeforeEnter=fn<O>  ... > 
  at <BOffcanvas class="lb-header-oc" id="lb-header-oc" modelValue=true  ... >
  ...
```

Can this help to find a fix?

**Comment by phlegx** [comment]
Could an own teleport wrapper node be a solution instead of teleport to body?

```html
<body>
  <div id="app">...</div>
  <div id="teleports"><!-- target teleports here --></div>
</body>
```

https://github.com/vuejs/core/issues/5242#issuecomment-1129829701

**Comment by phlegx** [comment]
@VividLemon like described in the official [documentation of vue](https://vuejs.org/guide/scaling-up/ssr.html#teleports), we should consider to use an own DOM node:

_Avoid targeting body when using Teleports and SSR together - usually, <body> will contain other server-rendered content which makes it impossible for Teleports to determine the correct starting location for hydration. Instead, prefer a dedicated container, e.g. `<div id="teleported"></div>` which contains only teleported content._

Every bootstrap-vue component, that uses teleport, can be configured (`:to=`). Default is `body` and SSR deployments need to set teleport `:to=` to `#teleported`.

We have two possible solutions:

1. Teleport components are rendered only on client side (no hydration node mismatch).

```html
<ClientOnly>
  <Teleport to="body">
    ...
  </Teleport>
</ClientOnly> 
```

3. Required SSR rendering of teleport components, by using a unique DOM node outside app node (solves hydration node mismatch).

```html
<Teleport to="#teleported">
  ...
</Teleport>
```

with `index.html` like:

```html
...
<body>
  <div id="app"></div>
  <div id="teleported"></div>
</body>
```

SSR rendering does something like:

```js
teleported = context.teleports['#teleported']
...
// Replace <div id="teleported"> with <div id="teleported">${teleported}
```

**Comment by StirStudios** [comment]
As always @VividLemon you describe the issue in great detail so we can understand the issue at hand!

Is tthere anything here that sparks a solution:
https://github.com/react-bootstrap/react-bootstrap/pull/6380/commits/ee779c74d16ffc10e0eb0a749bf5a12d9ababdf7
https://github.com/react-bootstrap/react-bootstrap/pull/6380

**Comment by VividLemon** [comment]
I believe I may have a solution

**Comment by StirStudios** [comment]
Of course you have, you are a rockstar!

**Comment by VividLemon** [comment]
I won't be able to release any of my fixes until https://github.com/qmhc/vite-plugin-dts/issues/218#issuecomment-1577287944 and my branch are fixed.

**Comment by StirStudios** [comment]
Got it, regardless, progress is key, and awesome to here. I just found those links and thought they might be useful!
