### ISSUE TITLE
[0.9.4] nothing worked - "tons" of TS2345 errors

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1162]
i installed latest 0.9.4. i'm getting about 400 errors for example that:

```
 <b-navbar-brand>
        <h5>blablabla</h5>
 </b-navbar-brand>
```

Argument of type '{}' is not assignable to parameter of type 'typeof import("c:/xampp/htdocs/pms/pms_frontend_vue3/node_modules/vue/dist/vue") & Record<string, unknown>'.
  Type '{}' is missing the following properties from type 'typeof import("c:/xampp/htdocs/pms/pms_frontend_vue3/node_modules/vue/dist/vue")': compileToFunction, compile, defineCustomElement, useCssModule, and 148 more.

**Comment by VividLemon** [comment]
You may want to try reinstalling node modules, and ensuring that Vue is >= v3.3

**Comment by susanne99** [comment]
Here are the working installed versions:

package.json
```
"@popperjs/core": "^2.11.8",
    "@types/bootstrap": "^5.2.6",
    "@vuelidate/core": "^2.0.2",
    "@vuelidate/validators": "^2.0.2",
    "axios": "^1.4.0",
    "bootstrap": "^5.3.0",
    "bootstrap-vue-next": "^0.8.13",
    "crypto-js": "^4.1.1",
    "d3": "^7.8.4",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "resize-observer-polyfill": "^1.5.1",
    "rrule": "^2.7.2",
    "uuid": "^9.0.0",
    "vue": "^3.3.4",
    "vue-datepicker-next": "^1.0.3",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.2.2",
    "vue3-swatches": "^1.2.3",
    "vuex": "^4.1.0"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.3.0",
    "@types/crypto-js": "4.1.1",
    "@types/d3": "^7.4.0",
    "@types/lodash": "^4.14.195",
    "@types/node": "^20.2.5",
    "@types/uuid": "^9.0.1",
    "@types/vuelidate": "^0.7.18",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/eslint-config-typescript": "^11.0.3",
    "@vue/tsconfig": "^0.4.0",
    "eslint": "^8.41.0",
    "eslint-plugin-vue": "^9.14.1",
    "npm-run-all": "^4.1.5",
    "sass": "^1.62.1",
    "typescript": "~5.1.3",
    "vite": "^4.3.9",
    "vue-tsc": "^1.6.5"
  }
```

npm -v -> 9.6.7
node -v -> v18.16.0



as soon as i install bootstrap-vue-next version: 0.8.15, the error occurs

**Comment by VividLemon** [comment]
Like I said, you may want to delete node modules & reinstall

**Comment by susanne99** [comment]
explain me why i should delete. that's illogical. why does 0.8.13 and 0.8.15 no longer work?
do they all have to delete and reinstall their node modules now?

**Comment by VividLemon** [comment]
Sometimes even when changing package versions, it doesn't install the newest version. It's the same reason why Nuxt recommends `nuxi upgrade --force` to upgrade Nuxt.

**Comment by susanne99** [comment]
but I'm cooperative, have deleted node_modules folder and reinstalled modules - as before, nothing has changed!

**Comment by susanne99** [comment]
okay, i found it. 
in file "index.d.ts" in folder "bootstrap-vue-next\dist\src\components" you export "BNavbarBrand": 
`export { default as BNavbarBrand } from './BNavbar/BNavbarBrand.vue';`
but in version 0.8.15 and higher there is no BNavbarBrand.vue.d.ts in folder "./BNavbar".
there is only bnavbar.vue.d.ts, bnavbarnav.vue.d.ts and bnavbartoogle.vue.d.ts.
in version 0.8.13 the file "BNavbarBrand.vue.d.ts" exists

**Comment by VividLemon** [comment]
K thanks

**Comment by VividLemon** [comment]
I am working on a fix for this, but it's a bit complicated of an issue. You will likely want to stay downgraded for the time being.

**Comment by susanne99** [comment]
no problem i can use 0.8.13 too. 
you just have to take out 0.8.15 and higher it is not complete and therefore unusable

**Comment by susanne99** [comment]
when do you solve this problem in the last version 0.9.9 the files are still missing. 
Please tell me how to use this package when files are missing. 
I wonder how the others do it - I don't understand

**Comment by VividLemon** [comment]
Update to https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrap-vue-next-v0.9.12
