### ISSUE TITLE
Tooltips show up even when content is empty

### ISSUE THREAD

**Issue by gjulianm** [bootstrap-vue-next/bootstrap-vue-next#1163]
**Describe the bug.** In bootstrap-vue-next 0.7.3, whenever the value bound to a `v-b-tooltip` directive was empty, the tooltip would not show up. In version 0.9.4, the tooltip does show up even with empty contents.

**To Reproduce.** 

Create an element with the `v-b-tooltip=''` directive.

**Expected behavior.** Tooltips should not show up when the content is empty.

**Screenshots.** 

An empty tooltip showing up: ![Screenshot 2023-06-02 at 11 53 42](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/1334568/d9141be5-70fa-47ce-bdb7-51b9ea0bed2f)

**Environment (please complete the following information):**

- OS: macOS Ventura 13, also seen in Linux
- Package Version: 0.9.4
- Npm/Yarn/Pnpm Version: npm@9.5.0

**Additional context.** 

I have tried to bind `v-b-tooltip` to an object such as `{ title: sometext, active: sometext.length > 0 }` but in that case the result is that an empty card pops up:

![Screenshot 2023-06-02 at 11 56 39](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/1334568/3c69e818-e332-43f5-b622-581657894cb7)

**Comment by VividLemon** [comment]
It's an odd thought to think that the preferred strategy for this would be to explicitly not showing the element if there is no text. When in HTML, that's not how it usually works. Is this how it works in Bootstrap-vue? Or vanilla Bootstrap?

**Comment by gjulianm** [comment]
Yes, in bootstrap-vue it does work like that when the content of the directive `v-b-tooltip` is empty or null. It also worked like that in bootstrap-vue-next@0.7.3. It is fairly useful because it reduces a lot of boilerplate when tooltips aren't always present. Compare the difference in two functionally equivalent codes between the previous behavior and the current one:

bootstrap-vue-next@0.7.3
```
<myelement v-b-tooltip="stringThatMightBeEmpty">...</myelement>
``` 

versus the following in bootstrap-vue-next@0.9.4.
``` 
<b-tooltip v-if="stringThatMightBeEmpty" :target="buildIdForItem(...)">{{ stringThatMightBeEmpty }}</b-tooltip>
<myelement :id="buildIdForItem(...)">...</myelement>
``` 

If the `active` property worked, we could have something intermediate such as

```
<myelement v-b-tooltip="{ title: stringThatMightBeEmpty, active: !!stringThatMightBeEmpty }">...</myelement>
``` 

which is still more code but at least doesn't need unique IDs for the target element, which is a hassle when putting tooltips in components that are reused through the page or are inside of loops.
