### ISSUE TITLE
Missing version 0.9.5 in npm

### ISSUE THREAD

**Issue by sfe-efficy** [bootstrap-vue-next/bootstrap-vue-next#1168]
Hi!

Latest version published in npm is 0.9.4.
https://www.npmjs.com/package/bootstrap-vue-next?activeTab=versions

The latest version still pending to be published.

https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrap-vue-next-v0.9.5

**Comment by VividLemon** [comment]
Don't do that ^

**Comment by gjulianm** [comment]
Oh, sorry, I used to install it locally and check that the changes were working as I expected. When is it planned the release to NPM? Thanks

**Comment by VividLemon** [comment]
https://www.npmjs.com/package/bootstrap-vue-next?activeTab=readme
