### ISSUE TITLE
docs: remove dead links

### ISSUE THREAD

**Issue by mbabker** [bootstrap-vue-next/bootstrap-vue-next#1173]
The "Comparison with BootstrapVue"  section of https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html links to a Parity List page to show feature compatibility with BootstrapVue but it looks like this was removed in #1076.

**Comment by VividLemon** [comment]
It was too out of date to be very useful. Dead links will be cleaned up at a later time.

**Comment by VividLemon** [comment]
Related: https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1642

**Comment by anrolmar** [comment]
At this moment, these are the dead links:

- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/form-validation
- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/settings
- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/size-props-and-classes
- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/spacing-classes
- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/starter-templates
- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/theming-bootstrap
- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/third-party-libraries
- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/utility-classes
