### ISSUE TITLE
sass error: rgba(var(--bs-body-bg-rgb), 0.85) is not a color

### ISSUE THREAD

**Issue by DGCK81LNN** [bootstrap-vue-next/bootstrap-vue-next#1177]
scss build error in bootstrap-vue-next at `components/BToast/_toast.scss:1`

~~~
Error: $color: rgba(var(--bs-body-bg-rgb), 0.85) is not a color.
  ╷
1 │ $b-toast-background-opacity: alpha($toast-background-color) !default;
  │                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\bootstrap-vue-next\src\components\BToast\_toast.scss 1:30  @import
  node_modules\bootstrap-vue-next\src\components\BToast\index.scss 1:9    @import
  bootstrap-vue-next\src\styles\styles.scss 12:9                          @import
  src\bootstrap-vue-3-lnn.scss 2:9                                        root stylesheet
~~~

https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/d17ed8c0a34ca0d8894d7a1294f7349836720334/packages/bootstrap-vue-next/src/components/BToast/_toast.scss#L1

**To Reproduce.** Steps to reproduce the behavior:

1. Clone `https://github.com/DGCK81LNN/bootstrap-lnn.git` and checkout tree `2331d109`
2. `npm install` and `npm run build-css`
3. See error

**Environment:**

- OS: Windows 7
- Package Versions: `bootstrap-vue-next@0.9.4`, `bootstrap@5.3.0`, `sass@1.62.1`
- Npm/Yarn/Pnpm Version: `npm@9.6.6`

**Additional context.**

Did not occur before upgrading `bootstrap` from v5.2.3 to v5.3.0. In this upgrade, the default value for `$toast-background-color` was changed from [`rgba($white, .85)`](https://github.com/twbs/bootstrap/blob/v5.2.3/scss/_variables.scss#L1362) to [`rgba(var(--#{$prefix}body-bg-rgb), .85)`](https://github.com/twbs/bootstrap/blob/v5.3.0/scss/_variables.scss#L1464).

**Comment by VividLemon** [comment]
Yeah, bootstrap 5.3 full release blindsided me with a change that affected some custom sass. Though, I think it works in the alphas. Next change will have a fix, which, is really just remove the problematic code, as I don't think its actually used. But a release may not occur in some time, as there is a crucial fix that needs to occur. But is a difficult fix

**Comment by VividLemon** [comment]
This should be fixed in the latest release. It fixes the issue, but the way it does it is by just removing the problematic files. BToast is a broken component so I'm not too concerned about removing the files at the moment.
