### ISSUE TITLE
Runtime directive used on component with non-element root node. The directives will not function as intended.

### ISSUE THREAD

**Issue by phlegx** [bootstrap-vue-next/bootstrap-vue-next#1181]
**Describe the bug.**

Using `b-link` with `:to=` property **and** `v-b-toggle` directive causes this warning:

```log
[Vue warn]: Runtime directive used on component with non-element root node. The directives will not function as intended. 
  at <RouterLink key=0 to=Object { name: "help" } > 
  at <BLink to=Object { name: "help" } >
  ... 
```

**To Reproduce.**

```html
<b-link :to="{ name: 'help' }" v-b-toggle.main-menu>
  ...
</b-link>
```

**Expected behavior.**

Like in bootstrap-vue v2.23.0 it should close the menu (offcanvas) with id `main-menu` and route the page to help.

**Environment (please complete the following information):**

- OS: Linux
- Package Version: 0.9.5
- Npm/Yarn/Pnpm Version: yarn@1.22.19

**Comment by phlegx** [comment]
Duplicate of #295 
Sorry!

**Comment by phlegx** [comment]
@VividLemon I am in the process of finding a solution here. Unfortunately without success. Any idea?

**Comment by phlegx** [comment]
Temporary work around could be a wrapper with toggle directive.

```html
<b-collapse id="main-collapse">
  Hello Collapse!
</b-collapse>
<div v-b-toggle.main-collapse>
  <b-link :to="{ path: 'home' }">
    Hello Link!
  </b-link>
</div>
```

**Comment by VividLemon** [comment]
> @VividLemon I am in the process of finding a solution here. Unfortunately without success. Any idea?
> 
> Meanwhile I have opened an issue on vue-router: [#1887](https://github.com/vuejs/router/issues/1887)

This is not something that vue or vue-router will support. Wrapping components is a solution, but ultimately, https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/295#issuecomment-1506113891 is likely the best permanent solution.

**Comment by VividLemon** [comment]
Closing in favor of https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/295 (because it's older)
