### ISSUE TITLE
Component global configuration

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1199]
Have a look at #662 and #1118 

In BootstrapVue.ts there are some lines 
```
const plugin: Plugin = {
  // TODO: use options in the future
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  install(app: App, options: BootstrapVueOptions = {}) {
    Object.entries(Components).forEach(([name, component]) => {
      app.component(name, component)
    })

   ....
}
```

BootstrapVueOptions are more or less declared.
I would like to write code in order to have global config but I need some suggestions 'cos I think it isn't possible to set props at this level.

Should BootstrapVueOptions be saved in ```app.config.globalProperties.$bootstrapVueOptions``` and then retrieved  in every component or there are better  ways to do that?

**Comment by makroxyz** [comment]
I'm trying to "up" this question since I'm porting a very large project to Bootstrap Vue Next.

I'm using inertiajs so I created an InertiaRouterLink component. 

In a BLink component I can use my component through router-component-name attribute

Without global configuration I must declare this attribute in every single component which uses a link (BLink, BDropdownItem, BButton...)

The global configuration feature (like old BootstrapVue version) is the key not only for translation purposes (for example BModal button okTitle or cancelTitle)

**Comment by VividLemon** [comment]
https://github.com/orgs/bootstrap-vue-next/projects/1/views/1?pane=issue&itemId=43924328

**Comment by VividLemon** [comment]
Moving this to https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1607
