### ISSUE TITLE
BFormFile any plans?

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1208]
BFormFile is not yet available in bootstrap-vue-next. Is it scheduled for development?

BFormInput also doensn't accept type="file" because it is not allowed.

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/85396d37e7f75fcd1a35b9de7d00cf0acea2e1c3

**Comment by VividLemon** [comment]
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-file.html

**Comment by VividLemon** [comment]
Duplicate of https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/752
