### ISSUE TITLE
[0.9.10] BFormInput and other components missing in "dist"-folder

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1214]
since version 0.8.15 components are missing in "bootstrap-vue-next/dist" folder. 
for instance BFromInput, BNavbar
therefore i cannot build a production version (npm run build) of my app
that's my npm list:

`@fortawesome/fontawesome-svg-core@6.4.0
@fortawesome/free-brands-svg-icons@6.4.0
@fortawesome/free-regular-svg-icons@6.4.0
@fortawesome/free-solid-svg-icons@6.4.0
@fortawesome/vue-fontawesome@3.0.3
@fullcalendar/bootstrap@6.1.8
@fullcalendar/core@6.1.8
@fullcalendar/daygrid@6.1.8
@fullcalendar/google-calendar@6.1.8
@fullcalendar/interaction@6.1.8
@fullcalendar/list@6.1.8
@fullcalendar/resource-common@5.11.5
@fullcalendar/resource-daygrid@6.1.8
@fullcalendar/resource-timeline@6.1.8
@fullcalendar/rrule@6.1.8
@fullcalendar/timegrid@6.1.8
@fullcalendar/timeline@6.1.8
@fullcalendar/vue3@6.1.8
@popperjs/core@2.11.8
@rushstack/eslint-patch@1.3.2
@types/bootstrap@5.2.6
@types/crypto-js@4.1.1
@types/d3@7.4.0
@types/lodash@4.14.195
@types/node@20.3.1
@types/uuid@9.0.2
@types/vuelidate@0.7.18
@vitejs/plugin-vue@4.2.3
@vue/eslint-config-typescript@11.0.3
@vue/tsconfig@0.4.0
@vuelidate/core@2.0.2
@vuelidate/validators@2.0.2
axios@1.4.0
bootstrap-vue-next@0.9.10
bootstrap@5.3.0
crypto-js@4.1.1
d3@7.8.5
eslint-plugin-vue@9.15.1
eslint@8.43.0
lodash@4.17.21
moment@2.29.4
npm-run-all@4.1.5
resize-observer-polyfill@1.5.1
rrule@2.7.2
sass@1.63.6
typescript@5.1.3
uuid@9.0.0
vite@4.3.9
vue-datepicker-next@1.0.3
vue-i18n@9.2.2
vue-router@4.2.2
vue-tsc@1.8.1
vue@3.3.4
vue3-swatches@1.2.3
vuex@4.1.0

`

**Comment by VividLemon** [comment]
Update to https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrap-vue-next-v0.9.12

**Comment by susanne99** [comment]
good job thank you !!
