### ISSUE TITLE
Issues with BImg and Nuxt3

### ISSUE THREAD

**Issue by DandrewsDev** [bootstrap-vue-next/bootstrap-vue-next#1220]
**What you are trying to do.** A clear and concise description of what you want to happen.
Display an image with BImg. This is in a nuxt3 app using the bootstrap-vue-next/nuxt package. 
The image works fine if I have nuxt devtools enabled. But when disabled either in dev, or during a prod build/preview. The image is broken and does not display.

**What you have already tried.** A clear and concise description of any alternative solutions or features you have considered.
I have tried various ways of pointing to the image path
/assets/images/test.png
~assets/images/test.png
~/assets/images/test.png
@assets/images/test.png 
_nuxt/assets/images/test.png 

All of which seem to work when running with devtools enabled in dev mode. But any prod build the images are not included and and broken.

However if I were to use a normal <img tag, instead of BImg, those images are included and work fine. 

**Any error messages you are getting.** If any, please list the errors you are getting.
None

**Environment (please complete the following information):**
- OS: Mac OS 13.2.1
- Package Version: "bootstrap-vue-next": "^0.9.12", "@bootstrap-vue-next/nuxt": "^0.1.2",
- Npm/Yarn/Pnpm Version: pnpm 8.6.3

**Comment by VividLemon** [comment]
You should try https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue#asset-url-handling

**Comment by DandrewsDev** [comment]
Thank you for that suggestion, I tried that out, and got my images to load. Thanks!
