### ISSUE TITLE
One vue App for each tooltip

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1232]
I just noticed that vue App is created for each tooltip/popover on the page. Is it right?

**Comment by VividLemon** [comment]
Find a different way to do it

**Comment by aceofwings** [comment]
@makroxyz That is correct. Also are you experiencing performance or debugging issues?

**Comment by makroxyz** [comment]
I can't say anything about performances for now. I'm migrating a very large
app, and I'm only at the beginning... I've noticed that while debugging in
Chrome with Vue extension and I found about 15 apps since I've a BTable
with buttons with tooltip for each row...

Il lun 3 lug 2023, 20:51 aceofwings ***@***.***> ha scritto:
