### ISSUE TITLE
bug(BFormGroup): Uncaught InternalError: too much recursion

### ISSUE THREAD

**Issue by phlegx** [bootstrap-vue-next/bootstrap-vue-next#1244]
**Describe the bug.** 

Adding property `label-cols-md` to `BFormGroup` ends with `Uncaught InternalError: too much recursion` using in combination with `label-sr-only` property.

**To Reproduce.**

```vue
<BFormGroup
  label='My Form Group'
  :label-cols-md='12'
  :label-sr-only='true'>
  Form Group Content
</BFormGroup>
```

**Expected behavior.**

Normal rendering without error.

**Environment:**

- OS: Linux
- Package Version: 0.9.17
- Npm/Yarn/Pnpm Version: npm@9.6.6, pnpm@8.6.2

**Comment by VividLemon** [comment]
Seems to have been fixed
