### ISSUE TITLE
Can't set focus on form input via ref

### ISSUE THREAD

**Issue by mike-kelly** [bootstrap-vue-next/bootstrap-vue-next#1250]
When trying to set the focus on a `<b-form-input>` field via its ref I get the error message `input.value.focus is not a function`
It works fine with a normal `<input />` field.

boostrap-vue-next version 0.9.14

This was reported previously, perhaps there has been a regression since it was fixed?
See issue referenced below.

_Originally posted by @mike-kelly in https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/32#issuecomment-1613191653_

**Comment by mike-kelly** [comment]
I found that this worked. I don't know if it's by design. Where the `<b-form-input>` component has a ref of `searchInput`:

```
this.$refs.searchInput.$refs.input.focus();
```

The focus instruction is wrapped in a `nextTick`

**Comment by VividLemon** [comment]
```html
<template>
  <BContainer>
    <BRow>
      <BCol> <BFormInput ref="foo" /> <BButton @click="a">Click me</BButton></BCol>
    </BRow>
  </BContainer>
</template>

<script setup lang="ts">
// You can use this file as a development spot to test your changes
// Please do not commit this file
import {ref} from 'vue'
const foo = ref()
const a = () => {
  foo.value.focus()
}
</script>

```
This works fine. Regardless on if TypeScript knows that the focus method exists, it still does.
Alternatively this syntax will provide type inferences:
```html
<template>
  <BContainer>
    <BRow>
      <BCol> <BFormInput ref="foo" /> <BButton @click="a">Click me</BButton></BCol>
    </BRow>
  </BContainer>
</template>

<script setup lang="ts">
// You can use this file as a development spot to test your changes
// Please do not commit this file
import {ref} from 'vue'
import type {BFormInput} from './components'
const foo = ref<null | InstanceType<typeof BFormInput>>(null)
const a = () => {
  foo.value?.focus()
}
```

**Comment by VividLemon** [comment]
You'd need to create an actual reproduction

**Comment by mike-kelly** [comment]
Strange one. I can't reproduce on StackBlitz with the same dependencies. :(
With a vanilla example like this it works fine: 

https://stackblitz.com/edit/vitejs-vite-cxr5sb?file=src%2Fcomponents%2FFormInput.vue
The value of the `b-form-input` ref, `foo.value` is shown in the console to be this: 

<img width="410" alt="Screenshot 2023-07-07 at 11 15 46" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/1119871/80bf1990-47bc-404c-927d-741302bb401e">

In my app, in an equivalent component, `foo.value` is shown in the console to be like the following. The Target is an Object rather than a Proxy(Object), so doesn't have the `focus()` function.

<img width="221" alt="Screenshot 2023-07-07 at 11 17 15" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/1119871/6ed6b545-79c9-40f6-b3f8-2fda59fac7c8">

Any suggestions of where I might be going wrong?

**Comment by VividLemon** [comment]
Perhaps you need to delete and reinstall node_modules

**Comment by mike-kelly** [comment]
Yep I tried that, cleared cache, tried changing node version, and various other tweaks. I guess it must be a quirk of my setup, feel free to close the issue and I will post an update if I can work out what's going on.

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrap-vue-next-v0.9.16

**Comment by mike-kelly** [comment]
I was using 0.9.14 before. Updating has fixed it. I thought I had tried that, obviously not! Thanks.
