### ISSUE TITLE
Sponsor a bit development on the BTable-component

### ISSUE THREAD

**Issue by JanBolmeson** [bootstrap-vue-next/bootstrap-vue-next#1253]
Hi!

We love this project and used the old bootstrap-vue extensively. Instead of putting in the time myself in choosing another component or doing the work in our own project, would it be possible for me to sponsor development for some BTable-functionality by some of the core-members? 

Thanks,
Jan

**Comment by devhus** [comment]
I am coming back soon to continue developing the BTable component, hopefully.

**Comment by VividLemon** [comment]
Any sponsorships should be done solely through the open collective or an individuals github sponsor links. I'm not going to tell individuals on how they can accept payments, but to protect all parties involved, it would be best to use official channels.

**Comment by JanBolmeson** [comment]
I am sorry, didn't mean to break any rules. Just tell me how to do it correctly and I will comply. Sorry. 🙈

**Comment by VividLemon** [comment]
There is no written rule. The issue is, hypothetically, if you were to convince someone to send you confidential financial details for the purposes of extorting or scamming them. This is what I seek to prevent by this statement.

**Comment by devhus** [comment]
@VividLemon Just to make it clear, I am not planning to get any money from anyone my collaboration will be for free.
@JanBolmeson I am just making a statement that i am gonna be back soon, so you don't really need to pay anyone.
However, if you need a specific feature/fix just submit an issue with it.

**Comment by VividLemon** [comment]
This ain't bootstrap-vue where people donate and the money just sits in an account for years. Anyone that has contributed and feel like their work has made an impact is free to submit an expense.

**Comment by devhus** [comment]
@JanBolmeson The feature has been added in this https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1262 PR

**Comment by VividLemon** [comment]
@devhus it would be really neat if the table component could utilize Vue 3.3s generic components. I could see a lot of things on that component utilizing generics

**Comment by devhus** [comment]
@VividLemon i am not up to date with vues updates, would you like to send me docs or article of the component generic you mentioned?

**Comment by VividLemon** [comment]
> @VividLemon i am not up to date with vues updates, would you like to send me docs or article of the component generic you mentioned?

https://blog.vuejs.org/posts/vue-3-3#generic-components
https://vuejs.org/api/sfc-script-setup.html#generics

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1533 considering this closed in the meantime
