### ISSUE TITLE
Library discovery difficulty

### ISSUE THREAD

**Issue by devhus** [bootstrap-vue-next/bootstrap-vue-next#1261]
I've noticed that the library is not very popular especially after merging with BV2 and being independent again. This issue is to discuss a few matters about the library info that should improve the package's SEO on NPM and other aspects.

_**All the given solutions are based on my point of view and might be wrong but the problems do exist. I will publish a PR that includes a few updates to improve the library discovery and this issue is just to clarify the PR  porpuse.**_

### The problem
As most of this library users know the library name used to be "bootstrap-vue-3" before merging with BV2 and jumping to bootstrap-vue-next repo. 
The problem with the current name "bootstrap-vue-next" is that it's not a very clear name to junior devs or the search bots as you can see in the image below you can't find the library when searching for something like "Vue 3 Bootstrap" 
![image](https://github.com/bootstrap-vue/bootstrap-vue/assets/58523735/9b811060-016a-4ca5-9898-bec3e4a4194f)

- We can see BV2 is getting the lead but is understandable since their website has a higher ranking..etc.
- The next search result is the NPM URL of the old package, which doesn't have any direct link to the new NPM package. The package is just deprecated 
- We can see the GitHub URL of the package but that not going to appear to most devs, it appears to me because of how many times visited this repo

### The solution
**Change the library name to "Bootstrap Vue 3".**
The library name (at least the display name) should include "vue 3" words, That will impact the search engine bots to be able to give better results when searching for direct libraries for vue 3. Keep in mind that the word "next" doesn't specify that the library is for vue 3 or 2, "next" can be used as an upgraded version of the library but not the main name or display_name.

### The problem
As we can all notice that all of the library read-me, description, and keywords are missing a lot of directions and clarifications about the library to be well noticed by both devs and search bots.

### The solution
Simply we will need to update the library's read-me, description, and keywords to include more directions and clarifications about the library such as using the word "vue 3", and "nuxt 3" more.

## Documentations
Nothing to say about this part since the docs are getting updated slowly to include all of the library aspects. We will just need to spend more time improving the documentation and the content's SEO

### The problem
I have no idea about what is going on behind the scenes but it's a very bad idea to keep changing the main repository and npm package of the library that will impact the library's popularity.

### The solution
Up to the library's owners to stop these kind of updates

**Comment by VividLemon** [comment]
This should help https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1263

**Comment by VividLemon** [comment]
Various things were improved after this PR.
A sitemap was generated
More robust title/description with og and twitter protocols implemented
A link was added to the bootstrap documentation linking to our documentation. 
I don't think anything else really needs to be changed.
