### ISSUE TITLE
BTable sorting does not work

### ISSUE THREAD

**Issue by JanBolmeson** [bootstrap-vue-next/bootstrap-vue-next#1269]
**Describe the bug.** 
Btable-component, if `sortable` is set to true for a field (=column) then it should sort on it. 

**To Reproduce.** 
1. Open sandbox.io:  https://vc96sx-5173.csb.app/
2. Click on e.g. column "Name", "My age", "ID" or "salary"

**Sandbox Code**
https://codesandbox.io/p/sandbox/quiet-bash-vc96sx?file=%2Fsrc%2FApp.vue%3A36%2C21

**Expected behavior.** 
It should be sorted on age or name. 

**Other info**
Columns that have `sortable === true` get a pointer-cursor so that seems to work. 

**Environment info**
```
"bootstrap": "^5.3.0",
"bootstrap-vue-next": "^0.9.20",
```

**Comment by devhus** [comment]
The issue is that you are not passing a ``v-model:sort-by``, you can pass it for now or wait until PR https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1262 gets published.

**Comment by JanBolmeson** [comment]
Ah, great. I must have missed that in the docs. I'm sorry. 🙈

I can confirm it works and I'll close the issue. 👍
