### ISSUE TITLE
BTable filter does not work - triggers error in itemHelper.ts

### ISSUE THREAD

**Issue by JanBolmeson** [bootstrap-vue-next/bootstrap-vue-next#1270]
**Describe the bug.** 
Filtering in Btable does not work and triggers errors in itemHelper.ts. 

**To Reproduce.** 
1. Open sandbox: https://4895tf-5173.csb.app/
2. Write something in the Filter box

Code for table:
https://codesandbox.io/p/sandbox/sandbox-bootstrap-vue-next-table-filter-bug-4895tf

**Expected behavior.** 
Writing: "An" should filter out everything that does not contain "An"

**Screenshots.** 
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/3698445/4ae0eaae-86b0-4954-9bec-38bb8a19d6ba)

**Environment (please complete the following information):**
```
"bootstrap": "^5.3.0",
"bootstrap-vue-next": "^0.9.20",
```

**Comment by devhus** [comment]
Thank you for the reproduction, after testing it on my end this issue seems to be fixed with this PR https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1262

**Comment by JanBolmeson** [comment]
Great @devhus - can you check if the prop that defines which fields to filter on also works?

```
:filter-included-fields="['name']"

```

old docs: 
https://bootstrap-vue.org/docs/components/table#filtering

**Comment by devhus** [comment]
@JanBolmeson it's handled by ``filterable`` prop now

**Comment by VividLemon** [comment]
Test this on 0.15 then make a new issue if it persists
