### ISSUE TITLE
top-row and bottom-row slot missing from b-table

### ISSUE THREAD

**Issue by stevemandl** [bootstrap-vue-next/bootstrap-vue-next#1276]
**Is this feature a Bootstrap-vue feature?** Yes. Documentation here: https://bootstrap-vue.org/docs/components/table#table-helper-components

When a `<template #top-row=...` or `<template #top-row=...` is included inside the b-table, the corresponding table row should be added.

**Comment by VividLemon** [comment]
Seems to be working now
