### ISSUE TITLE
Add msgBoxOk and msgBoxConfirm modal boxes

### ISSUE THREAD

**Issue by martin91s** [bootstrap-vue-next/bootstrap-vue-next#1279]
With `this.$bvModal` removed. There is no way to display confirm boxes. Are there plans to introduce this in the future? 

https://bootstrap-vue.org/docs/components/modal#modal-message-boxes

**Comment by anrolmar** [comment]
You could use useModalController to do that (https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html)

**Comment by suzumejakku** [comment]
> You could use useModalController to do that (https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html)

Yes, I need to upgrade and test. At the time of my post, there was no such solution... so now I need to test it out :)

**Comment by suzumejakku** [comment]
> You could use useModalController to do that (https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html)

This is something I will try with the new version, once I get the time to install it and test it.
