### ISSUE TITLE
bforminput adjustments

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1298]
Bforminput and its text area should be fixed up. Removal of ts any, add denounce and other missing features, as well as usage of more vueuse utilities like vueuse -- also the focus doesn't take full advantage of usefocus

**Comment by adholland** [comment]
Hi @VividLemon. Would the missing features include b-form-invalid-feedback? I am using that quite a bit so would be good news if it was the case.

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BForm/BFormInvalidFeedback.vue

**Comment by adholland** [comment]
@VividLemon not sure how I missed that, but thanks for getting back to me.
