### ISSUE TITLE
Btable captionTop is not functional

### ISSUE THREAD

**Issue by robertbarclayy** [bootstrap-vue-next/bootstrap-vue-next#1299]
With caption-top set to true with btable the caption is located below the table not above. 

1. Create a btable with caption-top="true" 
2. Set the caption: `		<template #table-caption>
			<h2 :class="fooClasses">
				{{ fooCaption }}
			</h2>
		</template>`
3. See the caption being set at the bottom. 

**Expected behavior.** The caption should be at the top.

**Screenshots.** 
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/32703993/85dd6ed3-886b-4af0-83e6-90546e55f307)
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/32703993/c5516871-3aed-4347-b7dc-3d440420a43f)

**Comment by VividLemon** [comment]
Tested with the following code block
```
<template>
  <div>
    <BButton @click="move = !move">Click me</BButton>
    <b-table striped hover :items="items" :caption-top="move">
      <template #table-caption>
        <h2>foo</h2>
      </template>
    </b-table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      move: true,
      items: [
        {age: 40, first_name: 'Dickerson', last_name: 'Macdonald'},
        {age: 21, first_name: 'Larsen', last_name: 'Shaw'},
        {age: 89, first_name: 'Geneva', last_name: 'Wilson'},
        {age: 38, first_name: 'Jami', last_name: 'Carney'},
      ],
    }
  },
}
</script>

```

And it seemed to be working fine. Bear in mind that I'm working on the latest branch -- which may include features in 0.10
