### ISSUE TITLE
Add full list in main page of repo in what state are components

### ISSUE THREAD

**Issue by DainisVerdins** [bootstrap-vue-next/bootstrap-vue-next#1301]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Greetings, I am a bit frustrated when working with bootstrap-vue-next because you do not have list of components what are implemented and what are not here or in documentation section. I assume what end goal of project is to implement all components from bootstrap 5.x.x and some from bootstrap-vue for vuejs (like star rating component). To detect what components are implemented you need to check source code of the library and its tedious to check every time what is already implemented and what me as DEV should implement for my needs.

**Describe the solution you would like.** A clear and concise description of what you want to happen
So my proposal is to add to main README.md some kind of table where visitor can see in what state are components (implemented, still in progress or not implemented yet)

**Describe alternatives you have considered.** A clear and concise description of any alternative solutions or features you've considered

- Alternative add in documentation section where is list implemented or not components.
- add link in README of image/list/text file where you can check if component is implemented yet or not.

**Additional context.** Add any other context or screenshots about the feature request here
Where should info about implemented components should be
![opera_r5PAu0oRbg](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/55252915/a0e5cda1-66f0-481f-a1a2-1ed2deec718e)

example of table 
![mspaint_5ITkhbVGk7](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/55252915/204b0dbf-2689-40cc-9c37-246a77d0b7d4)

**Comment by darthf1** [comment]
Have you checked https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components.html?

**Comment by DainisVerdins** [comment]
> Have you checked https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components.html for the list of components? Child components, props, events, slots are in there.

Hmm but what about components what are not implemented yet? Where could I see the list?

**Comment by VividLemon** [comment]
Maintaining a list of components and features seems like it would be more effort than just adding missing things. There used to be something called a "parity list", but this was removed as it became too out of date as it suffered from the same problem I described.

**Comment by DainisVerdins** [comment]
> Maintaining a list of components and features seems like it would be more effort than just adding missing things. There used to be something called a "parity list", but this was removed as it became too out of date as it suffered from the same problem I described.

I mean at least some kind of list or somewhere mention what this components are not implemented.
| Vue-2-bootstrap component | Implemented |
| ------------- | ------------- |
| Alert  |  :heavy_check_mark: |
| Aspect  |   |
| Avatar  |   |
|  Badge |   |
| Breadcrumb  |   |
| Button  |   |
| Button Group  |   |
| Button Toolbar   |   |
| Calendar |   |
| Card  |   |
| Carousel  |   |
| Collapse  |   |
|Dropdown  |   |
| Embed  |   |
| Form  |   |
| Form Checkbox  |   |
| Form Datepicker  |   |
| Form File  |   |
| Form Group |   |
| Form Input  |   |
| Form Radio  |   |
|  Form Rating |   |
| Form Select |   |
| Form Spinbutton  |   |
| Form Tags   |   |
| Form Textarea  |   |
| Form Timepicker |   |
| Image  |   |
|  |   |
|  |   |
|  |   |
|  |   |
|  |   |
|  |   |

**Comment by VividLemon** [comment]
And I'm respectfully saying that I'd rather not waste my time maintaining such a list, compared to implementing the missing features that it describes

**Comment by DainisVerdins** [comment]
> And I'm respectfully saying that I'd rather not waste my time maintaining such a list, compared to implementing the missing features that it describes

Okey rephrase my idea. If I would create list/table like and I will maintain it time to time(once a month update info for example). Could this "feature" be added to project docs somewhere? Or idea is still born and better to focus on implementing missing features and/or components instead?

example of table 
| bootstrap v5 component | have in vue2-bootstrap | have in vue-bootstrap-next |
|     :---:      |     :---:      |     :---:      |
| componentA   | :x:    | :heavy_check_mark:    |
|  componentB   | :heavy_check_mark:       | :x:     |

**Comment by DainisVerdins** [comment]
Finally I figured out that idea was and is stillborn because project already have "list" implemented components. If component can not be found there in the list it means it is not implemented.  Close with commit then this issue. Sorry for waste of time reading this...
