### ISSUE TITLE
Getting Started with Bootstrap-vue next

### ISSUE THREAD

**Issue by bladekaj** [bootstrap-vue-next/bootstrap-vue-next#1302]
**What you are trying to do.** A clear and concise description of what you want to happen.
I am trying to move/start a project in Vue 3 and bootstrap-vue next.  The project was a Vue 2 vue-cli bootstrap-vue holdover and I am trying to convert it to Vue 3.  This is my first attempt to use Vue 3 and bootstrap-vue-next so it may be something stupid. 
I am trying to import and use bootstrap-vue-next in my application. 

**What you have already tried.** A clear and concise description of any alternative solutions or features you have considered.

The error I get is saying (see below) that I 'may need an appropriate loader to handle this file type' when I try to import **bootstrap-vue-next.mjs.**  I have tried adding various loaders to my webpack.config.js file but it has not solved the problem.  I have also both included and excluded my node_modules in the rules since the error is pointing at the node_modules directory on my machine. Nothing has changed.   The error goes away when I comment out the import but then I don't get to use the bootstrap-vue-next components.  Google etc has not been particularly helpful and I have tried some of the solutions for react and other packages where this type of error has occurred. 

Any help pointing to a loader that will work would be greatly appreciated. 

Here is my webpack.config.js file

`const path = require('path');
const webpack = require('webpack');
module.exports = {
  entry: {
      main:path.resolve(__dirname,',/src/index.js')
    },
    module: {
      rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
          }
          // other vue-loader options go here
        }
        },
        {
          test: /\.(?:js|mjs|cjs)$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: [
                ['@babel/preset-env', { targets: "defaults" }]
              ]
            },
            resolve: {
              fullySpecified: false,
            },
          }
        }
      ]
    }
  }`

**Any error messages you are getting.** If any, please list the errors you are getting.
Here is the error I am getting:
 _```
error  in ./node_modules/bootstrap-vue-next/dist/bootstrap-vue-next.mjs

Module parse failed: Unexpected token (161:44) **_<--- This points to a '??' operation._** 
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const t = ms(e);
|   return !!(t && t.height > 0 && t.width > 0);
> }, Ae = (e) => ((e == null ? void 0 : e()) ?? []).length === 0, go = (e, t) => (Ue(t) ? t : Ma).querySelector(e) || null, Ss = (e, t) => Array.from([(Ue(t) ? t : Ma).querySelectorAll(e)]), qa = (e, t) => t && Ue(e) ? e.getAttribute(t) : null, _s = (e) => Ma.getElementById(/^#/.test(e) ? e.slice(1) : e) || null, ws = (e, t, l) => {
|   t && Ue(e) && e.setAttribute(t, l);
| }, $s = (e, t) => {

 @ ./src/main.js 2:0-50 9:8-24
 @ multi (webpack)-dev-server/client?http://10.0.0.152:8082&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```_



**Environment (please complete the following information):**

- OS: MacOS Monterey 12.6.6 (2015 macbook pro)
- Package Version: 0.9.24
- Npm version: 8.3.1

main.js file
`import { createApp } from 'vue';
import BootstrapVueNext from 'bootstrap-vue-next';
import App from './App.vue';
import router from './components/router';


import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue-next/dist/bootstrap-vue-next.css";

const app = createApp(App);
app.use(router);
app.use(BootstrapVueNext);
app.mount('#app');`

`package.json file
{
  "name": "which-one-is-special-vue3",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "bootstrap": "^5.3.0",
    "bootstrap-vue-next": "^0.9.24",
    "core-js": "^3.6.5",
    "vue": "^3.0.0",
    "vue-loader": "^17.2.2",
    "vue-router": "^4.2.4",
    "vue-template-compiler": "^2.7.14"
  },
  "devDependencies": {
    "@babel/core": "^7.22.9",
    "@babel/preset-env": "^7.22.9",
    "@vue/cli-plugin-babel": "~4.5.13",
    "@vue/cli-plugin-eslint": "~4.5.13",
    "@vue/cli-service": "~4.5.13",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "webpack": "^4.46.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

`

**Comment by VividLemon** [comment]
A full reproduction using webpack v5 would be useful so I can write the appropriate documentation section. In regards to this currently, it will likely be best to use Vite instead of webpack and follow the `npm create vue@3` to initialize your application

**Comment by bladekaj** [comment]
I upgraded webpack to 5.88.1 (the latest) and the original error disappeared but now I am getting 
 
ERROR  TypeError: Cannot read properties of undefined (reading 'NormalModule')
 
TypeError: Cannot read properties of undefined (reading 'NormalModule')
at VueLoaderPlugin.apply (/Users/Anthony/Documents/Github/which-one-is-special-vue3/node_modules/vue-loader-v16/dist/pluginWebpack5.js:44:47)
at webpack ***@***.***/cli-service/node_modules/webpack/lib/webpack.js:51:13)
at serve ***@***.***/cli-service/lib/commands/serve.js:163:22)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

>  
> 
Google tells me it is probably due to a version conflict but removing node_modules and package-lock.json and reinstalling does not clear it up.  I am also getting the following deprecated version warnings when I do npm install so that is probably part of the problem. 
 
npm WARN deprecated ***@***.***: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated ***@***.***: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated ***@***.***: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated ***@***.***: this library is no longer supported
npm WARN deprecated ***@***.***: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated ***@***.***: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated ***@***.***: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm WARN deprecated ***@***.***: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated ***@***.***: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated ***@***.***: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated ***@***.***: 3.x is no longer supported
npm WARN deprecated ***@***.***: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @***@***.***: Moved to 'npm install @sideway/address'
npm WARN deprecated ***@***.***: Please upgradeto version 7 or higher.Older versions may use Math.random() in certain circumstances, which is known to be problematic.See https://v8.dev/blog/math-random for details.
npm WARN deprecated ***@***.***: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @***@***.***: Switch to 'npm install joi'
npm WARN deprecated ***@***.***: This SVGO version is no longer supported. Upgrade to v2.x.x.
 
I can zip up my directory and send it to you now or would you rather I solve the deprecation warnings and see where that gets me?  I assume you are concerned about my original error, not this one, but I could be wrong.
 
Since I have gotten no where with this version, I will move onto vite and see what that gets me. 
 
Let me know about which version you want....

**Comment by VividLemon** [comment]
I'm not especially concerned with either error. Vue recommends Vite as a build tool, and so do I. However, I understand there is a market for using webpack, and would like to write documentation on how to use it.

The original error is likely because webpack 4 transpiles to an early version of the ecmascript. Whereas Vite, and this library use 2020 -- the null coalescing operator is a 2020 feature. There is some weirdness regarding mjs/umd, I'm not an expert, but I imagine webpack 4 is attempting to default to a cjs file, but only mjs and umd files are exported. So some sort of loader would be required for using webpack 4, however, webpack 5 likely doesn't default to this.

**Comment by bladekaj** [comment]
Well if you don't care;  Here (attached) is a version of my vscode (tar'ed and gzipped) directory (without the node_modules, obviously) where I used latest version of everything I could but npm run serve fails with a parsing error.  There is nothing to it except a single page (it has a router) with a form on it.  I was going to add other pages but needed a simple case to figure out what was going on. 
 
/Users/Anthony/Documents/Github/which-one-is-special-vue3/src/App.vue
0:0errorParsing error: require() of ES Module /Users/Anthony/Documents/Github/which-one-is-special-vue3/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/Anthony/Documents/Github/which-one-is-special-vue3/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/Anthony/Documents/Github/which-one-is-special-vue3/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules
 
Let me know if this works or if you need something else....I will move to vite...

**Comment by a-kriya** [comment]
I also have an app in Vue2/BV that I intend to migrate, and the approach I had in mind is to start a clean project and move things over page-by-page. I'd already switched to Vite with Vue2 a while ago, and most projects today (even in React) use it. You'll find more support for it than Webpack so it'll be a good idea to start with a clean project with that.

**Comment by VividLemon** [comment]
When I added the labels and assigned this, I was intending to create some documentation for vue-cli and webpack. However, as I'm actually getting around to building, I'm finding the process to not be all to different from the https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html#legacy-installation on the documentation. 

The best solution I can come up with when migrating is to do as suggested and to actually create a blank project and migrate your project structure over. This means dependencies and configs have a starting spot, then you can merge them over. 

In my example, I used vue-cli to create an application, which uses webpack v5. 

I mentioned it, but the issue is likely with webpack v4, and likely with some dependencies along with it. As mentioned we target ES2020, which is likely not what webpack v4 was natively built for, so it natively will likely require a plugin, but a better option is to upgrade to v5 or vite. Which, if you're going to Vue 3, is definitely a requirement imo
