### ISSUE TITLE
BCarousel carousel-item class disappears after transition

### ISSUE THREAD

**Issue by bielfrontera** [bootstrap-vue-next/bootstrap-vue-next#1303]
BCarouselSlide components are created with the class `carousel-item`. But after transition from one slide to another, both components (previous and current slide) lose this class.

I assume the problem is related to the presence of `carousel-item` in the computed properties `enterClasses` and `leaveClasses` that configure the TransitionGroup and the comment about the hack to make the transition work.

**Comment by VividLemon** [comment]
Feel free to fix the issue in a better way. Otherwise I'm not concerned with the exact nature of the classes. After all, the start/end added classes are actually backwards.
