### ISSUE TITLE
BTable typing of slot parameters

### ISSUE THREAD

**Issue by xmatthias** [bootstrap-vue-next/bootstrap-vue-next#1305]
**Describe the bug.** A clear and concise description of what the bug is.

In recent versions, typing for the "row" value of slots changed, so now `row.item` is of type `TableItem`.
That's per se correct (though it should be `TableItem<T>`) - but is causing some problems with typescript.

**To Reproduce.** Steps to reproduce the behavior:

```
<template>
  <b-table
    show-empty
    primary-key="id"
    :items="tableItems"
    :fields="tableFields"
  >
    <template #cell(profitOpen)="{ item }">
      <profit-pill
        :profit-open="(item as unknown as ComparisonItem).profitOpen"
      />
    </template>
</btable>
</template>
<script setup lang="ts">
import { TableField, TableItem } from 'bootstrap-vue-next';

interface ComparisonTableItems {
  botId: string | undefined;
  botName: string;
  profitOpen: number;
  profitOpenRatio?: number;

}

const tableFields: TableField[] = [
  { key: 'botName', label: 'Bot' },
  { key: 'trades', label: 'Trades' },
  { key: 'profitOpen', label: 'Open Profit' },
  { key: 'profitClosed', label: 'Closed Profit' },
  { key: 'balance', label: 'Balance' },
  { key: 'winVsLoss', label: 'W/L' },
];

const tableItems: TableItem<ComparisonItem>   = [
{
    botId: undefined,
    botName: 'Summary',
    profitOpen: 0,
    profitOpenRatio: undefined,
    stakeCurrency: 'USDT',
    wins: 0,
    losses: 0,
  }
];

</script>
```

**Expected behavior.** A clear and concise description of what you expected to happen.

Functionality itself is working perfectly fine - but typechecking with vue-tsc fails with "unknown is not assignable to type number" (the actual type varies by prop).
The above code already contains the necessary cast (`(item as unknown as ComparisonItem)`) - but that's more than cumbersome - and defeats the purpose of using typescript.

Is there any way to pass the type of the items to the table - so the component (and typescript) knows that the parameter for the slot is a `Tableitem<ComparisonItem>` - and has the type accordingly?
TableItem itself knows about the type  (`TableItem<T>`) - but the data comming back out doesn't.

**Screenshots.** If applicable, add screenshots to help explain your problem.
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5024695/7ca59431-94a7-4f62-9bf6-f9ef71bffb9c)

**Environment (please complete the following information):**

- OS: [e.g. Windows 11, Pop!_OS] linux
- Package Version: [e.g. 0.8.12] 0.9.26
- Npm/Yarn/Pnpm Version: [e.g. npm@9.6.6, pnpm@8.5.1]

**Additional context.** Add any other context about the problem here.

**Comment by VividLemon** [comment]
The typing didn't change in the library. What did change was Vue 3.3. In Vue 3.3 defineSlots was introduced. I'm suspecting the default transitioned from "any" to "unknown". Plans to use generics are underway

**Comment by xmatthias** [comment]
>  What did change was Vue 3.3. In Vue 3.3 defineSlots was introduced

i'm not sure about that if i'm honest. 
I've been using vue3.3 in that project a while now - and the last dependabot update ([here](https://github.com/freqtrade/frequi/pull/1368)) (don't ask me why dependabot never proposed any of the prior updates) started to show these signs.
I've since fixed it via explicit casting (last few commits) - but CI for the very first commit shows it [breaking](https://github.com/freqtrade/frequi/actions/runs/5594801498/job/15154421167) (Ci was passing prior to that commit).

**Comment by VividLemon** [comment]
And subsequently during that period _we_ updated to Vue 3.3

**Comment by makroxyz** [comment]
I have the same "issue"..

Could it be related to https://github.com/vuejs/language-tools/issues/2758#issuecomment-1533871006

**Comment by makroxyz** [comment]
Could it help?

https://github.com/vuejs/language-tools/issues/2758#issuecomment-1533871006

**Comment by makroxyz** [comment]
I'm in the same situation.. I can't imagine to  'cast' every single item in table slots...

**Comment by makroxyz** [comment]
I think @VividLemon is working on generics #1316 
This could be a step forward since with 0.10 BTable items property has type warning (previous post)
But I think we need to define cell scopes with defineScopes...

**Comment by makroxyz** [comment]
@VividLemon are you working on that? Can I help you?

**Comment by makroxyz** [comment]
> Though generics are possible with 3.3, they are in a buggy state which makes them near impossible to use. 

I understand... What do you suggest in the meantime? vue-sfc fails to build

**Comment by VividLemon** [comment]
You could make a PR that adds defineSlots to each of the tables without generics and just set the output to any. Just keep in mind the inheritance as things like this wont through errors afaik
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/86a3d5dc-dd81-4c56-8faa-ed43cbb1919d)

**Comment by makroxyz** [comment]
@VividLemon have a look at https://github.com/Shyam-Chen/Vue-Starter/blob/main/src/components/Table.vue this seems to work
