### ISSUE TITLE
BTable no longer updates dynamically with newer versioning

### ISSUE THREAD

**Issue by alexdohm** [bootstrap-vue-next/bootstrap-vue-next#1312]
**Describe the bug.** A clear and concise description of what the bug is.
I recently updated my package.json bootstrap-vue-next version from 0.9.20 to 0.9.26. BTable no longer renders with dynamically changing/updated/filtered data. I've had to move my version back down to 0.9.20 for the app to work. 

**To Reproduce.** Steps to reproduce the behavior:
One of my tables is defined as follows :
```
    <b-table
      :fields="computedFields"
      :items="myProvider"
      no-provider-paging
      :per-page="pagination.perPage"
      :current-page="pagination.currentPage"
      v-model:sort-by="sortBy"
      v-model:sort-desc="sortDesc"
      class="jobs-list"
      hover
      @row-clicked="viewJob"
      :busy="isBusy"
    >
...
   </b-table>
```

My provider is defined as follows:
```
myProvider() {
      let sortedJobs = structuredClone(this.jobs || []);

      const start = new Date(this.timeFilter.start);
      const end = new Date(this.timeFilter.end);

      // If the start or end dates are not valid, fall back to no start/end date
      if (isNaN(start.getTime())) start.setTime(-Infinity);
      if (isNaN(end.getTime())) end.setTime(Infinity);

      return sortedJobs
        .filter((job) => {
          const updatedDate = new Date(job.created.seconds * 1000);
          // Check if searchString is present in the recipe
          let stringMatch = true;
          if (this.filterJob) {
            stringMatch = JSON.stringify(job.name)
              .toLowerCase()
              .includes(this.filterJob.toLowerCase());
          }
          return updatedDate >= start && updatedDate <= end && stringMatch;
        })
        .sort(this.dynamicSort(this.sortBy, this.sortDesc));
    },
```
while dynamic sort just sorts the data based on the sortBy and sortDesc data. `Jobs` needs to load, therefore is initially empty when the page loads. The table should update when `Jobs` is populated or changes, however this does not happen. This occurs with every table in my code that has a similar workflow.

- OS: Mac Ventura 13.3
- Package Version: 0.9.26
- Npm: 8.19.4

**Comment by VividLemon** [comment]
A more robust example may help

**Comment by mediaessenz** [comment]
I think, the cause of this issue is exact the same I already descripted here: https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1331#issuecomment-1696443459
