### ISSUE TITLE
docs: overflow issue in nav when small screen

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1318]
The docs nav has an overflow issue when using small screens

**Comment by StirStudios** [comment]
@VividLemon can you supply a screenshot so I can see the issue? I am debugging on Chrome and cannot cause an overflow issue.

**Comment by VividLemon** [comment]
> @VividLemon can you supply a screenshot so I can see the issue? I am debugging on Chrome and cannot cause an overflow issue.

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/701e72fb-27e9-4f0a-b393-6be692c35636)

Preferably I'd like the "on this page" to go to a new line, but the icons stay at the top, just scrunched together

**Comment by StirStudios** [comment]
Got it, makes sense! Will jump on this in a few. I know I also owe you for the color mode stuff as well.

**Comment by StirStudios** [comment]
Fixed with a PR.
