### ISSUE TITLE
FOWS - Flash of white screen in dark mode

### ISSUE THREAD

**Issue by StirStudios** [bootstrap-vue-next/bootstrap-vue-next#1329]
I don't recall seeing this before. I wonder if this is caused by us needing to upgrade to the color mode?

Here is a video for reference.

https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/25397758/a96dfcba-e395-4bba-895c-371bf972a6e1

**Comment by VividLemon** [comment]
The docs app is being rendered in a sudo-MPA mode as there is an active hydration mismatch in Layout.vue

**Comment by VividLemon** [comment]
It should be noted that Vitepress in "dev" renders as a traditional SPA, so developing and browsing through dev will typically not show these types of issues. Disappointingly. Tbh, it likely has something to do with "isLargeScreen"

**Comment by StirStudios** [comment]
Interesting. I use the docs all the time and I have only just started noticing this (not in dev mode). I am always in dark mode as well. I swear I would have noticed this before.

//Tbh, it likely has something to do with “isLargeScreen"

Makes sense.

**Comment by VividLemon** [comment]
For any future people that found this because they use Vitepress with BVN

When any link has `target="_self"` it will cause Vitepress to ignore SPA routing, thus causing a full page reload. This conflicts with the libraries internal default which places _self as the default target. To fix this use `:target="null"`

**Comment by VividLemon** [comment]
> To fix this use :target="null"

Was a lie, this is no longer an issue. "_self" is no longer the default -- the default of target is undefined. (_self is implicit by the browser)
