### ISSUE TITLE
type-check fails after importing bootstrap-vue-next types

### ISSUE THREAD

**Issue by dnewkerk** [bootstrap-vue-next/bootstrap-vue-next#1330]
**Describe the bug.** A clear and concise description of what the bug is.

If you have imported any types from bootstrap-vue-next into a Vue 3 component, then run the `npm run type-check` command, the type check fails with errors from bootstrap-vue-next, and does not continue type checking the rest of the app. Confirmed in a clean Vue 3 install.

There were no errors in earlier releases, however I've confirmed that errors begin to show up as of version 0.9.20, and a bunch of additional errors appear as of version 0.9.23+

Output of running the command with version 0.9.26 installed:

```
> vue3-app@0.0.0 type-check
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false

node_modules/bootstrap-vue-next/src/components/BBadge/BBadge.vue:104:9 - error TS1005: ',' expected.

104       } satisfies Record<keyof Omit<BLinkProps, 'event' | 'routerTag'>, true>)
            ~~~~~~~~~

node_modules/bootstrap-vue-next/src/components/BBadge/BBadge.vue:104:19 - error TS1005: ',' expected.

104       } satisfies Record<keyof Omit<BLinkProps, 'event' | 'routerTag'>, true>)
                      ~~~~~~

node_modules/bootstrap-vue-next/src/components/BBreadcrumb/BBreadcrumbItem.vue:103:9 - error TS1005: ',' expected.

103       } satisfies Record<keyof Omit<BLinkProps, 'event' | 'routerTag'>, true>)
            ~~~~~~~~~

node_modules/bootstrap-vue-next/src/components/BBreadcrumb/BBreadcrumbItem.vue:103:19 - error TS1005: ',' expected.

103       } satisfies Record<keyof Omit<BLinkProps, 'event' | 'routerTag'>, true>)
                      ~~~~~~

node_modules/bootstrap-vue-next/src/components/BNav/BNavItem.vue:87:5 - error TS1005: ',' expected.

87   } satisfies Record<keyof Omit<BLinkProps, 'event' | 'routerTag'>, true>)
       ~~~~~~~~~

node_modules/bootstrap-vue-next/src/components/BNav/BNavItem.vue:87:15 - error TS1005: ',' expected.

87   } satisfies Record<keyof Omit<BLinkProps, 'event' | 'routerTag'>, true>)
                 ~~~~~~

node_modules/bootstrap-vue-next/src/components/BNavbar/BNavbarBrand.vue:77:9 - error TS1005: ',' expected.

77       } satisfies Record<keyof Omit<BLinkProps, 'event' | 'routerTag'>, true>)
           ~~~~~~~~~

node_modules/bootstrap-vue-next/src/components/BNavbar/BNavbarBrand.vue:77:19 - error TS1005: ',' expected.

77       } satisfies Record<keyof Omit<BLinkProps, 'event' | 'routerTag'>, true>)
                     ~~~~~~

node_modules/bootstrap-vue-next/src/directives/BPopover.ts:43:3 - error TS1005: ';' expected.

43 } satisfies Directive<ElementWithPopper>
     ~~~~~~~~~

node_modules/bootstrap-vue-next/src/directives/BTooltip.ts:45:3 - error TS1005: ';' expected.

45 } satisfies Directive<ElementWithPopper>
     ~~~~~~~~~

Found 10 errors in 6 files.

Errors  Files
     2  node_modules/bootstrap-vue-next/src/components/BBadge/BBadge.vue:104
     2  node_modules/bootstrap-vue-next/src/components/BBreadcrumb/BBreadcrumbItem.vue:103
     2  node_modules/bootstrap-vue-next/src/components/BNav/BNavItem.vue:87
     2  node_modules/bootstrap-vue-next/src/components/BNavbar/BNavbarBrand.vue:77
     1  node_modules/bootstrap-vue-next/src/directives/BPopover.ts:43
     1  node_modules/bootstrap-vue-next/src/directives/BTooltip.ts:45
```

**To Reproduce.** Steps to reproduce the behavior:

1. Install latest Vue 3 with Vite.
2. Run `npm run type-check` to confirm no errors.
3. Install and configure bootstrap-vue-next according to the install instructions.
4. Run `npm run type-check` to confirm still no errors just due to install.
5. Open any .vue component in the app and import a type from bootstrap-vue-next and save the file (tested with various type imports), e.g. `import type { PlaceholderAnimation } from 'bootstrap-vue-next/src/types'`
6. Run `npm run type-check` and the errors should appear.

**Expected behavior.** A clear and concise description of what you expected to happen.

No errors related to bootstrap-vue-next when running type-check command.

**Environment (please complete the following information):**

- OS: macOS 12.6.6
- Package Version: 0.9.20 - 0.9.26
- Npm/Yarn/Pnpm Version: tested npm@8.19.3 and npm@9.6.7

**Comment by VividLemon** [comment]
So there's a few things to unpack here
1. "Satisfies" is a TypeScript 4.9 feature. Perhaps you should check that you are indeed utilizing >4.9. You stated that you did a clean install of Vue 3, but that could mean a lot of things, as the most current and best method is using `npm create vue@3` which will install TypeScript >5
2. `import type { PlaceholderAnimation } from 'bootstrap-vue-next/src/types'` is not valid. Use `import type { PlaceholderAnimation } from 'bootstrap-vue-next'`. This indicates to me another issue with your TypeScript setup as it should fail with `Cannot find module 'bootstrap-vue-next/src/types' or its corresponding type declarations.ts(2307)` or an issue about respecting the libraries package.json exports list

You'd need to make a more robust reproduction

[vue-project.zip](https://github.com/bootstrap-vue-next/bootstrap-vue-next/files/12207512/vue-project.zip)

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1389
