### ISSUE TITLE
B-Table not working as expected after update from v0.8.15 to further versions

### ISSUE THREAD

**Issue by soorajsprakash** [bootstrap-vue-next/bootstrap-vue-next#1331]
**Describe the bug.**: 
B-Table not working as expect after update from v0.8.15 to further versions, including the latest v0.9.26. I followed the docs and updated the code, but its not working as expected. 

**To Reproduce.** :

1 .Initially our b-table code was like:

```vue
<b-table
        v-model:busy="isBusy"
        :items="items"
        :fields="fields"
        v-model:sort-by="sortBy"
        v-model:sort-desc="sortDesc"
        responsive="sm">

        <template v-slot:cell(createdAt)="data">
            {{ data.value }}
        </template>
        <template v-slot:cell(expires)="data">
            {{ data.value }}
        </template>
</b-table>
```
And then it would show table like: 
| Created At | Expires |
| - | - |
| 20 Jan 2023 | 20 March 2023 |
| 1 Sept 2022 | Never |

2. But now after the upgrade, its only showing the headers, value is not being shown. I modified the `b-table` code as follows:

```vue
<b-table
        :busy="isBusy"
        :items="items"
        :fields="fields"
        v-model:sort-by="sortBy"
        v-model:sort-desc="sortDesc"
        responsive="sm">

        <template v-slot:select-cell(createdAt)="data">
            {{ data.value }}
        </template>
        <template v-slot:select-cell(expires)="data">
            {{ data.value }}
        </template>
</b-table>
```
This is the output:
| Created At | Expires |
| - | - |

Here, when i inspect the tbody, its empty.

*** 

**Expected behavior**:
Expected to show the values.

**Screenshots**: 
Not necessary as no errors including typescript errors are thrown. Its just that no T-body i shown. 

**Environment:**

- OS: Ubuntu 23.04
- Package Version: Starting from v0.9.0. (Last working was v0.8.15)
- Npm Version: npm@8.19.3

*** 

If I'm doing it wrong, I'm sorry, but please throw some light on this.

**Comment by susanne99** [comment]
I have exactly the same thing, please fix it as soon as possible, this is a megabug
#1335

**Comment by VividLemon** [comment]
I'm going to need a reproduction because I'm seeing accurate things on my end.

**Comment by susanne99** [comment]
it is easy :)
compare version 0.9.23 with a higher version, then you will find the difference and see what happend.
version 0.9.23 is the latest working version with b-table !!!

**Comment by makroxyz** [comment]
Try 0.10. anyway I'm using BTable w/o any major issue. Can you post some
code?

Il mar 8 ago 2023, 07:20 susanne99 ***@***.***> ha scritto:

**Comment by soorajsprakash** [comment]
@makroxyz tried 0.10.0 rn and its still not working as expected.
```
        <b-table
            ref="table"
            :busy="isBusy"
            :items="keys"
            :fields="fields"
            v-model:sort-by="sortBy"
            v-model:sort-desc="sortDesc"
            responsive="sm"
        >
            <template v-slot:table-busy>
                <div class="text-center text-danger my-2">
                    <font-awesome-icon icon="spinner" class="fa-spin fa-fw center" />
                    <strong>Loading...</strong>
                </div>
            </template>
            <template v-slot:select-cell(index)="data">
                {{ data }}
            </template>
            <template v-slot:select-cell(createdAt)="data">
                {{ data }}
            </template>
            <template v-slot:select-cell(apiKey)="data">
                {{ data }}
            </template>
            <template v-slot:select-cell(expiresAt)="data">
                {{ data }}
            </template>
            <template v-slot:select-cell(actions)="data">
                {{ data }}
            </template>
        </b-table>
```

This is the bare minimum code, which was working fine in 0.8.15. But after that for any versions I'm not able to get it working,

I couldn't figure out what went wrong.

**Comment by soorajsprakash** [comment]
Also @VividLemon BTable playground is not updated right? Also BTable doc is missing.

**Comment by makroxyz** [comment]
it works for me 

```vue
        <b-table
            ref="table"
            :busy="isBusy"
            :items="keys"
            :fields="fields"
            v-model:sort-by="sortBy"
            v-model:sort-desc="sortDesc"
            responsive="sm"
        >
            <template v-slot:table-busy>
                <div class="text-center text-danger my-2">
                    <font-awesome-icon icon="spinner" class="fa-spin fa-fw center" />
                    <strong>Loading...</strong>
                </div>
            </template>
            <template #cell(index)="data">
                {{ data.value }}
            </template>
            <template #cell(createdAt)="data">
                {{ data.value }}
            </template>
            <template #cell(apiKey)="data">
                {{ data.value }}
            </template>
            <template #cell(expiresAt)="data">
                {{ data.value }}
            </template>
            <template #cell(actions)="data">
                {{ data.value }}
            </template>
        </b-table>

```

**Comment by soorajsprakash** [comment]
Sorry, forgot to mention that I'm dynamically setting "keys" value `beforeMount()` from backend using api calls.

**Comment by makroxyz** [comment]
So is it working now?

**Comment by soorajsprakash** [comment]
@makroxyz if the keys are static its working, 
If its dynamic, like when fetched from api, then it's not working. 
Checking docs now. 
Will update.

**Comment by rubebop** [comment]
I'm also experiencing lots of problems: I tried to update from 0.9.9 to 0.10.1 (and I tried the whole thing twice) → `b-table` was not working. Sometimes the headers were missing, sometimes the items/rows were missing and in other instances, everything was missing. I couldn't figure out a pattern. Personally, I'm sticking to 0.9.9 until this issue is cleared.

**Comment by soorajsprakash** [comment]
For me, all other things were working. Like the headers and all.
My table is not selectable or anything,

**Comment by susanne99** [comment]
Nice that it works for you, but there are several users where it doesn't work. we have been using the table for a long time, from 0.9.23 it no longer works without us having changed anything. I have 100 tables in my program, I can't change them all!

**Comment by makroxyz** [comment]
> Nice that it works for you, but there are several users where it doesn't work. we have been using the table for a long time, from 0.9.23 it no longer works without us having changed anything. I have 100 tables in my program, I can't change them all!

Could you post an example?

**Comment by susanne99** [comment]
not really, sorry, because it is a big app, and all my tables are dyn. filled with data from server. i don't have any "static table"

the problem exists, see other issues

 
 

Gesendet: Donnerstag, 10. August 2023 um 12:40 Uhr
Von: "Marco Curatitoli" ***@***.***>
An: "bootstrap-vue-next/bootstrap-vue-next" ***@***.***>
Cc: "susanne99" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [bootstrap-vue-next/bootstrap-vue-next] B-Table not working as expected after update from v0.8.15 to further versions (Issue #1331)


 


Nice that it works for you, but there are several users where it doesn't work. we have been using the table for a long time, from 0.9.23 it no longer works without us having changed anything. I have 100 tables in my program, I can't change them all!


Could you post an example?

**Comment by VividLemon** [comment]
So have any of you managed to figured out why you are having issues? Because I check a week later, and I still don't have a single replication

**Comment by soorajsprakash** [comment]
@VividLemon yes, ill explain.

If you pass the `items` directly as a data property, it works good. 

But when you add the items dynamically, say over an api call or something, then it won't display any rows.

Eg:
Lets say we initialise the `items` as an empty array in the data property. And then we fetch it in hook stage, say in `beforeMount`, we make the api call and set the `items` dynamically. At that time, it won't load the dynamically added rows. It still shows empty as we set in the data property.

**Comment by memen45** [comment]
Same issue here. I am using a vue ref as the items property, which is filled and updated with data from an API through SWRV (Stale-While-Revalidate for Vue). The table only takes the first value of the ref, and after that, the data remains the same. A minimal example:

```ts
<script setup lang="ts">
import useSWRV from 'swrv';
import { reactive } from 'vue';


interface ResponseType {
    items: Array<{
        id: number
        name: string
        total: number
    }>
}
let search = reactive({ pageSize: 10 });
const { data, error, isValidating, mutate } = useSWRV<ResponseType>(
    () => search ? '/url_to_api/?pageSize=' + search.pageSize : undefined
);
</script>

<template>
    <b-table :items="data?.items"></b-table>
</template>
```
In this example, the types are as follows:
`const data: Ref<ResponseType | undefined>;`
`const error: Ref<any>;`
`const isValidating: Ref<boolean>;`

Interestingly, adding the `:busy=isValidating` prop actually works perfectly. When changing e.g. the search from elsewhere, SWRV  will revalidate and the loading is shown during the fetching. So, it seems to affect the `:items` prop only.

Opening Vue devtools, I noticed that BTable contains a BTableLite. BTable shows the updated items prop value, while BTableLite shows only the initial items prop value. Hope this helps!

**Comment by mediaessenz** [comment]
Changing the per-page value dynamically is also not working. 

BTable stays at the initial value.

**Comment by mediaessenz** [comment]
I think I found at least one cause of this problem!

If I change this code part inside BTable.vue (line 242):
```typescript
const {
  computedItems,
  computedDisplayItems,
  updateInternalItems,
  filteredHandler,
  notifyFilteredItems,
} = useTableItems(
  props,
  {
    sortInternalBoolean,
    isFilterableTable,
    noProviderPagingBoolean,
    isSortable,
    requireItemsMapping,
    sortDescBoolean,
  },
  usesProvider,
  sortByModel
)
```
to this:
```typescript
const {
  internalItems,
  computedItems,
  updateInternalItems,
  filteredHandler,
  notifyFilteredItems,
  computedDisplayItems,
} = useTableItems(
  props,
  {
    sortInternalBoolean,
    isFilterableTable,
    noProviderPagingBoolean,
    isSortable,
    requireItemsMapping,
    sortDescBoolean,
  },
  usesProvider,
  sortByModel
)
```
at least the per-page prop is working now.

**Comment by mediaessenz** [comment]
I think I finally (after several hours deep diving) find the cause of the problem.

It stucks in the useTableItems composable inside the computedItems and  computedDisplayItems const definition.

Since this condition is in most cases true in case of using a table data provider:
```typescript
if (usesProvider.value && !flags.noProviderPagingBoolean.value) {
      return items
    }
```
this returns an empty array, because displayStartEndIdx has its initial value [0,0] (last one is zero, because internalItems.value.length = 0, because items prop is a empty array in the beginning.
Because of this, `return computedItems.value.slice(displayStartEndIdx.value[0], displayStartEndIdx.value[1])` returns an empty array as well, since displayStartEndIdx.value[0] = 0 and displayStartEndIdx.value[1] = 0.

Since the pagination is normaly done by the provider function it self (or better the api who delivers the data), there is no slice needed.

To fix this issue, an easy solution could look like this:
```typescript
const computedDisplayItems = computed<TableItem[]>(() => {
    if (
      tableProps.perPage === undefined ||
      (usesProvider.value && !flags.noProviderPagingBoolean.value)
    ) {
      return computedItems.value
    }
    return computedItems.value.slice(displayStartEndIdx.value[0], displayStartEndIdx.value[1])
  })
```
I created a forge of this repo, where I also enhance the filter prop to allow an object and some other small thinks.
I don't know if it makes sense, that I create a pull request for it, since I didn't followed the contribution guidelines (commit message format, more than one topic in one PR ...)

**Comment by mbain** [comment]
Even in the old Bootstrap-Vue, there were certain workarounds that you needed to perform in the case of async data loading.  Two possible workarounds:
-Set a `key:` prop on the table, and bind it to a data member that you increment whenever your data refreshes
-Add a `v-if` attribute to the table, and set it to a variable that evaluates to true when your data is loaded.

**Comment by lasolitudey** [comment]
I also have this problem. 
But I find the way to trigger this problem that when I add the sortable in fields, the data will missing.
If there is no sortable prop, data will be displayed.
```
// work fun
{ key: 'account', label: 'account' },

// didn't work
{ key: 'account', label: 'account', sortable: true },
```

**Comment by rubebop** [comment]
> Even in the old Bootstrap-Vue, there were certain workarounds that you needed to perform in the case of async data loading. Two possible workarounds: -Set a `key:` prop on the table, and bind it to a data member that you increment whenever your data refreshes -Add a `v-if` attribute to the table, and set it to a variable that evaluates to true when your data is loaded.

Adding something like `:key="JSON.stringify(myItems)"` is not only a bit ugly but also doesn't seem to work.

**Comment by cucuianr1978** [comment]
Hi, I have the same issue. When data is static it works perfectly. But when you change the source and filter, it is not working anymore. I add here an example with a component : **Select group 2 then filter by red word.**

<template>
    <b-row>
        <b-col sm="3">
            <b-form-select
                           :options="tableGroups"
                           v-model="selectedGroup"
                           textField="Name"
                           valueField="Id"
                           @input="groupSelected">
            </b-form-select>
        </b-col>
        <b-col sm="6">
            <b-form-input v-model="filterInput"
                          size="sm"
                          type="search"
                          placeholder="Type to Search"></b-form-input>
        </b-col>
    </b-row>

    <b-row>
        <b-col sm="12">
            <b-table :items="tableGroupItems"
                     :fields="fields"
                     :filter="filterInput"
                     filterable="['Code', 'Description']"
                     hover striped
                     show-empty
                     variant="light"
                     @filtered="onFiltered">
            </b-table>
        </b-col>
    </b-row>

</template>
<script >
    export default {
        name: 'FilterTableError',
        data: () => {
            return {
                selectedGroup: null,
                tableGroups: [],
                tableItems: [],
                tableGroupItems: [],
                fields: [],
                filterInput: '',
            }
        },
        created() {
            this.tableGroups = [
                { Id: 1, Name: 'Group 1' },
                { Id: 2, Name: 'Group 2' }
            ];
            this.fields = [
                { key: 'Description' },
                { key: 'Code' }
            ];
        },
        methods: {
            groupSelected(value) {
                let results = [];
                if (value == 1) {
                    results = [
                        { Description: 'apple', Code: '1' },
                        { Description: 'orange', Code: '2' }
                    ];
                }
                else {
                    results = [
                        { Description: 'pineapple', Code: '3' },
                        { Description: 'red orange', Code: '4' },
                        { Description: 'apple pie', Code: '5' }
                    ];
                }
                this.tableGroupItems = results;
            },
            onFiltered(filteredItems) {
                console.log(filteredItems);
            },
        }
    }
</script>

**Comment by balane** [comment]
I don't know if it's the same issue for everyone here but I found that upgrading past 0.9.26 broke my tables. After a lot of debugging it was because the keys for our items had periods "." in them. Once I replaced the periods wit underscores I could fully upgrade to 0.14.8.

//items
return data.map((key) => {
                //remove periods from keys because Bootstrap Vue Next > 0.9.26 doesn't like them
                return JSON.parse(JSON.stringify(key).replaceAll(".", "_"));
            }); 

//keys
return columns.map(({ key, shortTitle }) => {
                return {
                    key: key.replace(".", "_"),
                    label: shortTitle,
                    sortable: false,
                };
            });

**Comment by soorajsprakash** [comment]
Hi guys,  i just updated bvn to the latest version (v0.14.10) and bTable is working as expected. I have not made any changes apart from the ones i mentioned while opening the issue. 

If anyone have the same issue, please feel free to reopen the issue.
Thanks.

**Comment by Yan-Doshchinskiy** [comment]
I have same problem with v0.14.10

**Comment by VividLemon** [comment]
There isn't a whole lot of information as to what exact issue this issue seems too relate to. It simply states "just doesn't work". Regardless of this, I have tested variations of using the provider prop and things seem to be working on 0.15

**Comment by memen45** [comment]
Where/when is 0.15 scheduled for release? Cause the only reference I see is in the #1533 'chore release main' pull request, but it seems to be blocked?
