### ISSUE TITLE
`v-b-toggle` directive not working on dropdown items

### ISSUE THREAD

**Issue by darthf1** [bootstrap-vue-next/bootstrap-vue-next#1332]
**Describe the bug.** A clear and concise description of what the bug is.

Hi. When I use the `v-b-toggle` directive on a `b-button` component, it works like a charm. But when I use it on one of the `b-dropdown` subcomponents, it stops working. It looks like it stops working on any component which is wrapped by the `b-dropdown`.

**To Reproduce.** Steps to reproduce the behavior:
Works:

```vue
<template>
  <b-button v-b-toggle:my-modal>toggle</b-button>

  <b-modal id="my-modal">
    ...
  </b-modal>
</template>
```

Does not work:
```vue
<template>
  <b-dropdown>
    <b-dropdown-item-button v-b-toggle:my-modal>toggle</b-dropdown-item-button>
  </b-dropdown>

  <b-modal id="my-modal">
    ...
  </b-modal>
</template>
```

Also does not work (just for testing purposes):
```vue
<template>
  <b-dropdown>
    <b-button v-b-toggle:my-modal>toggle</b-button>
  </b-dropdown>

  <b-modal id="my-modal">
    ...
  </b-modal>
</template>
```

**Expected behavior.** A clear and concise description of what you expected to happen.
I would expect the directive to work for at least the `b-dropdown-item-button` component.

**Environment (please complete the following information):**

- OS: Ubuntu 23.04
- Package Version: 0.9.26
- Pnpm Version: 8.6.11

**Comment by phlegx** [comment]
Downgrade at least to 0.9.24. Version 0.9.25 produces the bug.

**Comment by VividLemon** [comment]
I found an issue with the code while working on this. BModal in your code does not have a bound v-model. 

I'm not sure how this code worked before, but afaik it shouldn't have worked. 

I worked out a fix to where the present code should work in all cases coming 0.10

**Comment by phlegx** [comment]
@VividLemon if I add `v-model='offcanvas.show'` to `b-offcanvas` and use `v-b-toggle.main-menu` on the `b-nav-item` it does not work with v0.10.0.

**Comment by VividLemon** [comment]
> @VividLemon if I add `v-model='offcanvas.show'` to `b-offcanvas` and use `v-b-toggle.main-menu` on the `b-nav-item` it does not work with v0.10.0.

@phlegx If this is true, create a new issue with a reproduction
