### ISSUE TITLE
Inject modal id to default slot

### ISSUE THREAD

**Issue by ms-mayya** [bootstrap-vue-next/bootstrap-vue-next#1333]
Can we inject generated modal id to default slot?

use case:

ComponentA.vue (with a custom modal footer):
```vue
<template>
   ...
   <Teleport :to="modal.id + '.modal-content'" />
</template>
<script setup>
   const modal = inject(BModalRef) // { id: string, ... }
</script>
```

The modal:
```vue
<BModal hide-footer>
 <ComponentA />
</BModal>
```

**Comment by VividLemon** [comment]
I don't get what you're trying to do

**Comment by ms-mayya** [comment]
Want to access parent `<BModal />` instance inside `<ComponentA />` , so the modal can be directly closed by it's child(slot) component or teleport the custom modal footer inside `<CompanentA />` to the modal without manually specify the id of modal.

**Comment by asika32764** [comment]
Try this workaround https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/120#issuecomment-1712844079 before  https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1430 get merged.

**Comment by VividLemon** [comment]
I still don't get the point

**Comment by ms-mayya** [comment]
What i want to achive is somthing like #1430 . without passing id or prop around to close the modal. and the problem has been resolved. thanks.
