### ISSUE TITLE
"Unhandled error during execution of scheduler flush" while using b-overlay

### ISSUE THREAD

**Issue by tbl0605** [bootstrap-vue-next/bootstrap-vue-next#1334]
Hi,
first of all, thank you for this great project ;)
I only had an issue so far and it was while using the b-overlay component.

I tried to create a demo based on my code by since it's very complex I tried to simplify it as much as possible.
Also, the problem seems only to happen in development mode, so I couldn't use my code with codesandbox.io for example.

When using the demo (in development mode), you'll get following error:
```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <BaseTransition mode=undefined appear=false persisted=false  ... > 
  at <Transition mode=undefined css=true name="fade"  ... > 
  at <BTransition no-fade=true trans-props= 
Object { enterToClass: "show" }
 name="fade"  ... > 
  at <BOverlay show=true opacity="0.6" no-fade=true > 
  at <AsyncVeeInput modelValue="A" onUpdate:modelValue=fn modelModifiers= 
Object { trim: true }
  ... > 
  at <Form class="needs-validation" novalidate="" onSubmit=fn > 
  at <HomeView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView> 
  at <App>
```

**To Reproduce.**

1. Fetch the [demo](https://github.com/tbl0605/boostrap-vue-next-demo)
```
git clone https://github.com/tbl0605/boostrap-vue-next-demo
cd boostrap-vue-next-demo
npm install
npx vite --port=4000
```
2. Write "a" (without the quotes) in the input field
3. See errors in console

**Expected behavior.**
No errors.

**Workaround**
Removing (or commenting out) the b-overlay component makes everything work again.

**Environment:**
- bootstrap-vue-next: 0.10.6
- Vite: 4.4.9
- Firefox and Chrome

**Comment by mbabker** [comment]
Seeing the same with 0.10.1 and Vue 3.3.4.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading '_leaveCb')
    at Object.beforeEnter (runtime-core.esm-bundler.js:2127:1)
    at mountElement (runtime-core.esm-bundler.js:5244:1)
    at processElement (runtime-core.esm-bundler.js:5156:1)
    at patch (runtime-core.esm-bundler.js:5028:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5773:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:1)
    at instance.update (runtime-core.esm-bundler.js:5814:1)
    at updateComponent (runtime-core.esm-bundler.js:5641:1)
    at processComponent (runtime-core.esm-bundler.js:5576:1)
    at patch (runtime-core.esm-bundler.js:5040:1)
```

When I expand out that stack trace in my browser dev console, it seems like the issue comes from when the `show` prop is dynamic and is updated.

```vue
<BOverlay :show="isCheckingInCustomer || isLoadingEvent || isLoading" spinner-variant="primary">
  <!-- inner content -->
</BOverlay>
```

**Comment by tbl0605** [comment]
Hi @VividLemon,
I updated my demo to use bootstrap-vue-next v0.10.6 and sadly the problem still occurs.

**Comment by tbl0605** [comment]
The bug is still valid with bootstrap-vue-next 0.16.0
I updated my demo to make it work with more recent versions of Node.js

**Comment by AKustov26** [comment]
I think my PR #1782  should solve this problem.

**Comment by tbl0605** [comment]
Hi @AKustov26,
you are right, this bug doesn't show up again after your PR was merged.
Thank you very much! :)
