### ISSUE TITLE
[0.9.26] !!!!!!!!!!!!!!!!!!!!!!!  B-Table does not work at all !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1335]
for god's sake what have you done. 
I didn't notice it right away, but the tables don't always show the data from the "items" property. 
I'm definitely not rebuilding my program, there are 100 tables in it, they all worked great!!!!

**Comment by makroxyz** [comment]
Have a look at #1308

Il dom 6 ago 2023, 08:52 susanne99 ***@***.***> ha scritto:

**Comment by susanne99** [comment]
i don't understand, why did you close.
the last working version is 0.9.23 .sine then the b-table has this very big bug !!!

**Comment by makroxyz** [comment]
@susanne99 
Are you sure that it is a bug? #1331
