### ISSUE TITLE
Can't import BTableProvider, BTableProviderContext

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1340]
I can't import these types... 
They aren't in @/types/exports and they're imported as bootstrap-vue-next/dist/src/types 

Bootstrap-vue-next 0.10.0 fresh node_modules folder

**Comment by VividLemon** [comment]
Make a PR

**Comment by VividLemon** [comment]
(All you need to do is add them to `types/exports/index.ts` btw)
