### ISSUE TITLE
Cannot install 0.10.0 with latest nuxt package

### ISSUE THREAD

**Issue by darthf1** [bootstrap-vue-next/bootstrap-vue-next#1341]
Hi,

I would like to try `v0.10.0`, but with the nuxt package `v0.1.3` I get a peerdependency issue:

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/17253332/dd9991a0-8fd8-4bc7-a8b9-321946d93e2e)

**Comment by cRoberts2-18** [comment]
+1 when updating to 0.10.1 I get the following error
<img width="584" alt="Screenshot 2023-08-14 at 13 26 45" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/75317368/b48df410-fa04-47a6-a916-9a72068318eb">
With
 ```
"bootstrap-vue-next": "^0.10.1",
"@bootstrap-vue-next/nuxt": "^0.1.3",
```
In dev dependencies

**Comment by VividLemon** [comment]
Update your /nuxt package

I will keep this in mind for the future. I was unaware of an npm rule.
