### ISSUE TITLE
Modal no longer displaying with version 0.10.0

### ISSUE THREAD

**Issue by adholland** [bootstrap-vue-next/bootstrap-vue-next#1342]
Modal dialog no longer displays with the latest version (0.10.0). The modal dialogs were successfully displaying with a number of the recent previous versions (including 0.9.16).

The is the properties I have been using and up to now working without issue: -
```
<template>
    <b-modal  
        :id="id"
        v-model="showModal"
        teleportTo="#da-teleport-area"
        modalClass="da-modal"
        dialogClass="da-modal-dialog"
        headerClass="da-modal-header"
        bodyClass="da-modal-body"
        contentClass="da-modal-content"
        footerClass="da-modal-footer"
        :title="title"
        centered
        no-close-on-backdrop
        lazy
        @close="handleClose"
    >
...
```

Please advise.

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/8c5f922e-4aa0-42da-b20b-483f7a1aafdd

**Comment by adholland** [comment]
@VividLemon Thanks for getting back to me. I can categorically state that for version 0.10.0 modals are no longer working for me. It is on 0.9.16 and before.

What seems to be missing is the following: -
on the root modal div (.modal) it is missing `display: block` 
on the child modal div (.modal-dialog) the z-index is missing.  It should be `z-index: 1051`.

Adding both manually shows the dialog as expected. Possibly it is as a result of using teleport not sure, but my simple vue file is as follows: -

```
<template>
    <b-modal  
        :id="id"
        v-model="showModal"
        teleportTo="#da-teleport-area"
        modalClass="da-modal"
        dialogClass="da-modal-dialog"
        headerClass="da-modal-header"
        bodyClass="da-modal-body"
        contentClass="da-modal-content"
        footerClass="da-modal-footer"
        :title="title"
        centered
        no-close-on-backdrop
        lazy
        @close="handleClose"
    >
        <template #header>
            <slot name="modalHeader"></slot>
        </template>
        <slot name="modalContent"><span v-html="message"></span></slot>
        <template #footer>
            <slot name="modalFooter"></slot>
        </template>
    </b-modal>
</template>

<script>

export default {
    name: "SimpleModal",
    props: {
        id: {
            required: true,
            type: String 
        },
        message: {
            required: false,
            type: String
        },
        title: {
            required: false,
            type: String
        }
    },
    data() {
        return {
            showModal: false,
        };
    },
    methods: {
        show() {
            this.showModal = true;
            this.$emit('show');
        },
        hide() {
            this.$nextTick(() => {
                this.showModal = false;
            });
        },
        handleClose() {
            this.hide();
            this.$emit('close');
        }
    }
};
</script>
```

**Comment by adholland** [comment]
@mbabker yes that looks to be the issue and related to https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1260.

I need to import the scss, but it is not complete, so I have to copy the contents of the css file and place within my own scss file. A bit of a hack. Moving to the latest version I hadn;t taken the associated css and bundled into my local scss file.

Closing the issue for now. 

Thanks for the help.
