### ISSUE TITLE
BModal  Initialization bug 

### ISSUE THREAD

**Issue by nszbf** [bootstrap-vue-next/bootstrap-vue-next#1354]
**Describe the bug:** When I have an external JavaScript that inserts a div into DOMContentLoaded, BModal will replace the contents inside.

**To Reproduce.** Steps to reproduce the behavior:

1. [Go to 'https://stackblitz.com/edit/nuxt-starter-chwmew?file=src%2Fpublic%2Fot.js'](https://stackblitz.com/edit/nuxt-starter-chwmew?file=src%2Fpublic%2Fot.js)

**Expected behavior.** A clear and concise description of what you expected to happen.

**Screenshots.** If applicable, add screenshots to help explain your problem.
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/16892834/bb6a1217-b922-4be6-a495-ea6efa3ce22d)

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/16892834/c047b942-a57b-41fd-9fa6-d00c9d5dc17c)

**Environment (please complete the following information):**

- Package Version: 0.9 0.10

**Comment by VividLemon** [comment]
Having external JavaScript combined with Vue is generally not recommended because of this exact problem.

**Comment by VividLemon** [comment]
That's the behavior of a teleport. This is a vue issue. If you want to modify the teleport, you can use teleportTo prop. You're using Nuxt. So plan accordingly. Closing as it's not a Vue bug, not a Nuxt bug, not a bootstrap-vue-next bug.

**Comment by VividLemon** [comment]
That being said, a nexttick or somehow waiting a time period may also fix it, but it may not fix it "under all circumstances"
