### ISSUE TITLE
`input` property of `<BFormInput>` is undefined

### ISSUE THREAD

**Issue by Atokulus** [bootstrap-vue-next/bootstrap-vue-next#1363]
Hi there 😊
I hope you are all doing fine.
When trying to migrate one of my applications to the latest versions of `bootstrap-vue-next` I stumbled open the following issue:

The `input` property of a `<BFormInput>` is undefined. This is contrary to documentation and has been working in past versions of *bootstrap-vue-next*. We use it frequently to call methods like 

```
this.$refs.newPassword.input.setCustomValidity()
this.$refs.newPassword.input.checkValidity()
this.$refs.newPassword.input.reportValidity()
```

To reproduce, check out the offical documentation example in https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-input.html#input-methods

Best regards
Markus

**Comment by xvaara** [comment]
@VividLemon should we actually expose input ref from every form component? Seems that this is missing after script setup refactor.

**Comment by VividLemon** [comment]
> should we actually expose input ref from every form component 

Yes
