### ISSUE TITLE
deep selector to inner class of BPopover does not work

### ISSUE THREAD

**Issue by fifzteen** [bootstrap-vue-next/bootstrap-vue-next#1379]
**Describe the bug.** 
deep selector to inner class of BPopover does not work

**To Reproduce.**

see [stackblitz](https://stackblitz.com/edit/vitejs-vite-e6giwr)

```vue
<script setup>
import { ref } from 'vue';

const value = ref('');
</script>

<template>
  <b-form-input id="input-outer" v-model="value" />
  <b-popover
    target="input-outer"
    v-bind:triggers="['click']"
    custom-class="custom-tip"
  >
    <b-form-input v-model="value" />
  </b-popover>
</template>

<style lang="scss" scoped>
.custom-tip {
  // doesn't work!
  :deep(.popover-body) {
    background-color: #aaaaaa;
    border-color: #aaaaaa;
    border-radius: inherit;
  }

  :deep(.popover-arrow) {
    &::before,
    &::after {
      border-top-color: #aaaaaa;
    }
  }
}
</style>
```

**Screenshots.**

![BTooltip_issues_on_Vue3_-_next_resolved__-_actual](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/25410805/89197282-430d-4bc2-8403-b1f04e839574)

`data-v-{hash:8}` attribute is not on BPopover.

If add `data-v-{hash:8}` attribute to popover element, it works as expected.

![BTooltip_issues_on_Vue3_-_next_resolved__-_expected](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/25410805/890cfa58-c9e3-40f8-907c-8c5667618069)

**Environment (please complete the following information):**

- OS: macOS 12.6.5
- Package Version: 0.10.8

**Additional context.** 

I'm trying the issue I posted on BootstrapVue repository below is resolved on BootstrapVueNext. 

https://github.com/bootstrap-vue/bootstrap-vue/issues/7151

1 and 3 are works fine!
If 2 (this issue) also resolved, I will use BootstrapVueNext on my product.

**Comment by xvaara** [comment]
Deep selectors don't work on multiroot node components like popover. It's as intended.

You need to use a wrapper for the popover to have the class correctly: https://stackblitz.com/edit/vitejs-vite-3tw7zd?file=src%2FApp.vue
