### ISSUE TITLE
Checkbox & radio issues

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue-next/bootstrap-vue-next#1382]
If you use array as v-model checkbox overwrites the array to value (ie [] -> 1).

just test on playground.
https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/130606/780c5faf-3f55-4187-b2bf-f416e4be5b2a

Or documentation: https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-checkbox.html#checkbox-values-and-v-model

Worked on 0.7.x, just upgraded to 0.10 and many things have changed for the worst. Will keep updating the bug reports.

**Comment by Kronhyx** [comment]
same here!

**Comment by xvaara** [comment]
it seems you're overriding the vue's native way of handling input elements: https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/d6257550f7907800e06e5b42b2605a3e567ee31d#diff-fe736d79412d0c67d64c9eb398a2089cacec94461d0f69f5376ad66caa9bcd3e

Why?

**Comment by VividLemon** [comment]
There are many issues with the implementation of both that and radio. The issue is likely to do with attempting to coordinate the feature for checked/unchecked as that is not a native feature. If that did not exist, then none of that code would not need to exist.

**Comment by VividLemon** [comment]
Related https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1278
