### ISSUE TITLE
Typescript error: Build vue project, receive: Type parameter declaration expected

### ISSUE THREAD

**Issue by marciado** [bootstrap-vue-next/bootstrap-vue-next#1389]
**Describe the bug.** A clear and concise description of what the bug is.
I use a vue3 project with typescript and webpack. I used the old installation process and the recommended but nothing works if you run `npm run build`

**Expected behavior.**

Build without exceptions

**Screenshots.** 
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/94978135/68061efb-ab8a-498a-aa4d-6bfde7f8a9c6)

**Environment (please complete the following information):**

- OS: Linux
- Package Version: 0.10.10
- Npm/Yarn/Pnpm Version: 9.8.1

**Comment by bjni** [comment]
@marciado
We are having the exact same issue. What was your solution?
Thanks in advance

**Comment by marciado** [comment]
> @marciado We are having the exact same issue. What was your solution? Thanks in advance

In my case I had to update the typescript version to latest... seems that this library needs some of the new introduced types. A warning or a information would be useful

**Comment by VividLemon** [comment]
It is a typescript v5 feature https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters

**Comment by bjni** [comment]
Thanks for the quick responses, updating fixed the issue
