### ISSUE TITLE
BNavItem doesn't support active with "to"

### ISSUE THREAD

**Issue by thekarinka** [bootstrap-vue-next/bootstrap-vue-next#1395]
If I am using BNavItem with link in to attribute, it does not work active highlight, when I change it to href attribute it works.

**To Reproduce.** 

Run this code
```vue
    <BNav pills>
      <BNavItem class="nav-item" to="/to" :active="true"> active nav item with to </BNavItem>
      <BNavItem class="nav-item" href="/href" :active="true"> active nav item with href </BNavItem>
    </BNav>
``` 

**Expected behavior.** 
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/7302263/bc861862-53df-4760-953b-49334fd370df)

**Screenshots - actual behaviour** 
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/7302263/78b01dd8-ea9d-457c-81b1-24aeec1779b5)

**Environment (please complete the following information):**
- OS: Ubuntu
- Package Version: 0.10.10
- Npm/Yarn/Pnpm Version: yarn@1.22.19

**Comment by suzumejakku** [comment]
Did it work like this on Bootstrap-Vue ? 

I also have <BNavItem>s with to attributes, and Bootstrpa-Vue used to *not* highlight the selected menu (which I assumed was the correct) - to be more precise, it highlighted the menu when clicking  on it, but did not stay highlighted afterwards.

Note that it used to work as you describe on version 0.10.9. I just upgraded to 0.10.10 and could see the difference (which for me is now correct :))

Apologies if I misunderstood the description of the bug.

**Comment by VividLemon** [comment]
> Did it work like this on Bootstrap-Vue ?
> 
> I also have `<BNavItem>`s with to attributes, and Bootstrap-Vue used to _not_ highlight the selected menu (which I assumed was the correct) - to be more precise, it highlighted the menu when clicking on it, but did not stay highlighted afterwards.
> 
> Note that it used to work as you describe on version 0.10.9. I just upgraded to 0.10.10 and could see the difference (which for me is now correct)
> 
> Apologies if I misunderstood the description of the bug.

the presence of :active="true" attached the class router-link-active. This is not a bootstrap class. "active" is a valid class, which is expected. Additionally there are some slight issues with the logic when to use the default and when to not use the default (default is 'active').
