### ISSUE TITLE
Regression introduced by version 0.10.8 when using component BFormInput 

### ISSUE THREAD

**Issue by tbl0605** [bootstrap-vue-next/bootstrap-vue-next#1398]
Hi,
In my case, the patch [0b3fcc5](https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/0b3fcc58f84f056ab25c1fb772145da8989563af) (see issue #1089) from version [0.10.8](https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/bootstrap-vue-next-v0.10.7...bootstrap-vue-next-v0.10.8) introduced a regression when using an BFormInput component. In some cases its content is not updated correctly, probably because I manually update its v-model, the underlying input content and use the `focus()` method (all at same time). 

I tried to provide a short demo project, by extracting relevant code from my project, but it's still a bit complicated code, sorry for that.

Also note that equivalent code for Vuejs 2.7 and bootstrap-vue v2.23.0 works as expected (since a long time now).

**To Reproduce.** Steps to reproduce the behavior:

1. get the [demo](https://github.com/tbl0605/boostrap-vue-next-demo2) project: `git clone https://github.com/tbl0605/boostrap-vue-next-demo2`
2. npm install
3. npx vite --port=4000
4. write "PAR" (without the quotes) in the BFormInput field
5. click on the "75000 PARIS" line **using the mouse** (this point is important)
6. the field content should be updated to "PARIS" but it doesn't work anymore

![chrome-capture-2023-7-26](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/3315731/7dec7a5a-cfa3-4248-b868-c4ebec7c3703)

**Expected behavior.**
When you write "PAR" (without the quotes) in the BFormInput field and click on the "75000 PARIS" line using the mouse, the field content should be updated to "PARIS".

**Workaround.**
Using version <= 0.10.7 of bootstrap-vue-next will make everything work again.

**Environment:**

- OS: Windows 10
- Browsers: latest Chrome and Firefox
- Package Version: >= 0.10.8

**Comment by xmatthias** [comment]
i think an even simpler reproduction can be with a input-field and a "reset" button - where the UI will simply ignore the reset-button (but the model below is properly reset).

I'm not sure about the >=10.8 version - i've tried this now with 10.7, and experience the same - all external updates to the v-model are ignored by the component - also on 10.7

**Comment by xvaara** [comment]
Here's a better reproduction of the bug: https://stackblitz.com/edit/vitejs-vite-hetpcq?file=src%2FApp.vue

**Comment by xmatthias** [comment]
@xvaara that's a rather interesting reproduction
clicking FIRST on one, then on the other seems to (somewhat) work ... so it appears like it's just "one" comparison / event that somehow goes missing ...


![52T4vMgkq6](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5024695/92a4c6df-d3fe-45a9-8477-38ab06c7fd9c)
