### ISSUE TITLE
b-nav-form contents now shows on new line 

### ISSUE THREAD

**Issue by adholland** [bootstrap-vue-next/bootstrap-vue-next#1410]
package: 0.11.0

Accessibility issue relating b-nav-form as part of #1346 has been resolved. Unfortunately the fix #1348 included a class of `container-fluid`, which forces content within a nav element onto a new line.

Is there anyway this can be removed or overridden via a property?

**Comment by xvaara** [comment]
Can you show an example that forces a newline? 
Here's an base for you: https://stackblitz.com/edit/vitejs-vite-w3rsk6?file=src%2FApp.vue

**Comment by VividLemon** [comment]
https://github.com/VividLemon/bootstrap-vue-next/commit/186e97a24af88ab5a14d65b6a044590ce45df9a1
