### ISSUE TITLE
Multiple individual BFormCheckbox behave like radio inputs

### ISSUE THREAD

**Issue by matt-e-king** [bootstrap-vue-next/bootstrap-vue-next#1423]
Multiple individual `BFormCheckbox` components bound to the same `ref([])` does not have expected behavior of adding/removing the value. Instead it begins to behave more like a radio button, where it only assigns the value of the individual checkbox clicked on.

This can be reproduce in two ways:

1. Manually create two `BFormCheckbox`es and bind them to a `ref([])`. Give the first checkbox the `value` of 1, and then second the `value` of 2. Click on the first one, the bound reference will be equal to `1` instead of `[1]`. Here is the code:

```
<BFormCheckbox
  v-model="checkBoxGroup"
  :value="1"
  name="testCheckBoxes"
>
  Item one
</BFormCheckbox>

<BFormCheckbox
  v-model="checkBoxGroup"
  :value="2"
  name="testCheckBoxes"
>
  Item two
</BFormCheckbox>

....

const checkBoxGroup = ref([])
```

2. This is broken in the docs also. Go to the [Inline and Stacked Checkboxes](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-checkbox.html#inline-and-stacked-checkboxes) section, scroll to the section in the demo labelled "Individual stacked checkboxes (default)" and click on "Orange". It breaks the `BFormCheckboxGroup` that are bound to the same `checkEx3Selected` reference.

Of course you can use `BFormCheckboxGroup` in a simple example like this, but in my use case, I want to wrap list items around my checkboxes so I need to render them individually.

Thanks so much for your work on creating the next iteration of BootstrapVue. I'm really hoping my bandwidth will open up soon and I'd like to start contributing.

- OS: macOS Monterey 12.6
- Package Version: 0.9.26
- Yarn: 1.22.19

**Comment by xvaara** [comment]
I fixed this last week, test with the newest version.

**Comment by xvaara** [comment]
Sorry, npm doesn't have the latest, 0.12.1 should include the fixes. Hopefully npm release will be fixed soon.
