### ISSUE TITLE
How to use BToast in *none* composition mode?

### ISSUE THREAD

**Issue by mediaessenz** [bootstrap-vue-next/bootstrap-vue-next#1437]
In bootstrap-vue there was the option to create a toast programatically this way:
```
this.$bvToast.toast('Message', {
					title: 'Title',
					autoHideDelay: 5000,
					appendToast: true,
					variant: 'success',
					solid: true,
				});
```
How can I accomplish this in bootstrap-vue-next without using the composition api ?

Background:
I have to port a relative complex vue2/vuex/bootrap-vue (bootrap 4) web application to vue3 + bootrap 5 with the minimum of effort. 

Because of this I do not want to switch from the "classic" options api to the composition api.

Unfortunately all example I found here, showing the compoisition api way, with make use of "useToast". But this seem not working for me.

Maybe someone can help me?

**Comment by xvaara** [comment]
This is a horrible hack to create similar options api, please take care with it... but in any case: https://stackblitz.com/edit/vue-tsggs2?file=src%2FApp.vue,src%2Fcomponents%2FComp.vue

Toast isn't that far along and is waiting refactoring and documentation. 

pull requests or sponsors are welcomed.

note that bootstrap 5.3 doesn't use variants anymore, and our toast component hasn't been converted to the new format yet:
https://getbootstrap.com/docs/5.3/components/toasts/#color-schemes

**Comment by VividLemon** [comment]
The only and likely best way to use it in a component that isn't converted to script setup is to interop it with options api 

```ts
import { useToast } from 'bootstrap-vue-next'

export default {
  setup () {
    const {show} = useToast()

    return {show}
  },
  methods: {
    generate(){
      this.show('FooBar!')
    }
  }
}
```

Of course, you will need to do `<BToaster />` somewhere in the app. And of course, this is _technically_ composition api.

**Comment by VividLemon** [comment]
You had asked a question, then proceeded to not make any movement on the question. Which makes me wonder, why did you even bother asking the question
