### ISSUE TITLE
BDropdown change has broken Nav drop down not sure if Bug or intentional

### ISSUE THREAD

**Issue by graemedewe** [bootstrap-vue-next/bootstrap-vue-next#1438]
**Change to BDropdown has changed the layout of an existing site.**

**I believe this is the change that has caused the layout difference** https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1337/files#diff-8fb2aa4b9e64fcfc83279f6f83dc799c8ca5b33e3673d8723f5d223647dd47deR40-R57

The Change has made my basket drop-down b0rk see screenshots of <= v0.9.26

![Screenshot-20230913110246-783x600](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/16539189/05725da6-b6fe-4cc7-a7f6-a6c88d413925)

but now I get this with > v 0.9.26

![Screenshot-20230912175248-806x752](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/16539189/df496eb0-e23f-469b-bc07-b9b26f16012a)

What was the rationale in making this change and what suggestions do you have to regain my previous layout?

**Comment by VividLemon** [comment]
I'd need the code

**Comment by graemedewe** [comment]
> I'd need the code
Hi thanks for replying, so I've looked at the docs https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/dropdown.html
 and have added the `strategy` and `start` props I understand why it's rendering as it was before as even in your examples the drop-down is not constrained by anything but the content which makes sense however we had used the nav button width to set the drop-down width on our site, here is a snipped of the code just for the drop-down, let me know what else you need as its quite a complex nav component I would need to sanitise some of the content before pasting 

`            <b-nav-item-dropdown
              v-for="nav in navigationObjects.filter(o => o.type === 'component')"
              :id="nav.reference"
              :key="`component-` + nav.reference"
              :data-reference="nav.reference"
              strategy="fixed"
              start
            >
              <template #button-content>
                <slot>
                  <span
                    class="basket-count"
                  >
                    {{ nav.reference === 'basket' ? totalBasketProducts : '' }}
                  </span>
                  <i
                    v-if="nav.icon"
                    class="fas fa-icon"
                    :class="'fa-' + nav.icon"
                  />
                  <span class="nav-text"> {{ nav.name }}</span>
                </slot>
              </template>
              <b-nav-form class="d-block">
                <component :is="nav.component" />
              </b-nav-form>
            </b-nav-item-dropdown>`

generates

![screenshot-egift microsite local-2023 09 14-08_54_08](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/16539189/179905ff-bb7a-4eed-b35a-260a63a1f839)

**Comment by xvaara** [comment]
@VividLemon is there a reason for the width: max-content on https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue#L48

We could remove that so that it can be overwritten easily in styles. bootstrap.js doesn't add width to them.

**Comment by graemedewe** [comment]
> @graemedewe you can overwrite the widths of the btn-group and dropdown-menu like this: https://stackblitz.com/edit/vitejs-vite-tbhee2?file=src%2Fcomponents%2FComp.vue

Thanks, I'll give that a go, applied the changes quickly and they did not work as per your example so will strip my code back and see, thanks for the suggestion

**Comment by graemedewe** [comment]
@xvaara I have discovered why your solution was not working an errant `:justified="true"` on the `<b-navbar-nav> removing that seems to have fixed it. Appreciate your time , thank you very much

**Comment by VividLemon** [comment]
@xvaara related https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1439
