### ISSUE TITLE
Vue props type error for BPopover if using HTMLElement

### ISSUE THREAD

**Issue by asika32764** [bootstrap-vue-next/bootstrap-vue-next#1455]
### Describe the bug

If the `<BPopover>` use `target` or `reference` bind a HTMLButtonElement, it will show this warning in console.

![screenshot 2023-09-15 下午7 20 50](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/1639206/29be9600-7f17-4a67-982d-5ffe4030e557)

It's seems the type declaration in source code is correct

![screenshot 2023-09-15 下午7 21 09](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/1639206/2ba8ad56-f39b-418b-946f-e944bb5ecc55)

I think maybe it is that Vue striped the HTMLElement  from props type.

But use function works

```
<BPopover :target="() => button">
```

### Reproduction

https://stackblitz.com/edit/github-heccuu?file=src%2FApp.vue

Open Browser console can see the warning

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 174.09 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v14.18.2/bin/npm
    pnpm: 8.7.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.5.1
    Safari Technology Preview: 16.4
```

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
After researching this for a while I think we can't use "type-based declaration" for props that have HTMLElement and function in them. Since vue compiler strips the type for all the types except Function and Boolean. So we end up with faulty production code.

this syntax seems to be only option:
```ts
defineProps({
  target: {type: [Function, String, HTMLElement, null] as PropType<() => HTMLElement| string | HTMLElement | null>}
}) 
```

any ideas @VividLemon

**Comment by VividLemon** [comment]
> this might also interfere with our intent to share props as interfaces

Are these props only shared with BPopover and BTooltip?

**Comment by xvaara** [comment]
> Are these props only shared with BPopover and BTooltip?

Yes... well BTooltip doesn't have any props at the moment, I was lazy and it just v-bind="$attrs" to BPopover.

**Comment by VividLemon** [comment]
> > Are these props only shared with BPopover and BTooltip?
> 
> Yes... well BTooltip doesn't have any props at the moment, I was lazy and it just v-bind="$attrs" to BPopover.

It should get props definition as it adds type inferences.

Since it really only affects minimal components, reverting to runtime props is likely the best option as there isn't any great alternatives

**Comment by xvaara** [comment]
Or we remove the ability to have a function there. That should also fix the "problem".

**Comment by asika32764** [comment]
I think vue should compile all interfaces to `type: Object`, since type checking is only work on development.

I searched vue's repository, It seems no one report this issue yet. I'll report this to there first.

**Comment by xvaara** [comment]
> I think vue should compile all interfaces to `type: Object`, since type checking is only work on development.
> 
> I searched vue's repository, It seems no one report this issue yet. I'll report this to there first.

There are multiple issues that I found. And vue compiles the props to null in production.

**Comment by VividLemon** [comment]
> Or we remove the ability to have a function there. That should also fix the "problem".

The function doesn't interfere. The issue is that the compiler needs to somehow infer an object type. If you were able to say, add an interface that the compiler could understand (it isn't understanding htmlelement) then it would solve all of our problems. However, there's no clean way to do this. At least, no clean way that doesn't involve adding an unnecessary type that doesn't belong

**Comment by asika32764** [comment]
> And vue compiles the props to null in production.

This is expected behavior. But the problem of this issue is that vue strip types in development mode.

**Comment by xvaara** [comment]
> > Or we remove the ability to have a function there. That should also fix the "problem".
> 
> The function doesn't interfere. The issue is that the compiler needs to somehow infer an object type. If you were able to say, add an interface that the compiler could understand (it isn't understanding htmlelement) then it would solve all of our problems. However, there's no clean way to do this. At least, no clean way that doesn't involve adding an unnecessary type that doesn't belong

I don't remember why I added the ability to have a function in those props. I'm not sure it's worth keeping, since the same could be done with a computed on the the component using popover.

**Comment by xvaara** [comment]
> > And vue compiles the props to null in production.
> 
> This is expected behavior in production mode. But the problem of this issue is that vue strip types in development mode.

You're using production build of bootstrap-vue-next in your environment if you installed it from npm.

**Comment by asika32764** [comment]
> You're using production build of bootstrap-vue-next in your environment if you installed it from npm.

Ah, I see. So it is an expected warning there.

**Comment by asika32764** [comment]
My 2 cents, we can consider remove interface declaration and keep `Function` type, it is make sense if developer want to send any custom element into it.

This is similar to vue `Function Refs`: https://vuejs.org/guide/essentials/template-refs.html#function-refs

**Comment by xvaara** [comment]
You could just use 
```vue
<BPopover :target="eles[my][element][ref]">
```
and maintain reactivity. The problem is that function isn't reactive.

You can use a function that returns a value. It has some reactivity cavets I think.
```vue
<BPopover :target="getElement()">
```

Computed would probably be the best option.
