### ISSUE TITLE
BTable prop items not "reactive" (inertiajs)

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1466]
I'm using inertiajs.
My controller passes items to a vue page with a BTable that renders these items.
In that page I can update a record, post to controller that refresh the previous page with new items property... the BTable component doesn't update his content even if ```items``` property is actually updated.

Using BTableLite in place of BTable and everything's fine.

While BTableLite is rendering ```item``` prop directly, BTable uses a composable receiving the table props. 
I can't really undestand why is "loosing" reactivity but probably useTableItems.ts composable has something to fix.

Any ideas?

**Comment by raizdev** [comment]
I am experience the same issue.

I solved it with a workaround to give it a unique key, something like:
````<b-table
                        striped
                        responsive
                        small
                        :key="JSON.stringify(measurements.data)"
                        :fields="['status', 'serviceid', { key: 'dslam', label: 'olt' }, 'ont', 'start', 'end', 'user', { key: 'description', sortable: true }, 'view']"
                        :items="measurements.data"
                        show-empty
                    />
````

**Comment by makroxyz** [comment]
Hi! I know the workaround... but it would be better to solve this little
issue.

Il mar 19 set 2023, 19:53 Bryan ***@***.***> ha scritto:

**Comment by makroxyz** [comment]
@VividLemon 
could you help to solve this? Any ideas?

**Comment by VividLemon** [comment]
The goal was to force people that want the table to fix it by themselves. I have never touched the table components. Breaking it was not my fault. I have never done anything outside of a few global changes here and there. 

However, since nobody really seems to give a shit, and the issue list seems to pile up. I guess I'm going to need to do something. Even though I have just as much knowledge on the component as literally everybody else. 

I guess it's like the last thing besides BTabs, and maybe BSelect. Even though those both technically work

**Comment by makroxyz** [comment]
@VividLemon you're right, and I totally agree with you. I'm collaborating as much as I can and I did some PRs for BTable and other components. My question was technical oriented... I mean you have more knowledge about TS and Vue than me and I'm missing something that I can't get in useTableItems composable params....

**Comment by makroxyz** [comment]
@devhus can you help us?

**Comment by devhus** [comment]
I believe that i have already made the items reactive, did someone break something? 😂

**Comment by devhus** [comment]
Could you please provide an example of the issue? Try to make it in pure vue code without inertiajs.

**Comment by raizdev** [comment]
https://stackblitz.com/edit/vitejs-vite-jjydub?file=src%2FApp.vue

**Comment by devhus** [comment]
> I would prefer to take over development of the table components.

Seems like a good idea, there are a lot of updates that happened to the table component and, I have no idea about them.
I believe the reactivity of the items prop has broken between these updates so you should check them out.
Sorry for being too busy, I don't get much free time in summer.

**Comment by makroxyz** [comment]
> https://stackblitz.com/edit/vitejs-vite-jjydub?file=src%2FApp.vue

Perfect example! Thanks @raizdev 

Last working version in the example is bootstrap-vue-next 0.9.23
In version 0.9.24 ```useTableItems.ts``` composable was introduced and something in this composable looses items reactivity.

**Comment by devhus** [comment]
@makroxyz I am not sure yet need to make a few tests first on the code, but it seems to me like this commit of yours https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/47cdb478fcd7c1e4a64e8317bab5d1644c8ce319
broke something

@VividLemon I might be wrong but could you check out the changes as you go through this issue? I will take a look as well if i get any free time soon.

**Comment by makroxyz** [comment]
@devhus 
have a look here: https://stackblitz.com/edit/vitejs-vite-c19o4f
this uses bootstrap-vue-next-0.9.24 the first release with ```useTableItems.ts``` and there aren't my commits

**Comment by xvaara** [comment]
The internalItems that mapItems uses isn't reactive. And updateInternalItems isn't called then items props is updated. The whole internalItems is weird... why is it needed? seems overly complex to create a update for the items just for the provider when we could just use something like a ref or computed?

**Comment by makroxyz** [comment]
> The internalItems that mapItems uses isn't reactive. And updateInternalItems isn't called then items props is updated. The whole internalItems is weird... why is it needed? seems overly complex to create a update for the items just for the provider when we could just use something like a ref or computed?
> 
> ```js
> watchEffect(() => updateInternalItems(props.items))
> ```
> 
> fixes this for now.

isn't better?
```js
watch(() => props.items, (value) => updateInternalItems(value))
```
