### ISSUE TITLE
Bimg src: No match found for location

### ISSUE THREAD

**Issue by jefhild** [bootstrap-vue-next/bootstrap-vue-next#1470]
I'm trying to use local asset resources, an img src in this case: 

`<BImg src="@/assets/logo.svg"></BImg>`

I consistently get the following error:

`[Vue Router warn]: No match found for location with path "/@/assets/logo.svg"`

It's as if the Asset URL Handling isn't being taken into consideration as I think it would be.  Or as if transformAssetUrls needs to be manually added to nuxt.config.ts. 

I've tried the different default values for access to my assets directory. I'm clearly misunderstanding something. Any help would be appreciated.

These are my installed dependencies:

```
  "devDependencies": {
    "@bootstrap-vue-next/nuxt": "^0.13.3",
    "@nuxt/devtools": "latest",
    "@nuxtjs/google-fonts": "^3.0.2",
    "bootstrap": "^5.3.2",
    "bootstrap-vue-next": "^0.13.3",
    "nuxt": "^3.7.3"
  }
```

- OS: [Mac Ventura]
- Package Version: [0.13.3]
- Npm Version: [8.19.2]

**Comment by VividLemon** [comment]
>  Or as if transformAssetUrls needs to be manually added to nuxt.config.ts.

And why didn't you already try it

**Comment by jefhild** [comment]
Two reasons: This info from the documentation: "If using the [BootstrapVue Nuxt](https://bootstrap-vue.org/docs#nuxtjs-module) module with Nuxt.js, the plugin module will automatically add in the BootstrapVue specific transformAssetUrls configuration for you." And, I'm not 100% sure how to do this correctly.

**Comment by VividLemon** [comment]
That isn't our documentation
