### ISSUE TITLE
BNavBar `type="dark"` doesn't appear to work

### ISSUE THREAD

**Issue by Morgul** [bootstrap-vue-next/bootstrap-vue-next#1480]
### Describe the bug

When in the light theme, setting the `type` property to `"dark"` doesn't seem to work; I would expect the text to change to be lighter, but it stays black, making the navbar difficult to read. This is visible right on the docs:

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/770655/486f5257-30af-498b-b87d-52f41786351d)

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/navbar.html

### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 20.27 GB / 64.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.16.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
```

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Morgul** [comment]
I first noticed this in my project, but going to the docs, it was trivial to just change the theme to `light` and all the navbars show the same problem.

**Comment by VividLemon** [comment]
Whether or not you like it, that's the default behavior when you use variants.

But did you know, there's a fancy thing called color modes?

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/895c3a5b-6b87-41ab-8b1f-f013c6dd8382)

**Comment by VividLemon** [comment]
Whether or not you like it, that is Bootstraps default behavior. 

However, you can however solve this issue by using color modes

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/baeee1c8-d737-480e-bd0e-5664349189ae)

https://getbootstrap.com/docs/5.3/components/navbar/#color-schemes

**Comment by VividLemon** [comment]
Technically :eyes: 

...

You could

...

Add

`class="navbar-dark"`

**Comment by Morgul** [comment]
> Whether or not you like it, that is Bootstraps default behavior.

Well, yes, but in BootstrapVue (and the docs for BootstrapVueNext, currently) the `type` property is supposed to change the text color from light to dark. From the current BootstrapVueNext docs:

> Control the text color by setting type prop to `light` for use with light background color variants, or `dark` for dark background color variants.

(https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/navbar.html#color-schemes)

So while you're right that color modes could be used to fix it, that's both not documented, and a deviation from BootstrapVue, which is why I assumed this was a bug and not an intended breaking change.

Personally, I've never been the biggest fan of the `type` property on navbars and would like to simply set the text variant I want; so I'm fine if that's the new direction. I just also don't want to do my own thing if the intent was to keep this and make it work in the future.

**Comment by VividLemon** [comment]
I didn't even know the type property existed in the docs. (Totally have read them, I promise. Jk, totally haven't). But the type property doesn't exist in the lib. Docs are usually out of date, mostly because I don't update them when I make changes.

**Comment by Morgul** [comment]
> I didn't even know the type property existed in the docs. (Totally have read them, I promise. Jk, totally haven't). But the type property doesn't exist in the lib. Docs are usually out of date, mostly because I don't update them when I make changes. It's on the todo list. Alternatively, _you_ could fix it 👀

Haha, fair enough, I'm down to fix it. I can check the BootstrapVue code, but I believe it was literally just swapping between the `navbar-light` and `navbar-dark` classes. Is that implementation good enough, or do you want something more in depth?

**Comment by VividLemon** [comment]
Neither navbar-light nor navbar-dark classes should be referenced. They are deprecated classes. We are going to direct people to use color modes only. `type` props should be removed from the documentation. The files are navbar.md and navbar.data.ts. A section will likely need to be made called `Color Schemes` or something. It should briefly talk about how if a global scheme is used, it may not be needed, but if a static variant navbar is used, then you may want to override the global scheme.
