### ISSUE TITLE
 Error: Cannot find module '@nuxt/kit'

### ISSUE THREAD

**Issue by MonnyDesign** [bootstrap-vue-next/bootstrap-vue-next#1488]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html

### Describe the missing feature

When I install bootstrap-vue-next for Nuxt project, I use the command from the documentation: yarn add bootstrap `bootstrap-vue-next @bootstrap-vue-next/nuxt -D `
It installed well but when I add the code below in nuxt.config.js file:

```
export default defineNuxtConfig({
  modules: ['@bootstrap-vue-next/nuxt'],
})
```

I have an error in Docker:
```
Error: Cannot find module '@nuxt/kit'
Require stack:
- /var/www/html/node_modules/@bootstrap-vue-next/nuxt/dist/module.mjs
- /var/www/html/node_modules/@bootstrap-vue-next/nuxt/dist/module.cjs
- /var/www/html/node_modules/@nuxt/core/dist/core.js
- /var/www/html/node_modules/@nuxt/cli/dist/cli-chunk.js
- /var/www/html/node_modules/@nuxt/cli/dist/cli.js
- /var/www/html/node_modules/nuxt/bin/nuxt.js
```

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by VividLemon** [comment]
The simplest solution is to probably just add @nuxt/kit to your dependencies. There's nothing that's really our problem, as @nuxt/kit is already a bundled dependency. If it's getting removed, it's likely an issue with your build process. Albeit a rather odd issue, as I don't know why a bundler would remove or ignore a dependency. Likely docker is just not including it as a dependency, so you'll need to just figure out a way to have it include it as a dependency. 

Also, this isn't a missing feature
