### ISSUE TITLE
BTab not work for custom component

### ISSUE THREAD

**Issue by yanghoxom** [bootstrap-vue-next/bootstrap-vue-next#1491]
### Describe the bug

When I render b-tab in a Child, b-tabs can not detect to render them

### Reproduction

https://stackblitz.com/edit/nuxt-starter-tdgrnw

### System Info

```Shell
"@bootstrap-vue-next/nuxt": "^0.14.5",
"bootstrap": "^5.3.2",
"bootstrap-vue-next": "^0.14.5",
"nuxt": "^3.7.4"
```

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
This is a known issue (just no issue in github, thx for the report), there is a line in BTabs.vue:
```js
// TODO simplify this! YOu cannot do things like nest BTab in a wrapper component!
```
😄 

We need to convert tabs to use provide/inject instead of default slot. I have a proof of consept for it, maybe I'll have time next week to finnish it.

**Comment by VividLemon** [comment]
Its unlikely that you'd be able to do it in bootstrap vue either. But I haven't tried

**Comment by VividLemon** [comment]
@xvaara You will likely want to use this as a guide 

https://skirtles-code.github.io/vue-examples/patterns/coupled-components-with-provide-inject.html

https://skirtles-code.github.io/vue-examples/components/tabs.html

```ts
const tabs = ref([])
const register = (id: {}) => {
  tabs.value.push(id)
}
const prov = provide('BTabsInjectkey', register)

//
const register = inject('BTabsInjectkey', null)

const parentData = register?.({ title: toRef(() => props.title) }) // Various things to pass around, title, etc ig.
```

**Comment by xvaara** [comment]
@VividLemon yes, I got that far previously, not all the props working yet. The problem I faced then was that the order of the array doesn't stay in sync with the VNode tree. This evening I tested ordering them by dom and it seems to work. Took the inspiration from here: https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/utils/focus-management.ts#L165-L181

**Comment by yanghoxom** [comment]
@xvaara @VividLemon
Thanks for reply
I got it
I will use b-tabs and b-tabs directly for now
I look forward to your updates
