### ISSUE TITLE
b-modal not showing in production

### ISSUE THREAD

**Issue by Lawrence-ekale** [bootstrap-vue-next/bootstrap-vue-next#1499]
**Tried to run ```npm run prod``` to build the assets and it works fine.** After that the b-modal is not working.

**I have tried different versions of bootstrap-vue-next but still not working**

**No error messages shown either**

**Environment **

- OS: Kali Linux
- Package Version: 0.14.6 of bootstrap-vue-next
- Npm/Yarn/Pnpm Version: npm

**Comment by VividLemon** [comment]
And yet the docs work in production, so your issue ticket with almost no info and no reproduction is useless to me.

**Comment by Lawrence-ekale** [comment]
> And yet the docs work in production, so your issue ticket with almost no info and no reproduction is useless to me.

During asset building is where the problem is. When I run ```npm run dev``` the modal is working. Sending some code snippets in a few.

**Comment by beahtsantos** [comment]
Hi @Lawrence-ekale. Have you solved the problem? Can you share me how? I am facing the same issue. Thank you

**Comment by Lawrence-ekale** [comment]
@beahtsantos ,check how many files of js files were created(minified) and in the browser developer tool confirm that all of them have been injected to the page.


I found out later and added code to include all of them.
