### ISSUE TITLE
Tooltip do not close when open dropdown

### ISSUE THREAD

**Issue by yanghoxom** [bootstrap-vue-next/bootstrap-vue-next#1503]
### Describe the bug

I use tooltip for dropdown title
but it do not hide after I click on dropdown

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rutkpp

### System Info

```Shell
"@bootstrap-vue-next/nuxt": "^0.14.5",
"bootstrap": "^5.3.2",
"bootstrap-vue-next": "^0.14.5",
"nuxt": "^3.7.4"
```

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
Hmm... I think this works as intended, since dropdown has the menu inside it and you are still hovering it when clicking. Use noninteractive tooltip:
```
v-b-tooltip="{title: 'test tooltip', noninteractive: true}"
```

**Comment by VividLemon** [comment]
What is the bootstrap vue behavior

**Comment by xvaara** [comment]
it seems bsv2 removes the focus from the dropdown button when dropdown is opened and the tooltip closes.
https://codesandbox.io/s/exciting-shadow-r4njy4?file=/App.vue

**Comment by yanghoxom** [comment]
@VividLemon yes, on boottrap-vue, tooltip will be hide when I move the mouse into dropdown list

**Comment by yanghoxom** [comment]
@xvaara thank you so much for the fix
but, I found another issue related to the tooltip and dropdown
the tooltip will show up when we hover on the dropdown list
https://stackblitz.com/edit/nuxt-starter-224v5z?file=app.vue

**Comment by yanghoxom** [comment]
@xvaara thank you for reply, it works well 😍 
I don't know if it's too much if I ask you about the two options `reference` and `target`
I guess `target` refers to the id of the target we want the tooltip to stick to, what about `reference`?
