### ISSUE TITLE
Base icon for sortable columns in BTable

### ISSUE THREAD

**Issue by cRoberts2-18** [bootstrap-vue-next/bootstrap-vue-next#1504]
### Clear and concise description of the problem

One minor quality of life thing that base bootstrap vue tables offer is a 'base' symbol which is used to depict which columns in a table are sortable, as seen below
![Screenshot 2023-10-03 at 14 26 07](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/75317368/720872e8-dc89-44af-a68f-9b7b7912f843)
A similar icon being applied to sortable rows which are not currently sorted by would be a useful addition in order to make tables where not all rows are sortable easier to use

### Suggested solution

Add another class to `.b-table-sortable` in BTable/_table.scss to display an icon when unsorted and add that class to the logic for determining which class to apply to the header if its sortable in `BTable.vue`

### Additional context

This is needed to make it more obvious for customers to know which columns they are able to sort their data by in a business context

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
0.15
