### ISSUE TITLE
Table footer shown wrong

### ISSUE THREAD

**Issue by cucuianr1978** [bootstrap-vue-next/bootstrap-vue-next#1505]
### Describe the bug

Hello! 
I have an issue converting fom vue 2 to vue 3 components. Table Footer on specified column not shown.
I attached here a component(ErrorTableFooter). Just add it into a project: the total for column Qty should be shown. For the column name footer should be empty.

Thank you!
Ramon

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-e4zekm?file=src%2Fcomponents%2FComp.vue

### System Info

```Shell
https://bootstra-vue-next-template-e4zekm.stackblitz.io
```

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by makroxyz** [comment]
Please upgrade bootstrap-vue-next to latest version it works fine.
the ```footer-variant``` property is not yet implemented.
