### ISSUE TITLE
NavBar Right Align doesn't work

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#1510]
### Describe the bug

I am using the first navbar sample from the [documentation](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/navbar.html) and the second `BNavbarNav`, which is supposed to be right aligned according to the comments, just butts up against the first `BNavbarNav`.

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5083020/88c8295c-05dd-4352-b509-1b3d41884ecc)

I would expect Lang and User to righted align as the comments states rather than left aligned with link and disabled.

Is there a different way to do this?  If the sample in the documentation is out of date, I'd be happy to update it.

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-nyzjqn?file=src%2Fcomponents%2FComp.vue

### System Info

```Shell
I don't believe this is system/browser specific - it repros with the above stackblitz on everything I have access to.
```

### Used Package Manager

n/a

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
That's all just classes. If you want to align your items and stuff, you're going to need to use flexbox and whatnot.

**Comment by dwgray** [comment]
Thanks for the quick response @VividLemon.  So this looks like it's a doc bug - I have a [stackblitz](https://stackblitz.com/edit/bootstra-vue-next-template-jvghf8?file=src%2Fcomponents%2FComp.vue) with the fix to the sample.  I just changed me-auto to ms-auto as suggested by [this SO](https://stackoverflow.com/a/65365121/2197085) answer.  If that makes sense to you, I'll take a look at fixing the sample in the docs.
