### ISSUE TITLE
Tooltip how to append tooltip to another place (ex: outside body)? (avoid breaking display flex)

### ISSUE THREAD

**Issue by yanghoxom** [bootstrap-vue-next/bootstrap-vue-next#1513]
**What you are trying to do.** A clear and concise description of what you want to happen.
Currently, the tooltip element will be added next to the target in the DOM
this will damage the structure of the part if it is using flex
In my case, I'm using display: flex and justify-content: space-between
The fact that the tooltip is added at the same position as the target makes the space-between work no longer correctly
I am having to fix it by wrapping the target inside another div tag.

**What you have already tried.** A clear and concise description of any alternative solutions or features you have considered.
I tried viewport, window but it did not work 

I hope to have an option or another way to handle this case without wrap my target into a div
Normally, the tooltip will be added outside the body to avoid break the structure of the page

**Environment (please complete the following information):**

- OS: Ubuntu 20
- Package Version: 0.13.2
- Npm/Yarn/Pnpm Version: Yarn

**Comment by susanne99** [comment]
i don't know which tooltip technic you use, but try. an example would be helpful

```
 <b-popover
        container="body"
```

**Comment by yanghoxom** [comment]
@susanne99  sorry, I forgot about it.
I use this syntax
```
v-b-tooltip="test"
```

**Comment by yanghoxom** [comment]
@xvaara @susanne99 
I found this to be an issue, maybe consider it a bug of the tooltip/popover
The `container: 'body'` option does work, it will append the tooltip to the body, but it doesn't solve the "breaking the DOM structure" problem I mentioned above, because it still appends a span tag to the target's DOM structure
and this will cause an error when we use display flex for that block
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/10399540/ce8ac5af-585b-4a89-8781-b04935e03c0e)

**Comment by yanghoxom** [comment]
@xvaara Hello, looks like you missing this, please reopen this issue, it still causes error
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1513#issuecomment-1764219847

**Comment by toneysix** [comment]
Reopen this
