### ISSUE TITLE
Modal opens behind another modal if element is defined first

### ISSUE THREAD

**Issue by mclmax** [bootstrap-vue-next/bootstrap-vue-next#1516]
### Describe the bug

If I defined two modals, Modal1 and Modal2, where a button in one modal opens the other and the second modal to open is defined before the first, it opens behind the first modal.

Modal1 opens first, button in Modal1 opens Modal2, which opens underneath Modal1.
```
<Modal2 />
<Modal1 />
```

In this case it works as you'd expect. Modal1 opens, button in Modal1 opens Modal2 on top of Modal1.
```
<Modal1 />
<Modal2 />
```

In my mind the stacking should work independent of element order.

I'm super keen to get a PR for this as well if this is unintended behaviour. Was hoping to get your feedback before diving into that. If you point me in the right direction more than happy to fix.

Thanks

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-69h4lk?file=src%2FApp.vue

### System Info

```Shell
Not sure how to run this on stackblitz
```

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Didn't even mention that no-stacking isn't working

**Comment by susanne99** [comment]
z-index is always the same. hardcoded in BModal.vue
no calculation of it !

```
.modal-dialog {
  z-index: 1051;
}
```

In my case I have an EditDialog open, and after 10 minutes of inactivity a modal dialog appears with the message that you have been logged out. Unfortunately you can't see it because it's hidden behind the edit dialog due to the same z-index.

I know that with jquery or my own typescript function I can close all open modals. A z-index calculation wouldn't be bad

**Comment by mclmax** [comment]
Yeah so that was what i was thinking as well @susanne99. If the modals are stored in a stack where each new item gets a z-index + 1. I'll take another gander.

**Comment by VividLemon** [comment]
In terms of organizing which modals are open you will need to make these modifications 
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/71479e8e-facb-4f56-9a39-956cd7e0c4d9)
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/50510131-942b-44a7-aa0e-722c654b1986)
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/0413bada-6f83-417e-84d6-bf99ad80a64f)

The names could possibly be improved to indicate what they're being used for. As the modal manager has a few duties, so better naming could indicate what the properties are being used for

However, organizing z-index isn't the only solution, as https://stackoverflow.com/questions/36073656/element-with-higher-z-index-value-not-overlaying-another is an issue with the implementation. Which, I am not sure how to fix.

**Comment by susanne99** [comment]
@mclmax : Increasing the z-index by 1 is exactly what bootstrap vue does - it actually works perfectly. It would be really great if you could specify a starting z-index, then I could overrule other elements with perhaps a higher z-index

**Comment by susanne99** [comment]
@VividLemon : I wouldn't worry about that. The only important thing is that the z-index is incremented for several modal dialogs. Which rules then apply to positioning is no longer your concern, but rather has to do with the W3C specification. The programmer then has to take care of it

**Comment by VividLemon** [comment]
> @VividLemon : I wouldn't worry about that. The only important thing is that the z-index is incremented for several modal dialogs. Which rules then apply to positioning is no longer your concern, but rather has to do with the W3C specification. The programmer then has to take care of it

I don't think you're quite understanding the issue. But I've given half of the solution, the rest is css. The issue is that the implementation that bvn has is pretty close to that of bootstrap. And bootstrap doesn't allow multiple modals on top of each other with its css. So, our css needs to adapt. Hence the issue noted in the SO. The downstream dev wont need to take care of this issue. Simply updating the z index is not a catch all solution here.

**Comment by susanne99** [comment]
OK, if you think I don't understand that - so be it

**Comment by VividLemon** [comment]
Feel free to manually update the z index as you proposed in a test environment using direct browser manipulation and let me know how it goes.

The answer is I've already tried just updating the z index. It doesn't work

**Comment by mclmax** [comment]
Thanks for the code @VividLemon, helped a bunch. I've cobbled together something of a fix for my case specifically. Not sure if that works with cases outlined in the SO post.

Just copying your code verbatim and adding a computed style to the modal with:

`const defaultModalDialogZIndex = 1055;
const computedZIndex = computed<CSSProperties>(() => ({
  'z-index': defaultModalDialogZIndex + position.value,
}))`

Sort of works. It does introduce a bit of ugliness when opening a additional modal. There seems to be a small window where the modal still appears behind the first which ruins the fade in animation. Will tinker some more.

**Comment by xvaara** [comment]
> z-index is always the same. hardcoded in BModal.vue no calculation of it !
> 
> ```
> .modal-dialog {
>   z-index: 1051;
> }
> ```
> 
> In my case I have an EditDialog open, and after 10 minutes of inactivity a modal dialog appears with the message that you have been logged out. Unfortunately you can't see it because it's hidden behind the edit dialog due to the same z-index.
> 
> I know that with jquery or my own typescript function I can close all open modals. A z-index calculation wouldn't be bad

@susanne99 @mclmax you can also play around with the teleport, since z-index context matters also. So for example low priority model `teleport-to="#app"` and high priority `teleport-to="body"` (which is the default) or you could even use `teleport-disabled` to move the modal to the current z-index context.

**Comment by susanne99** [comment]
@VividLemon hmm, before i used vue-next, i used bootstrap-vue. 
It actually worked quite well and correctly, at least for my app with almost 1000 users


Here is the component of bootstrap-vue, but I assume you know it of course
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/modal/modal.js

**Comment by VividLemon** [comment]
> > z-index is always the same. hardcoded in BModal.vue no calculation of it !
> > ```
> > .modal-dialog {
> >   z-index: 1051;
> > }
> > ```
> > 
> > 
> > In my case I have an EditDialog open, and after 10 minutes of inactivity a modal dialog appears with the message that you have been logged out. Unfortunately you can't see it because it's hidden behind the edit dialog due to the same z-index.
> > I know that with jquery or my own typescript function I can close all open modals. A z-index calculation wouldn't be bad
> 
> @susanne99 @mclmax you can also play around with the teleport, since z-index context matters also. So for example low priority model `teleport-to="#app"` and high priority `teleport-to="body"` (which is the default) or you could even use `teleport-disabled` to move the modal to the current z-index context.

I'm thinking if you have multiple in a row, this wont really work out. It will work for displaying the one for the top most priority, but the ones in the background may shift. Hypothetically if you have modal 1,2,3  then 3 opens and 2 is smaller than 1, but the order in the dom would move 2 behind 1, then you'd have some weird transition issues where it appears like 2 bounces behind 1. The order is specific, and I might have gotten the exact steps wrong, but it is similar to this core issue.

**Comment by mclmax** [comment]
I took a quick look at the Teleport stuff. I'm not super familiar with it so wasn't able to get it to play nice.

I've dropped a PR of what I think fixes the issue? It might be too wonky?
