### ISSUE TITLE
Vitepress + bootstrap-vue-next : how to ?

### ISSUE THREAD

**Issue by ezzle** [bootstrap-vue-next/bootstrap-vue-next#1524]
**What you are trying to do.** A clear and concise description of what you want to happen.

Use with vitepress.
I am unable to add bootstrap-vue-next to vitepress config.ts

**What you have already tried.** A clear and concise description of any alternative solutions or features you have considered.

Tried to use the config suggested in the doc.

**Any error messages you are getting.** If any, please list the errors you are getting.

**Environment (please complete the following information):**

- OS: [e.g. Windows 11, Pop!_OS]
- Package Version: [e.g. 0.8.12]
- Npm/Yarn/Pnpm Version: [e.g. npm@9.6.6, pnpm@8.5.1]

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/tree/main/apps/docs

**Comment by ezzle** [comment]
> https://github.com/bootstrap-vue-next/bootstrap-vue-next/tree/main/apps/docs

Sorry. Not a solution. No info about how to use bootstrap-vue-next in a vitepress project.
What I am trying to do is NOT use vitepress to build a doc for bootstrap-vue-next
But use and integrate bootstrap-vue-next in my own vitepress project : bootstrap is one of dependencies alongside vitepress.

Thank you for your help

**Comment by VividLemon** [comment]
Mf the docs are literally made in vitepress. Wtf are you saying
