### ISSUE TITLE
v-b-tooltip not working?

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [bootstrap-vue-next/bootstrap-vue-next#1531]
### Describe the bug

"button"  v-b-tooltip.hover.top.title="'ass'"> Click  "/button"

### Reproduction

No

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.15 GB / 15.69 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.57)
```

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JoseAntonioNavasSolutia** [comment]
In StackBlitz work good but i use nuxt 3 with SSR and not work. Sorry for my english.

**Comment by xvaara** [comment]
@JoseAntonioNavasSolutia did you btw. import the directives? As documented the nuxt module doesn't load them automatically.
