### ISSUE TITLE
BTable Refactor & fixes

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1534]
BTable needs a number of fixes.
1. It should utilize downstream components - BTr, THead, BTd, etc.
2. BTableLite needs to be created. BTable is a wrapper around BTableLite, which is a wrapper around BTableSimple
BTable -> BTableLite -> BTableSimple
Doing it in this format means that downstream fixes will fix all issues.
3. BTable fixes. All of the issues described in the issues tab should be addressed.

**Comment by yashwp** [comment]
@VividLemon rowSelected key is not exposed it seems in the latest version of the package
