### ISSUE TITLE
Adding classes on BAccordion 

### ISSUE THREAD

**Issue by ptdev** [bootstrap-vue-next/bootstrap-vue-next#1535]
### Clear and concise description of the problem

Hi there, 

First of all, thanks a lot for maintaining this repository, it definitely makes it much more pleasant to use on vue/nuxt instead of the standard bootstrap. 👍 

My new feature proposal is related to the accordion component:

The BAccordion component doesn't allow adding custom classes to the generated buttons that toggle the collapse nor the parent element or the "content" part of the accordion.

It appears as bcollapse has a hardcoded "accordion-collapse" and each collapse button has "accordion-button" and "collapsed" classes only.

It would be useful to have some props so we could add some classes to either of them.

### Suggested solution

I would suggest some props that allow classes to be added to the parent accordion as well as each collapse button and collapse content. Something simillar to how the BTab(s) component has their "contentClass", "navClass", etc props.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
https://github.com/orgs/bootstrap-vue-next/projects/1?pane=issue&itemId=31679414
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/756

**Comment by ptdev** [comment]
Hi,

Sorry for commenting on this closed issue, but even with these latest fixes, we're still unable to assign dynamic classes to the accordion-item div.

For example, the classes assigned to BAccordionItem are correctly passed to the accordion-item div, but if we use some dynamic classes there, then they do not reflect on the accordion-item div.

Just to clarify a bit better on what we want to achieve it would look something like this:

```
<BAccordion>
  
  <BAccordionItem title="Accordion Item #1" class="class1 class2" :class="{ 'class3': somevariable }">
     lorem ipsum content
  </BAccordionItem>
  
  <BAccordionItem title="Accordion Item #2" class="class1 class2" :class="{ 'class3': somevariable }">
    lorem ipsum content
  </BAccordionItem>
  
</BAccordion>
```

On this example, just class1 and class2 get assigned to the "accordion-item" div but class3 never get's assigned, even when somevariable is true.

All that we're trying to do is to simply change the border color of the accordion-item that is visible, which shouldn't be so hard imho.

Thanks, cheers.
