### ISSUE TITLE
v0.14.2 (#1470) breaks Nuxt's <img> src resolution

### ISSUE THREAD

**Issue by AaronDewes** [bootstrap-vue-next/bootstrap-vue-next#1539]
### Describe the bug

Since #1478, "normal" `<img>` tags don't resolve aliases correctly anymore. Without bootstrap-vue-nuxt or any version without that PR, it works fine.

### Reproduction

https://stackblitz.com/github/AaronDewes/bootstrap-vue-nuxt-bug?startScript=dev

### System Info

```Shell
Not relevant here, I'll share it if you can't reproduce it and need it.
```

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
related to https://github.com/nuxt/nuxt/issues/24038

**Comment by AaronDewes** [comment]
Thank you!
