### ISSUE TITLE
ComponentReference.vue doesn't correctly support Events and Slots

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#1570]
### Describe the bug

ComponentRefrence.vue loops through Properties, Events and Slots and renders them all in the same way.  But events and slots have nearly completely different fields.  The data structures all look like they're correctly defined, we just need the component to correctly interpret them.

bootstra-vue-next
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5083020/eca9cdf0-d498-4c8b-a143-eac3d4b1d0fb)

bootrstrap-vue
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5083020/d06a9067-1164-435a-a326-1173c23113db)

### Reproduction

See screenshots above

### System Info

```Shell
This is not a system specific issue
```

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dploc96** [comment]
fix by https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1571

**Comment by dwgray** [comment]
This was resolved by #1571
