### ISSUE TITLE
Pagination of b-table is not work anymore after 0.15.1 update

### ISSUE THREAD

**Issue by mediaessenz** [bootstrap-vue-next/bootstrap-vue-next#1613]
### Describe the bug

Pagination of b-table using a provider is not work anymore after 0.15.1 update

### Reproduction
[https://stackblitz.com/edit/github-qcjewr](https://stackblitz.com/edit/github-qcjewr)

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
If a reproduction is not made I will close the issue
