### ISSUE TITLE
Add option to make popover persistent.

### ISSUE THREAD

**Issue by yanghoxom** [bootstrap-vue-next/bootstrap-vue-next#1615]
### Describe the bug

Describe the bug
The application becomes very slow when initializing content with tooltip container 'body'

Reproduction
Sorry, I cannot provide an exact reproduction link because it requires a Weglot key.
I can only describe how it happened.

First, weglot will automatically detect changes in website elements to translate them
The problem is when I use container: 'body', the application runs extremely slow, it's like weglot has to check a lot of unnecessary/continuously changing elements in the DOM.
Even if I just scroll the page, no tooltip is displayed, the logic that checks the page to translate new elements is still triggered.
I checked and found it originates from boottrap-vue-next/tooltip

with the logic without the 'body' container, we would see the MutationObserver executed about 600 times
With the logic having container 'body', we see the actual MutationObserver when about 800 times
(The difference may not seem too big, but the problem still occurs)

I don't know the details of this difference, but this makes my application very slow when adding/initializing many elements with tooltip containers
System Info
OS: Ubuntu 20
Package Version: 0.13.2
Npm/Yarn/Pnpm Version: Yarn

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vcdfsk?file=app.vue

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by benjivm** [comment]
This is the caused by the same recursive updates happening in #1622 so it isn't just the `<BModal>` component.

**Comment by VividLemon** [comment]
I agree that utilizing the native Vue Teleport component to teleport to the body is going to have more overhead than not utilizing it. In regards to this, I'm not sure what you want me to do about it. 



> This is the caused by the same recursive updates happening in #1622 introduced in the `0.15.x` update, so it isn't just the `<BModal>` component.

There were no errors shown in the example of that issue. 

In addition, both reproductions that I tested here work "fine". So, I'm not sure what the issue is

**Comment by VividLemon** [comment]
If there is more evidence that's substantial I'll look at this further. 0.15 was pretty large and there has been, and is likely to be more, issues that occur

**Comment by xvaara** [comment]
@yanghoxom test with the latest 0.15.5 and add option persistent so that the tooltip element will stay in the dom even when hidden.

**Comment by yanghoxom** [comment]
@xvaara @VividLemon 
thank you so much.
As I said above, this is not a way to reproduce the real problem.
It shows clearly when I use a lot of popovers with weglot (an automatic translation tool that tracks changes in the DOM for continuous translation).

I will try with 0.15.5, tried `persistent`, and the lag issue still persists (lag has decreased, but still exists)
I suggest you try registering a Weglot account and try it (it's free).

**Comment by xvaara** [comment]
@yanghoxom Can you share the site that has the lag? since we can push 100 popovers in 20ms it's not our end. I think weglot is making api calls when you add the popover elements to translate them. That we can't help or solve on our end, you need to talk to weglot if they can do or advice something to make things faster.

**Comment by yanghoxom** [comment]
@xvaara 
thank you for the reply
>Can you share the site that has the lag? 
unfortunately, my site is private, so I can not share it.
>  I think weglot is making api calls when you add the popover elements to translate them

No, weglot does not make any API call when we run logic to add new popover because I checked in the network tab, and no request has been sent
besides, the reason I said the problem came from bootstrap-vue-next is that the lag was gone when I remove the option `container: 'body'`
