### ISSUE TITLE
BDropdownItem variant default to secondary

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1616]
property ```variant``` is BDropdownItem is set to 'secondary' by default 

Is it a mistake or wanted?

**Comment by xvaara** [comment]
That is an excellent  question. Maybe leftover from some copypaste?

**Comment by xvaara** [comment]
@VividLemon you added that in https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/6d4741300b4e05920f11c15ceead90471e3a514c is it required for some reason? seems like a mistake.

**Comment by VividLemon** [comment]
Seems like an accident on my end
