### ISSUE TITLE
Checkbox Group expects stable object as modelValue

### ISSUE THREAD

**Issue by kalekseev** [bootstrap-vue-next/bootstrap-vue-next#1623]
### Describe the bug

This watch https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/48d25fa75d90cbe76745b2ce0a1e8a6bd542e1a2/packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckboxGroup.vue#L163C2-L163C2 will fire recursively if modelValue array is not the same object. In my reproduction I've tried to show real life example where user would need to modify modelValue array.

I investigated Checkbox Group only but other components may also be affected.

### Reproduction

https://stackblitz.com/edit/github-jfyohs-ef8cfh?file=src%2FPages%2FIndex.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kalekseev** [comment]
Updated reproduction link with the correct one.

**Comment by kalekseev** [comment]
@VividLemon potentially radio group is also affected,  modelValue typings imply it can be object or array but I haven't tested this case https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/8f31d37a43389fff40743b0c25f4720419cdf2a4/packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue#L132-L142

**Comment by VividLemon** [comment]
> @VividLemon potentially radio group is also affected, modelValue typings imply it can be object or array but I haven't tested this case
> 
> https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/8f31d37a43389fff40743b0c25f4720419cdf2a4/packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue#L132-L142

https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1626

**Comment by kalekseev** [comment]
With this fix checkbox group has internal sync that's not in sync with modelValue prop, try click "no" in repro https://stackblitz.com/edit/github-jfyohs-yazvho?file=src%2FPages%2FIndex.vue it will check while modelValue array is empty

**Comment by VividLemon** [comment]
That's going to be the expected behavior
