### ISSUE TITLE
SSR hydration mismatches

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue-next/bootstrap-vue-next#1632]
### Describe the bug

I added all the playground components to nuxt to test SSR, and noticed 53 warning, most of which were about hydration missmatches.

The reproduction on stackblitz doesn't generate that many warnings.

We should figure out a better way to test ssr.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-lqee3m?file=layouts%2Fdefault.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
@ptdev could you create a little example on stackblitz? just fork the one linked in this and make it fail like you have? That would help me to focus on your problem and maybe find it faster.

**Comment by ptdev** [comment]
Hey,

Sure, [here](https://stackblitz.com/edit/nuxt-starter-mzvvbx?file=app.vue) is a simplified sample of what i'm using.

But note that even without modification, your stackblitz link already shows an hydration error (at least on my end :) )

Thanks, cheers! 👍

**Comment by xvaara** [comment]
@ptdev this will be fixed in 0.16, we hope to get that out soon.

**Comment by xvaara** [comment]
nuxt render teleport elements in the beginning of body, not the end like vue. We'll have to wait for this to be fixed for some of the hydration missmatches: https://github.com/nuxt/nuxt/issues/24207

**Comment by sebbayer** [comment]
@xvaara since v3.11.0 nuxt now includes a teleports root element within the body tag. 

https://github.com/nuxt/nuxt/releases/tag/v3.11.0

I think the `#teleports` target ID has to be set by boostrap-vue-next to fix the hydration warnings.

**Comment by VividLemon** [comment]
> @VividLemon should we default all the teleports to `#teleports` and maybe add a check to see that it exists and warn about that in dev mode? or could we just create it if missing?

Once global options is supported, the nuxt module could just globally set the teleportTo for nuxt specific envionments

**Comment by xvaara** [comment]
more missmatch stuff from upstream: 
nuxt: https://github.com/nuxt/nuxt/issues/27378
vue core: https://github.com/vuejs/core/issues/6638

so if using ssr, set your own id:s for the components

**Comment by xvaara** [comment]
@VividLemon Also noticed that: [nuxt] `useId` might not work correctly with components that have `inheritAttrs: false`
so we maybe need to pick the https://github.com/nuxt/nuxt/blob/4d063f1f85cf53f4fa97978f3f8724aacb24174a/packages/nuxt/src/app/composables/id.ts#L5 nuxt attrs and put that to the wrapping element for ids to work. At the moment they aren't working in about half of the components.

**Comment by VividLemon** [comment]
I saw that useId doesn't work with inheritAttrs false, which is a problem considering we can't modify what is properly a fragment component.

So, if `data-n-ids` is the key to fixing this problem, then I'm all for it.

Technically we could pass through a variable from the nuxt module to check if we are in a nuxt environment and selectively add this attr. Or we could just add it regardless, doesn't really matter. 

> Then we have a problem with all the other ssr/ssg generator.

Other generators won't get first class support. Nuxt is the most popular by far. If an issue comes that is specific to one framework, those will be dealt on a case by case basis, like we shouldn't just ignore problems, but unless other frameworks have a modules system we can build for, its up to the dev in most cases to fix the issues. (They can implement their own useId function)

**Comment by xvaara** [comment]
There seems to be a lot of fixes in vue 3.5 for ssr!
Let's see if it's new useId also fixes our problems. We should maybe use that directly instead of the nuxt one.
3.4.35 has fixes for teleport also.

**Comment by VividLemon** [comment]
This seems to have been fixed by Vue 3.5. I checked, not hydration mismatches
