### ISSUE TITLE
BTable busy state hides current items

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1636]
### Describe the bug

When table is busy all the current rows are hidden, only loading message is visible...
In tables with provider and pagination this makes a "boing" effect on table.
Previous BootstrapVue3 (as BV2) just overlays rows with loading message floating in the middle

### Reproduction

https://stackblitz.com/edit/github-yfxyc5-eab59g?file=src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by makroxyz** [comment]
> Yes, that's expected behavior
> 
> https://bootstrap-vue.org/docs/components/table#table-busy-state

In the link you posted it's expected when you have ```table-busy``` slot, but if you set ```busy``` prop to ```true```  table should be "muted" as written a few lines above

**Comment by makroxyz** [comment]
@VividLemon without the default table-busy slot BTable works as the old BV2

**Comment by makroxyz** [comment]
@VividLemon 

In order to obtain the same BV2 behaviour on BTable busy state


BTable.vue  rows from 55 to 65 should be:
```vue
<template #custom-body="scope">
      <BTr
        v-if="busyBoolean && $slots['table-busy']"
        class="b-table-busy-slot"
        :class="getBusyRowClasses"
      >
        <BTd :colspan="scope.fields.length">
          <slot name="table-busy" />
        </BTd>
      </BTr>
    </template>
```

and ```busyLoadingText``` prop should be removed.

Any chances to have this?

**Comment by VividLemon** [comment]
My bad, this got lost in the past. I will fix it up soon

**Comment by VividLemon** [comment]
Literally just using the code you gave, smh

**Comment by ltickett** [comment]
@VividLemon I have been wondering for the last few days while my tables are no longer showing loading/busy state

I think I linked it back to this "fix".

I really like the behaviour before (showing the loading spinner).

Is there any way we can bring this back? Perhaps with a simple prop?

Or maybe we still show the previous rows but overlay the spinner while busy- I think that is what the bug was about?

Otherwise, I guess I need to create my own wrapper component to pass in BOverlay and BSpinner to the slot?

TIA 🙏

**Comment by VividLemon** [comment]
> @VividLemon I have been wondering for the last few days while my tables are no longer showing loading/busy state
> 
> I think I linked it back to this "fix".
> 
> I really like the behaviour before (showing the loading spinner).
> 
> Is there any way we can bring this back? Perhaps with a simple prop?
> 
> Or maybe we still show the previous rows but overlay the spinner while busy- I think that is what the bug was about?
> 
> Otherwise, I guess I need to create my own wrapper component to pass in BOverlay and BSpinner to the slot?
> 
> TIA 🙏

```html
<BTable>
<template #table-busy>
            <BOverlay show>
              <template #overlay>
                <div class="d-flex align-items-center gap-2 mt-5">
                  <BSpinner />
                  <strong>{{ props.busyLoadingText }}</strong>
                </div>
              </template>
            </BOverlay>
          </template></BTable>
```

**Comment by ltickett** [comment]
Thanks @VividLemon
