### ISSUE TITLE
Toast `delay` property is not working. Or Toast `delay` vs. `value` mismatch in docs and type of `BToastProps` is incorrect.

### ISSUE THREAD

**Issue by sceee** [bootstrap-vue-next/bootstrap-vue-next#1638]
### Describe the bug

When using Toasts, I noticed there is a mismatch for the autoHide `delay` in the docs as well as the types and the actual behavior.

In the [Component Reference docs](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/toast.html#comp-reference-btoast-properties), it states that there is a `delay` property (as it used to be in `bootstrap-vue`) for the autohide feature.
When using the `delay` property, it does not work.

However, in the docs for [Automatic Countdown](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/toast.html#automatic-countdown), in the example it used `value` instead to set the autoHide delay.

But then, when using it in Typescript, `BToastProps` do not include a `value` property but it includes a `delay` property.

So either the Component Reference docs and `BToastProps` types are wrong, or the actual behavior and the Automatic Countdown sample is wrong.

I attached a sample to demonstrate the behavior when setting `delay` vs. `value`. When setting `delay` to 10s, the toast is still dismissed after 5s.

### Reproduction

https://stackblitz.com/edit/github-yu36yr?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Delay prop was never used. Use value

**Comment by sceee** [comment]
Thanks, @VividLemon !
