### ISSUE TITLE
[Docs] Most References not found

### ISSUE THREAD

**Issue by stritti** [bootstrap-vue-next/bootstrap-vue-next#1642]
### Describe the bug

Try to open one of the references at https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference.html you get error, that the file is not found for following sections:

* [Form Validation](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/form-validation)
* [Settings](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/settings)
* [Size props and classes](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/size-props-and-classes)
* [Spacing classes](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/spacing-classes)
* [Starter Templates](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/starter-templates)
* [Theming Bootstrap](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/theming-bootstrap)
* [Third party libraries](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/third-party-libraries)
* [Utility Classes](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference/utility-classes)

just a few are available. I have not found files in git which could correspond to the missing links at https://github.com/bootstrap-vue-next/bootstrap-vue-next/tree/gh-pages/reference

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/reference.html

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
This is slightly similar to https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1173 , in that all of these issues would be fixed by that issue. Given that, I'm going to close this and point to that ticket instead. But yes, it is a problem
