### ISSUE TITLE
BModal emits `show` and `hide` more than once

### ISSUE THREAD

**Issue by corymccarty** [bootstrap-vue-next/bootstrap-vue-next#1655]
### Describe the bug

BModal emits `show` multiple times (three for `useModal()` and two for `v-model`) when shown, and emits `hide` twice when dismissed using the backdrop or either of the default buttons. `shown` and `hidden` are only emitted once (as expected).

### Reproduction

https://github.com/corymccarty/bootstrap-vue-next-modal-emits

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anrolmar** [comment]
I did this PR (https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1693) to fix the modals
