### ISSUE TITLE
BTab: v-bind to titleLinkClass causes infinite loop

### ISSUE THREAD

**Issue by corymccarty** [bootstrap-vue-next/bootstrap-vue-next#1663]
### Describe the bug

The linked reproduction is a close adaptation of the [`titleLinkClass` example](https://bootstrap-vue.org/docs/components/tabs#apply-custom-classes-to-the-generated-nav-tabs-or-pills) from the old BootstrapVue docs.

<img width="1139" alt="image" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/424572/8e106b7b-a44d-4f34-b6f7-897bc51ea1f9">

### Reproduction

https://github.com/corymccarty/bs-vue-next-tabs-loop

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
Using functions in v-bind is a reactivity nightmare. The function is evaluated on every read and causes computed to run it again and again since the returned array can't be identified as the same.

return a string:
```ts
function linkClass(classTabIndex: number) {
  if (tabIndex.value === classTabIndex) {
    return 'bg-primary text-light'
  }
  return 'bg-light text-info'
}
```

or evaluate in the template:
```vue
<BTabs v-model="tabIndex">
    <BTab
      title="Tab 1"
      :title-link-class="tabIndex === 0 ? ['bg-primary', 'text-light'] : ['bg-light', 'text-info']"
    >
      <p>Tab 1</p>
    </BTab>
    <BTab
      title="Tab 2"
      :title-link-class="tabIndex === 1 ? ['bg-primary', 'text-light'] : ['bg-light', 'text-info']"
    >
      <p>Tab 2</p>
    </BTab>
  </BTabs>
```
  
or create a computed:
```ts
const linkClassComputed = computed(() =>
  Array.from({length: 2}, (_, i) => {
    if (tabIndex.value === i) {
      return ['bg-primary', 'text-light']
    }
    return ['bg-light', 'text-info']
  })
)
```
```vue
<BTabs v-model="tabIndex">
    <BTab title="Tab 1" :title-link-class="linkClassComputed[0]">
      <p>Tab 1</p>
    </BTab>
    <BTab title="Tab 2" :title-link-class="linkClassComputed[1]">
      <p>Tab 2</p>
    </BTab>
  </BTabs>
```

You can use activeNavItemClass to set a class for the active tab, but there is no way to set class for the inactive elemenet yet. I'll create a pr for that.

**Comment by corymccarty** [comment]
Thank you for taking the time to go through that and suggest work-arounds! Just returning a string seems to work great, and I'll look a little more at which approach seems the cleanest. (I like the computed suggestion.)
