### ISSUE TITLE
BModal documentation for shown event has incorrect timing

### ISSUE THREAD

**Issue by celaena** [bootstrap-vue-next/bootstrap-vue-next#1677]
### Describe the bug

The [documentation for BModal's events](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html#comp-reference-bmodal-events) state that the `shown` event occurs _just before_ the modal is shown, but it is emitted _after_ the modal transition is entered and the default focus is activated. I believe the behavior is correct and the documentation just needs to be updated.

https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/e2e171e8743f60950c4f7a6f4c05372422fe8737/apps/docs/src/data/components/modal.data.ts#L393-L403

### Reproduction

https://stackblitz.com/edit/github-vf39ah?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
This doesn't just only the shown event, all four of the related events contain issues. Also, multiple components define those same events, most of which don't have definitions. Perhaps a new issue should be made to cover those?

**Comment by anrolmar** [comment]
I totally agree with you @VividLemon. Because I'm working on it, I'll change only the shown event documentation.
If the other events (show, hide and hidden) have issues, then it would be better to have a different ticket for each one
