### ISSUE TITLE
Make BTable and BTableLite Generic components

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#1682]
### Describe the bug

The underlying types for TableItem and TableField have generic variants, but to fully utilize them, I believe you have to make BTable and BTableLite generic components.  That way, typescript should be able to handle complex types used as table items correctly.  I may be missing something fundamental here, but it seems this is a direct application of what generic components are intended for.

I've got a (not working) first crack at doing this here: https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1681 - It doesn't work so I may be going down the wrong path.  I'm going to step back and do some more playing with generic components. 

### Reproduction

https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1681

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anrolmar** [comment]
Hi @dwgray. Are you still working on it?

**Comment by VividLemon** [comment]
Typing slot parameters will likely be interesting, considering many dynamic slot fields.

**Comment by dwgray** [comment]
@anrolmar Had some other priorities during the week but should have some time to work on this in the next couple of days.

**Comment by VividLemon** [comment]
It's likely not possible to `defineSlots` for BTable components. TypeScript can't use dynamic keys in type literals

(But this is ancillary to the PR)

**Comment by dwgray** [comment]
> It's likely not possible to `defineSlots` for BTable components. TypeScript can't use dynamic keys in type literals
> 
> (But this is ancillary to the PR)

I agree if we can't use `defineSlots` I don't think we'll be able to get TypeScript to play nicely with slots.

But, I'm closing in on getting something working with generics that correctly handles properties and events.  I'd like to scope this PR to that and take a closer look at options for typing slots in the future.
