### ISSUE TITLE
isEmptySlot method is deprecated

### ISSUE THREAD

**Issue by anrolmar** [bootstrap-vue-next/bootstrap-vue-next#1695]
There are some methods like `isEmptySlot` used on several components (as BFormRadio, for example), that are deprecated.

Code from `BFormRadio`,
`const hasDefaultSlot = toRef(() => !isEmptySlot(slots.default))`

Code from `utils/dom.ts`,
`/**
 * @deprecated
 */
export const isEmptySlot = (el: Slot | undefined): boolean => (el?.() ?? []).length === 0`

Do we need to take care of these deprecated methods?

**Comment by VividLemon** [comment]
I marked everything deprecated, regardless of its actual utility. Some things can stay. The goal was to ensure the use of certain functions are limited. I will look at this soon.

**Comment by VividLemon** [comment]
(A method is a function of a class. isEmptySlot is a function attached to no class... Therefore its technically a function)
