### ISSUE TITLE
Compiling errors with the last release on main branch

### ISSUE THREAD

**Issue by anrolmar** [bootstrap-vue-next/bootstrap-vue-next#1698]
Hi.

I've just pulled the last changes in main on my local branch and when I did a pnpm i (because I saw some changes in the package.json), I got two different errors:

- Playground project

<img width="1399" alt="Screenshot 2023-12-24 at 10 56 36" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/30998580/1368c7b0-d3ba-4f4c-a298-ed6e8e5bd5e3">

- Nuxt project
<img width="1379" alt="Screenshot 2023-12-24 at 10 56 23" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/30998580/440f7450-c51f-46a5-b93c-7bde8b7f0eb3">

Because of that, I cannot merge the changes on my current branches to keep working on issues

**Comment by VividLemon** [comment]
Ignore the issues. You can continue working on issues and PRs without it building. I will handle the fixes later

**Comment by anrolmar** [comment]
I cannot ignore that, because once I want to do a PR, husky fails en the pre-commit stage

**Comment by VividLemon** [comment]
`git commit --no-verify`

**Comment by VividLemon** [comment]
The goal of pulling my changes prematurely was to have other prs recognize their merge conflicts before they were fully finished. It didn't go as smoothly as hoped mb

**Comment by anrolmar** [comment]
Don't worry. It's quite difficult to work completely separately from the other in a project like this. I'll ask again when I find something like this.

**Comment by anrolmar** [comment]
I close the issue, then
