### ISSUE TITLE
Docs build infinite loop

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1702]
### Describe the bug

There exists some issue with processing the docs. First, during build it executes an infinite loop. The second issue is that when "dev" navigation of pages declares "vitepress data not properly injected in app". I suspect these two things are related. I'm not sure when this started (though its from a series of my changes). Something in https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/ca16a168687dc0e17d6dc5c6210205c1911dd793

### Reproduction

f

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sidneygijzen** [comment]
Regarding the second issue; I found an [upstream bug report](https://github.com/vuejs/vitepress/issues/3389) for the `vitepress data not properly injected in app`. The error goes away by upgrading to VitePress 1.0.0-rc.35.

However after upgrading VitePress, I'm still running into an error: `ReferenceError: document is not defined` while trying to build the docs locally. Is this what you mean with the 'infinite loop' issue you encountered?

I'm running:
- `pnpm --filter docs run build --stream` to test a build and
- `pnpm --filter docs run dev --stream` to view the docs locally.

**Comment by VividLemon** [comment]
> Regarding the second issue; I found an [upstream bug report](https://github.com/vuejs/vitepress/issues/3389) for the `vitepress data not properly injected in app`. The error goes away by upgrading to VitePress 1.0.0-rc.35.
> 
> Hmm, a bit strange though that the command line prints:
> 
> ```
> docs:build: ✓ rendering pages...
> docs:build: - generating sitemap...
> docs:build: ✓ generating sitemap...
> docs:build: build complete in 28.63s.
> ```
> 
> But it doesn't exit automatically... Is this what you mean with the 'infinite loop' issue you encountered?

Yes

**Comment by VividLemon** [comment]
Mentioned here https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1710#issuecomment-1880146326 this should be the only thing that 0.16 requires

**Comment by sidneygijzen** [comment]
Thanks for confirming the infinite loop error. I will look into it.

**Comment by VividLemon** [comment]
It may not be an infinite loop. It was the first thought I had for why it might be hanging

**Comment by sidneygijzen** [comment]
Thanks for the additional info and thoughts :+1:  I'll keep you posted.
