### ISSUE TITLE
Open a modal programmatically by passing the component (see Buefy)

### ISSUE THREAD

**Issue by dword-design** [bootstrap-vue-next/bootstrap-vue-next#1706]
### Clear and concise description of the problem

Opening a modal by defining it in the template has the problem that the component is always there and doesn't follow the usual lifecycle of a component, namely that it is mounted and destroyed when opened and hidden. This requires the modal to react to show and hide events to reset local data.

### Suggested solution

Provide a programmatic solution to open modals by passing the component and props. There is a [nice solution in Buefy](https://buefy.org/documentation/modal/#programmatic) that works like this:

```js
this.$buefy.modal.open({
    parent: this,
    component: SomeModal,
    props: {
      name: 'foo',
    },
})
```

Of course this could also be implemented using composition API.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by xvaara** [comment]
Adding a component programmatically seems really weird to me.  We could add an option to unmount the component at close. Now you can add lazy to have the mounted lifecycle run when opened.

**Comment by VividLemon** [comment]
> Adding a component programmatically seems really weird to me. We could add an option to unmount the component at close. Now you can add lazy to have the mounted lifecycle run when opened.

This already exists, just not released https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/ca16a168687dc0e17d6dc5c6210205c1911dd793/packages/bootstrap-vue-next/src/composables/useModalController.ts#L55

```ts
import MyCustomBModal from '..'
import BModal from '..'

const {show} = useModalController()

show(MyCustomBModal, computed(() => ({ noCloseOnBackdrop: true }))
show(h(BModal, { noCloseOnBackdrop: true })
show({noCloseOnBackdrop: true})
```

https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/apps/docs/src/docs/composables/useModalController.md#creating-modals

Doesn't show up on the docs because somewhere the docs gets stuck in an infinite loop when building. Not sure why

**Comment by VividLemon** [comment]
I suppose only an object parameter could make things more simple :thinking:

**Comment by VividLemon** [comment]
Finalized in https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1712 release planned 0.16
