### ISSUE TITLE
v-b-tooltip directive is not working with BDropdownItem

### ISSUE THREAD

**Issue by ertu96** [bootstrap-vue-next/bootstrap-vue-next#1708]
### Describe the bug

Using the Tooltip directive inside a dropdown is only partly working. What I need is a tooltip for a BDropdownItem element on the left-hand side but it is not showing up. Also it is not showing at all, if there is only a single BDropdownItem.
It used to work when working with Vue 2.

Only the second dropdown shows the tooltips. But in my case I need the first example to be working. Also note that the `disabled` styling is not properly set for the BDropdownItem.

### Reproduction

[https://stackblitz.com/edit/vitejs-vite-2qdgah](https://stackblitz.com/edit/vitejs-vite-2qdgah)

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
The tooltip is added next to the element, and dropdown has it's own scroll context. For now you can move it to body like so:
`v-b-tooltip.hover.left="{content: 'left', container: 'body'}"`

need to add a modifier for this. Or change the default for the directive.

**Comment by ertu96** [comment]
It worked. Thank you for the work around.
