### ISSUE TITLE
Dropdown positions are not working in Vue3 project

### ISSUE THREAD

**Issue by tarun-themesbrand** [bootstrap-vue-next/bootstrap-vue-next#1713]
### Describe the bug

We have added dropdown of bootsrap-vue-next, but any positions of dropdowns are not working. we have tried all dropdown positions with diffrent ways.

```
     <BDropdown class="d-inline-block" variant="white" toggle-class="header-item" dropup>
          <template #button-content>
            <img class :src="flag" alt="Header Language" height="16" />
            {{ text }}
          </template>
          <BDropdownItem linkClass="text-dark" href="javascript:void(0);" class="notify-item" v-for="(entry, i) in languages" :key="`Lang${i}`" :value="entry" @click="setLanguage(entry.language, entry.title, entry.flag)" :class="{ active: lan === entry.language }">
            <img :src="`${entry.flag}`" alt="user-image" class="me-1" height="12" />
            <span class="align-middle">{{ entry.title }}</span>
          </BDropdownItem>
        </BDropdown>
``` 

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-5883ra?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
Your code block is missing the dropdown tag, you reproduction works if you make space top of the dropdown.

Fixed the reproduction with space:
https://stackblitz.com/edit/bootstra-vue-next-template-mhihkx?file=src%2FApp.vue

Can you share your code?

**Comment by tarun-themesbrand** [comment]
I have followed the documentation but it will be not working.

**Comment by xvaara** [comment]
Provide a reproduction that shows when it's not working. the one you provided worked.
