### ISSUE TITLE
BNavItem does not consider RouterOptions for linkExactActiveClass and linkActiveClass

### ISSUE THREAD

**Issue by noehmeier** [bootstrap-vue-next/bootstrap-vue-next#1720]
**What i are trying to do.**
Vue Router has the option to change the default classes `router-link-active` and `router-link-exact-active`, see [here ](https://router.vuejs.org/api/interfaces/RouterOptions.html#linkExactActiveClass) and [here](https://www.webmound.com/custom-active-class-to-router-link-in-vue-3/). I want to use it, to override the Vue classes with the Bootstrap `active` class.

**What i have already tried.**
```javascript
// at router/index.ts
const router = createRouter({
    history: createWebHashHistory(process.env.BASE_URL),
    routes,
    linkActiveClass: "",
    linkExactActiveClass: "active",
});
```

I set the following navigation links:
```html
<BNav
	vertical
	class="nav-pills mb-auto"
>
	<BNavItem
		:to="{ name: ROUTES_PROJECT_ADD }"
		link-class="link-dark"
	>
		add
	</BNavItem>
	<router-link
		:to="{ name: ROUTES_PROJECT_ADD }"
		class="nav-link link-dark"
	>
		add
	</router-link>
</BNav>
```

That generates the following DOM, if the link is active:
```html
<ul class="nav flex-column nav-pills mb-auto">
	<li class="nav-item">
		<a href="#/project/add" class="router-link-active router-link-exact-active nav-link link-dark"> add </a>
	</li>
	<a href="#/project/add" class="active nav-link link-dark" aria-current="page"> add </a>
</ul>
```

**Any error messages i are getting.**
This shows for me, that `BNavItem` did not recognize the global Vue router settings, while the Vue native `router-link` did. I see in the documentation also no way, how to fix that. The `active` parameter seems only be useful if i want to set it by myself manually, but that is not the use case, i want to use the Vue router settings for automatically set `active` for the correct Bootstrap css.

To dynamically and automatically use the Bootstrap `active` class, based on Vue router settings, in my opinion the `BNavItem` should register and use the Vue settings. Or if not, how else is the "correct" way to solve this problem in an easy way?

**Environment:**

- OS: Windows 10
- Package Version: 0.15.5
- npm@10.1.0

Thank your very much for responses in advance!

**Comment by VividLemon** [comment]
There is no way to do what you're requesting at the moment. Refer to https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1607
