### ISSUE TITLE
BToastOrchestrator no way to selectively enable/disable fade transition

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1724]
### Describe the bug

When using useToast.show with BToastOrchestrator, there is no way to turn on and off the animation for fading. This was a small design decision to have it finished _now_ as I explore other options. 

### Reproduction

TToast.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Renuka9527** [comment]
Is there any way where we pass VnodesMsg and VnodeTitle to the useToast. I tried to pass it is return the vnodes directly instead of rendering the content.
Need something which is similar to https://bootstrap-vue.org/docs/components/toast. Show Toast with content.

**Comment by VividLemon** [comment]
> Is there any way where we pass VnodesMsg and VnodeTitle to the useToast. I tried to pass it is return the vnodes directly instead of rendering the content.
> 
> Need something which is similar to https://bootstrap-vue.org/docs/components/toast. Show Toast with content.

This is not related to the issue. Please leave unrelated questions out of issues. Whatever you're looking for probably exists, but your question is also unclear.

**Comment by VividLemon** [comment]
Might not do this: TransitionGroup doesn't really allow for this
