### ISSUE TITLE
BootstrapVueNextPlugin not exist / BToastOrchestrator not found?

### ISSUE THREAD

**Issue by noehmeier** [bootstrap-vue-next/bootstrap-vue-next#1727]
**What i am trying to do.**
I want to run `BToastOrchestrator`, but if i use i set it, i get the error `Uncaught SyntaxError: ambiguous indirect export: BToastOrchestrator`

```html
<template>
    <BToastOrchestrator />
       [...]
</template>
```
The general components like BButton, BCard, ... are running without the use of the BoostrapVueNextPlugin import.

**What i have already tried.**
I installed Bootstrap and BoostrapVueNext with npm. I also installed with npm `unplugin-vue-components` and configured it. It seems to work, on vite update it register components in my `components.d.ts`.

The introduction says, i have to import `BoostrapVueNextPlugin` to use  `BToastOrchestrator`, but this seems not to exist. Vue tells me, there is `BoostrapVueNext`, so i tried this:

```javascript
// main.ts
// not working, BootstrapVueNextPlugin not found
// import {BootstrapVueNextPlugin} from 'bootstrap-vue-next'

// my solution
import { BootstrapVueNext } from "bootstrap-vue-next";
import { createApp } from "vue";

import { registerPlugins } from "@/plugins";
import App from "./App.vue";

import "bootstrap";
import "bootstrap-vue-next";

const app = createApp(App);

registerPlugins(app);

// also tried this, not working too
// app.use(BootstrapVueNext, { components: true, directives: true });
app.use(BootstrapVueNext);

app.mount("#app");
```

The `unplugin-vue-components` seems to work here, in `components.d.ts` i have
```javascript
export {}

declare module 'vue' {
  export interface GlobalComponents {
    [...]
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
  }
}
```

I do not know if the problem is the maybe wrong BootstrapVueNextPlugin/BootstrapVueNext import or something with `<BToastOrchestrator />`? Hope you can help me out, thank you in advance.

**Any error messages i am getting.**
`Uncaught SyntaxError: ambiguous indirect export: BToastOrchestrator`

`Vue:  "bootstrap-vue-next"  has no exported member named  BootstrapVueNextPlugin . Did you mean  BootstrapVueNext ?`

**Environment:**

- OS: Windows 10
- Package Version: "bootstrap-vue-next": "^0.15.5"
- Npm/Yarn/Pnpm/Bun Version: npm@10.1.0

**Comment by Fajfa** [comment]
Regarding the plugin I managed to import it with
```
import BootstrapVueNextPlugin from 'bootstrap-vue-next'
app.use(BootstrapVueNextPlugin)
```

Im having the issue of using BToastOrchestrator though

```
does not provide an export named 'BToastOrchestrator
```

**Comment by noehmeier** [comment]
Thank you @Fajfa, that fixed the Plugin import error. But as you wrote, still the `<BToastOrchestrator />` problem, too. 🤷🏽‍♂️

**Comment by Fajfa** [comment]
@noehmeier As far as i can see `BToastOrchestrator` was replaced by `BToaster`
Im using it like this

```

    <BToaster />
  </main>
</template>

<script setup>
import { computed } from 'vue'
import { useToast } from 'bootstrap-vue-next'

const { show } = useToast()

show?.({
  props: computed(() => ({
    body: 'Foo bar baz',
  })),
})
</script>
```

**Comment by VividLemon** [comment]
```ts
registerPlugins(app);

// also tried this, not working too
// app.use(BootstrapVueNext, { components: true, directives: true });
app.use(BootstrapVueNext);

```
Strange as this is a plugin, that could be included in the registerPlugins function

...

The docs are for an unreleased version. There is no separation between what is released and what is on the docs. This is a very poor strategy, but alas I'm not going to fix it now. 

The plugin is exposed as the default export. You can name that whatever you want. 

BToastOrchestrator may or may not be released yet, idk. I'm guessing not. Tbh the useToast may not be released yet either, I don't know. Regardless, release planning soon so not a huge problem. 

All that being said, that installation may change as well soon. 

Not a whole lot of information on how to fix the issue...
Using the plugin is not necessary at the moment when using unplugin vue components. I suggest to simply remove the plugin.

Install using unplugin vue components.

Then call it a day, you're done for now

However: when 0.16 is released, even with using unplugin vue components you **will** need to use the plugin. Usage with useToast, useModalManager, breadcrumbs, etc will all throw a runtime warn with `'x' symbol not found`
