### ISSUE TITLE
Default component ids are not SSR friendly

### ISSUE THREAD

**Issue by Al-Rozhkov** [bootstrap-vue-next/bootstrap-vue-next#1730]
### Describe the bug

If component id is not explicitly specified, it is generated using Math.random(), which leads to hydration errors:

```
Hydration attribute mismatch on <input id=​"__BVID__921175___BV_form-check__" class=​"form-check-input" type=​"checkbox">​ 
  - rendered on server: id="__BVID__921175___BV_form-check__"
  - expected on client: id="__BVID__935395___BV_form-check__"
```

Solution: use the bootstrap-vue strategy. If the component id is not specified, leave it empty during SSR and generate it `onMounted`.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-bavjvy?file=app.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
I'd prefer an alternative solution. Something more like https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/util/getCurrentInstance.ts#L26

**Comment by Al-Rozhkov** [comment]
It should be considered that `getCurrentInstance` is internal API: https://github.com/vuejs/docs/issues/1422#issuecomment-1032120675.

Which is why it's not in the official documentation.
