### ISSUE TITLE
BFormCheckbox: switch attribute not working

### ISSUE THREAD

**Issue by ertu96** [bootstrap-vue-next/bootstrap-vue-next#1732]
### Describe the bug

The `switch` attribute for the `<BFormCheckbox />` component does not have any effect. I have tried alternative syntaxes as without the composition API and the kebab-case syntax `<b-form-checkbox switch />`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-2qdgah?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
That reproduction is using Bootstrap v4. 
![Screenshot from 2024-02-06 asdf12-47-53](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/5f417986-be3c-4fcb-9a0d-232964b2497c)

**Comment by VividLemon** [comment]
> I have tried alternative syntaxes as without the composition API and the kebab-case syntax <b-form-checkbox switch />

Neither of these would matter. They're outside the scope of this library as Vue is the one that handles those transformations. Whatever syntax you choose will have no effect (mostly)
