### ISSUE TITLE
BOffcanvas doesn't seem to use class for the whole component like sidebar-class on Bootstrap-vue

### ISSUE THREAD

**Issue by anrolmar** [bootstrap-vue-next/bootstrap-vue-next#1733]
I'm trying to set a class for the BOffcanvas component:

`<BOffcanvas
      v-model="show"
      placement="end"
      body-class="px-0"
      header-class="header"
      lazy
      :backdrop="false"
      class="myclass"
    />`

The style is like this (I'm using SCSS and scoped):

`
.myclass {
  width: 50% !important;
  box-shadow: 0 0 1.5rem #6c757d;
}
`

But, the class name is on the rendered component, but the class is not rendered or not applying

**Comment by VividLemon** [comment]
It's important to separate that offcanvas and sidebar are two different things. The bootstrap vue sidebar was not officially supported in Bootstrap, only in v5 of bootstrap was offcanvas added. So, your question is more of a Bootstrap question than a bvn question

There is a variable that you can change https://getbootstrap.com/docs/5.3/components/offcanvas/#variables `--#{$prefix}offcanvas-width: #{$offcanvas-horizontal-width};`
