### ISSUE TITLE
Docs: Syntax highlighting is broken 

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#1738]
### Describe the bug

Sometime fairly recently it looks like syntax highlighting was broken in the docs.  This appears to be true for all of the examples, the example below is an example I modified recently and I'm pretty sure it was highlighting correctly when I did that in #1725, but I probably hadn't merged #1723 when I did the testing on that, so that may be a candidate.

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5083020/9e22c188-6abd-49c0-a48b-3f4e1c8635ea)

### Reproduction

See the above image.

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dwgray** [comment]
Thanks @VividLemon , I should have some time today or tomorrow to take a look at this unless you're already working on it.

**Comment by VividLemon** [comment]
> Thanks @VividLemon , I should have some time today or tomorrow to take a look at this unless you're already working on it.
> 

No, I'm not actively working on it
