### ISSUE TITLE
BFormSelect missing value-field disabled-field text-field html-field props

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1739]
### Describe the bug

In 0.16 release 
BFormSelect properties ```value-field``` ```disabled-field``` ```text-field```  ```html-field``` are missing while 
BFormRadioGroup and BFormCheckboxGroup still have these props

It really breaks everything!

Can we restore these props?

### Reproduction

https://stackblitz.com/edit/github-95vcad?file=src%2Fmain.ts,src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by makroxyz** [comment]
@VividLemon please have a look at this issue. If it is wanted I'll go for a workaround in project, otherwise I can write a PR.
Thanks

**Comment by VividLemon** [comment]
None of them were meant to be removed. The only thing that was meant to be removed was https://bootstrap-vue.org/docs/components/form-select#options-as-an-object

**Comment by VividLemon** [comment]
I believe the changes to "SelectOption" were supposed to include something like mapped types, or some other TS voodoo to get working. But I think it was an accident to include those changes -- I likely got mixed up with something else.

**Comment by makroxyz** [comment]
Can you rollback the changes or should I go for a PR?

**Comment by VividLemon** [comment]
A PR would be appreciated
