### ISSUE TITLE
Keyboard interaction with BFormSelect inside BDropdownForm

### ISSUE THREAD

**Issue by helenezspeer** [bootstrap-vue-next/bootstrap-vue-next#1742]
### Describe the bug

Using a keyboard, it's not possible to select a value in a BFormSelect when inside a BDropdownForm. I can use the tab key to navigate to the select, but the arrow keys have no effect.

This is what I tried (same as in StackBlitz).

  ```
  <BDropdown text="toggle content" :autoClose="false">
      <BDropdownForm>
        <label>
          Try to control this select with arrow keys
          <BFormSelect>
            <option>One</option>
            <option>Two</option>
          </BFormSelect>
        </label>
      </BDropdownForm>
    </BDropdown>
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-a4hmiy?file=src%2Fcomponents%2FHelloWorld.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
@helenezspeer what browser you have? keys work for me. Chrome on a mac and edge on windows.

**Comment by xvaara** [comment]
Ah, now I get it. Arrow key doesn't open the select box. Arrow keys should navigate to the next dropdown item. Maybe we need to add some ignores to that that...
