### ISSUE TITLE
Inconsistent BAvatar Size Prop

### ISSUE THREAD

**Issue by ijay-bm** [bootstrap-vue-next/bootstrap-vue-next#1748]
### Describe the bug

In the documentation for BAvatar's sizing (https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/avatar.html#sizing), various usages of the `size` prop are shown. However, they are inconsistent when rendered. 

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/81517464/c536289c-ef4a-4270-a601-b02819036b74)

### Reproduction

https://stackblitz.com/~/edit/github-wapqys?file=src%2Fcomponents%2FComp.vue%2Csrc%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lqbach** [comment]
@VividLemon can be closed with #1760
