### ISSUE TITLE
Global config option (component)

### ISSUE THREAD

**Issue by mzee19** [bootstrap-vue-next/bootstrap-vue-next#1751]
### Describe the bug

After smoothly running on version 0.15.0, I encountered rendering issues when updating to version 0.16.0 of my application. Despite attempting to set the options parameter to `true`, the components did not render globally.

Version0.15.0
 ![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/72722281/96099b27-b6f4-4872-89e8-de993c7d0cb0)

Version 0.16.0
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/72722281/4494e7e2-11a2-470e-bf75-5aeba4fee48f)

### Reproduction

...

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Short answer:

`use TypeScript`

Long answer:

The default export is a function https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html#installation-vue-js

It seems like a lot of libs do this, Vuetify, Pinia. I suspect its to make up for some shortcomings in the TS in Vue plugins, which is why I made it a function instead.
