### ISSUE TITLE
Inconsistent placement props BDropdown and others

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1752]
### Clear and concise description of the problem

BDropdown does dropup, dropend, etc. This is quite dumb. A single "location" prop, or position prop should be created instead. Similar, if not the same as, https://vuetifyjs.com/en/api/v-tooltip/#props-location . The goal is to remove these individual position props, and unify them. Then to unify all components to this expected structure

### Suggested solution

asdf

### Alternative

asdf

### Additional context

asdf

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by xvaara** [comment]
Should we just use floating-ui ones?

**Comment by VividLemon** [comment]
What are the differences between the two types?

**Comment by VividLemon** [comment]
I also need to catalogue what possibly shares "location" values. Location on a drop down popover is different than bcardimg being "end"

**Comment by xvaara** [comment]
https://floating-ui.com/docs/computePosition#placement

**Comment by xvaara** [comment]
I kinda would like it to be booleans... Not sure about this but:
```
// bottom by default. props boolean for left, right and top, and start end.
<BTooltip top end> ... </BTooltip>
<BTooltip left start> ... </BTooltip>
```

**Comment by VividLemon** [comment]
I prefer the simple location prop, as I feel like it's a lot of bloat. Having multiple location items makes the template look weird, and in our code you have to do like 4 or 5 useBooleanish statements. In addition, it also makes it easier to see that these props, top, start, end, etc are all related. I think it would just add a lot more simplicity if they were merged and standard throughout the components.

But speaking of Booleanish, after making the changes to useBooleanish and making it a simple !!, it made me think that allowing strings is kinda silly. We may consider using only booleans instead.
