### ISSUE TITLE
Implement aliasing system

### ISSUE THREAD

**Issue by yogeshgalav** [bootstrap-vue-next/bootstrap-vue-next#1753]
### Clear and concise description of the problem

When migrating from bootstrap-vue  to bootstrap-vue-next, one of the major problem which leads to major code change is
"BInput" component not present, this componen is present but with other name "BFormInput"
Goal: minimum code change while migrating from bootstrap-vue.
Benifit: less boiler plate for component name, less or no code change for migration

### Suggested solution

The Alias for BFormInput should be BInput
just like Bootstrap-vue
This can be achieved with component.d.ts

### Alternative

New component BInput which directly exports BFormInput

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
Related: 
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1607
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1569

**Comment by VividLemon** [comment]
In my point of view, "internal aliasing" is just bloat. I have mixed feelings about adding official aliased names and instead would prefer a system where users could maintain their own sets of aliases.

**Comment by xvaara** [comment]
IMHO, if it's just one search and replace on the codebase, I don't think we need to worry about this. Just document the change to a migration guide.

**Comment by yogeshGroony** [comment]
@VividLemon Just wanted to save time and effort to change lot of codebase.
Please do it, from product point of view it would be great.
If you don't want to make internal alias, then you can keep short ones
Like everyone will prefer BInput over BFormInput
From product point please make the change,
there is no other alternate available for bootstrap-vue in market.

**Comment by VividLemon** [comment]
I was thinking about the purpose of the internal alias the other day, and came to the realization that it's a bit silly not to include it by default... It doesn't necessarily need to be a default, but could be an opt in feature (one that would hopefully require a simple one line change perhaps). Or simply just be made the default. That being said, the inclusion of default aliases would also require the ability to add custom aliases. So, in conclusion, once I finish the alias system, I will include plans for default aliases.
