### ISSUE TITLE
BTooltip does not stay open when being hovered with the mouse

### ISSUE THREAD

**Issue by sceee** [bootstrap-vue-next/bootstrap-vue-next#1757]
### Describe the bug

When creating a BTooltip with interactive content (e.g. a link), the BTooltip needs to stay open while being hovered by the mouse so that the user can interact with the content (e.g. click the link).

However, at the moment (bootstrap-vue-next 0.16.1) the tooltip hides as soon as you move away from the original hover element making it impossible to interact with the content (e.g. click the link).

**Expected**
* BTooltip stays open while being hovered with the mouse

_Update:_
Actually I just noticed this is a difference between `bootstrap-vue` and `bootstrap` (5.3):
* In `bootstrap-vue` (see https://bootstrap-vue.org/docs/components/tooltip#noninteractive-tooltips ) the tooltips are interactive by default and stay open on hover
* But in bootstrap 5.3 (see https://getbootstrap.com/docs/5.3/components/tooltips/#custom-tooltips ) it is closed when hovering
So it might indeed not be a bug but rather a feature request to be able to keep it open on hover (= have the possibility to keep the BootstrapVue interactive behavior).

_Update 2:_
It can still be made interactive (=stay open), see my [comment below](https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1757#issuecomment-1935707454) for an improvement suggestion.

### Reproduction

https://stackblitz.com/edit/github-ydahcf?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sceee** [comment]
I now noticed it works if the `BTooltip` gets `:noninteractive="false"` set. Then it stays open on hover.

So this works to keep the BTooltip open on hovering the tooltip:
```
<BTooltip :target="..." placement="..." :noninteractive="false">
</BTooltip>
```

However, it seems a bit strange to have to set a "negated" property `noninteractive` to `false` to make the BTooltip interactive.

So as an improvement suggestion:
Probably it would be better to change this property to be named `interactive` which defaults to false (e.g. matches the Bootstrap 5.3 behavior) and if explicitly set to true, it makes the BTooltip stay open.

**Comment by xvaara** [comment]
tooltip now has interactive prop.
