### ISSUE TITLE
[Vue warn]: injection "Symbol(modalManagerPlugin)" not found. 

### ISSUE THREAD

**Issue by bcorey85** [bootstrap-vue-next/bootstrap-vue-next#1758]
### Describe the bug

- BModal components cause a Vue injection warning on fresh install and do not open via `useModal().show`

Steps to Reproduce:
1. npm install
2. npm run dev
3. Observe console warning - [Vue warn]: injection "Symbol(modalManagerPlugin)" not found. 
4. Try opening modal

### Reproduction

https://github.com/bcorey85/bootstrap-vue-next-modal-debug

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ErikVerheul** [comment]
Have the same problem when rendering on the client (not NUXT) for every instance of BModel. Revert to version 0.15.5 which does not have this issue.

**Comment by bcorey85** [comment]
@VividLemon This PR fixed the issue in our core app, but unit tests involving modals are still throwing `injection "Symbol(modalManagerPlugin)" not found` errors.

I updated the original example repo [https://github.com/bcorey85/bootstrap-vue-next-modal-debug](url) with an example: 

1. npm install
2. npm test
3. observe `[Vue warn]: injection "Symbol(modalManagerPlugin)" not found.` thrown from `BModal.test.ts`

**Comment by alekswebnet** [comment]
For me, it has been resolved by installing required plugin:

`import bootstrapVue from 'bootstrap-vue-next'`

`app.use(
    bootstrapVue({
      plugins: {
        modalController: true
      }
    })
  )`

**Comment by OliveLeb** [comment]
Had the warning too and what worked for me was to follow installation instructions from the [docs](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html) 🤡 
```
// main.js/ts
import {createApp} from 'vue'
import {createBootstrap} from 'bootstrap-vue-next'

// Add the necessary CSS
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue-next/dist/bootstrap-vue-next.css'

const app = createApp(App)
app.use(createBootstrap()) // Important
app.mount('#app')
```
The `import and use createBootstrap` part

**Comment by caro3801** [comment]
Using the built in registration works but it seems that the issue is still present in version 0.16.6 using the [​Tree-shaken Installation Method](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html#tree-shaken-installation-method). Any idea?

Reverting to v0.15.5 (many thanks to the maintainers for all the work !)

**Comment by VividLemon** [comment]
> Using the built in registration works but it seems that the issue is still present in version 0.16.6 using the [​Tree-shaken Installation Method](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html#tree-shaken-installation-method). Any idea?

The two sections are different from each other. You always need to do https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html#install . Anything else is extra

**Comment by caro3801** [comment]
My bad, thanks for the explanations
