### ISSUE TITLE
BToast invalid docs

### ISSUE THREAD

**Issue by mediaessenz** [bootstrap-vue-next/bootstrap-vue-next#1769]
### Describe the bug

The bug is also visible on the official documentation of this project.
Go to https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/toast.htm, scroll down to "Automatic Countdown" and press the "Show" button.

The toast will be visible with only 2 pixels height.

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/toast.html

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mediaessenz** [comment]
Maybe it's a bug or the docs are outdated.

If I put the properies inside an object with a props key it works:
```
toast.show({props: {
   title: 'Toast title',
   body: 'Toast body',
   variant: 'success'
}}); 
```

**Comment by VividLemon** [comment]
Outdated docs

**Comment by VividLemon** [comment]
Feel free to submit a PR updating those examples

**Comment by VividLemon** [comment]
Here https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/toast.html
Schemas should be converted from 
show?.('Watch me!', {
        title: 'Counting down!',
        variant: 'info',
        pos: 'middle-center',
        value: 10000,
        interval: 100,
        progressProps: {
          variant: 'danger',
        },
      })

To match that shown in 
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useToast.html

**Comment by Renuka9527** [comment]
useToast is not working. May be this could be Bug. 
Feel free to submit a PR updating those updated documentation or examples. It should be pretty straightforward. 
Here is below example I tried
<template>
  <BButton
    @click="
      show?.('Watch me!', {
        title: 'Toast title',
        body: 'Toast body',
        value: true, 
        variant: 'success',
        pos: 'bottom-center'
      })
    "
  >
    Show
  </BButton>
</template>

<script setup lang="ts">
import { useToast } from "bootstrap-vue-next";
const {show} = useToast()
</script>
