### ISSUE TITLE
Remove `Booleanish` type. Replace with boolean

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1774]
### Clear and concise description of the problem

The Booleanish type was created to match those in the HTMLAttributes base interfaces. However, the inclusion of 'true' & 'false' don't play much of a role. 

### Suggested solution

Remove Booleanish, replace with pure boolean values

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sceee** [comment]
@VividLemon would you accept smaller PRs that applies this change to single or a few components at a time?
Or would you prefer to have the change in one big PR?

I had a look at it and tried to remove all at once but it caused a lot of tests to fail so I think it might be better to do it in smaller steps.
