### ISSUE TITLE
Remove deprecated Bootstrap classes -- or even outdated classes!

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1779]
There are instances of using Bootstrap classes that are either deprecated or much worse, removed.

One instance of this is/was btn-block

**Comment by VividLemon** [comment]
These items need to be removed and updated to reflect their bootstrap 5 capabilities.

**Comment by sceee** [comment]
I've worked through https://getbootstrap.com/docs/5.3/migration/#v500 , I found references to the following breaking changes from bootstrap 5 in `bootstrap-vue-next` and think these need to be adressed:

SASS:

- [ ] Previously deprecated `hover-focus-active()` mixin was removed (https://getbootstrap.com/docs/5.3/migration/#sass)

Grid:

- [ ] There is no only `.order-1` to `.order-5` out of the box ( https://getbootstrap.com/docs/5.3/migration/#grid-updates ). `.order-6` is used at least in a `BCol` test

Forms:

- [ ] `.custom-range` (used in the docs) was renamed to `.form-range` (https://getbootstrap.com/docs/5.3/migration/#forms-1)
- [ ] `.input-group-append` and `.input-group-prepend` have been dropped (used in scss) (https://getbootstrap.com/docs/5.3/migration/#forms-1)

Components:

- [ ] `.badge-*` color classes have been dropped (used in the docs) (https://getbootstrap.com/docs/5.3/migration/#badges)
- [ ] `.card-deck` was dropped (used in scss and BCardGroup) (https://getbootstrap.com/docs/5.3/migration/#card)
- [ ] `.card-columns` was dropped (used in scss and BCardGroup) (https://getbootstrap.com/docs/5.3/migration/#card)
- [ ] `flip` option for Dropdown plugin was dropped in favor of native Popper configuration (used in BDropdown) (https://getbootstrap.com/docs/5.3/migration/#dropdowns-1)

Utilities:

- [ ] Renamed `.ml-*` and `.mr-*` to `.ms-*` and `.me-*` (used in the docs and playground) (https://getbootstrap.com/docs/5.3/migration/#utilities-3)
- [ ] Renamed `.sr-only` to `.visually-hidden` (used in docs and playground) (https://getbootstrap.com/docs/5.3/migration/#utilities-3)

I _hope_ I detected most. It's sometimes pretty hard to detect these as you cannot simply search for the deprecated/removed classes as they are sometimes joined together from different strings/props.

**Comment by VividLemon** [comment]
Tyvm

**Comment by VividLemon** [comment]
fixed by https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2264
