### ISSUE TITLE
Incorrect custom event names for BCarousel

### ISSUE THREAD

**Issue by jonkri** [bootstrap-vue-next/bootstrap-vue-next#1783]
### Describe the bug

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/carousel.html#comp-reference-bcarousel-events mentions `sliding-end` and `sliding-start`. As far as I can tell, these event names should be `slid` and `slide`.

### Reproduction

https://stackblitz.com/edit/github-85u2cx?file=src%2FApp.vue

When changing `sliding-start` to `slide` and `sliding-end` to `slid` respectively I can see the `console.log` entries.

### Used Package Manager

n/a

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jonkri** [comment]
I think the solution is to just rename the events in `apps/docs/src/data/components/carousel.data.ts`.

Thanks for a great library! 😊

**Comment by VividLemon** [comment]
> I think the solution is to just rename the events in `apps/docs/src/data/components/carousel.data.ts`.

This is correct. PR welcome
