### ISSUE TITLE
documentation for useModalController is missing imports

### ISSUE THREAD

**Issue by stevemandl** [bootstrap-vue-next/bootstrap-vue-next#1787]
### Describe the bug

The examples at https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html don't work. The addition of an import fixes them. Unless there is some way to add useModalController globally, 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rwxgc7?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
None of the examples contain import statements for brevity

**Comment by stevemandl** [comment]
> None of the examples contain import statements for brevity
The docs for useBreadcrumb do, so I thought they should be consistent. I spent a bunch of time trying to figure out why useModalController didn't work; I thought I might have missed something in the new installation instructions that should have made it globally available. Merging this might save someone else that time. I thought developers might prefer examples that work as written.

**Comment by VividLemon** [comment]
> > None of the examples contain import statements for brevity
> 
> The docs for useBreadcrumb do, so I thought they should be consistent. I spent a bunch of time trying to figure out why useModalController didn't work; I thought I might have missed something in the new installation instructions that should have made it globally available. Merging this might save someone else that time. I thought developers might prefer examples that work as written.

I think it just adds bloat. I don't think we need to hold the devs hand so much that we need to explicitly tell them to `import {ref} from 'vue'`. I think people can generally figure out that `"useModalController" is not defined` means that its not defined

> useBreadcrumb do, so I thought they should be consistent

This was an accident on useBreadcrumb then.
