### ISSUE TITLE
BTable selectMode="single" doesn't work

### ISSUE THREAD

**Issue by waiyanmintun** [bootstrap-vue-next/bootstrap-vue-next#1793]
### Describe the bug

v 0.16.5
When select another row, the prev selected row doesn't get unselected.
Current workaround is calling unselectRow(prevRowIndex) in rowClicked event.

### Reproduction

https://codesandbox.io/p/devbox/btable-single-select-n7rgrf?file=%2Fapp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by makroxyz** [comment]
Solved in next release
