### ISSUE TITLE
BTable rowDblClicked event not working

### ISSUE THREAD

**Issue by yogeshgalav** [bootstrap-vue-next/bootstrap-vue-next#1795]
### Describe the bug

rowDblClicked event should work on double click of table row, but nothing is happening, no console error.
This is a major bug.

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-bs9ztq?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yogeshgalav** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BTable/BTable.vue
this component had defined but haven't used any emit row-dbl-clicked.

**Comment by VividLemon** [comment]
You're likely the most knowledgeable about what `rowDblClicked` is meant to do. Creating a pr would likely fix your issue

**Comment by VividLemon** [comment]
https://discord.com/channels/335455578921107456/1136992114417348638/1210609857636339793

**Comment by yogeshgalav** [comment]
@VividLemon Can't install it due to turbopack, It should have used vite.
