### ISSUE TITLE
@sort-changed not working with vue3

### ISSUE THREAD

**Issue by amjadkhalil33** [bootstrap-vue-next/bootstrap-vue-next#1798]
### Describe the bug

B-table @sort-changed not working with vue3

### Reproduction

/

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by waiyanmintun** [comment]
not a bug but method name changed to @sorted(sortBy string, isDesc boolean)
[](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/table.html)

but :sort-by :sort-desc outlined doesn't work

**Comment by VividLemon** [comment]
It appears this https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1798#issuecomment-1970397987 is the correct behavior. With the change to `sortBy` becoming a v-modelable value, one could use that to determine when sort has changed (@update:sort-by). Alternatively, the `sorted` event emits which value has changed in the sortby. Although one could do the same by checking the diff of the model
