### ISSUE TITLE
useVModel => defineModel upgrade

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1799]
### Clear and concise description of the problem

We want to upgrade to defineModel. useVModel syntax needs to adjust to this

```ts
const props = withDefaults(defineProps<{modelValue?: string}>(), {modelValue: '123'})
const emit = defineEmits<{ 'update:modelValue': [string]}>()

const modelVal = useVModel(props, 'modelValue', emit, {passive: true})
```
=> 
```ts
const modelVal = defineModel<string>({default: '123'})
```

There shouldn't be any unexpected breaking changes. I'm pretty sure the two should behave identically

Lastly, I believe this can adjust the workflow for BFormInput. We can explicitly define the modifiers, and create more straightforward syntax for modifiers. https://vuejs.org/api/sfc-script-setup.html#modifiers-and-transformers 

```ts
const [modelValue, modelModifiers] = defineModel<string, 'trim' | 'number'>({
  // get() omitted as it is not needed here
  set(value) {
    // if the .trim modifier is used, return trimmed value
    if (modelModifiers.trim) {
      return value.trim()
    }
    if(modelModifiers.number) {
      //
    }
    // otherwise, return the value as-is
    return value
  }
})
```

etc etc

**Comment by xvaara** [comment]
Have you tested that it works like passive: true? I'm not 100% sure about that.

**Comment by xvaara** [comment]
To answer my own question, vue should detect if there isn't an variable in the prob it creates a local one

**Comment by VividLemon** [comment]
> To answer my own question, vue should detect if there isn't an variable in the prob it creates a local one

Yes. If it didn't create a ref, I wouldn't be sure how "default" works.
