### ISSUE TITLE
'value' slot prop on the BTd 'cell(*)' slot is not using the 'formatItem' function

### ISSUE THREAD

**Issue by Melordship** [bootstrap-vue-next/bootstrap-vue-next#1805]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/table#custom-empty-and-emptyfiltered-rendering-via-slots

### Describe the missing feature

The 'value' slot prop on the BTd 'cell(*)' slot in the BTableLite component is not using the 'formatItem' function as it was in bootstrap-vue. 

BTableLite.vue
![Screenshot 2024-03-08 at 11 29 08](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/162338419/28c69b13-a4bd-4e25-998f-4bbe9dd493f3)

BoostrapVue (mixin-tbody.js)
![Screenshot 2024-03-08 at 11 29 00](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/162338419/1b39156c-4e1a-45cd-9f6a-7b0c72feb884)

From 'bootstrap-vue' documentation
![Screenshot 2024-03-08 at 11 33 37](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/162338419/67964afc-fc03-4641-9fa7-737de7f9a67f)

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by VividLemon** [comment]
Is next on the TODO list. Hopefully I remember lol

**Comment by Melordship** [comment]
> Is next on the TODO list. Hopefully I remember lol

Great! I'm trying to get some time to potentially contribute to this project to help push it over to release 1.0.0.
