### ISSUE TITLE
Jumbotron seems to be missing

### ISSUE THREAD

**Issue by Kunwark** [bootstrap-vue-next/bootstrap-vue-next#1807]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/jumbotron

### Describe the missing feature

<b-jumbotron> component is missing. 

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by VividLemon** [comment]
https://getbootstrap.com/docs/5.3/migration/#jumbotron
