### ISSUE TITLE
chore: update vue-tsc 2.0

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1811]
### Clear and concise description of the problem

vue-tsc needs to be updated. The following needs to occur:

1. `    "type-check": "vue-tsc --build --force",` replace the script in bvn to this
2. Tsconfigs need to be updated:

Merge ours with the following:
```json5
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",

    "baseUrl": ".",
  }
}

```

```json
{
  "extends": "@tsconfig/node20/tsconfig.json",
  "include": [
    "vite.config.*",
    "vitest.config.*",
    "cypress.config.*",
    "nightwatch.conf.*",
    "playwright.config.*"
  ],
  "compilerOptions": {
    "composite": true,
    "noEmit": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",

    "module": "ESNext",
    "moduleResolution": "Bundler",
    "types": ["node"]
  }
}
```

```json
{
  "extends": "./tsconfig.app.json",
  "exclude": [],
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.vitest.tsbuildinfo",

    "lib": [],
    "types": ["node", "jsdom"]
  }
}
```

Some things are not to be merged. For example, we don't use jsdom. 

Once that is done, the build errors need to be fixed.

### Suggested solution

n

### Additional context

`pnpm create vue@3` to create a blank template, then merge in some of the structural changes.

Other packages need to be updated as well if they haven't already (playground, etc)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
If https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1810 hasn't been merged yet by the time this is finished, rebase and request to push into that branch. Either https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1810 goes out standalone, or this goes with https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1810

**Comment by sceee** [comment]
Just wanted to note here that I experienced errors when updating to `vue-tsc` v2 in a project using `bootstrap-vue-next` and created this issue for it in vuejs/language-tools which is not yet resolved as of today:
https://github.com/vuejs/language-tools/issues/4026

**Comment by VividLemon** [comment]
I'm aware, although, I don't believe that is their issue. I believe it's more of a setup issue. But I may be wrong. V2 has been a bit messy. I expected it to be somewhat simple based on the changelog, but has issues like described which has been unpleasant.
