### ISSUE TITLE
BTable : tbody-tr-attr isn't working

### ISSUE THREAD

**Issue by bpemca** [bootstrap-vue-next/bootstrap-vue-next#1816]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/table#row-styling-and-attributes

### Describe the missing feature

tbody-tr-attr from https://bootstrap-vue.org/docs/components/table#row-styling-and-attributes isn't working anymore

### Validations

- [x] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by VividLemon** [comment]
Seems to have been fixed

**Comment by bpemca** [comment]
Hi @VividLemon, do you know what version fixes this ? 
Thx a lot
