### ISSUE TITLE
Who is maintaining the project? (create page with contributors & financial backers)

### ISSUE THREAD

**Issue by dword-design-honestly** [bootstrap-vue-next/bootstrap-vue-next#1826]
Hi guys,

first of all, thanks for the great work so far on bringing Bootstrap to Vue 3 🙏.

I was looking for some info who is maintaining the project. Afaik you are working on it in your free time, so no company behind it, right? How many?

Thanks already!

**Comment by MaaxGr** [comment]
Hey @dword-design-honestly,
you can look at the Github Contributors Graph who commited in the e.g. last 12 months:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/graphs/contributors?from=2023-03-26&to=2024-03-26&type=c

But there are also huge "non-code contributions", see for example #1775

Kind Regards
Max

**Comment by dword-design-honestly** [comment]
@MaaxGr Ok, but there is no page [like this](https://primevue.org/team/) in the docs about it, right? Like, are there core maintainers? The contributors graph is basically everyone who got a PR merged.

**Comment by xvaara** [comment]
We do it at our free time. No company behind this. 

Would love to have access to BootstrapVue open collective so @VividLemon (Issayah) or myself could work on this for a little more. https://opencollective.com/bootstrap-vue there is just 62k USD sitting there doing nothing, that we could use to work on this project.

https://opencollective.com/bootstrap-vue-next we do have our own open collective if you want to sponsor the work.

**Comment by MaaxGr** [comment]
Although there is no company behind, I like the idea from @dword-design-honestly of having a dedicated team page on the website with all current core contributors. So that you also get more credit for your amazing work @xvaara and @VividLemon  :)

**Comment by VividLemon** [comment]
I'll likely make some modifications when the project is v1. Including sponsor badges and contributors page.

**Comment by VividLemon** [comment]
("wontfix" label for pre v1)

**Comment by FelixSchwarz** [comment]
> We do it at our free time. No company behind this.

Thank you so much for all the work you put into this project!

> https://opencollective.com/bootstrap-vue-next we do have our own open collective if you want to sponsor the work.

Would money help improving this project in the short term? (e.g. over the next 6 months?) I can see that your OpenCollective also accumulated 8000 USD which is of course much less than 60k but still a bit of money which might fund a developer for a month or so. I'm thinking of a situation when you are working on a full-time project without much capacity to spare, regardless of money.

Of course, I'm not expecting you to disclose your situation in detail, just wanting to know if additional money would be of any help.

**Comment by xvaara** [comment]
@FelixSchwarz most of that is from BootstrapVue OpenCollective, they are helping us to push towards 1.0 . There is still a lot of work to be done for us declare 1.0, so any monetary help gives us more time to put towards this project.
