### ISSUE TITLE
b-skeleton is missing

### ISSUE THREAD

**Issue by bpemca** [bootstrap-vue-next/bootstrap-vue-next#1828]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/skeleton

### Describe the missing feature

Hi, 

b-skeleton is missing.

Thank you for your great job

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by makroxyz** [comment]
BPlaceholder Is the new component

Il mar 26 mar 2024, 09:50 bpemca ***@***.***> ha scritto:

**Comment by bpemca** [comment]
Oh thank you, you're right ! 
I close the issue
