### ISSUE TITLE
Toast `useToast` method doesn't work

### ISSUE THREAD

**Issue by KB1RD** [bootstrap-vue-next/bootstrap-vue-next#1833]
### Describe the bug

All toast examples on the docs involving `useToast` do not work. Visit [here](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/toast.html#automatic-countdown) and click on `Show` to reproduce. Nothing will appear to happen. If you click a number of times, you will see small grey bars appear in the right hand corner of the screen, which appear to be zero-length toasts. No errors appear in console.

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/toast.html#automatic-countdown

### Used Package Manager

n/a

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Fixed by https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1809 wait for docs to be published in 0.17
