### ISSUE TITLE
Hydration mismatch on BNavItemDropdown with v0.17

### ISSUE THREAD

**Issue by ptdev** [bootstrap-vue-next/bootstrap-vue-next#1844]
### Describe the bug

Adding a BNavItemDropdown inside a BNavbarNav triggers a hydration mismatch on Nuxt.

Reproduction example is using the [example from the documentation](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/navbar.html#bnavitemdropdown)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-g6bzks?file=layouts%2Fdefault.vue

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
@VividLemon if the :to in teleport is undefined, the disabled teleport won't render in ssr 😆

**Comment by ptdev** [comment]
Thanks @rhelling 

I can confirm that we no longer get hydration errors after applying your workaround.

Cheers
