### ISSUE TITLE
BFormCheckbox type check failed for prop "modelValue"

### ISSUE THREAD

**Issue by geozaur** [bootstrap-vue-next/bootstrap-vue-next#1853]
### Describe the bug

Hello and thank you for contributing this project!

When using a `BFormCheckbox` with custom checked and unchecked values (`1` and `0`), there is a warning stating that the prop type is wrong.

This was not happening in previous versions (before 0.17).

```
[Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected Boolean, got Number with value 1. 
```

### Reproduction

https://stackblitz.com/edit/github-khmwbw?file=src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by suzumejakku** [comment]
Probably same as #1846

**Comment by xvaara** [comment]
It's the same, it's a vue bug: https://github.com/vuejs/core/issues/10726

**Comment by geozaur** [comment]
Same as #1846
