### ISSUE TITLE
BPopover error on first click in version 0.17

### ISSUE THREAD

**Issue by geozaur** [bootstrap-vue-next/bootstrap-vue-next#1854]
### Describe the bug

Hello!

When trying to use a `BPopover` with `click`, the first time a user clicks on the target or outside, there is an error logged in the console. The following clicks work normally.

```
Uncaught TypeError: inject(...) is not a function
```

### Reproduction

https://stackblitz.com/edit/github-tb3ye7?file=src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
fixed in #1848, not released yet. next time please search the issues before submitting bugs.
