### ISSUE TITLE
Fade not working for BModalOrchestrator

### ISSUE THREAD

**Issue by dword-design-honestly** [bootstrap-vue-next/bootstrap-vue-next#1861]
### Describe the bug

Looks like the modals created via BModalOrchestrator don't fade. Or am I missing something? See also the [examples in the doc](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html).

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stevemandl** [comment]
I noticed hide() is not working with modals created with BModalOrchestrator. I guess this is the same thing, just a different way of saying it.
I started troubleshooting and noticed that BModal state does not show up in vue devtools, even though other components show up just fine. 
From what I can tell the show class is never getting removed when hide is called, even though the promise resolves correctly.

**Comment by dword-design-honestly** [comment]
I especially mean when the modal is showing up. It's instantly there.

**Comment by stevemandl** [comment]
@dword-design-honestly  OK then this is a separate but probably related issue. I mean hide is not working; it is not possible to make the modal go away. The bug I'm describing is also apparent on the example in the docs you cited. If desired, I will create a separate bug-issue.

**Comment by dword-design-honestly** [comment]
Looking forward to this since imho the modal orchestrator is one of the main improvements compared to the old project 😊.

**Comment by ckrieger** [comment]
> @dword-design-honestly OK then this is a separate but probably related issue. I mean hide is not working; it is not possible to make the modal go away. The bug I'm describing is also apparent on the example in the docs you cited. If desired, I will create a separate bug-issue.

I have the same issue since v0.17.0. On v0.16.6 hiding the modal is working. Might be a good idea to create separate issue for this 👍

**Comment by VividLemon** [comment]
Whatever the next breaking release is, it will be out then

**Comment by dword-design-honestly** [comment]
@VividLemon Why breaking? 😊 Sry maybe I've miss something.
