### ISSUE TITLE
Invalid prop: type check failed for prop "size". Expected Object, got String with value "lg"

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1864]
### Describe the bug

After upgrade to 0.17.2 I have this warning in browser console:
```Invalid prop: type check failed for prop "size". Expected Object, got String with value "lg". ```
the same for variant or all props defined on component

this happens on all my InputText object.
I think it's something to export type related but I can't understand what it is.

Below reproduction, please remember to open console

### Reproduction

https://stackblitz.com/edit/github-dqx2in?file=src%2FApp.vue,package.json,src%2Fcomponents%2FTextInput.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
This appears to be a bug in Vue. I tried switching between Vue v3.4.23 -> 3.4.24 and before/after it caused the issue. 

In-lining 

```ts
interface BaseSize {
  sm: unknown
  md: unknown
  lg: unknown
}

// type Size = 'sm' | 'md' | 'lg'
type Size = keyof BaseSize
```

Onto 
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/97d33118-73bf-4074-bc72-f2b8014b60d4)

Shows the issue more clearly

Please make an issue in Vue core
