### ISSUE TITLE
Random error in console: inject(...) is not a function

### ISSUE THREAD

**Issue by dword-design-honestly** [bootstrap-vue-next/bootstrap-vue-next#1865]
### Describe the bug

I sometimes get the above mentioned error message in the console. Doesn't seem to lead to an actual unexpected behavior but I guess it shouldn't happen. I couldn't reliably reproduce it yet, but maybe the issue is known by someone else. I did have some issues with hot reload outputting errors in the console, so maybe it's somehow related to that.

![Bildschirmfoto 2024-04-23 um 14 34 07](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/153498584/3422d649-4a95-4a04-ac52-1741009e2c06)

### Reproduction

Couldn't reproduce but screenshot attached

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
in #1854 we saw this in popover. Are you using the latest version?

**Comment by dword-design-honestly** [comment]
Closing, didn't find it via `in:title` search, that's why.
