### ISSUE TITLE
Can we preserve the records sent to BTable/BTableLite?

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#1868]
### Describe the bug

I know that it's generally been the case that table items need to be able to make it through a JSON.stringify/JSON.parse loop - [Table | Components | BootstrapVue (bootstrap-vue.org)](https://bootstrap-vue.org/docs/components/table#table-item-notes-and-warnings).  However, in BSV and BSVN up until version .17, the objects that were sent back to my own code were the original object (including the prototype).  They were preserved in things like `item` in the cell slot and `value` in the `formatter` function.

This is pretty useful and one of the reasons that I spent time typing tables.  @VividLemon and @xaava, I'd be happy to take a run at this but let me know if you think this is a reasonable objective.

### Reproduction

N/A

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
There would either need to be a v-model or there would need to be a separation between the cloned object and the users object. Both of which are less than ideal. Although I suppose I'd opt for internal values

**Comment by dwgray** [comment]
Thanks - I'll dig into it.  I mostly wanted to may sure you didn't have an immediate strong negative reaction to pursuing this before I spent time on it.

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1879 fixes this in a better way (internalItems is removed)
