### ISSUE TITLE
BTable selected-items issues

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#1875]
### Describe the bug

BTable and v-model:selected-items has  some issues 
- when table items changes (for example using a provider property that paginates items) 
- when selected-items have a pre-selection

for example using  provider that paginates, switching a page will loose the selected color on table.
The ```primaryKey``` property solves the table selection issue BUT the ```select-mode``` 'single' doesn't work in any case

At the end items inside the BTable are not the same even if they are the same object...

### Reproduction

https://stackblitz.com/edit/github-xfblxu?file=src%2Fcomponents%2FComp.vue,src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
I'd need a reproduction for both, using a provider and using this pre-selection. I'm confused as to what you're trying to do and what is expected

**Comment by VividLemon** [comment]
The given reproduction works after #1877 . The other issues mentioned do not have a reproduction. Closing
