### ISSUE TITLE
BCollapse Accordion mode not working

### ISSUE THREAD

**Issue by aktiWeb** [bootstrap-vue-next/bootstrap-vue-next#1883]
### Describe the bug

Following code is not working for me:
```
<div class="accordion" role="tablist">
    <div v-b-toggle="'collapse-a'" role="button">Toggle Collapse A</div>
        <b-collapse id="collapse-a" role="tabpanel" accordion="my-acc">
            I am collapsible content A!
        </b-collapse>
    <div v-b-toggle="'collapse-b'" role="button">Toggle Collapse B</div>
        <b-collapse id="collapse-b" role="tabpanel" accordion="my-acc">
            I am collapsible content B!
        </b-collapse>
</div>
```
I expect "I am collapsible content A!" will dissapear when clicking "Toggle Collapse B". But this is not happen. Both contents are visible.

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-ba2n3y?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by makroxyz** [comment]
Use BAccordion component
