### ISSUE TITLE
Is `BFormDatepicker` planned?

### ISSUE THREAD

**Issue by someonewithpc** [bootstrap-vue-next/bootstrap-vue-next#1893]
**What you are trying to do.** Use `BFormDatepicker`

**What you have already tried.** N/A

**Any error messages you are getting.** No such component

**Environment (please complete the following information):**

- OS: GNU/Linux
- Package Version: 0.17.5
- Npm/Yarn/Pnpm/Bun Version: npm@10.2.4

@VividLemon Before I spend time working on it, is `BFormDatepicker` planned, in progress, or explicitly not going to be added? If so, what am I supposed to use, when migrating an existing app?

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1860

Yes. The implementation should be a wrapper around https://www.radix-vue.com/components/date-picker

**Comment by VividLemon** [comment]
Move the conversation to the other issue to avoid duplicates
