### ISSUE TITLE
BAvatar icon property incorrect type

### ISSUE THREAD

**Issue by adam-antite** [bootstrap-vue-next/bootstrap-vue-next#1900]
### Describe the bug

The type of BAvatar's `icon` property is not set to `string` primitive, so it only accepts the literal values "", "true", and "false" instead of icon data.

### Reproduction

https://stackblitz.com/edit/github-rst39v-9wdhm8

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
The icon prop is deprecated and will be removed in 0.19. 

Instead use the default slot with your icon of choice

```html
<BAvatar rounded="circle">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-person-fill"
            viewBox="0 0 16 16"
          >
            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
          </svg>
        </BAvatar>
```

(We don't have an icons library internally)

**Comment by VividLemon** [comment]
(Note: it actually has an _icon_ prop, but this affects the behavior of the blink)
