### ISSUE TITLE
Dropdown radius broken

### ISSUE THREAD

**Issue by ujex256** [bootstrap-vue-next/bootstrap-vue-next#1907]
### Describe the bug

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/input-group.html#dropdown-addons
When using Dropdown in InputGroup, the radius of the button does not seem to fit correctly.
The menu displayed also had a radius of 0 for the right half.

The same was true in the official documentation.
```vue
<BForm>
  <BInputGroup>
    <BDropdown text="Test">
      <BDropdownItem>abcdef</BDropdownItem>
      <BDropdownItem>ghijkl</BDropdownItem>
    </BDropdown>
    <BInputGroupText>Txt</BInputGroupText>
    <BFormInput placeholder="hello" />
  </BInputGroup>
</BForm>
```

![bs-dropdown](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/105550500/a2d5d78c-e64f-4784-91e2-9e877f317cff)

### Reproduction

https://stackblitz.com/edit/github-4brggy

### Used Package Manager

bun

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
This is because we render an extra div around the dropdown that has the class btn-group. It's only needed for slit buttons I think.

@VividLemon I'd like to remove the div with RenderOrSkipComponent when not needed, but that would break the directive usage. I've been thinking about the dropdown component and it's split. I'd like to remove it from dropdown component and make dropdown to a "pure" component about dropdown. 

ie. If you'd neet a split, this is how it would be done:
```vuejs
<div class="btn-group>
  <BButton>button</Button>
  <BDropdown>...</BDropdown>
</div>
```

it would simplify the component and bring more functionality for the user. But it's a breaking change. Thoughs?

**Comment by VividLemon** [comment]
> I'd like to remove the div with RenderOrSkipComponent

Do this. I imagine a provide/inject bus to detect whether or not its in a group would suffice. 

Keeping in mind that button groups behave differently https://getbootstrap.com/docs/5.3/components/button-group/#nesting , placing a btn-group in another btn-group is fine.

Input groups don't want wrapper elements https://getbootstrap.com/docs/5.3/forms/input-group/#buttons-with-dropdowns

Given that previous documentation, I'm not sure how they activate https://getbootstrap.com/docs/5.3/components/dropdowns/#directions , but this is a bootstrap issue ig

**Comment by xvaara** [comment]
@VividLemon btn-group is `display: inline-flex;` and dropdown class is `display: block;`. Should we change single dropdown to that class or not? Basic btn is `display: inline-block;` so it's no coherent inside bootstrap. Any Ideas what we should do? prop wrapperClass but by default use 'btn-group' ?

**Comment by VividLemon** [comment]
Probably:
default `dropdown`
split `btn-group`
nested in input group `RenderComponentOrSkip`
