### ISSUE TITLE
Flexible bottom row targeting by adding a class.

### ISSUE THREAD

**Issue by kbamponsem** [bootstrap-vue-next/bootstrap-vue-next#1908]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/6ceeac5ce479ca758308ccf23f5e5df8673fd89b/packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue#L147

It will be very good to easily target the bottom row for cases where you would want to remove it from a computation of the elements in the `tbody` and not be worried about it.

**Comment by kbamponsem** [comment]
I guess this unnecessary when you can use `tbodyTrClass` to target the `item rows` and in your selection target those rows.

**Comment by VividLemon** [comment]
I don't understand the issue

**Comment by kbamponsem** [comment]
Let me provide a bit more context:

I am currently using BTableLite and some times in my table my data rendered will not be able to fill up the entire space in the table (as in there will far fewer rows rendered than what my min table height will be).

So the idea would be to "dynamically stretch the bottom-row" to fill up the entire space.
And if there is more "elements rendered than the min-height of my table" then we do not show the bottom-row).

Now, I am already using `tbodyTrClass` to target my rows when there is a state change like `when I click on the row, I would like to add some classes to say "highlighted" or something like this`.

If I would like to target the bottom row in CSS when I have already classes targeting the regular table rows `tr:not('.bottom-row')`, currently this will be hard because you cannot assume that the bottom row is always the last element.

I hope the issue is slightly clearer. I know, it's a very specific use-case but for now, I have found a way around so I guess it's not a problem.
