### ISSUE TITLE
feat!: props composition > prop inheritance

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#1913]
### Clear and concise description of the problem

Many components extend other components. Instead, what we should do is allocate a prop that combines those other props all in one. Leading to more expected behavior (For example, BAvatar had an icon prop, BLink had an icon prop. Who's do you use? [Although BAvatar.icon is gone now, it's an example])

### Suggested solution

The extended BLink props turn into `linkProps: BLinkProps`. With exceptions to Exclude elements

**Comment by cdmoro** [comment]
My two cents, I do not think the final user wants/needs to know that the link used in a component is a `BLink` under the hood. In any case, we can type the props in a way that is scalable for us, for example, if a component uses two props from other component we can have something like:

``` typescript
export interface MyComponent {
  otherProp: string
  href: BLinkProps["href"]
  rel: BLinkProps["rel"]
}
```

Following the approach you propose, components will look like this and I definitely think we should create the least object-like props.

``` vue
<BAvatar
  :linkProps="{ href: 'https://www.vuejs.org', rel: '_blank' }"
  alt="Vue.js"
  badge="foo"
/>
```

Apart from that, it would be nice to have a "BoostrapVueNext desition record" everytime we decided to make a breaking change, with this if we need to revisit a desition we have them documented in one place.

**Comment by VividLemon** [comment]
The issue is that blink has like 40 props, which when mixed in a flattened way with other other components, it makes it difficult to find actual props from the component. 

However this doesn't extend to actual extended values. Typically blink is the root component, so it makes sense for it to be an extension rather than composited (is that the right word?). My issue is more with nested component structures like BProgress/BProgressBar or Bavatar/BBadge. Where its not the main focus of the component being consumed

@xvaara
