### ISSUE TITLE
BTable - how to use selectAllRows() and clearSelected()

### ISSUE THREAD

**Issue by m-demydiuk** [bootstrap-vue-next/bootstrap-vue-next#1915]
In BootstrapVue we used next code to select/deselect all rows in table
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/2910327/6a387a39-a083-4922-ab5c-2259e8f01b84)

In bootstrap-vue-next slot is missing methods selectAllRows and clearSelected
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/2910327/5544a5f3-57e8-4def-a2de-ca09cda595ea)
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/2910327/54383ae0-58ae-425a-92fa-37e4749e7d36)

Also I tried to use table ref to call these methods on table level as described here https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1515
But ref just don't show any BTable stuff
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/2910327/a624986e-ea00-46d8-a524-3101eec8ff01)

The documentation of the BTable component is not complete, and I can't figure out how to use these methods.
Could you provide some example?

**Environment (please complete the following information):**

- OS: Windows 10
- Package Version: bootstrap-vue-next@0.18.1 vue@3.4.27
- pnpm@9.1.0

**Comment by VividLemon** [comment]
`ref<typeof BTable ...` => `ref<InstanceType<typeof BTable> | null>`

**Comment by m-demydiuk** [comment]
@VividLemon thank you for the quick reply.
But it still doesn't work, not sure why.
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/2910327/c146ca25-4235-4c73-b12a-897c434a6d61)

**Comment by VividLemon** [comment]
https://github.com/vuejs/core/issues/10077
https://github.com/vuejs/core/issues/6643

Doesn't seem to work. I suggest using ref<any> as it's just a TS issue
