### ISSUE TITLE
When using useModelController, how to hide a programatically created modal? 

### ISSUE THREAD

**Issue by adrianhardy** [bootstrap-vue-next/bootstrap-vue-next#1919]
Using the "Creating Modals" example in the documentation [here](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html#creating-modals), how would you then hide that modal? I think there's a slight error in the docs as it talks about modals and the code talks about toasts, but I'm guessing the principle is the same.

I have tried bringing in `hide` from `useModalController` (as described lower down, [here](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html#globally-hiding-modals)) but the `hide` method fails to hide a modal which has been created programmatically - am I doing something wrong?

Unfortunately, my lack of understanding of TS and Vue3 innards means I'm finding this very difficult to debug.... 

The only thing I can figure out is that after calling `hide` (from useModalController),  BModal's `hideFn` is called, but it never emits 'hidden'. That's because because `onAfterLeave` is never called, and I'm assuming that's because v-show never evaluates to false... but I don't know why that would be... because modelValue gets set to false at the bottom of `hideFn`. 

Very simple SFC using the old Vue style (apologies)

```vue
<template>
    <b-modal-orchestrator />
</template>

<script>
import {useModalController} from "bootstrap-vue-next";
export default {
    name: "DemoComponent",
    mounted() {
        setTimeout(async () => {
            let outcome = await this.show?.({
                props: {body: 'test'}
            });
            // no effect
            this.hide();
            // no effect
            this.hideAll();
            // BModalOrchestrator's @hidden should handle for us... but I need to call it manually :(
            this.remove(this.modals[0].value);
        }, 500);
    },
    setup() {
        const {show, hide, hideAll, modals, remove} = useModalController();
        return {
            hide, show, hideAll, modals, remove
        }
    }
}
</script>
```
I can only assume I'm doing something incorrect here, so I apologise if I'm doing something silly.

 - OS: Fedora 40
- bootstrap-vue-next@0.19
- node@10.2.4

**Comment by Pequem** [comment]
Same here, i think that is a bug. When a create a modal with Confirm function the modal nevers close.

**Comment by manuelnaldi** [comment]
Same here, i think this should be definitely marked as bug.

**Comment by VividLemon** [comment]
`await this.show` means that you've blocked further execution of the function. The promise is only resolved when the modal is closed. So you're trying to close something that's waiting to be closed. Doesn't really make sense.

The second issue here is that "hide" needs to first be pushed to an "active stack". It's only pushed after the modal has entered its transitions "onBeforeEnter" hook. It could be added during execution of the modals setup scope, but even this would require an `await nextTick()`, and it would also trigger the animation briefly. (How would you remove something that hasn't entered the dom yet)

This would be the required code
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/73fee594-cf14-4901-a393-88b2617c6982)

But again, you'd still always see the show animation flash between the this.show() & this.hide().

**Comment by VividLemon** [comment]
So I'm closing this as not planned. I had committed the small changes in execution time (it will get added to the stack in the running of its setup scope, not necessarily during the watcher)

However there is no other way to allow for doing this earlier using the hide method. The hide method's whole functionality depends on a modal being entered into the dom, then we remove it from there. So, you can't just remove it before its entered.

That being said, your methodology is still flawed, as discussed before, you're awaiting a promise that gets resolved when its closed. Its fundamentally not possible. (Although you can _not_ await the promise, as shown in the picture, that will still work. Although you'll get slightly odd visual effects depending on the timing of the hide())
