### ISSUE TITLE
Modal created by useModalController can’t be closed 

### ISSUE THREAD

**Issue by Pequem** [bootstrap-vue-next/bootstrap-vue-next#1921]
### Describe the bug

When a modal is created using confirm function, it’s never go away. 

When close ou Ok buttons is clicked, the promise is resolved but the modal is still on the screen.

This error is also happening in the documentation

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Seems fixed
