### ISSUE TITLE
we should sanitize v-html props in components or remove them

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue-next/bootstrap-vue-next#1930]
There are many places that accept v-html input and the input isn't sanitized for xss attacks, we leave this to the user. I think we should remove all the v-html places since we have slots everywhere that the user can use to shoot them self in the foot.

**Comment by xvaara** [comment]
@VividLemon any thoughts on this one?

**Comment by VividLemon** [comment]
Tbh I agree with this one. It seems safest to force slot usage instead so v-html can be flagged by people using `eslint-plugin-vue`

**Comment by xvaara** [comment]
@VividLemon do you also agree that we should remove this from popover/tooltip? 
some people might be using v-tooltip="very <b>important</b> tooltip".
I think we should guide these people to use a component instead. popover has a sanitize function lifted from bootstrap that only allows a limited html: https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/8bfc3c3d9fc4abb9bee39632d0ff8d1a1f03a5e3/packages/bootstrap-vue-next/src/utils/sanitizer.ts#L59-L91
the component btw only uses v-html if html prop is set to true (which the directives do)

or should we add this same sanitization to other component that have v-html?

**Comment by VividLemon** [comment]
I'd prefer to never do any sanitation for the user. It's not up to us on what they should or shouldn't be allowed to do with their code. Maybe they want xss issues, idrk, not my problem
