### ISSUE TITLE
BFormInput - @input event passes InputEvent as argument instead value of the input.

### ISSUE THREAD

**Issue by m-demydiuk** [bootstrap-vue-next/bootstrap-vue-next#1939]
I use BFormInput as:
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/2910327/79e50880-75d7-4024-a823-cb3f7ad038c6)

And I expect that `handleInputValue` function will receive a value of the input as string.
But instead, I got `InputEvent`:
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/2910327/323859c4-ccbd-402f-b91c-7baef97c9532)

Is it how it supposed to be? I can't get actual value of the input, because `val.data` contains only one character that was pressed in current event. Or null if I press backspace.

In bootstrap-vue @input was passing string value of the input field. Why has this changed?

Also, in this comment also said that val should be string:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/558#issuecomment-1215183620

- OS: Windows 10
- Package Version: ^0.19.0
- Pnpm 9.1.0

**Comment by m-demydiuk** [comment]
I got it, I need to use `@update:modelValue` in vue 3 instead `@input`.

**Comment by VividLemon** [comment]
The vue 2 modelvalue in general was different. It _was_ input event and value prop. With the vue 3 changes, it simply made more sense to pass the native events. I think it provides more details and expected functionality when messing with input components
