### ISSUE TITLE
New regression on BModal initial load with v0.21.0

### ISSUE THREAD

**Issue by 3cp** [bootstrap-vue-next/bootstrap-vue-next#1943]
### Describe the bug

BModal initial load should respect modelValue (default false) on whether showing it.
That worked with version before. With latest 0.21.0, BModal now is always displayed in initial rendering.

Also I cannot bypass this issue with an explicit binding to false. The following code could not hide it either.
```
<BModal v-model="showing"></BModal>
const showing = ref(false)
```

### Reproduction

https://stackblitz.com/edit/github-994z6g?file=src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Strange. This never appeared during my testing

**Comment by 3cp** [comment]
It's reproducible on stackblitz. Something happened on deployed package.

**Comment by 3cp** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/7d54af2ea98a20d0a745e8beda9097cd06b24ede/packages/bootstrap-vue-next/src/components/BModal/BModal.vue#L5

Hi @VividLemon, is this the reason?

**Comment by 3cp** [comment]
That seems the cause based on my testing.

**Comment by ptdev** [comment]
> That seems the cause based on my testing.

Hi, I can confirm that this is also happening on our end and this does indeed fixes it.

Thanks 👍

**Comment by tbl0605** [comment]
Huge regression in my case, my main project (based on bootstrap-vue-next) is totally broken with v0.21.0, but applying patch https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1946 seems to fix the issue (at least for me).

Waiting for next release ^^
