### ISSUE TITLE
Regression with 0.21.0, BInputGroupAppend and BInputGroupPrepend are not exported

### ISSUE THREAD

**Issue by 3cp** [bootstrap-vue-next/bootstrap-vue-next#1944]
### Describe the bug

The two are missing. Worked with 0.20.0.
Go to the stackblitz and open browser console to read the error.

### Reproduction

https://stackblitz.com/edit/github-994z6g-jtkr58?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrapvuenext-v0.21.0

**Comment by 3cp** [comment]
Sorry!
