### ISSUE TITLE
Content shifts right/left when modal opens/closes on pages with a vertical scrollbar.

### ISSUE THREAD

**Issue by ddanger** [bootstrap-vue-next/bootstrap-vue-next#1953]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/modal

### Describe the missing feature

**Bootstrap** and **BootstrapVue** modals have code that adjusts the content on the page when modals are opened/closed so it appears content does not move despite the scrollbar disappearing when the modal is open.

**To Recreate**
- set your OS to always show scrollbars
  - on Mac: System Settings -> Appearance -> Show scroll bars -> Always
- navigate to the [bootstrap-vue modal docs](https://bootstrap-vue.org/docs/components/modal) and verify you have a vertical scrollbar visible on the page
- click the "Launch demo modal" button to see correct behavior
- navigate to the [bootstrap-vue-next modal docs](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html#usage) and verify you have a vertical scrollbar visible on the page
- click the "Toggle modal" button
- EXPECT: content to remain in place
- ACTUAL: content shifts right

**Insufficient Workaround**
Setting `bodyScrolling` to `true` hides the problem by keeping the scrollbar in place and allowing users to scroll the page under the overlay while the modal is open. But many would consider this a negative user-experience.

**Link to BootstrapVue Implementation**
The code that handles this in BootstrapVue appears to be [here](https://github.com/bootstrap-vue/bootstrap-vue/blob/5173dd19f6f46dc9d125cd7233fb59ccd2ef9296/src/components/modal/helpers/modal-manager.js#L146). (See the `modalCount` watcher and `getScrollbarWidth()`, `setScrollbar()`, and `resetScrollbar()`.

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by IGx89** [comment]
Confirmed this is still an issue in v0.23.2.

**Comment by ddanger** [comment]
Confirmed this is still an issue in v0.24.7

**Comment by xvaara** [comment]
note to self: this is how bootstrap.js fixes this: https://github.com/twbs/bootstrap/blob/main/js/src/util/scrollbar.js
