### ISSUE TITLE
Reduce redundancy in component data

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#1957]
### Clear and concise description of the problem

There are quite a few properties that are used by many components. I'm not talking about things that are necessarily related in the code, but just basic properties that are the same throughout the product. Things like `aria-role`, `name` and `variant`. It's cumbersome to maintain these for all of the different components that use them.

### Suggested solution

The way that BSV solves this problem is by having a [common-props.json](https://github.com/bootstrap-vue/bootstrap-vue/blob/576e67b3af434037a5ee17533a232465527d5edd/docs/common-props.json) file that specifies props that can be used by any of the documentation. And then it uses generic names like 'the component' in the description rather than the name of the component.  This doesn't seem like a loss of information - I didn't even realize BSV was doing this until I dug into how they generate the docs, and I've been using BSV for years.

In our case, I propose adding a common-properties.json file that has an array of properties (we'd have to factor out ComponentReference props), then make any prop in the concrete component's ComonentReference that just has undefined `type`, `description` or `default` fields pull from the equal named `prop` in the common-properties.json file. Fairly straightforward and let's us override properties that have the same name but different types or descriptions while reducing the copy/paste and maintenance overhead of the common cases.

There is some additional magic involved in BSV where it seems to be using the underlying code to know which properties to populate. At some future point I might dive into trying some variation of that, possibly based on get the typescript compiler to spit out the type info for the component props, but I think the proposal outlined above is still a significant win.

### Additional context

@VividLemon I'm happy to tackle this - I'd like to spend part of my time reducing the overhead of filling out the documentation as I move forward, cleaning up things, and filling out the parity report. I just want to get an initial reaction as to whether you think something like this makes sense before diving in.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
If you're talking about for the documentation, the files are just TS files. You can import values, spread arrays, and do anything else you want to share common prop definitions

**Comment by dwgray** [comment]
I've got PR #1964 up with an initial implementation of what I meant by the straightforward approach.

> There is some additional magic involved in BSV where it seems to be using the underlying code to know which properties to populate. At some future point I might dive into trying some variation of that, possibly based on get the typescript compiler to spit out the type info for the component props, but I think the proposal outlined above is still a significant win.

What I meant by the above, is that I'm still manually specifying which props are included in each component and the type and default are still defined manually in the `PropertyReference` object. In BSV it looks like this is pulled from the code, since it's in JSON already. In BSVN this information is encoded in the typescript types. Since typescript doesn't have a built-in concept of runtime meta-data and introspection, it seems difficult to access this information for, say `BFormCheckboxProps` - and then the defaults are buried in the withDefaults macro.

I did some digging and https://github.com/janjakubnanista/ts-reflection will generate the properties of an interface, but it does this by wrapping tsc, since the extension mechanism it's using is [typescripts language service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) which is meant for design-time (in editor) experiences, not build time. So that seems suboptimal. As do the several other approaches that I bounced around.

All of that to say, I think I've got the easy 80% of the problem solved, and I'm not sure it's worth solving the other 20% (or even possible to do so cleanly). But maybe I'm missing something obvious?

**Comment by VividLemon** [comment]
Hypothetically, there is a way in which one could _read_ the simple ts file, and populate _text_ with what is written

**Comment by dwgray** [comment]
>Hypothetically, there is a way in which one could read the simple ts file, and populate text with what is written on the file, inherently different than importing the file and consuming the TS file, one could simply read the text on the file

I don't think I want to go down the path of parsing typescript (even .d.ts files) - I grew up writing debuggers and other tools that had 'mini' expression evaluators to mimic the language being debugged, and that always ended in pain - but maybe I'm overly sensitive due to past trauma :-)

In any case, I think this is a nice to have, and shouldn't block the main task of getting rid of the rest of the redundancy in the property descriptions.
