### ISSUE TITLE
[Solved] Upgrade from 0.14.10  to 0.22.1 all components are unresolved

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1968]
### Describe the bug

I upgraded from 0.14.10 to 0.22.1 and nothing worked
**here my main.ts**
`// Assign app to a variable
const app = createApp(App);

// Assign the global variable before mounting
// app.config.globalProperties.v$ = useVuelidate                // wichtig, nicht mit $ in vuejs 3 beginnen, es dürfen var's nicht mit einem sonderzeichen anfangen !!!!!!!!!!!!
// app.provide('v$', useVuelidate)

app.use(createBootstrap());
app.use(store);
app.use(router);
app.use(VSwatches );
// app.use(Vue3Toastify, ToastifyOptions)

app.component('font-awesome-icon', FontAwesomeIcon);
app.component('DatePicker', VueDatePicker);

app.mount('#vueroot');             `

**Here my npm list**
`pms_frontend_vue3@0.0.0 C:\xampp\htdocs\pms\pms_frontend
├── @fortawesome/fontawesome-svg-core@6.5.2
├── @fortawesome/free-brands-svg-icons@6.5.2
├── @fortawesome/free-regular-svg-icons@6.5.2
├── @fortawesome/free-solid-svg-icons@6.5.2
├── @fortawesome/vue-fontawesome@3.0.8
├── @fullcalendar/bootstrap@6.1.14
├── @fullcalendar/core@6.1.14
├── @fullcalendar/daygrid@6.1.14
├── @fullcalendar/google-calendar@6.1.14
├── @fullcalendar/interaction@6.1.14
├── @fullcalendar/list@6.1.14
├── @fullcalendar/resource-common@5.11.5
├── @fullcalendar/resource-daygrid@6.1.14
├── @fullcalendar/resource-timeline@6.1.14
├── @fullcalendar/rrule@6.1.14
├── @fullcalendar/timegrid@6.1.14
├── @fullcalendar/timeline@6.1.14
├── @fullcalendar/vue3@6.1.14
├── @popperjs/core@2.11.8
├── @rushstack/eslint-patch@1.10.3
├── @types/bootstrap@5.2.10
├── @types/crypto-js@4.2.2
├── @types/d3@7.4.3
├── @types/lodash@4.17.5
├── @types/node@20.14.8
├── @types/uuid@10.0.0
├── @types/vuelidate@0.7.21
├── @vitejs/plugin-vue@5.0.5
├── @vue/eslint-config-typescript@13.0.0
├── @vue/tsconfig@0.5.1
├── @vuelidate/core@2.0.3
├── @vuelidate/validators@2.0.4
├── @vuepic/vue-datepicker@8.8.0
├── axios@1.7.2
├── bootstrap-vue-next@0.22.1
├── bootstrap@5.3.3
├── crypto-js@4.2.0
├── d3@7.9.0
├── eslint-plugin-vue@9.26.0
├── eslint@8.57.0
├── lodash@4.17.21
├── moment@2.30.1
├── npm-run-all@4.1.5
├── resize-observer-polyfill@1.5.1
├── rrule@2.8.1
├── sass@1.77.6
├── typescript@5.1.6
├── uuid@10.0.0
├── vite@5.3.1
├── vue-i18n@9.13.1
├── vue-router@4.4.0
├── vue-tsc@1.8.11
├── vue@3.4.30
├── vue3-swatches@1.2.4
├── vue3-toastify@0.2.1
└── vuex@4.1.0

`

**here the output of the brwoser debugger console:**
`chunk-ITPIWJHN.js?v=194174d9:1532  [Vue warn]: Failed to resolve component: b-navbar-toggle
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Loginnavbar> 
  at <Loginlayout> 
  at <LoginPage onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>`

### Reproduction

sorry, i cannot isolate this problem - it happens to the whole program

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by susanne99** [comment]
i forgot this:
Automatic Registering of Components

**Comment by VividLemon** [comment]
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html

**Comment by VividLemon** [comment]
You may also find it better to import useVuelidate individually than setting it as a global property. Especially if youre just provide/injecting its the same amount of code, just that importing directly is tree shakable

**Comment by VividLemon** [comment]
In relation to 

> Should probably switch up to use Tree-shaken Installation Method anyways

This is going to be fully removed in v0.23

Commit at https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1992/commits/33412786e697548c15facf0cc63efff6750622a8

Reason: based on a discussion https://discord.com/channels/335455578921107456/1136992114417348638/1255237078929899630 there seems to be an issue with createBootstrap not treeshaking components. Previously createBootstrap needed to import all components to run Object.keys on it. Meaning that it could never get treeshaken off. Given this, and the fact that those features should never be used in production applications, I've decided to remove them
