### ISSUE TITLE
BNavItemDropdown broken on Nuxt?

### ISSUE THREAD

**Issue by jonkri** [bootstrap-vue-next/bootstrap-vue-next#1972]
### Describe the bug

Create a new Nuxt 3 project. Pick the default options.

```
$ npx nuxi@latest init b-nav-item-dropdown-example
$ cd b-nav-item-dropdown-example
```

Install `bootstrap`, `bootstrap-vue-next` and `@bootstrap-vue-next/nuxt`:

```
$ npm install --save-dev bootstrap bootstrap-vue-next @bootstrap-vue-next/nuxt
```

Add `modules: ['@bootstrap-vue-next/nuxt'],` and `css: ['bootstrap/dist/css/bootstrap.min.css'],` to `nuxt.config.ts`.

Replace `app.vue` with:

```html
<template>
  <BNavItemDropdown text="Test">
    <BDropdownItem>Test</BDropdownItem>
  </BNavItemDropdown>
</template>
```

Start the project:

```
$ npm run dev
```

Click on the dropdown. Note the error in the console (“TypeError: el is null”).

Including all composables and directives didn't make a difference.

I've tried some other components (like `BButton`) and they have worked fine.

There's also a hydration mismatch.

The same code worked on StackBlitz.

### Reproduction

N/A

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DGCK81LNN** [comment]
I have the same probem with nuxt@3.11.2, vue@3.4.31, bootstrap@5.3.3, bootstrap-vue-next@0.22.7, and @bootstrap-vue-next/nuxt@0.22.7

**Comment by DGCK81LNN** [comment]
Can reproduce on bootstrap-vue-next and @bootstrap-vue-next/nuxt versions 0.22.7, 0.21.2 and 0.20.0, but it works fine on 0.19.0.

**Comment by jonkri** [comment]
Here's a reproduction.

[bootstrap-vue-next-issue-1972.zip](https://github.com/user-attachments/files/16569122/bootstrap-vue-next-issue-1972.zip)
