### ISSUE TITLE
Typescript error when build

### ISSUE THREAD

**Issue by darkman97i** [bootstrap-vue-next/bootstrap-vue-next#1993]
### Describe the bug

* bootstrap-vue-next version 0.22.7
* npm version 9.8.1
* node version 20.14.0
* typescript version 4.5.5

I can run the serve without issues but when I execute the build it is raising several typescript errors like 
```
 ERROR  Failed to compile with 40 errors                                                                                                                                                                                      20:04:19

 error  in node_modules/bootstrap-vue-next/dist/src/composables/useBLinkHelper.d.ts:3:61

TS1139: Type parameter declaration expected.
    1 | import { MaybeRefOrGetter } from 'vue';
    2 |
  > 3 | declare const _default: <T extends Record<string, unknown>, const B extends readonly PropertyKey[]>(props: MaybeRefOrGetter<T>, pickProps?: MaybeRefOrGetter<B | (keyof T)[]>) => {
      |                                                             ^^^^^
    4 |     computedLink: Readonly<import('vue').Ref<boolean>>;
    5 |     computedLinkProps: import('vue').ComputedRef<Pick<{
    6 |         [x: string]: any;

```

I have checked the tsconfig.json parameters to ensure `skipLibCheck` was marked as `true` like it was indicated in an old issue but I have not found why it is not doing the build.

I attach the [error.txt](https://github.com/user-attachments/files/16072675/error.txt) and a sample project [sample-ui.zip](https://github.com/user-attachments/files/16072682/sample-ui.zip)

Thanks for your time

### Reproduction

https://github.com/user-attachments/files/16072682/sample-ui.zip

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Typescript 5 is required
