### ISSUE TITLE
BOffcanvas within a BModal

### ISSUE THREAD

**Issue by ijay-bm** [bootstrap-vue-next/bootstrap-vue-next#1996]
### Describe the bug

Opening a BOffcanvas located within a BModal will open it but appears behind the BModal.

This can be somewhat solved by overriding the BOffcanvas' z-index, but due to the BModal's focus trap, its not possible to interact with anything in the BOffcanvas.

Another solution is to use the teleportTo property of the BOffcanvas. This method allows for interaction with the BOffcanvas' contents. However, this solution has two problems:
- It requires timing the BOffcanvas to ensure that the target `teleportTo` exists
- There is the user expectation that upon pressing the escape key, it is the BOffcanvas that is hidden first. And upon pressing the escape key a second time, the BModal is hidden. Unfortuantely, pressing the esacpe key wil close both BModal and BOffcanvas.

Any suggestions regarding this matter would be greatly appreciated. For now, I will try to implement what the stakeholders want  without utilizing BOffcanvas within a BModal or achieve it through some other way.

### Reproduction

https://stackblitz.com/edit/github-w818ht?file=src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mbabker** [comment]
I ended up patching out the `useFocusTrap` bits in BModal for the moment.  We have a workflow on our site where a simple form gets submitted inside a BModal, and in certain conditions for that form, the server might send back a response that requires the user to confirm their action before the submission will go through.  With the focus trap active, it traps focus too well; the confirmation dialog that pops up over the modal can't be interacted with at all because focus is being trapped on the modal.

**Comment by ijay-bm** [comment]
> I ended up patching out the `useFocusTrap` bits in BModal for the moment. We have a workflow on our site where a simple form gets submitted inside a BModal, and in certain conditions for that form, the server might send back a response that requires the user to confirm their action before the submission will go through. With the focus trap active, it traps focus too well; the confirmation dialog that pops up over the modal can't be interacted with at all because focus is being trapped on the modal.

If I understand your issue correctly, I think it's solvable by following what's shown here: https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html#globally-hiding-modals. Rather than modifying the source code for specific bits, `bootstrap-vue-next` does allow for nested **BModals**.  Hope it helps.

This is the solution I went with in my case. Instead of attempting to use a BOffCanvas within a BModal, I replaced the BOffCanvas with a BModal. Still, it does not have the same aesthetic as the BOffCanvas.

The likely solution for this will be to treat the BOffCanvas as if they were BModals so that their focus and opening/closing order is also respected.

**Comment by mbabker** [comment]
We aren't trying to hide the modal when that verification step is needed, though.  In this case, a Sweetalert prompt pops up over the modal to handle that confirmation, then the form is submitted again.  The alert's visible, and before the focus trap was introduced, it worked without any issue (somewhat related, the focus trap also breaks interactivity of one of our development toolbars that get injected into the webpage, so it's not just this specific workflow but basically every click behavior or event listener that visually you'd expect to work seems to be affected by the focus trap).

**Comment by ijay-bm** [comment]
Oh, I was unclear in my previous response, I did not mean to reference the [example](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html#globally-hiding-modals) as a way to close the `BModal` form, but rather, to open another `BModal` as the confirmation prompt of the verification step. This way, you avoid the focus-trap preventing you from interacting with the `SweetAlert`.

I think that you could replace that Sweetalert with a BModal (or that's what I'd try do do anyway), but again, I am not fully aware of the constraints of your project. However, I would try my best to avoid using similar components from different libraries, but sometimes they are unavoidable. I myself use both Primevue and bootstrap-vue-next on a project. Sorry for the lack of clarity or miscommunication.

**Comment by mbabker** [comment]
> Essentially, you replace that `Sweetalert` with a `BModal` (or that's what I'd try do do anyway).

Maybe one day, but a lot of this application has been slowly moved from server-rendered HTML with jQuery back in the Bootstrap 3 days over to a mixed rendering/interaction state built around Vue.  So a lot of stuff that has just worked for us is still there (like Sweetalert), and sometimes to my surprise, it all works well together until it doesn't.  For us, that means it's much simpler to patch out the focus trap than it is to rewrite all of our UI components using Sweetalert (confirmation prompts, toast-like messages, etc.).

Your hint's definitely helpful in the long run though!

**Comment by VividLemon** [comment]
This is somewhat of a difficult ask because there isn't any guidance on how the two components should interact with each other in bootstrap - https://stackblitz.com/edit/sdc5jk?file=index.html

Here's my issue: if you make it so the offcanvas goes over the modal, then the modal faces the same issue but in the reverse. One of the two components will be disproportionately affected unless you manually change the z index of one or the other

In regards to the focus trapping, there's no way for us to know if an offcanvas has been opened, so we can't stop the trap. However, a prop could be added that disables the focus trap, so you could modify the z index manually when needed and disable the trap when its opened

**Comment by VividLemon** [comment]
Try 0.23.3

**Comment by VividLemon** [comment]
Note the z index issue as well

**Comment by ijay-bm** [comment]
> This is somewhat of a difficult ask because there isn't any guidance on how the two components should interact with each other in bootstrap - https://stackblitz.com/edit/sdc5jk?file=index.html

I understand.

> Here's my issue: if you make it so the offcanvas goes over the modal, then the modal faces the same issue but in the reverse. One of the two components will be disproportionately affected unless you manually change the z index of one or the other

Yes, prior to 0.23.3, setting the z-index manually was not enough. So using the nested `BOffCanvas`'s `teleportTo` property is how I solved the order of appearance and the focus-trap issue. Now, like I outlined in the reproduction, this was still not ideal as pressing the escape key made both the `BModal` and `BOffcanvas` close at the same time.

> In regards to the focus trapping, there's no way for us to know if an offcanvas has been opened, so we can't stop the trap. However, a prop could be added that disables the focus trap, so you could modify the z index manually when needed and disable the trap when its opened

Giving us the ability to disable the trap at will is nice as this allows control over the focus trap on specific events or all the time. But for UI/UX adherence, I really don't see any benefits to disabling the focus trap. While I appreciate the added capability, I don't think its the ideal solution. But I do understand that this is less of a priority right now not only due to other pressing matters and limited commitment, but also having no bootstrap guidance. But to quote my ideal solution for this:
> The likely solution for this ticket will be to treat the BOffCanvas as if they were BModals so that their focus and opening/closing order is also respected.
I think that if this is doable, it would be the ideal solution. In addition to that, perhaps the ability to add custom modal components into the "modal stack" (I don't know what to call it) or to treat a custom component as such.

My solution for this is to use a nested `BModal` instead of `BOffcanvas` for now. This ticket can be ignored given how niche the application is. But again, adding `noTrap` on both the `BModal` and `BOffcanvas` is a nice addition for niche uses.

**Comment by VividLemon** [comment]
> Just a brief note on that noTrap prop, will the focus-trap reactivate upon toggling it back on? Feel free to ignore this question.

I didn't add this, mostly because I didn't think about it. A small oversight that I don't think warrants a change tho
