### ISSUE TITLE
Using :value and @change instead v-model

### ISSUE THREAD

**Issue by israeloriente** [bootstrap-vue-next/bootstrap-vue-next#2002]
**What you are trying to do.** A clear and concise description of what you want to happen:

I'm migrating from vue 2 to vue 3 and I've replaced bootstrap-vue with bootstrap-vue-next. 

The problem I'm running into is that the data is coming through props from various components above and I'm not able to use the v-model. 

In the old code (vue 2) it basically plays this role, but now this happens:
https://stackblitz.com/edit/vitejs-vite-pxa5ft?file=src%2FApp.vue

My question is, why does the <BFormInput> not write if in vue 2 with bootstrap-vue it works?

Here is the old code in vue 2:
![346670841-08c636bf-3df9-4b56-bd25-437566c72e68-ezgif com-video-to-gif-converter](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31784632/f98f04db-f84b-44b3-9758-0edaebb0b6bb)

Here it is now with vue 3:
![346671049-34ca2593-16c2-40a8-b0d9-6bfdce4a08f6-ezgif com-video-to-gif-converter](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31784632/e2a1f591-0a1a-4c00-9fe1-f6376f7c4752)

**Environment:**

- OS: [MacOS]
  "dependencies": {
    "bootstrap": "^5.3.3",
    "bootstrap-vue-next": "^0.22.7",
    "vue": "^3.4.29"
  },

**Comment by VividLemon** [comment]
Because selectedText is a `reactive` and doesn't have a .value property

**Comment by VividLemon** [comment]
Also in the provided snippet you didn't import ref

**Comment by VividLemon** [comment]
But the chain in logic is wrong. @change will only run during the @change 's input event, naturally. But you have blocked changing of the `value` of the input. It's odd behavior.

You may prefer using the following code, assuming you even need the change event

```html
<template>
  <div>
    <BFormInput v-model.lazy="selectedText" @change="console.log('changed')" />
    <div class="mt-2">Value: {{ selectedText }}</div>
  </div>
</template>
<script setup>
import { ref } from 'vue';

const selectedText = ref('Hello World');
</script>

```

**Comment by israeloriente** [comment]
> But the chain in logic is wrong. @change will only run during the @change 's input event, naturally. But you have blocked changing of the `value` of the input. It's odd behavior.
> 
> You may prefer using the following code, assuming you even need the change event
> 
> ```
> <template>
>   <div>
>     <BFormInput v-model.lazy="selectedText" @change="console.log('changed')" />
>     <div class="mt-2">Value: {{ selectedText }}</div>
>   </div>
> </template>
> <script setup>
> import { ref } from 'vue';
> 
> const selectedText = ref('Hello World');
> </script>
> ```

You're right, ref is working, I'll test it in my code now, but I read in the documentation that I should use reactive instead of ref when using complex objects (which is my case)

**Comment by VividLemon** [comment]
Regardless the reactive isn't the issue.

The vue docs mention reactive but I think most people will use ref for everything

I'm surprised `<input :value="selectedText" @change="changeValue($event)" />` works. Logically it doesn't make any sense on how the value is meant to change. But vue's usage of input v-models is different than that of a component v-model

**Comment by VividLemon** [comment]
The reason why it works in bootstrap-vue though is because they overwrote the native @input and @change events. This is because of how vue 2 handles v-models -- a v-model in vue 2 compiled to `:value="" @input=""` whereas in vue 3 its' `:value="" @update:modelValue=""`. So, in the last few iterations I made the decision to not overwrite the natives, as anything you can get from them you can do using Vue 3 features (modelValue)

**Comment by VividLemon** [comment]
When you submit reproductions you'd always need to show what you're doing. This mov is meaningless to me

**Comment by israeloriente** [comment]
> When you submit reproductions you'd always need to show what you're doing. This mov is meaningless to me

What do you need to see?
