### ISSUE TITLE
ResizeObserver is not defined

### ISSUE THREAD

**Issue by ltickett** [bootstrap-vue-next/bootstrap-vue-next#2006]
### Describe the bug

Some of my tests are failing with the error `ResizeObserver is not defined` when bumping bootstrap-vue-next from 0.22.7 to 0.23.1

https://gitlab.com/gitlab-renovate-forks/contributors-gitlab-com/-/jobs/7290647744

```
ReferenceError: ResizeObserver is not defined
 ❯ whileElementsMountedOption ../../node_modules/.pnpm/@floating-ui+dom@1.1.1/node_modules/@floating-ui/dom/dist/floating-ui.dom.browser.min.mjs:1:6784
 ❯ C ../../node_modules/.pnpm/@floating-ui+vue@1.1.1_vue@3.4.27/node_modules/@floating-ui/vue/dist/floating-ui.vue.mjs:150:37
 ❯ callWithErrorHandling ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:196:19
 ❯ callWithAsyncErrorHandling ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:203:17
 ❯ job ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6043:9
 ❯ resetScheduling ../../node_modules/@vue/reactivity/dist/reactivity.cjs.js:266:34
 ❯ triggerEffects ../../node_modules/@vue/reactivity/dist/reactivity.cjs.js:310:3
 ❯ triggerRefValue ../../node_modules/@vue/reactivity/dist/reactivity.cjs.js:1075:5
 ❯ RefImpl.set value [as value] ../../node_modules/@vue/reactivity/dist/reactivity.cjs.js:1122:7
 ❯ doSet ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3711:21
```

I couldn't find any existing issues, but I did see some changes relating to floating which seems to tie in with the stack trace?

Are there any known issues?

### Reproduction

https://gitlab.com/gitlab-renovate-forks/contributors-gitlab-com/-/jobs/7290647744

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Does this happen on v23

**Comment by VividLemon** [comment]
Try adding @floating-ui/vue as a devdependency

**Comment by ltickett** [comment]
Thanks @VividLemon 

Unfortunately adding `@floating-ui/vue` didn't help.

I checked when adding `@floating-ui/vue` the following were implicitly adding:

```
@floating-ui/core
@floating-ui/dom
@floating-ui/utils
@floating-ui/vue
```

**Comment by mbabker** [comment]
Updated today and added `@floating-ui/vue` as a dev dependency, similar error & stack trace

```shell
ReferenceError: ResizeObserver is not defined
at Da (/app/node_modules/.pnpm/@floating-ui+dom@1.1.1/node_modules/@floating-ui/dom/dist/floating-ui.dom.browser.min.mjs:1:6879)
at C (/app/node_modules/.pnpm/@floating-ui+vue@1.1.1_vue@3.4.27/node_modules/@floating-ui/vue/dist/floating-ui.vue.mjs:161:1)
at callWithErrorHandling (/app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:196:19)
at callWithAsyncErrorHandling (/app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:203:17)
at job (/app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6043:9)
at resetScheduling (/app/node_modules/@vue/reactivity/dist/reactivity.cjs.js:266:34)
at triggerEffects (/app/node_modules/@vue/reactivity/dist/reactivity.cjs.js:310:3)
at triggerRefValue (/app/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1075:5)
at RefImpl.set value [as value] (/app/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1122:7)
at doSet (/app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3711:21)
at flushPostFlushCbs (/app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:378:32)
at flushJobs (/app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:414:5)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The `contributors-gitlab-com` repo looks to be using Vite, Vitest, and plain JavaScript.  The application I'm seeing this in is using Webpack, Jest, and TypeScript.

Unfortunately, looking over my test failures, I don't think I can strip anything down to a reproduction case (the one Vue component that is somewhat standalone still has a lot of external requirements), but, as soon as I remove `BDropdown` and `BDropdownItem` from that component, its tests pass.

**Comment by VividLemon** [comment]
You could try to locally build a dist copy that has them reregistered in our lib as direct dependencies. That and possibly reverting the versions back to their 0.22 used versions. Then try that

I could do it, but I wouldn't be able to get to it for a bit

**Comment by VividLemon** [comment]
This was the diff for the package https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/bootstrapvuenext-v0.22.7...bootstrapvuenext-v0.23.1#diff-e04aecfce6b6cb542767b096855fc5eb2681ba5a764f65167447440a9df1a92e

& 

https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/bootstrapvuenext-v0.22.7...bootstrapvuenext-v0.23.1#diff-8fb2aa4b9e64fcfc83279f6f83dc799c8ca5b33e3673d8723f5d223647dd47de

(But the bdropdown diff didn't change in a substantial way, just some type differences and different imports)

**Comment by ltickett** [comment]
It's not a huge drama at the moment. There's no rush to bump the package in my project. Hopefully, you'll figure it out at some point (it looks like I won't be the only one with this issue either) then we can jump straight to a future release.

Thanks for the quick responses 🙏

**Comment by mbabker** [comment]
> (But the bdropdown diff didn't change in a substantial way, just some type differences and different imports)

Yeah, I agree here.  I checked a handful of pages in the app and everything was working, it's just our test build that blew up.  I think the fact my test worked after removing the dropdown components is more tied to how `@floating-ui/vue` (and its dependencies) get imported in 0.23 and not necessarily a change in this library (I'm also not a frontend person primarily, so we're getting into stuff that just goes over my head with this specific error scenario 😅)

**Comment by ltickett** [comment]
It looks like there are a few workaround here: https://github.com/jsdom/jsdom/issues/3368

I'm not sure what best practice is (e.g. should we be raising an upstream MR to add the polyfill to jsdom?)

**Comment by VividLemon** [comment]
Out of curiosity try using 0.23.2

**Comment by mbabker** [comment]
Still getting the same error in our tests on 0.23.2.  Production build's just fine.

**Comment by VividLemon** [comment]
Tbh I really don't think this is our issue. I _feel_ like it's a vitest v2 issue. `Simplify mock function generic types and align with jest` https://github.com/vitest-dev/vitest/releases/tag/v2.0.0 ... But I really have no idea. All I know is its really not because of us. The best thing you can do is add a mock for ResizeObserver

**Comment by VividLemon** [comment]
Attempt to add

`global.ResizeObserver = require('resize-observer-polyfill)` & `npm add resizeobserver-polyfill`

**Comment by magistrator** [comment]
I sorted this issue with ['jsdom-testing-mocks'](https://github.com/trurl-master/jsdom-testing-mocks)


```
import { mockResizeObserver } from 'jsdom-testing-mocks'
.......
  beforeEach(async () => {
    mockResizeObserver()
  })
```
The idea is to mock ResizeObserver before each test execution.
