### ISSUE TITLE
BModal: Focus trap exception on modal display with custom header and footer hidden

### ISSUE THREAD

**Issue by tvore** [bootstrap-vue-next/bootstrap-vue-next#2016]
### Describe the bug

Hello,

I have the following exception occurring when trying to show a modal with a custom header and footer hidden. See reproduction below.

Operational consequences: modal not working and application is blocked

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/145966330/f12ea7de-40a2-4a12-b2cc-0f5a180bbd38)

Kind regards,
Tvore

### Reproduction

https://stackblitz.com/edit/github-hspdt1?file=src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
.23.3
