### ISSUE TITLE
:state="false" on BFormCheckbox

### ISSUE THREAD

**Issue by jonkri** [bootstrap-vue-next/bootstrap-vue-next#2017]
### Describe the bug

Shouldn't the first checkbox on https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-checkbox.html#contextual-state-and-validation-example be red since the `state` prop is set to `false`?

I have a required checkbox that I want to highlight in red under certain circumstances.

This code didn't produce a checkbox at all on StackBlitz for some reason:

```html
<BFormCheckbox :state="false">Should be red</BFormCheckbox>
```

### Reproduction

N/A

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dwgray** [comment]
@jonkri - Thanks, the individual `checkbox === false` behavior is a bug. I have #2019 up to address that. I'm not reproing the no checkbox issue. Can you add a link to your stackblitz?

**Comment by VividLemon** [comment]
0.23.3

**Comment by jonkri** [comment]
@dwgray: Thanks! False alarm on the stackblitz problem... I didn't realize I had to import the components in that context. 😅
