### ISSUE TITLE
BTable Column width varies when paginating 

### ISSUE THREAD

**Issue by leonardootoni** [bootstrap-vue-next/bootstrap-vue-next#2023]
**What you are trying to do.** A clear and concise description of what you want to happen.

I want to set BTable columns with qual width. 
According to the documentation description for "<b-table>" on Bootstrap Vue 2.23.0, the property "fixed" is intended for that:
_Makes all columns equal width (fixed layout table). Will speed up rendering for large tables. Column widths can be set via CSS or colgroup_  

The same prop is also present on BTable. So, I presume it should serve the same principle on <BTable/>
Here is my current declaration:

`<BTable
          thead-tr-class="thead-th"
          @row-clicked="selectRowItem"
          class="my-4"
          hover
          bordered
          striped
          small
          :responsive="true"
          :sort-by="[{ key: 'model', order: 'asc' }]"
          :items="dataTableItems"
          :fields="sortTableFields"
          :current-page="currentPage"
          :per-page="rowsPerPage"
          :fixed="true"
        />`

However, setting fixed as true does not force the columns width to equal size.
Without enforce width by css, is there any other option that can be used? Not sure if this case is a real problem or a side effect of a misconfigured component.

**What you have already tried.** A clear and concise description of any alternative solutions or features you have considered.

Binding true/false to :fixed 

**Any error messages you are getting.** If any, please list the errors you are getting.

No error messages

**Environment (please complete the following information):**

- OS: [e.g. Windows 11, Pop!_OS]

   Mac OS

- Package Version: [e.g. 0.8.12]

    "bootstrap-vue-next": "^0.23.2",

- Npm/Yarn/Pnpm/Bun Version: [e.g. npm@9.6.6, pnpm@8.5.1]

    npm@10.5.2

**Comment by m-demydiuk** [comment]
@VividLemon This is still not working.
