### ISSUE TITLE
BDropdown issues

### ISSUE THREAD

**Issue by martin91s** [bootstrap-vue-next/bootstrap-vue-next#2024]
### Describe the bug

There's 2 issues I've noticed whilst using the `BDropdown` component.

1. When focusing on to the dropdown using Tab, use the up or down arrow keys on your keyboard - Notice 100's of tabs open causing page to crash
2. I am using the Nuxt module, the dropdown won't open on page refresh without the use of `<client-only>` wrapping the dropdown component

### Reproduction

https://stackblitz.com/edit/nuxt-starter-csegoj?file=app.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by afv** [comment]
> 1. When focusing on to the dropdown using Tab, use the up or down arrow keys on your keyboard - Notice 100's of tabs open causing page to crash

This still happens with the latest version (0.25.13). Arrow down ▼ on a dropdown opens hundreds of `about:blank` tabs, until out of memory.
