### ISSUE TITLE
BDropdown radius in BButtonGroup

### ISSUE THREAD

**Issue by amokrunnr** [bootstrap-vue-next/bootstrap-vue-next#2025]
### Describe the bug

Dropdown button radius inside a BButtonGroup was broken at some point, this is a snapshot from the docs example:
![image](https://github.com/user-attachments/assets/2485a43e-ce67-433a-821e-200f206c47d7)

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/button-group.html

### Used Package Manager

n/a

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anrolmar** [comment]
I've just checked the repository content and the bug is already fixed

**Comment by jongbonga** [comment]
@VividLemon This is what I see with the latest build

![Screenshot 2024-10-25 at 16 25 17](https://github.com/user-attachments/assets/65c2ebc6-029e-4812-929c-185727cfd82a)

**Comment by VividLemon** [comment]
> @VividLemon This is what I see with the latest build, the last button doesn't get the end radius
> 
> ![Screenshot 2024-10-25 at 16 25 17](https://private-user-images.githubusercontent.com/12111716/380182046-65c2ebc6-029e-4812-929c-185727cfd82a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjY3ODgsIm5iZiI6MTcyOTg2NjQ4OCwicGF0aCI6Ii8xMjExMTcxNi8zODAxODIwNDYtNjVjMmViYzYtMDI5ZS00ODEyLTkyOWMtMTg1NzI3Y2ZkODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE0MjgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZTZhMTY5MjZkZTMyN2Y0NTMyZDc2OTAyYjg3NzQzODI5ZmI3ZjNhYTM5YWY4MDE2Y2EyYWQ5MWRiMzhkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1raP3QdzkyQnHVXTD5hnWOwDpNcDJ_KTPbpRAj9zK_w)

@jongbonga Make a new issue with a reproduction
