### ISSUE TITLE
`shown` event not triggered when wrapping `BModal` in a component

### ISSUE THREAD

**Issue by jonkri** [bootstrap-vue-next/bootstrap-vue-next#2027]
### Describe the bug

The `shown` event is not triggered when `BModal` is used within a component, like so:

**`App.vue`:**

```html
<script setup lang="ts">
  import { ref } from "vue";
  import TestModal from "./components/TestModal.vue";

  const modal = ref(false);
</script>

<template>
  <TestModal v-model="modal" />
  <input @click="modal = !modal" type="button" value="Show" />
</template>
```

**`TestModal.vue`:**

```html
<script lang="ts" setup>
  import { BModal } from "bootstrap-vue-next";

  function onShown() {
    alert("This doesn't show up!");
  }
</script>

<template>
  <BModal :shown="onShown">
    <code>shown</code> event <b>is not</b> triggered.
  </BModal>
</template>
```

However, if I use `BModal` directly in `App.vue` then the `shown` event is triggered as expected:

```html
<script setup lang="ts">
  import { ref } from "vue";
  import TestModal from "./components/TestModal.vue";

  const modal = ref(false);
</script>

<template>
  <TestModal v-model="modal" />
  <input @click="modal = !modal" type="button" value="Show" />
</template>
```

### Reproduction

[bootstrap-vue-next-issue-2027.zip](https://github.com/user-attachments/files/16196788/bootstrap-vue-next-issue-2027.zip)

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
```html
<template>
  <BModal :shown="onShown">
    <code>shown</code> event <b>is not</b> triggered.
  </BModal>
</template>
```
This is incorrect syntax

```html
<template>
  <BModal @shown="onShown">
    <code>shown</code> event <b>is not</b> triggered.
  </BModal>
</template>
```
`@shown="onShown">`

In vue, in addition, if you wrap the root element like so:

```html
<template>
  <div>
  <BModal @shown="onShown">
    <code>shown</code> event <b>is not</b> triggered.
  </BModal>
</div>
</template>
```

You would need to re-emit it (only root events bubble up)


```html
<template>
  <div>
  <BModal @shown="onShown">
    <code>shown</code> event <b>is not</b> triggered.
  </BModal>
</div>
</template>

<script setup lang="ts">
const emit = defineEmits<{ shown: [] }>()

const onShown = () => {
  emit('shown')
}
</script>
```

**Comment by jonkri** [comment]
Oh, how silly of me! 😅 Thanks!
