### ISSUE TITLE
`hide` from `useModal` doesn't hide the modal when `BvTriggerableEvent` is prevented

### ISSUE THREAD

**Issue by jonkri** [bootstrap-vue-next/bootstrap-vue-next#2028]
### Describe the bug

`hide` from `useModal` doesn't hide the modal when `BvTriggerableEvent` is prevented.

Here's an example:

```html
<template>
  <BModal id="modal" @ok.prevent="onClick">
    <input @click="onClick" type="button" value="Hide" />
  </BModal>
</template>

<script setup lang="ts">
  import { onMounted } from "vue";
  import { BvTriggerableEvent, useModal } from "bootstrap-vue-next";
  import { BModal } from "bootstrap-vue-next";

  const { hide, show } = useModal("modal");

  onMounted(() => {
    show();
  });

  function onClick(_event: BvTriggerableEvent | MouseEvent) {
    hide();
  }
</script>
```

The modal can be hidden by pressing the “Hide” `input` button. However, it can't be hidden by pressing the OK button. Both buttons call the same function.

### Reproduction

[bootstrap-vue-next-issue-2028.zip](https://github.com/user-attachments/files/16197532/bootstrap-vue-next-issue-2028.zip)

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
I'm not sure your thought process for saying "it doesn't hide when I prevent the default on the event". Thats the entire point of preventDefault

**Comment by jonkri** [comment]
I see, thanks!

I didn't realize I could call `hide` asynchronously, for instance like so:

```ts
setTimeout(() => {
  hide();
}, 0);
```

Closing.

**Comment by xvaara** [comment]
@jonkri see https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2376#issuecomment-2501563603 for some info. You can prevent the hide in the function if needed for something. Otherwise the ok will hide the modal.
