### ISSUE TITLE
Popover target prop function not working

### ISSUE THREAD

**Issue by jacobg** [bootstrap-vue-next/bootstrap-vue-next#2038]
### Describe the bug

In the old bootstrap-vue, the Popover accepted a target prop with a function that returns the target component or element, e.g.,
```
:target="() => $refs.btn"
```

In bootstrap-vue-next, although the documentation says the target type can be a `(() => HTMLElement | VNode)`, it doesn't actually work.
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/popover.html

### Reproduction

https://stackblitz.com/edit/github-jwsdlr?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
We removed it since we don't see a need for it. Can you provide an example where you need to use it? If you have a lot of them, you could just use slots so no need to generate ids for the elements.

**Comment by jacobg** [comment]
Ah, didn't realize it has the `#target` slot. That's fantastic! Thank you! Issue closed!

> We removed it since we don't see a need for it. Can you provide an example where you need to use it? If you have a lot of them, you could just use slots so no need to generate ids for the elements.
> 
> The documents are out of date.

**Comment by dword-design-honestly** [comment]
Same here, totally fine with it and cleaner!
