### ISSUE TITLE
BFormGroup missing class="form-group" and bottom margin

### ISSUE THREAD

**Issue by jacobg** [bootstrap-vue-next/bootstrap-vue-next#2039]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-group.html#component-reference

### Describe the missing feature

In original bootstrap-vue, the BFormGroup component created a <div> element with class="form-group", and that style had a 1rem bottom margin:
https://bootstrap-vue.org/docs/components/form-group

But in the current bootstrap-vue-next, no "form-group" class is declared, nor is there a bottom margin:
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-group.html#component-reference

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by VividLemon** [comment]
I decided against this https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2042#issuecomment-2229087517
