### ISSUE TITLE
`BDropdown` not working on bootstrap-vue-next.github.io

### ISSUE THREAD

**Issue by Skyost** [bootstrap-vue-next/bootstrap-vue-next#2046]
### Describe the bug

Hey,

It seems that the dropdown components (available [here](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/dropdown.html) or [here](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/navbar.html#bnavitemdropdown) for instance) are not working at all. This could be related to #2024 and #1972.

Here's the console content :

![image](https://github.com/user-attachments/assets/4eecf5df-a322-4c52-a8bf-74cdf1eea9aa)

### Reproduction

Go to [this page](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/dropdown.html) with a Chromium browser. Not tested on Firefox or Safari tho.

EDIT : It seems to happen only when rendered server side. So if it works while testing, try to _F5_ the page before retrying 🙂

### Used Package Manager

n/a

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Skyost** [comment]
A workaround if you're using Nuxt : wrap your `BDropdown` component inside of a `ClientOnly` component.

**Comment by plaughton** [comment]
We experienced the same issue with nuxt 3.12.4 and bootstrap-vue-next 0.24.7... thanks @Skyost for the workaround - it does mean the menu jumps slightly on loading but at least it gets us going.
