### ISSUE TITLE
Any idea on how to use toast with vue3 with typescript?

### ISSUE THREAD

**Issue by srikanth2042** [bootstrap-vue-next/bootstrap-vue-next#2050]
**What you are trying to do.** 
Trying to use bootstrap toast with Vue3+Typescript combination

**What you have already tried.**
Tried using `show` from toast with help of `useToast` but its not working.

**Any error messages you are getting.** If any, please list the errors you are getting.
No error message but toast not working

**Environment (please complete the following information):**

- OS: Windows 11
- Package Version: 0.23.1
- Npm/Yarn/Pnpm/Bun Version: npm@9.8.1

Code:
my-component.ts:
```
import { defineComponent } from 'vue';
import { ref } from "vue";
import { useToast } from 'bootstrap-vue-next';

export default defineComponent({
  data() {
    return {
      abc: '',
    }
  },
  setup() {
    const toast = useToast()
    return toast
  },
  async mounted() {
    // do nothing
  },
  methods: {
    async testToast() {
      try {
        this.show?.({props: {variant: 'success', title: 'Message', body: 'Toasted successfully!'}});
      } catch (err) {
        console.log(err)
        this.show?.({props: {variant: 'danger', title: 'Message', body: 'Something went wrong!'}})
      }
    }
  }
})
```

MyComponent.vue:
```
<template>
  <div class="my-component">
    <BButton @click="testToast" variant="success">Click Me</BButton>
  </div>
</template>
<script lang="ts">
  import MyComponent from './my-component';
  export default MyComponent;
</script>
```

Please note that MyComponent is being injected into App.vue file as a sub component.

**Comment by VividLemon** [comment]
![image](https://github.com/user-attachments/assets/cd77c7f2-676f-4b55-a263-439b59a4a9ea)
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useToast.html
