### ISSUE TITLE
Can't reset `BFormFile` by assigning an empty array

### ISSUE THREAD

**Issue by jonkri** [bootstrap-vue-next/bootstrap-vue-next#2052]
### Describe the bug

When using `BFormFile` with an array `v-model` value, replacing the array with a new empty array (`[]`) doesn't reset the `BFormFile` component. In other words, after having assigned a new empty array to the `v-model` ref the `BFormFile` component still displays the file(s) selected.

```html
<template>
  <BFormFile multiple v-model="files" />
  <input @click="files = []" type="button" value="Reset files" />
  <p><code>files</code>: {{ files }}</p>
</template>

<script setup lang="ts">
  import { ref } from "vue";
  import { BFormFile } from "bootstrap-vue-next";

  const files = ref([]);
</script>
```

To reproduce:

1. Activate the file chooser and select a file.
2. Click on the **Reset files** button.
3. Note how the upload element still displays the file that was selected in Step 1.

Note that if arrays are not used, and `null` is used when a file is not selected, then the **Reset files** button works as expected.

```html
<template>
  <BFormFile v-model="file" />
  <input @click="file = null" type="button" value="Reset files" />
  <p><code>file</code>: {{ file }}</p>
</template>

<script setup lang="ts">
  import { ref } from "vue";
  import { BFormFile } from "bootstrap-vue-next";

  const file = ref(null);
</script>
```

It actually doesn't actually matter whether `multiple` is used or not. The problem is that assigning an empty array doesn't reset the `BFormFile` component.

### Reproduction

[bootstrap-vue-next-issue-2052.zip](https://github.com/user-attachments/files/16255559/bootstrap-vue-next-issue-2052.zip)

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
This is really a browser security thing. I'm a bit disappointed the bootstrap vue allows you to set the value an empty array. The value is more or less read only. Realistically the only way that one _should_ reset a file input would be to manually set it to an empty string. 

I'm going to close this as not planned and add a note to the lib parity. You should really be using "", or null (which is just something we've added) for security. 

For example, a malicious script could create an array that attaches itself to the input. Say if you were to do

```js
const blankArray = []

const reset = () => {
  input.value = blankArray
}
```
A malicious script could

```js
blankArray.push(myBadFile)
```

So browsers don't really allow for this kind of behavior
