### ISSUE TITLE
BModal - add event for close on backdrop click or esc

### ISSUE THREAD

**Issue by m-demydiuk** [bootstrap-vue-next/bootstrap-vue-next#2054]
### Clear and concise description of the problem

Now, BModal emits `close` event when `X` button in header is clicked, and `cancel` event when `Cancel` button in footer is clicked.
We have a method `onClose` that handles `close` and `cancel` events. onClose does some logic before closing dialog, like clearing dialog and some resources, and some other actions. and in the end hides dialog with setting `show = false`, that is binded via v-model.

Everything works perfect, but today we realised that `close` or `cancel` events are not emitted when click on backdrop or esc. So the dialog closes, but resources are not cleared.

### Suggested solution

Option 1 - emit `close` event when click on backdrop and esc.
Option 2 - emit another event(s) when click on backdrop and esc.
Option 3 - add BModal props `emitCloseOnBackdrop` and `emitCloseOnEsc`, and if true emit close event.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
This is also an option

```ts
<BModal @close="onClose">

const onClose = (event) => {
  if(event.trigger === 'esc') { /* do esc */ }
}
```

**Comment by VividLemon** [comment]
Fixed in https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2054

**Comment by m-demydiuk** [comment]
> This is also an option
> 
> ```ts
> <BModal @close="onClose">
> 
> const onClose = (event: BvTriggerableEvent) => {
>   if(event.trigger === 'esc') { /* do esc */ }
> }
> ```

This is not an option, because event is not triggered when click on backfrop or esc button.

**Comment by VividLemon** [comment]
```ts
<BModal @hide="onClose">

const onClose = (event: BvTriggerableEvent) => {
  if(event.trigger === 'esc') { /* do esc */ }
}
```

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BModal/BModal.vue#L95
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BModal/BModal.vue#L393C3-L393C22
