### ISSUE TITLE
autofocus of inputs not working in modals

### ISSUE THREAD

**Issue by dword-design-honestly** [bootstrap-vue-next/bootstrap-vue-next#2056]
### Describe the bug

When adding `autofocus` to an input inside a modal, the input isn't focused. I also tried around with the `autoFocus` prop of the modal but no change. Also, passing e.g. the `close` button as an auto focus button doesn't work, so it looks like also the focusing of the predefined buttons in the modal doesn't work. Maybe I'm missing something. Happy about help!
![Bildschirmfoto 2024-07-17 um 15 30 26](https://github.com/user-attachments/assets/8c04cecb-fb76-4d8e-8676-0edbdb0e2ef9)

### Reproduction

https://github.com/dword-design-honestly/demo-bootstrap-vue-next-modal-autofocus-not-working

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
At the time of opening, you can't focus the element. Manual focusing is likely the best option:

```html
<template>
  <b-button @click="onClick" />
  <b-modal id="isShown" v-model="isShown" :auto-focus="false">
    <b-form-input ref="inp" />
  </b-modal>
</template>

<script setup lang="ts">
import {nextTick, ref} from 'vue'
import type {BFormInput} from './components'

const isShown = ref(false)
const inp = ref<null | InstanceType<typeof BFormInput>>(null)
inp.value?.focus()

const onClick = () => {
  isShown.value = true
  nextTick(() => {
    inp.value?.focus()
  })
}
</script>
```

**Comment by dword-design-honestly** [comment]
@VividLemon Ok thanks for the info. May I ask why not planned? 🙂 Since it works in BootstrapVue and I think it would be great to avoid refs and to keep things declarative.

**Comment by VividLemon** [comment]
I really don't think it warrants a section of its own. It's an edge case that deals with the scheduling of when events occur. I suppose a Vue novice wouldn't really know why it doesn't focus, but the reason is simply that they are not in the same tick. It's not something that we really have control over, the only way that we could fix it is to always be adding nexttick to focusing, which is a lot to ask for an edge case that the user can fix themselves. You wouldn't ask a nested component to change its behavior simply because some grandparent component decided not to render it. The child component doesn't know its not rendered

**Comment by dword-design-honestly** [comment]
@VividLemon Current state seems to be that inputs already `nextTick` the focusing at [this place](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/composables/useFormInput.ts#L49). So in this case I'd expect that if a modal is opened (especially when it is freshly created via a modal controller), the input is activated and then is focusing himself in the next tick. Since most modals have some autofocus happening and there is already special behavior of this autofocus property that goes beyond the default HTML5 way of focusing on page load, it feels inconsistent to me that this behavior isn't working for modals.

Apart from that, I haven't understood yet why it's not working since as written above inputs already seem to deal with the activated hook and nextTick.

**Comment by dword-design-honestly** [comment]
@VividLemon Another use case I found was that if you have a component for the form inside the modal or the autofocus element is in some subcomponent, reffing it will not work (note that also getting a ref of a ref will not always work, see scoped slots). So example:

```js
<!-- AppUserForm.vue -->

<template>
  <!-- Possibly containing validation and other complexity -->
  <b-form>
    <b-form-group label="Name">
      <b-form-input autofocus />
    </b-form-group>
  </b-form>
</template>
```

```js
<!-- UserModal.vue -->

<template>
  <b-modal>
    <app-user-form />
  </b-form>
</template>
```

This form could then be used inside or outside of a modal and expects to auto-focus the input.

Also I think that refs should be avoided if possible to keep things declarative.
