### ISSUE TITLE
Options API support for modals (confirmations)

### ISSUE THREAD

**Issue by tomastan** [bootstrap-vue-next/bootstrap-vue-next#2065]
**What you are trying to do.**

Trying to use Options API for confirm modal while migrating from `bootstrap-vue` on a large app. While it's clear how to use it with Composition API, unfortunately I found no examples of options API in docs. Is there a support for Options API and if so, how it is possible to make it work?

**What you have already tried.**

As mentioned I try to migrate the code:

```javascript
...
export default {
	// ...
	methods: {
		openConfirmation(){
			this.$bvModal.msgBoxConfirm('... Are you sure?', {
				title: "Warning",
			}).then(() => {....})
		}
	}
}
...
```

While it's not something expected to work, I tried to combine options API with composition elements and `<BModalOrchestrator />` added:
```javascript
const { confirm } = useModalController()

export default {
	// ...
	methods: {
		async openConfirmation(){
				let x = await confirm?.({
					props: {
						body: '... Are you sure?',
						title: 'Warning',
					},
				})

				console.log(x) // No confirmation modal shown. x is always "undefined"
		}
	}
}
```

And as expected the code above is not working.

**Any error messages you are getting.**
No confirmation modal shown and x is always "undefined" 
```
[Vue warn]: inject() can only be used inside setup() or functional components.
```

**Environment (please complete the following information):**
(irrelevant)

**Comment by tomastan** [comment]
Ok. It looks I found an answer in another ticket (#1437) but it helped. For those interested and want to save time:

```javascript
	setup(){
		const { confirm } = useModalController()
		return {
			confirm,
		}
	},
```
and then `this.confirm()` works as expected

**Comment by platform-kit** [comment]
@tomastan can you give a more complete explanation of how to use this code in options api?

**Comment by tomastan** [comment]
The `setup()` is a way to use Composition API in Options API components: https://vuejs.org/api/composition-api-setup.html

In short example (haven't tested it, but gives an idea):

```vue
<template>
  <div>
    <button @click="openConfirm">Click</button>
    <BModalOrchestrator /> <!-- this should be placed somewhere globally for better reusing in components https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useModalController.html#bmodalorchestrator  -->
  </div>
</template>

<script>
import { useModalController } from 'bootstrap-vue-next'

export default {
  setup(){
    const { confirm } = useModalController()

    return {
      confirm, // this.confirm() now is available in this component
    }
  },

  methods: {
    openConfirm(){
      this.confirm({
        props: {
          body: "Are you sure?",
        }
      }).then(value => {
        if(value){
          // ... Confirmed
        }else{
          // ... Not confirmed
        }
      })
    }
  },
}
</script>
```
