### ISSUE TITLE
BNavBar does not support `-subtle` variants

### ISSUE THREAD

**Issue by Morgul** [bootstrap-vue-next/bootstrap-vue-next#2079]
### Describe the bug

`BNavBar` (and I suspect other places) throws a Typescript error when attempting to use and of the `-subtle` color variants:

![image](https://github.com/user-attachments/assets/48f0855e-5e53-4e81-8190-3e41d797833a)

The documentation states:

> Set the variant prop to one of the following values to change the background color: primary, secondary, success, info, warning, danger, dark, light, _or any of the *-subtle variants._

(See [here](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/navbar.html#color-schemes).)

## Note on Reproduction

In StackBlitz I can't get it to do type inference (it thinks `variant` is a string), which is why the repo doesn't "show an error". But Webstorm shows the error just fine.

### Reproduction

https://stackblitz.com/edit/github-qebqsr?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
https://getbootstrap.com/docs/5.3/customize/color/#using-the-new-colors
