### ISSUE TITLE
Including the prop teleportDisabled without a value in BOffcanvas will result in false.

### ISSUE THREAD

**Issue by 082137** [bootstrap-vue-next/bootstrap-vue-next#2080]
### Describe the bug

In Vue, a Boolean prop included without a value is typically true, but in BOffcanvas, it is being set to false.

![image](https://github.com/user-attachments/assets/3f458674-a4be-48fa-8fa4-9b7c96165479)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zh3fgt?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Seems to have been unintentionally fixed at some point 
![image](https://github.com/user-attachments/assets/f2677ff0-74e6-4ce9-96d7-068819b60f79)
Both offcanvases render in the same spot (in place)
