### ISSUE TITLE
Are some specified props of <Toast> not working correctly?

### ISSUE THREAD

**Issue by kolj4** [bootstrap-vue-next/bootstrap-vue-next#2082]
The documentation specifies the no-auto-hide prop and the no-fade prop for <BToast> The no-auto-hide prop does not seem to exist and the no-fade prop exists, but it doesn't seem to impact the animation behavior of the Toast. Am I doing something wrong?

**Comment by VividLemon** [comment]
> no-auto-hide 

This prop didn't do anything that wasn't achievable through other means.

`<BToast v-model="trueRef">Foo</BToast>`

`const trueRef = ref(true)`

That should fix that issue
