### ISSUE TITLE
Tooltip/Popover closed when hovering out of the trigger onto the Tooltip/Popover

### ISSUE THREAD

**Issue by dword-design-honestly** [bootstrap-vue-next/bootstrap-vue-next#2086]
### Describe the bug

When hovering over a tooltip trigger, the tooltip is opened, but when hovering from there onto to tooltip to click something, it's closed. It should be possible to do that to click something inside the tooltip, e.g. a button or a link to more information.

### Reproduction

https://github.com/dword-design-honestly/demo-bootstrap-vue-next-tooltip-hover

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Hiws** [comment]
I believe that's what the `interactive` is used for.

**Comment by dword-design-honestly** [comment]
@Hiws Looks like it, thanks for the quick answer. I didn't see the prop conversion happening in BTooltip between interactive and noninteractive. The components need docs, but that's a different story. Closing.
