### ISSUE TITLE
BModals wrongly gets focus since version 0.24.2

### ISSUE THREAD

**Issue by tbl0605** [bootstrap-vue-next/bootstrap-vue-next#2095]
### Describe the bug

Hi,
I created this bug report so my original [comment ](https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2064#issuecomment-2242533050) doesn't get lost.

After fixing bug #2064, BModals can now get focus when tabbing their content.

Btw, why was the need to add `tabindex="0"` in [BModal.vue](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/e63c230318dd24334b9700dbe1b60fa1974fe6a2/packages/bootstrap-vue-next/src/components/BModal/BModal.vue#L24)?

Focus traps should work without it,no?
And the visual effect is pretty bad if you use `<b-modal centered />` for example:

![350905605-bdf39344-3cf0-4a3c-b3dc-3713f81439ec](https://github.com/user-attachments/assets/d7ba4e9a-f351-41ca-be41-0841f4d91c09)

I updated https://github.com/tbl0605/boostrap-vue-next-bug so you can see what I mean.

Thank you!

### Reproduction

https://github.com/tbl0605/boostrap-vue-next-bug

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Focus trap requires at least one tabable element which breaks when you dont have a footer. I cant think of a different way to fix the issue

**Comment by tbl0605** [comment]
Hi @VividLemon,
thank you for your answer!

But at least wouldn't it be better to move ` tabindex="0"`
from
`<div class="modal-dialog" :class="modalDialogClasses" tabindex="0">`
to
`<div v-if="lazyShowing" class="modal-content" :class="props.contentClass" tabindex="0">`
?

As I said earlier, it doesn't look very nice when using `<b-modal centered />`^^

**Comment by VividLemon** [comment]
If lazy isnt showing then it encounters the same issue

**Comment by tbl0605** [comment]
Hi @VividLemon,
thank you very much for your hard work to improve and make bootstrap-vue-next such a great framework :)
