### ISSUE TITLE
Add optional key field property to BTable and prevent row re-redering

### ISSUE THREAD

**Issue by danielvy** [bootstrap-vue-next/bootstrap-vue-next#2096]
### Clear and concise description of the problem

Currently `BTable` (via `BTableLite`) uses plain indexes as `key` for vue's `v-for` when rendering table rows.

In _BTableLite.vue_:
`<template v-for="(item, itemIndex) in props.items" :key="itemIndex">`

This causes all the rows to be re-rendered every time the table is sorted or filtered, which can also have ugly UI side effects (if row's content contains transitions, for example).

### Suggested solution

Consider adding ability to prevent re-rendering of unchanged rows when sorting. Add an optional property to `BTable`/`BTableLite` for key field name to be used as row key, table rows will use the item's value for that field as key. Fallback to item index if no key is provided (or use item hash as key).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tbl0605** [comment]
Bootstrap-vue had the [primary-key](https://bootstrap-vue.org/docs/components/table#table-render-and-transition-optimization) property to optimize and deduplicate rows rendering, it would be nice to reintroduce it ^^
