### ISSUE TITLE
HTML not rendering in toast

### ISSUE THREAD

**Issue by scottgrobinson** [bootstrap-vue-next/bootstrap-vue-next#2123]
### Describe the bug

Apologies - Unsure if bug or a feature request. HTML doesn't appear to render within the toast body, it brings the HTML out as a string.

Expectation there is that if HTML is included, it's rendered as HTML!

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-pzkwxb?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dwgray** [comment]
Take a look at using the [component property](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useToast.html#advanced-usage) - I think that will do what you want.

**Comment by scottgrobinson** [comment]
Thanks @dwgray - Appreciate your pointer, that's got me what I need :)

```
    var message = ["Switching to ", h("strong", source), " failed"];

    this.show?.({
        props: {
            title: 'Switching Update',
            variant: 'default',
            value: 2500
        },
        component: h(BToast, null, {default: () => message}),
    })
```
