### ISSUE TITLE
Accessibility not fully implemented for BButton

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#2133]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/button#accessibility

### Describe the missing feature

It doesn't look like we've implemented the keydown listeners on the button when the button is a href="#" link. We also set the role="button" in more conditions than BSV.

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by VividLemon** [comment]
Idrk why they do this but K
