### ISSUE TITLE
Rename useToast to useToastController

### ISSUE THREAD

**Issue by dword-design-honestly** [bootstrap-vue-next/bootstrap-vue-next#2155]
### Clear and concise description of the problem

When using the `useToast` composable, there is a bit of a naming conflict between the entity managing the toasts and the actual toast. So when I'm writing `const toast = useToast()`, it looks like a toast but it is actually the toast controller. Also, the naming is inconsistent with `useModalController`.

### Suggested solution

I think `useToastController` is more consistent because useToast doesn't actually return a toast but a controller that manages the toasts, similar to `useModalController`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
_I agree_ v0.25 expected

**Comment by dword-design-honestly** [comment]
@VividLemon Where is it I don't see it in the release PR?

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2251

**Comment by dword-design-honestly** [comment]
@VividLemon Why is it closed if the PR is not merged? 😋
