### ISSUE TITLE
BModal causes infinite loop with vue-compat

### ISSUE THREAD

**Issue by hackel** [bootstrap-vue-next/bootstrap-vue-next#2159]
### Describe the bug

When triggering a modal with the vBModal directive, the modal appears just fine, but then disappears and locks the browser in an infinite loop, gobbling up memory.  I haven't yet had any success in debugging this further.  Without using vue-compat, it works normally.

Is this project intended to be compatible with vue/compat?  I'm working on migrating from bootstrap-vue 2.x, and still have many compat issues to resolve.

Thanks for your hard work on this amazing project!

### Reproduction

https://stackblitz.com/edit/github-341juo?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
> Is this project intended to be compatible with vue/compat

No. It's really not possible to keep maintainability at this point
