### ISSUE TITLE
BFromCheckbox doesn't update if modelvalue is returned back to previous from event

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue-next/bootstrap-vue-next#2163]
Testing event's and noticed that checkbox has mark even after the event is prevented and modalvalue is returned to false.

## reproduction

https://stackblitz.com/edit/nuxt-starter-rgoc4e?file=app.vue

**Comment by VividLemon** [comment]
This is a duplicate of some other issued that I recall working on but scrapped my changes because I couldn't get it to work (I recall I was trying to fix the show.prevent for modals... I think offcanvas has that same TODO issue)

**Comment by xvaara** [comment]
resolved in #1821
