### ISSUE TITLE
Directive no longer working on wrapper button component

### ISSUE THREAD

**Issue by darthf1** [bootstrap-vue-next/bootstrap-vue-next#2164]
### Describe the bug

Since `0.24.10`, the `v-b-toggle` directive no longer works on a wrapper component, which (in this case) wraps the `b-button` component.

It works if you downgrade to `0.24.9`. It also works if you remove the line `defineProps<BButtonProps & { title?: string }>();` from `MyButton.vue`.

### Reproduction

https://stackblitz.com/edit/github-5mfqan-cgqxhl?file=src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by blasdfaa** [comment]
It will work like this
```vue
 <b-button v-bind="{...$props, ...$attrs}" :pressed="undefined"> 👈
    <template v-for="(_, name) in $slots" #[name]="scope">
      <slot :name v-bind="scope ?? {}" />
    </template>
  </b-button>
```
for some reason, `pressedValue` is at `...$props` is set to `false` for the first time, and after that `isToggle` becomes `true`

perhaps this is the reason
https://vuejs.org/api/sfc-script-setup.html#definemodel
<img width="695" alt="image" src="https://github.com/user-attachments/assets/3d89c459-04a0-4ae5-ace0-99cc21193739">

but for example, it will work like this
```vue
 <b-button>
    <template v-for="(_, name) in $slots" #[name]="scope">
      <slot :name v-bind="scope ?? {}" />
    </template>
  </b-button>
```

**Comment by xvaara** [comment]
@VividLemon should we remove pressed from BButtonProps, since it's not a defineModel? I don't like that now our props type doesn't include modelValue and other props that are defined with defineModel, but what other option we have? Go back to vueuse's definevmodel?

**Comment by xvaara** [comment]
the problem is `defineProps<BButtonProps>();` with `<b-button v-bind="{ ...$props, ...$attrs }">` the directive is just a symptom I think.

since pressed is a definemodel and defined in BButtonProps it get's compiled in twice I think, and one of them is missing default value and is boolean so vue is nice and friendly and sets it to false.

**Comment by VividLemon** [comment]
> since pressed is a definemodel and defined in BButtonProps it get's compiled in twice I think, and one of them is missing default value and is boolean so vue is nice and friendly and sets it to false.

This is false. The issue is strictly that no value was passed to the BButton component, meaning that it has become de-synchronized. In this case, you could either `defineProps<Omit<BButtonProps, 'pressed'>>()` or `withDefaults(defineProps<BButtonProps>(), {pressed: undefined})`. There is no way around it

**Comment by xvaara** [comment]
actually just adding `:pressed="false"` to b-button disables the directive. So pressed causes the element to work in a way that it changes the dom element, in the directive we run the handleUpdate, which removes the event listener and adds it back. so we loose the event... :)

**Comment by xvaara** [comment]
@VividLemon but shouldn't we remove the pressed from BButtonProps since it's defineModel? now it's twice in the builded code:
```
  __name: "BButton",
  props: /* @__PURE__ */ me({
    loading: { type: Boolean, default: !1 },
    loadingFill: { type: Boolean, default: !1 },
    loadingText: { default: "Loading..." },
    pill: { type: Boolean, default: !1 },
    pressed: { type: Boolean },
    size: { default: "md" },
    squared: { type: Boolean, default: !1 },
    tag: { default: "button" },
    type: { default: "button" },
    variant: { default: "secondary" },
    active: { type: Boolean, default: !1 },
    activeClass: { default: void 0 },
    disabled: { type: Boolean, default: void 0 },
    exactActiveClass: { default: void 0 },
    href: { default: void 0 },
    icon: { type: Boolean, default: !1 },
    noRel: { type: Boolean },
    opacity: { default: void 0 },
    opacityHover: { default: void 0 },
    rel: { default: void 0 },
    replace: { type: Boolean, default: void 0 },
    routerComponentName: { default: void 0 },
    routerTag: { default: void 0 },
    stretched: { type: Boolean, default: !1 },
    target: { default: void 0 },
    to: { default: void 0 },
    underlineOffset: { default: void 0 },
    underlineOffsetHover: { default: void 0 },
    underlineOpacity: { default: void 0 },
    underlineOpacityHover: { default: void 0 },
    underlineVariant: { default: null }
  }, {
    pressed: { type: Boolean, default: void 0 },
    pressedModifiers: {}
  }),
```

**Comment by VividLemon** [comment]
> @VividLemon but shouldn't we remove the pressed from BButtonProps since it's defineModel? now it's twice in the builded code:
> 
> ```
>   __name: "BButton",
>   props: /* @__PURE__ */ me({
>     loading: { type: Boolean, default: !1 },
>     loadingFill: { type: Boolean, default: !1 },
>     loadingText: { default: "Loading..." },
>     pill: { type: Boolean, default: !1 },
>     pressed: { type: Boolean },
>     size: { default: "md" },
>     squared: { type: Boolean, default: !1 },
>     tag: { default: "button" },
>     type: { default: "button" },
>     variant: { default: "secondary" },
>     active: { type: Boolean, default: !1 },
>     activeClass: { default: void 0 },
>     disabled: { type: Boolean, default: void 0 },
>     exactActiveClass: { default: void 0 },
>     href: { default: void 0 },
>     icon: { type: Boolean, default: !1 },
>     noRel: { type: Boolean },
>     opacity: { default: void 0 },
>     opacityHover: { default: void 0 },
>     rel: { default: void 0 },
>     replace: { type: Boolean, default: void 0 },
>     routerComponentName: { default: void 0 },
>     routerTag: { default: void 0 },
>     stretched: { type: Boolean, default: !1 },
>     target: { default: void 0 },
>     to: { default: void 0 },
>     underlineOffset: { default: void 0 },
>     underlineOffsetHover: { default: void 0 },
>     underlineOpacity: { default: void 0 },
>     underlineOpacityHover: { default: void 0 },
>     underlineVariant: { default: null }
>   }, {
>     pressed: { type: Boolean, default: void 0 },
>     pressedModifiers: {}
>   }),
> ```

https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2147/commits/1b54313f32c400caaedb31347ae16b473588034a
