### ISSUE TITLE
[BPagination] first-number has no effect with hide-goto-end-buttons set

### ISSUE THREAD

**Issue by darthf1** [bootstrap-vue-next/bootstrap-vue-next#2165]
### Describe the bug

Thanks for https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2148!

I noticed that `first-number` has no effect with `hide-goto-end-buttons`. I would like to hide the button to the last page, but show the button to the first page. In my recollection this used to work, before I noticed the issues with https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2107

### Reproduction

https://stackblitz.com/edit/github-bpwgvy?file=src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dwgray** [comment]
@darthf1 - I believe this will be fixed with #2171.

**Comment by darthf1** [comment]
> @darthf1 - I believe this will be fixed with #2171.

It does! Thanks.

https://stackblitz.com/edit/github-bpwgvy-8u1lgd?file=package.json
