### ISSUE TITLE
Question  - BCollapse Not Working 

### ISSUE THREAD

**Issue by Gajaluxsan** [bootstrap-vue-next/bootstrap-vue-next#2174]
i am using  BCollapse as  b-collapse  E.g.=>component('b-collapse', BCollapse) 
 and button like <b-button v-b-toggle="`${row.hourStart}-ins`" size="sm">{{ $t('InDuration')  }}</b-button>
it Not Working click button 
did not get any Error in console

- OS: [e.g. Windows 11, ]
- Package Version: ["vue": "^3.2.13",,"webpack": "^5.94.0","bootstrap-vue-next": "^0.24.10",]

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2173
