### ISSUE TITLE
Vue is complaining about a performance issue because BToast component is reactive 

### ISSUE THREAD

**Issue by thomaspaillot** [bootstrap-vue-next/bootstrap-vue-next#2178]
### Describe the bug

The newest version of Vue (3.5) is triggering a warning in console about a performance issue because BToast component is reactive:

> Vue received a Component that was made a reactive object. This can lead to unnecessary performance overhead and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`.
Component that was made reactive:  {__name: 'BToast'…

From what I can see, this is due to `toasts` being a `ref` in [toastPlugin.ts](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/0b666e6f7f9adfd494accf594ad818010469853c/packages/bootstrap-vue-next/src/plugins/toastPlugin.ts#L18). Can `toasts` be made a `shallowRef` or the component mark with `markRaw`? 

### Reproduction

https://stackblitz.com/edit/github-jqognj?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DidenkoDmytro** [comment]
The same problem with "useModalController". Similar error ...

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2176
