### ISSUE TITLE
vue-i18n error

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#2184]
Using vue-i18n version 9.14 or later this error occours: Property '$t' does not exist on xxxxxx

it seems something related to third party libs and vue 3.4.38+

have a look here: https://github.com/intlify/vue-i18n/pull/1919#issuecomment-2294946937

Since I have this error in my project I can't understand if BVNext is "involved"

**Comment by xvaara** [comment]
we don't use globals, so I don't think it's us.
