### ISSUE TITLE
Failed to resolve import BTab on v0.24.13

### ISSUE THREAD

**Issue by hackel** [bootstrap-vue-next/bootstrap-vue-next#2185]
### Describe the bug

After updating to v0.24.13, I'm unable to compile my project, getting the following error from Vite:
```
[vite]: Rollup failed to resolve import "bootstrap-vue-next/components/BTab" from "/var/www/html/resources/assets/vue/modules/Connections/Index/View.vue".
```

I'm using BootstrapVueNextResolver with unplugin-vue-components.  Even if I import BTab manually, I get the same error.

Edit: I reverted to 0.24.12 and it's working fine.  

### Reproduction

N/A

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DidenkoDmytro** [comment]
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/35c7d732-f7b7-4537-bef5-eac5a3dca662">

**Comment by DidenkoDmytro** [comment]
Wrong paths

<img width="909" alt="image" src="https://github.com/user-attachments/assets/dde74c93-3d94-4149-b379-80f6b94e4dc0">

**Comment by DidenkoDmytro** [comment]
And problem with BTable types

<img width="795" alt="image" src="https://github.com/user-attachments/assets/7ca7ed27-0a01-4cd3-bec4-6f8b0cc5d041">

**Comment by VividLemon** [comment]
> And problem with BTable types
> <img alt="image" width="795" src="https://private-user-images.githubusercontent.com/11676229/366755750-7ca7ed27-0a01-4cd3-bec4-6f8b0cc5d041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU5NjQsIm5iZiI6MTcyNjE1NTY2NCwicGF0aCI6Ii8xMTY3NjIyOS8zNjY3NTU3NTAtN2NhN2VkMjctMGEwMS00Y2QzLWJlYzQtNmY4YjBjYzVkMDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZTRlMzE3Y2I0NjE0MGQ1ZmY2Njk4Yzk5ZjdmYjU2MjYyOTM0ZGRiYTIzNzk0YzRmNGEzY2FiNDAzMTgxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-BNK2stbeX6SSijgA1yGm-qAKvzl5GtP32vsuy8MQlQ"> <img alt="image" width="612" src="https://private-user-images.githubusercontent.com/11676229/366756605-970cabc1-db83-48f2-b5c5-a1d68a293671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU5NjQsIm5iZiI6MTcyNjE1NTY2NCwicGF0aCI6Ii8xMTY3NjIyOS8zNjY3NTY2MDUtOTcwY2FiYzEtZGI4My00OGYyLWI1YzUtYTFkNjhhMjkzNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOWM2YTc2NjIwMjdiODc5MWQxNGIzYzJiZGNhODZmNmVlNWQzZjhiYTIwNDc1NzJhNTJiNDFmNDIxZTA5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pC2iRPvnpVOa76OMPSkUNaLI0EoJvpwSEwUrhUT880Q"> <img alt="image" width="482" src="https://private-user-images.githubusercontent.com/11676229/366756749-f828a3d7-fed9-45ba-b29c-8208c63559e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU5NjQsIm5iZiI6MTcyNjE1NTY2NCwicGF0aCI6Ii8xMTY3NjIyOS8zNjY3NTY3NDktZjgyOGEzZDctZmVkOS00NWJhLWIyOWMtODIwOGM2MzU1OWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOGNmNDNmMzM2N2Q2Zjk0MmJiYWViNmE0MmIzZmZkZjRmMjQ4OThjMmIwNDk1MzE3ZWQ2NTMxNTg1ZDYxMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lcaT4JwTr2XyJ62vtU8rRuLVluC1LbCxw-_bHAVCmC4"> <img alt="image" width="455" src="https://private-user-images.githubusercontent.com/11676229/366756940-6f5fec09-48e6-4861-92a1-d0648a0e4e36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU5NjQsIm5iZiI6MTcyNjE1NTY2NCwicGF0aCI6Ii8xMTY3NjIyOS8zNjY3NTY5NDAtNmY1ZmVjMDktNDhlNi00ODYxLTkyYTEtZDA2NDhhMGU0ZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjZlMGMxOWU0NjYwZTAyNDdlMTYzMjdlZTNkM2M4NGMzNGQyNWQzZWI1OGIwMzg3N2QxODI1ZGJjZTI5ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p_fF4XOQaY7lzN7xMEhfwPO0KGz_dGjwhym6pUBJIzw">

This is not an issue with the lib. 

The useTemplateRef can only infer types if the component is imported in the same file. If you're using unplugin-vue-components or (I suspect) global component registration, then it won't be able to automatically infer the type. You're probably best off manually typing, `const myCarousel = useTemplateRef<InstanceType<typeof BCarousel>>('myCarousel')` or manually importing the component. I suspect just `import type {BTable}` or whatnot is the best solution

Other than that though, the import has been fixed

**Comment by VividLemon** [comment]
Auto imported:
![image](https://github.com/user-attachments/assets/a9e25d90-daea-422d-bbb0-81dcee5084eb)
Doesn't work

Manual import 
![image](https://github.com/user-attachments/assets/1d3b3716-da1e-4c2a-a0f1-c80fbdbb07ac)
works

Manual type import
![image](https://github.com/user-attachments/assets/3541e31a-73d2-4ccc-8210-4034e9539f7d)
works

**Comment by DidenkoDmytro** [comment]
> > And problem with BTable types
> > <img alt="image" width="795" src="https://private-user-images.githubusercontent.com/11676229/366755750-7ca7ed27-0a01-4cd3-bec4-6f8b0cc5d041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU5NjQsIm5iZiI6MTcyNjE1NTY2NCwicGF0aCI6Ii8xMTY3NjIyOS8zNjY3NTU3NTAtN2NhN2VkMjctMGEwMS00Y2QzLWJlYzQtNmY4YjBjYzVkMDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZTRlMzE3Y2I0NjE0MGQ1ZmY2Njk4Yzk5ZjdmYjU2MjYyOTM0ZGRiYTIzNzk0YzRmNGEzY2FiNDAzMTgxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-BNK2stbeX6SSijgA1yGm-qAKvzl5GtP32vsuy8MQlQ"> <img alt="image" width="612" src="https://private-user-images.githubusercontent.com/11676229/366756605-970cabc1-db83-48f2-b5c5-a1d68a293671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU5NjQsIm5iZiI6MTcyNjE1NTY2NCwicGF0aCI6Ii8xMTY3NjIyOS8zNjY3NTY2MDUtOTcwY2FiYzEtZGI4My00OGYyLWI1YzUtYTFkNjhhMjkzNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOWM2YTc2NjIwMjdiODc5MWQxNGIzYzJiZGNhODZmNmVlNWQzZjhiYTIwNDc1NzJhNTJiNDFmNDIxZTA5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pC2iRPvnpVOa76OMPSkUNaLI0EoJvpwSEwUrhUT880Q"> <img alt="image" width="482" src="https://private-user-images.githubusercontent.com/11676229/366756749-f828a3d7-fed9-45ba-b29c-8208c63559e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU5NjQsIm5iZiI6MTcyNjE1NTY2NCwicGF0aCI6Ii8xMTY3NjIyOS8zNjY3NTY3NDktZjgyOGEzZDctZmVkOS00NWJhLWIyOWMtODIwOGM2MzU1OWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOGNmNDNmMzM2N2Q2Zjk0MmJiYWViNmE0MmIzZmZkZjRmMjQ4OThjMmIwNDk1MzE3ZWQ2NTMxNTg1ZDYxMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lcaT4JwTr2XyJ62vtU8rRuLVluC1LbCxw-_bHAVCmC4"> <img alt="image" width="455" src="https://private-user-images.githubusercontent.com/11676229/366756940-6f5fec09-48e6-4861-92a1-d0648a0e4e36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU5NjQsIm5iZiI6MTcyNjE1NTY2NCwicGF0aCI6Ii8xMTY3NjIyOS8zNjY3NTY5NDAtNmY1ZmVjMDktNDhlNi00ODYxLTkyYTEtZDA2NDhhMGU0ZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjZlMGMxOWU0NjYwZTAyNDdlMTYzMjdlZTNkM2M4NGMzNGQyNWQzZWI1OGIwMzg3N2QxODI1ZGJjZTI5ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p_fF4XOQaY7lzN7xMEhfwPO0KGz_dGjwhym6pUBJIzw">
> 
> This is not an issue with the lib.
> 
> The useTemplateRef can only infer types if the component is imported in the same file. If you're using unplugin-vue-components or (I suspect) global component registration, then it won't be able to automatically infer the type. You're probably best off manually typing, `const myCarousel = useTemplateRef<InstanceType<typeof BCarousel>>('myCarousel')` or manually importing the component. I suspect just `import type {BTable}` or whatnot is the best solution
> 
> Other than that though, the import has been fixed

Then how do you explain that everything works in version 0.24.12? The types of all components are defined without their imports.

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/da5886fb-4b33-471e-a0e0-d05061dc283b">
