### ISSUE TITLE
BModal: calculated right padding in body misssing

### ISSUE THREAD

**Issue by noehmeier** [bootstrap-vue-next/bootstrap-vue-next#2187]
### Describe the bug

The BModal component appears to be missing a feature present in the original Bootstrap modal logic: a calculated right padding when a scrollbar is shown. This omission leads to an undesirable jumping effect when the modal is opened and closed.

The padding width varies by browser:
- Firefox and Chrome: `17px`
- Edge: `15px`

To illustrate the difference (Firefox):

1. Bootstrap original modal:
   ```html
   <body style="overflow: hidden; padding-right: 17px;" class="modal-open">
   ```

2. BModal:
   ```html
   <body style="overflow: hidden;" class="modal-open">
   ```

You can observe this discrepancy by comparing the button/modal combination examples on:
- Bootstrap: https://getbootstrap.com/docs/5.3/components/modal/#live-demo
- Bootstrap Vue Next: https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal

Could you please implement this original functionality in BModal to ensure consistent behavior?

Thank you for your attention to this matter.

### Reproduction

https://stackblitz.com/edit/github-mvlpyk?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
I think this was fixed in #2211
