### ISSUE TITLE
Failed to resolve component v0.24.13

### ISSUE THREAD

**Issue by 082137** [bootstrap-vue-next/bootstrap-vue-next#2192]
### Describe the bug

It seems that there was a path error in version 0.24.13, and I noticed that you made changes to `BTab` in version 0.24.14 to address this issue. (https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2185)

The same issue is occurring not only with the `BTab` component but also with `BCloseButton` and `BTransition`.

Thank you.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zbf8aj?file=src%2Fpages%2Findex.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
BTransition was only meant to be used internally, and is deprecated in favor of just using a internal composable
