### ISSUE TITLE
Modal issues with 0.24.15

### ISSUE THREAD

**Issue by ptdev** [bootstrap-vue-next/bootstrap-vue-next#2195]
### Describe the bug

Hi,

When using the Modal component with the latest update (v0.24.15) on Nuxt, we get some errors.

If we place the modal component inside ClientOnly tags, we get the following console error (even though the modal still works):

```js
[Vue warn]: injection "Symbol(bvn::modalManagerPlugin)" not found. (...)
```

If we try to use the modal without using ClientOnly then we get the same error as above as well as many hydration mismatch errors. And on this case, the modal does not work and gives the following errors when trying to open.

```js
[Vue warn]: Unhandled error during execution of watcher callback 

(...)

Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
```

The reproduction link includes demos for both cases described above.

Cheers

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mou6rk?file=pages%2Findex.vue

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oliver681** [comment]
I get the same error using the `v-b-modal` directive as in the example from the documentation:

```js
<BButton v-b-modal.modal-scrollable>Launch scrolling modal</BButton>

<BModal id="modal-scrollable" scrollable title="Scrollable Content">
  <p class="my-4" v-for="i in 20" :key="i">
    Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in,
    egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
  </p>
</BModal>
  ```

**Comment by rimonmath** [comment]
I am getting same issue while trying to add v-model support:
[Vue warn]: injection "Symbol(bvn::modalManagerPlugin)" not found.

**Comment by ptdev** [comment]
Hello again,

Updating Nuxt from v3.13.1 to v3.13.2 has apparently fixed all issues that I reported on the initial post.

See here a forked version of the reproduction above with Nuxt updated:

https://stackblitz.com/edit/nuxt-starter-obx8cv?file=package.json

Note that there are no longer injection or hydration issues.

So, this was probably not actually an issue with this package or maybe some combination of versions from other packages that caused it.

Either way, closing the ticket as it appears to be solved.

Cheers
