### ISSUE TITLE
Sticky header functionality not working

### ISSUE THREAD

**Issue by oliver681** [bootstrap-vue-next/bootstrap-vue-next#2199]
### Describe the bug

There is the closed issue #1824, stating that the sticky header functionality should work, but that doesn't seem to be the case in the current version (0.24.16).

I tested the following assignments to the `sticky-header` prop:

`sticky-header="true"`
`sticky-header="100"`
`sticky-header="100px"`
`sticky-header="100%"`

I couldn't observe any effect with all of these.

### Reproduction

https://stackblitz.com/edit/github-sylkhu-6f7ffl?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
`sticky-header="true"` is invalid -- it should be `:sticky-header="true"`
The stackblitz is using a very old version
```json
"node_modules/bootstrap-vue-next": {
      "version": "0.16.6",
      "resolved": "https://registry.npmjs.org/bootstrap-vue-next/-/bootstrap-vue-next-0.16.6.tgz",
      "integrity": "sha512-CDjq3KgIOALJO/Zvmcgxqavv1NznFROUl7yWHAmp4T4R8IRJLfyMj1zizjw2OzCvQ+uJ9PZ28T1Cx7xq8+m2xg==",
      "dependencies": {
        "@floating-ui/vue": "^1.0.6",
        "@vueuse/core": "^10.7.2"
      },
      "funding": {
        "type": "opencollective",
        "url": "https://opencollective.com/bootstrap-vue-next"
      },
      "peerDependencies": {
        "vue": "^3.4.18"
      }
    },
```
Lastly, `sticky-header="100%"` doesn't make logical sense. It is sticky, but doesn't work because it takes up the full length of the page

**Comment by oliver681** [comment]
Oh, sorry. My mistake. I didn't verify the version and was assuming stackblitz would use the most current version automatically when ` "bootstrap-vue-next": "*"` is specified.
