### ISSUE TITLE
New Vue warning in version 0.24.13

### ISSUE THREAD

**Issue by ErikVerheul** [bootstrap-vue-next/bootstrap-vue-next#2201]
### Describe the bug

Since version 0.24.13 i get this console message in both Firefox and Chromium when i run my Vue3 app:
[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

I can not find any wrongdoing in my code. Can it be a change in the bootstrap-vue-next code?

### Reproduction

https://github.com/ErikVerheul/onebacklog

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
which file gives that error? You might be passing a ref of a ref or something like that, or watching route object (just based on 1min of googling). 

Please provide a reproduction that doesn't require an installation of other software and configurations.

**Comment by ErikVerheul** [comment]
Sorry for the inconvenience. I should have put this as question. For what i could see in the browser debugger the problem has a relation with the use of JSON.stringify. But not in my code. I try to recreate the bug with stackblitz but without success until now.

**Comment by xvaara** [comment]
only json.stringify are in table (when sorting/filterin) and tooltip/popovet directive. Maybe the way you are using them?

**Comment by ErikVerheul** [comment]
I pinpointed the cause of the warning to a change in git: **fix directives on element update during interaction (#2170)** at September 5 by Jukka. My debugger points at line 22  **el.$__binding = JSON.stringify(binding)**  in the file BPopover.ts and to line 23, with the same line content, in BTooltip.ts. 
I am still trying to recreate the bug but without success until now.

**Comment by xvaara** [comment]
@ErikVerheul could you try with the pull request if that fixes your warnings?

change the version in package.json to https://pkg.pr.new/bootstrap-vue-next/bootstrap-vue-next@2208 and run pnpm/npm/yarn i

**Comment by ErikVerheul** [comment]
YES! Problem solved, the warning is gone. I had to install pnpm and to run 'pnpm i'. However i got a totally unrelated error: 
`Uncaught TypeError: this.emitter is undefined
    update 						quill.js:4401
    quill @vueup_vue-quill.js:7147
    ScrollBlot2 quill.js:7190
    Scroll2 quill.js:4227
    create quill.js:184`
I look forward to your next release with your fix. Meanwhile i undo the changes pnpm introduced and use npm. I expect the new error to disappear.

By the way, i thank you for your effort to create this great peace of software.

**Comment by xvaara** [comment]
I'll release a new one later today
