### ISSUE TITLE
Styling of BTr in thead-top slot

### ISSUE THREAD

**Issue by oliver681** [bootstrap-vue-next/bootstrap-vue-next#2207]
I am trying to style a table header top row with a custom color.

In `bootstrap-vue`, I used inline styles and it worked fine:

```vue
<template #thead-top>
      <b-tr style="background-color: #ed7d31; color: white; font-weight: bold;">
            <b-td colspan="4">
                    Differenz:
            </b-td>
      </b-tr>
</template>
```

With `bootstrap-vue-next`, the background-color and color seem to be overridden (adding `!important` doesn't change the behaviour, too). Does someone know the reason for this and how to style it properly with `bootstrap-vue-next`?

Example: https://stackblitz.com/edit/github-sylkhu-6f7ffl?file=src%2FApp.vue

**Comment by xvaara** [comment]
bootstrap 5 uses variables, so easiest way is to change that style prop to:
```
          --bs-table-bg: #ed7d31;
          --bs-table-color: white; !important;
```
