### ISSUE TITLE
[Vue warn]: injection "Symbol(bvn::toastPlugin)" not found. 

### ISSUE THREAD

**Issue by adamwallillinois** [bootstrap-vue-next/bootstrap-vue-next#2209]
### Describe the bug

I'm not sure if this is an issue with Nuxt or Vue, but when updating my project with the latest versions of nuxt, vue, and bootstrap-vue-next, toasts that are created with the `useToast` composable are not appearing anymore with the following warning in the console: 

```
[Vue warn]: injection "Symbol(bvn::toastPlugin)" not found. 
  at <App key=4 > 
  at <NuxtRoot>
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-21x7kb?file=app.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by se-be** [comment]
I do get the same with useModal and useModalController as well with a similar set up.

**Comment by VividLemon** [comment]
I can't really figure it out, hopefully https://github.com/nuxt/nuxt/issues/29081 can help

**Comment by xvaara** [comment]
@VividLemon It seems your refactor caused vite to split the bundles differently. Now there is a chunk in vite cache fir useToast which basically is: (removed all the other keys)
```js
// node_modules/bootstrap-vue-next/dist/src/composables/useToast/index.mjs
import { inject } from "/_nuxt/node_modules/vue/dist/vue.runtime.esm-bundler.js?v=e055a883";

// node_modules/bootstrap-vue-next/dist/keys-CLEaYsGj.mjs
// snip
var toastPluginKey = Symbol("bvn::toastPlugin");
var modalControllerPluginKey = Symbol("bvn::modalControllerPlugin");
var tooltipPluginKey = Symbol("bvn::toastPlugin");
var popoverPluginKey = Symbol("bvn::toastPlugin");

// node_modules/bootstrap-vue-next/dist/src/composables/useToast/index.mjs
var useToast = () => ({ ...inject(toastPluginKey) });

export {
  carouselInjectionKey,
 // snip
  toastPluginKey,
  modalControllerPluginKey,
  tooltipPluginKey,
  popoverPluginKey,
  useToast
};
//# sourceMappingURL=chunk-Z6EX2N6T.js.map

```
So it does not import from the same keys-HASH.mjs file.

**Comment by xvaara** [comment]
@VividLemon I think nuxt module.ts imports the composables "wrong" but I don't know what the right path is.

**Comment by VividLemon** [comment]
> @VividLemon I think nuxt module.ts imports the composables "wrong" but I don't know what the right path is.
> 
> https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/nuxt/src/module.ts#L81-L90

This would throw a different error



> @VividLemon It seems your refactor caused vite to split the composables differently. Now there is a chunk in vite cache (/_nuxt/node_modules/.cache/vite/client/deps/chunk-Z6EX2N6T.js?v=e055a883) for useToast which basically is: (removed all the other keys)
> 
> ```js
> // node_modules/bootstrap-vue-next/dist/src/composables/useToast/index.mjs
> import { inject } from "/_nuxt/node_modules/vue/dist/vue.runtime.esm-bundler.js?v=e055a883";
> 
> // node_modules/bootstrap-vue-next/dist/keys-CLEaYsGj.mjs
> // snip
> var toastPluginKey = Symbol("bvn::toastPlugin");
> var modalControllerPluginKey = Symbol("bvn::modalControllerPlugin");
> var tooltipPluginKey = Symbol("bvn::toastPlugin");
> var popoverPluginKey = Symbol("bvn::toastPlugin");
> 
> // node_modules/bootstrap-vue-next/dist/src/composables/useToast/index.mjs
> var useToast = () => ({ ...inject(toastPluginKey) });
> 
> export {
>   carouselInjectionKey,
>  // snip
>   toastPluginKey,
>   modalControllerPluginKey,
>   tooltipPluginKey,
>   popoverPluginKey,
>   useToast
> };
> //# sourceMappingURL=chunk-Z6EX2N6T.js.map
> ```
> 
> So it does not import from the same /_nuxt/node_modules/bootstrap-vue-next/dist/keys-CLEaYsGj.mjs file as the plugins and components.

This is likely the cause. The symbol is likely being initialized as something else due to the way vite is bundling and caching deps.

To solve this, I just made them static strings.

**Comment by xvaara** [comment]
@VividLemon well it would be nice if nuxt also included the composables from the same package, so that vite in nuxt doesn't need to package them again in chunks.

**Comment by VividLemon** [comment]
What

**Comment by xvaara** [comment]
other than runtime compusables are imported from "package" ie. /_nuxt/node_modules/bootstrap-vue-next/dist/useDefaults-BYx9NNxn.mjs?v=d0a5396f

runtime composables are build to chunks: /_nuxt/node_modules/.cache/vite/client/deps/chunk-F3OKO2SS.js?v=d0a5396f not from the "package", So I think this is an issue with the way composables are imported, or how vite is configured. Not with the symbols.
