### ISSUE TITLE
Performance dropped when use many tooltip directives or popovers

### ISSUE THREAD

**Issue by hairit** [bootstrap-vue-next/bootstrap-vue-next#2232]
### Describe the bug

I have the listing table that use tooltip directives and popovers for many columns as I need to display texts fully when hovering them.

Everything is good until I change page size to 100 records/page then the performance dropped (It takes a while after typing is finished to display text on input)

I opened Performance tab for investigating, recorded then changed page size to 100 and noted that there are bulk of Activities relevant to "Timer" and they come from bootstrap-vue-next. are they effecting that performance issue?

![image](https://github.com/user-attachments/assets/fd0b0b62-b973-4a52-9ef2-0ff56b8b9f25)

Thanks!!

### Reproduction

none

### Used Package Manager

pnpm

### Validations

- [ ] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [ ] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
@hairit Can you test if it's also when you use the component? The directive is kinda hack and not very performant.

**Comment by xvaara** [comment]
Notes for myself: the useMouseInElement are installing event listeners with useMouse to the whole page, and then using that to parse if mouse is in the element. This causes a lot of unnecessary calculations, getClientRect checks and updating of variables. We need this check on in one if clause, so I think we need to hoist this to a function.

**Comment by xvaara** [comment]
@VividLemon I was just testing creating a "PopoverOrchestrator" that creates 10 popovers and cycles their target/content based on @pointerover event. Works great when having thousands of popovers.

 Maybe using that with directives (require user to add that component to the root/layout/parent) we could remove the current hacky way of creating a vue-app for each popover directive? But that would require the component to be present... or maybe leave the old way as a backup in there?

**Comment by VividLemon** [comment]
It may be beneficial to remove the dorective and use the composable i started building. The only issue is i dont know how to use popovers

**Comment by xvaara** [comment]
@VividLemon I don't think people will like if we remove them. I'd like to remove them also 😄 

the orgestrator was just a test component:
```vue
<template>
  <div class="d-flex flex-wrap">
    <span
      v-for="i in 2000"
      :id="'b' + i"
      :key="i"
      class="m-1 p-2 border rounded"
      @mouseenter="showPopover($event, i)"
    >
      button {{ i }}
    </span>
  </div>
  <BPopover
    v-for="(p, index) in popovers"
    :key="index"
    v-model="p.show"
    tooltip
    non-interactive
    :delay="{show: 0, hide: 0}"
    :target="p.target"
    :title="p.msg"
  />
</template>
<script setup lang="ts">
import {ref} from 'vue'
const popovers = ref<{id: number; show: boolean; target: EventTarget; msg: string}[]>([])
const amount = 8

let popoversCount = 0
let loop = 0

function showPopover(e: MouseEvent, i: number) {
  if (!e.target) return
  const index = popovers.value.findIndex((p) => p.target === e.target)
  if (index > -1) {
    popovers.value[index].show = true
    return
  }
  if (popovers.value.length < amount) {
    popovers.value.push({id: popoversCount++, show: true, target: e.target, msg: `title ${i}`})
  } else {
    const old = popovers.value[loop++]
    loop = loop % amount
    if (old) {
      old.show = true
      old.target = e.target
      old.msg = `title ${i}`
    } else {
      // console.log('no old')
      popovers.value.push({id: popoversCount++, show: true, target: e.target, msg: `title ${i}`})
    }
  }
}
</script>
```
