### ISSUE TITLE
Overflowing modal puts backdrop over scrollbar

### ISSUE THREAD

**Issue by amokrunnr** [bootstrap-vue-next/bootstrap-vue-next#2236]
### Describe the bug

The overflowing modal puts the backdrop overlay above the y scrollbar. Here are snapshots from the docs sites of both bootstrap-vue and bootstrap-vue-next for comparison.

bootstrap vue:
![image](https://github.com/user-attachments/assets/2534840b-0cb1-4365-bd4a-0e1c82f14b47)

bootstrap vue next:
![image](https://github.com/user-attachments/assets/2a8802f0-7496-4653-830c-a193fa0e1692)

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
The backdrop div should be out of the modal div. I'll put this in my other modal fixes.
