### ISSUE TITLE
Missed BTable event 

### ISSUE THREAD

**Issue by DidenkoDmytro** [bootstrap-vue-next/bootstrap-vue-next#2238]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/table

### Describe the missing feature

Missed event "row-contextmenu". We have used it often in our projects.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/55cf059e-4d10-4510-b44f-fafb0b265ba0">

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by VividLemon** [comment]
Won't be able to merge until I finish https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2240#issuecomment-2381455076
