### ISSUE TITLE
Type checks on complex props

### ISSUE THREAD

**Issue by ianef** [bootstrap-vue-next/bootstrap-vue-next#2242]
### Clear and concise description of the problem

I am in the process of migrating from BootstrapVue to BootstrapVueNext and I've ended up spending a lot of time debugging JS crashes where prop changes from BV to BVN are significant.

A particularly good example of this is the sortBy prop on BTable. This used to be a string but is now an array of objects. It took a fair bit of debugging to track down where the crash was happening, then cross referencing props to determine what should be required.

### Suggested solution

Currently there is no migration guide for BTable, which would have helped, but regardless of this I feel it would be better to type check props in the watch methods when we are dealing with none scalar properties. Issuing a warning there if the type of the property is incorrect.

In this particular example the code was attempting to use the Array.find method on a string, an instant failure, which then prevented the document from loading correctly.

This would help enormously when people are migrating code, as a warning would be seen in dev tools, and the code would still run hopefully to completion. It is far better to ignore an incorrect parameter than to crash and prevent further loading.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by VividLemon** [comment]
This is too much overhead and _us_ watching props isn't our responsibility. 

You'd be better off assisting with writing the migration guide
