### ISSUE TITLE
v-model trim regression

### ISSUE THREAD

**Issue by jacobg** [bootstrap-vue-next/bootstrap-vue-next#2253]
### Describe the bug

In bootstrap-vue-next 0.24.2, v-model trim works as expected, i.e., can type multiple words like "abc def ghi" and trimming only happens at the end.  Here is a demo:
https://stackblitz.com/edit/github-jwsdlr-egmstb

In bootstrap-vue-next 0.24.3, it no longer works as expected, after typing "abc" then <space> it immediately trims before being able to type "def". If 2 double spaces are entered then it will add the space and then you can type "def". See this demo:
https://stackblitz.com/edit/github-jwsdlr-ayhxxc
This bug persists even to the latest version now 0.24.23.

### Reproduction

https://stackblitz.com/edit/github-jwsdlr-ayhxxc

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
seems that this was introduces in #2066 but don't seem why.

@VividLemon @dwgray the trim is weird since it modifies the value in the computed. Vue itself just modifies the dom element on change event: https://github.com/vuejs/core/blob/main/packages/runtime-dom/src/directives/vModel.ts#L69-L73

Is there a reason why we do this, since vue already does this for us?

**Comment by dwgray** [comment]
> seems that this was introduces in #2066 but don't seem why it started to act up then, since it was just moving code around.
> 
> @VividLemon @dwgray the trim is weird since it modifies the value in the computed. Vue itself just modifies the dom element on change event: https://github.com/vuejs/core/blob/main/packages/runtime-dom/src/directives/vModel.ts#L69-L73
> 
> Is there a reason why we do this, since vue already does this for us? Seems to work almost fine if I comment out the `set: (v) => normalizeInput(v, modelModifiers)` line.

I don't have the history on this, but I did rip out the props that mirrored the model modifiers in #2066 under the assumption that the underlying vue.js modifiers would act correctly and missed the fact that we're still overriding its behavior. I would lean towards seeing if we can let vue.js handle these modifiers and layer our behavior on top of that. What doesn't work if you comment out the normalizeInput line?

**Comment by VividLemon** [comment]
> I would lean towards seeing if we can let vue.js handle these modifiers

It would be great to let vue take over. But sadly there isnt any way i know of to pass dynamic model modifiers

Yes its because it works off the change event. But i was having some issue when i moved it to onchange a few days ago. I forget

**Comment by xvaara** [comment]
>  What doesn't work if you comment out the normalizeInput line?

It doesn't trim the form value, the modelValue is trimmed by vue when emitted from the component.

**Comment by VividLemon** [comment]
Yes, that was the issue, when i used the change event it didnt change the forms value, but the modelvalue was mostly correct.
