### ISSUE TITLE
Regression: BModals no longer respect the "no-close-on-backdrop" attribute since version 0.25

### ISSUE THREAD

**Issue by tbl0605** [bootstrap-vue-next/bootstrap-vue-next#2260]
### Describe the bug

Hi,
since version 0.25, when you use `<BModal no-close-on-backdrop />` the modal closes when clicking on the background (outside the b-modal).

### Reproduction
1. Go to https://stackblitz.com/edit/github-rzxbjv-m6jegu
2. Click on the "Open Modal" button
3. Click with the mouse on the background (outside the b-modal), the b-modal will close (but it shouldn't !)

### Reproduction

https://stackblitz.com/edit/github-rzxbjv-m6jegu

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tbl0605** [comment]
Btw, and this is probably a separate issue, but I find that the gray background is now "flashing" when it appears with the popup, as if it was drawn with 2 different gray tones. It seems that the "no-fade" attribute no longer works the same way as before.

**Comment by VividLemon** [comment]
@xvaara https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2250/commits/4c2c3badefefbe21989b1f32bf97638b83537917#diff-cd72a1f9c87225b810f18bdb37eebfea076561a2f038495c8aa295fbe915c584R23

**Comment by xvaara** [comment]
I'll take a look tomorrow.

**Comment by tbl0605** [comment]
Thank you for the fix :)
