### ISSUE TITLE
Easy use of themes from Bootswatch.com?

### ISSUE THREAD

**Issue by TheGeekPharaoh** [bootstrap-vue-next/bootstrap-vue-next#2266]
I've installed and make use of bootstrap-vue-next in my Vue 3 application.  I'd like to leverage one of the themes/color schemes from https://bootswatch.com.  Is there a recommended way to incorporate them when using bootstrap-vue-next?  Is it just a matter of including the _variables.scss and _bootswatch.scss files?  Or is there something else I need to do with respect to bootstrap-vue-next?

**Comment by VividLemon** [comment]
We dont control css incorporation. If the classes are named the same, you can import them however you want.

We only add our own css for some specific cases. Which wouldnt be effected, either negative or positive

**Comment by VividLemon** [comment]
```ts
// main.js/ts
import 'bootstrap/dist/css/bootstrap.css'
```
Replacing that line should be everything you need to do
