### ISSUE TITLE
BModal backdrop doesn't show when component is shown using v-if

### ISSUE THREAD

**Issue by IGx89** [bootstrap-vue-next/bootstrap-vue-next#2268]
### Describe the bug

If a BModal is initially hidden using v-if and then later shown, the backdrop isn't visible. This is a regression in v0.25.0, introduced in #2250.

Fix is simple, will submit a PR shortly!

### Reproduction

https://stackblitz.com/edit/github-2ugohm?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nicofrand** [comment]
The issue seems to also appear with v0.24.23 somehow. And if I am not mistaken, the reproduction link (https://stackblitz.com/edit/github-2ugohm?issueRepo=bootstrap-vue-next/bootstrap-vue-next&issueNumber=2268) uses v0.24.23 in the package-lock.json ?

**Comment by IGx89** [comment]
That Stackblitz, running on 0.24.23, properly shows the gray background so it would seem to show that 0.24.23 does not have this bug. This bug is fixed in the latest 0.25.x versions, hence why it's closed now.

**Comment by nicofrand** [comment]
It does not show anything on my side…

![image](https://github.com/user-attachments/assets/ad2856b2-c035-4f3b-b974-3eb1202dbdd2)


Maybe 0.24.23 just needs 4c2c3badefefbe21989b1f32bf97638b83537917 too? 

Sorry to discuss a closed ticket, but I thought the 0.24.23 was missing this fix, or some others (previous fix + this one)…

**Comment by IGx89** [comment]
That's a different issue if so -- this issue the modal still was shown, it was just the gray background that was missing. 0.24.x has other bugs that would prevent the modal itself from showing in certain situations though, such as #2203. Definitely want to be on 0.25.x if you're using modals.
