### ISSUE TITLE
BTooltip directive not updating content when title changes

### ISSUE THREAD

**Issue by IGx89** [bootstrap-vue-next/bootstrap-vue-next#2273]
### Describe the bug

Given the following BTooltip directive usage:

```vue
<div v-b-tooltip :title="msg">Hover over me</div>
```

If I change the value of msg after the tooltip is initially rendered, the tooltip still contains the old value.

This is a regression introduced in v0.24.13 by #2170. That PR made changes to the `updated` lifecycle method to not update the tooltip's content if it's unchanged. That logic is only checking the binding however and not the title attribute/result of the resolveContent call.

### Reproduction

https://stackblitz.com/edit/github-d5nonv?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
Is this really a problem? I'd rather remove the option to use title="foo" than getting into trying to get this to work. We'd need to add a mutation observer to the element to watch the change, or find some hacky way to get to the vue prop. 

Remember, even vue docs recomend against using directives. They are only ment to manipulate the dom, everything else is quite complex. They don't work great on custom componenents and fail completely on multiroot components.

I'd just note in the docs that this isn't reactive, use the other 9 different ways to do Popover/Tooltip that are reactive.

@VividLemon thoughts?

**Comment by VividLemon** [comment]
Id rather just have the composable built out and remove the directive. Seems to be more harm than good.

**Comment by xvaara** [comment]
I feel like people like the simplicity off directives, but are not aware of the limitations. I'll try to find time to do the documentation for them.

**Comment by IGx89** [comment]
Thanks for your replies! Adding a note to the docs at a minimum would be good so others are aware of this new limitation, otherwise you might get more bug reports in the future.

**Comment by VividLemon** [comment]
A mutation observe is also probably fine if directives want to be preserved
