### ISSUE TITLE
`useSafeScrollLock` document is not defined SSR

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#2286]
### Describe the bug

![image](https://github.com/user-attachments/assets/9cdba8d1-053b-4513-b464-2b30e404cf7e)
This change assumes that document is defined, which it wont be in an SSR env

### Reproduction

Use modal in SSR

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
@xvaara 
![image](https://github.com/user-attachments/assets/f2d21280-2d59-4d00-bc90-1cf56ab761d3)
You may want to double check this creation of a var outside a composable. It may be shared in an SSR env (similar to 
```ts
const foo = ref(0)
export const useSomething () => { return { foo } }
```
is shared
)

**Comment by xvaara** [comment]
I'm also quite sure that those variables aren't ever written into in a ssr context. Or is there some way of opening a modal/offcanvas in ssr? Maybe in the next commit in the show/hide PR I'm working on, but even in that I think it won't really open it in ssr... I'll have to test somehow, before creating anything complex to solve this.

**Comment by VividLemon** [comment]
If you recall usages of createSharedComposable were replaced with injected plugins. I renamed the defaultsPlugin to bootstrapPlugin. Any required injected state can use that plugin, any non required should be its own plugin.

Plugins are the best, most consistent, way to have a global state. Otherwise SSR leaks could occur

**Comment by VividLemon** [comment]
I saw the error in the docs build

**Comment by VividLemon** [comment]
> So it should accept undefined as parameter, so what error are you getting

The issue is that `console.log(foo?.bar)` -- optional chaining doesn't work on non-defined variables. In a context like this, `document` isn't `defined` rather than being `undefined`. Js weirdness
