### ISSUE TITLE
RFC: lazy prop in show/hide components

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue-next/bootstrap-vue-next#2292]
We have a few places that have lazy prop already, but they don't work the same way.

Modal mounts the children on the first show an keep them mounted.
Dropdown mounts on the show and unmounts on the hide.

Do we want to keep the dropdown way? Do we want to give a prop like lazyPersistance for the first one? What would be the correct way for all the components to work in the same way?

@VividLemon @dwgray thoughts?

**Comment by VividLemon** [comment]
The best way is to have it be the dropdown way, but the dropdown shouldn't unmount on hide

('lazyOnce' always is preferred. If you render the component, there is no reason to un-render the component)

**Comment by xvaara** [comment]
in #1821 I added lazy (to load on show) and persistent to not unmount on hide. In lazy = false & persistent = true, then the children are mounted the whole time.

**Comment by xvaara** [comment]
I changed the props to lazy and unmountLazy. By itself the unmountLazy doens't do anything, but with lazy it unmounts the children on hide.

**Comment by VividLemon** [comment]
Related: https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1685

**Comment by xvaara** [comment]
@VividLemon should we have some components (BModal?) that have lazy behaviour as default and no-lazy as prop? I'm fine with everything being non-lazy by default.
