### ISSUE TITLE
BFormGroup refactor dom changes causing layout issue

### ISSUE THREAD

**Issue by jacobg** [bootstrap-vue-next/bootstrap-vue-next#2312]
### Describe the bug

There was a major refactor to BFormGroup affecting dom structure:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/07daa80aef41df5b8e31578c2bc695823c2f6510#diff-b574f4386f94d3b497d215b3aff561daae615a8e86e6d36178a930439805438d

The label is not displaying. Actually it seems the prop name was changed from `labelCols` to `labelCol` (without s).

Also, when using vue-multiselect field inside this form group it causes it to wrap lines which did not happen previously. It looks like the wrapping div and use of flexbox has changed. See MRE links below of last version it worked, and now not working.

@VividLemon 

Thanks.

### Reproduction

Broken in version 0.25.10:
https://stackblitz.com/edit/github-jwsdlr-cu5ssa?file=package.json,src%2Fcomponents%2FComp.vue

Last working in version 0.25.6:
https://stackblitz.com/edit/github-jwsdlr-gwlnnd?file=package.json,src%2Fcomponents%2FComp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hackel** [comment]
I just ran into this issue as well.  The previous version of BFormGroup was closer to what bootstrap-vue did, and worked perfectly in my layout.  With 0.25.7+ it is collapsing the select within my BFormGroup down to just an arrow.

I don't know if this is helpful, but here is the difference in HTML:
Original:
```html
<fieldset>
    <div class="row d-flex flex-wrap">
        <legend
            class="col-auto col-form-label bv-no-focus-ring col-form-label"
            tabindex="-1"
        >Steamship Line
        </legend>
        <div class="col">
            <div class="d-flex align-items-center">
                <select class="form-select">
                    <option value="1">Not sure at this time</option>
                </select>
            </div><!----><!----><!---->
        </div>
    </div>
</fieldset>
```
New:
```html
<fieldset class="form-group"><!----><!---->
    <div class="col-auto">
        <legend
            class="col-form-label bv-no-focus-ring col-form-label"
            tabindex="-1"
        >Steamship Line
        </legend>
    </div>
    <div class="d-flex align-items-center">
        <select class="form-select">
            <option value="1">Not sure at this time</option>
        </select>
    </div><!----><!----><!---->
</fieldset>
```

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2316#issuecomment-2450938419

**Comment by loicduong** [comment]
@jacobg label-cols is still working normally. You can't see it because it has been overlaid by the select.

**Comment by jacobg** [comment]
@loicduong In the stackblitz, label only displays when changing name to `label-col` without "s". Maybe it's a different side effect.

**Comment by loicduong** [comment]
@jacobg This is just a coincidence. You just need to not use `label-cols` and the problem will occur.
