### ISSUE TITLE
BModal: class properties e.g. "body-class" not being applied

### ISSUE THREAD

**Issue by rubebop** [bootstrap-vue-next/bootstrap-vue-next#2315]
I was trying to use of the **BModal** property `body-class` but I can't make it work. (I've look for other issues but didn't find anything on this topic.)

I have a BModal like:
```
    <BModal
      body-class="decay-modal"
      v-model="decaysModalParams.show"
      scrollable
    >
        yoo
    </BModal>
```
I have a style such as:

```
.decay-modal {
  background: #25527a; 
}
```

Using Chrome's developer tools, I inspect the Elements an I can find something that would make sense:

```
<div data-v-8a2b2b28="" id="__BVID__589422___BV_modal__-body" class="modal-body decay-modal">
    [...]
</div>
```

Unfortunately, I don't find under Styles of that element the class `decay-modal`.

Is this a bug or am I missing something?

- OS: Windows 10
- Package Version: 0.17.6 and 0.25.10
- Npm: 10.9.0

**Comment by xvaara** [comment]
Can't really tell what the problem is. We are adding the class to the modal? Sounds like you are not loading your styles for the page, or you have them scoped.

**Comment by rubebop** [comment]
Thanks a lot for your answer.
You are right the mentioned class was defined as **scoped**:
```
<style lang="scss" scoped>
    .decay-modal {
      background: #25527a; 
    }
</style>
```
I already thought about that and I tried to use a **deep selector** to fix the problem:
```
<style lang="scss" scoped>
    :deep(.decay-modal) {
      background: #25527a; 
    }
</style>
```
But it didn't help. So to solved the issue, I defined an additional **non-scoped `style` section** and it worked as expected:

```
<style>
    .decay-modal {
      background: #25527a; 
    }
</style>
```

---------------------------------------------------

As an **additional comment**: in the past I've been able to **"manually"** change the style of a **BTable** such as:
```
<b-table
        class="custom-table"
        :items="filteredTableItems"
        :fields="tableFields"
/>
```
```
<style lang="scss" scoped>
  .custom-table::v-deep(table) >thead>tr>th{
    color: white;
    background: #25527a;
  }
</style>
```

I tried to do something similar with the **BModal** but I was totally unable to select its elements:
```
<BModal
      class="decay-modal"
      v-model="decaysModalParams.show"
      scrollable
>
        yoo
</BModal>
```
```
<style lang="scss" scoped>
.decay-modal:deep(div) {
  background: #25527a; 
}
</style>
```

I wonder why.

**Comment by rubebop** [comment]
Thanks a lot: that's what I sort of suspected by carefully inspecting the DOM. Glad that you confirmed it. Again, thanks for the useful tip concerning the teleport-disabled prop 🙏
