### ISSUE TITLE
Margin issue with b-form-group in latest update

### ISSUE THREAD

**Issue by rademax** [bootstrap-vue-next/bootstrap-vue-next#2316]
### Describe the bug

After updating Bootstrap Vue Next to the latest version, I noticed that `b-form-group` elements no longer have the expected default margin (especially `margin-bottom).` This styling used to be applied to maintain proper spacing between form elements but seems to have been removed or altered in the latest release.

### Steps to Reproduce:
Update to the latest version of Bootstrap Vue Next.
Use b-form-group components in a Vue 3 project.
Check padding and margin on b-form-group components in DevTools.

**Expected Behavior:**
`b-form-group` elements should have consistent spacing (`margin-bottom`) applied by default, similar to previous versions.

**Current Behavior:**
`b-form-group` components lack `margin-bottom`, causing form elements to appear closely packed without spacing.

### Screenshots:
<img width="1632" alt="Screenshot at Oct 30 18-56-34" src="https://github.com/user-attachments/assets/14af922a-caf6-4fb8-996c-5c8839551240">

### Additional Context:
I’ve applied temporary CSS overrides to address this issue, but an official fix would help avoid maintaining custom CSS for each project.

### Reproduction

https://stackblitz.com/edit/github-amz8xq

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
I kind of didn't know what I was doing with this refactor, someone else working on this issue would be appreciated as I don't quite know how to fix it

**Comment by loicduong** [comment]
In Bootstrap 4, there is a class .form-group with the margin-bottom property. This class has been removed in Bootstrap 5, leading to issues like the one above.

https://getbootstrap.com/docs/5.3/migration/#forms-1

**Comment by rademax** [comment]
@loicduong Ok, thanks.

**Comment by jacobg** [comment]
There's a similar issue to a few months ago:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2039

In Vue 2, bootstrap vue set `class="form-group"` which was styled with `margin-bottom: 1rem;` or something like that. In Vue 3, boostrap-vue-next no longer sets this class or styles it.
