### ISSUE TITLE
Issue with b-form-group wrong position with invalid-feedback

### ISSUE THREAD

**Issue by Shnitzelil** [bootstrap-vue-next/bootstrap-vue-next#2330]
### Describe the bug

We are using invalid-feeback with the horizontal alignment which appear in the wrong location.
Worked well until version 0.25.6 (before [Commit 07daa80](https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/07daa80aef41df5b8e31578c2bc695823c2f6510))
The feedback should appear under the input field.

Starting from version 0.25.7 it appear on the right of the input field

```vue
<b-form-group
	:invalid-feedback="$t('message.Validations.ParameterName')"
	:label="$t('message.AddNewParameter.Parameter_name')"
	:state="nameInputState"
	class="form-row"
	horizontal
	label-for="nameInputPopover"
	ref="nameInput">
		<b-form-input
		:state="nameInputState"
		@keydown.enter.native="onOk"
		@keydown.esc.native="onClose"
		class="name_input"
		id="nameInputPopover"
		ref="nameInput_ref"
		size="sm"
		v-model="nameInput"
	/>
</b-form-group> 
```

Please advise

### Reproduction

https://stackblitz.com/fork/bootstra-vue-next-template?file=src%2Fcomponents%2FComp.vue,src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
There is no horizontal prop in the BFromGroup component, and form-row class doesn't exist in bootstrap 5, check the documentation for the component to see how trigger horizontal: https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-group.html#horizontal-layout
