### ISSUE TITLE
BDropdown/BNavItemDropdown default slot doesn't implement focus property

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#2334]
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/nav#comp-ref-b-nav-form-props

### Describe the missing feature

`BDropdown` and `BNavItemDropdown` both have a boolean argument on the `hide` method of their `default` slot which if true returns focus to the toggle button.

Caught this on parity pass, don't think it blocks anything as adding an optional argument shouldn't be a breaking change.

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided link is to the documentation of the missing feature.

**Comment by VividLemon** [comment]
Although it is possible to return focus to the button, bootstrap v5 by default doesn't have the focus ring that v4 has. Because of this I'm not going to implement this

**Comment by dwgray** [comment]
> bootstrap v5 by default doesn't have the focus ring that v4 has. Because of this I'm not going to implement this

Fair enough - I've updated the migration guide to reflect this in my pending PR #2332
