### ISSUE TITLE
Is there an MVP of how to create a vitest test for a bootstrap vue next component?

### ISSUE THREAD

**Issue by ajmcgrail** [bootstrap-vue-next/bootstrap-vue-next#2335]
Title, just looking for an MVP on how to make a vitest for a bootstrap vue next component. I couldn't find anything in the repo, or as a stackblitz (I did find an MVP for bug finding, but not for vitest). I'm having problems with testing the BDropdown component when it's being clicked, but I want to make sure that I'm not missing something obvious before I make an issue regarding it.

Thanks for your time.

**Comment by dwgray** [comment]
Not sure it this is what you're looking for, but we do have tests that cover `BDropdown` being clicked - Take a look here https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BDropdown/dropdown.spec.ts#L309

**Comment by ajmcgrail** [comment]
I wanted something smaller, but has a different issue. I wanted to check the *effect* of the click, not that the component registered that it clicked, and that's what I was having trouble with. But what you linked is probably good enough for anyone in the future who looks at the thread, so I'll go ahead and close it. Thanks!

**Comment by VividLemon** [comment]
Are you referring to adding unit tests in the library?
