### ISSUE TITLE
Set operation on readonly target warnings with 0.25.14

### ISSUE THREAD

**Issue by mbabker** [bootstrap-vue-next/bootstrap-vue-next#2337]
### Describe the bug

After updating from 0.25.13 to 0.25.14, I started to get a lot of `[Vue warn] Set operation on key "value" failed: target is readonly.` messages in my browser console and test output.  I'm guessing https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2325 is the culprit here.

Searching for the error, I landed on https://github.com/vuejs/core/issues/11795 which seems to imply that the variable name in the script section shouldn't match the name of the template ref, and that PR uses `<li v-bind="page.li" ref="pageElements">` and `const pageElements = useTemplateRef<HTMLLIElement[]>('pageElements')` respectively.

There isn't a unique reproducer attached here, copying the example from the pagination component docs, running it in StackBlitz, and inspecting the browser console is enough to see it.

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/pagination.html

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tbl0605** [comment]
Hi,
I have exactly the same warnings since version v0.25.14.

Reverting to version v0.25.13 makes the warnings disappear.

**Comment by xvaara** [comment]
@VividLemon yeah, we shouldn't use the useTemplateRef if we don't need. It add complexity to a non problem.

**Comment by VividLemon** [comment]
> @VividLemon yeah, we shouldn't use the useTemplateRef if we don't need. It add complexity to a non problem.

It simplifies binding a template ref. I dont understand your issue
