### ISSUE TITLE
BTable - BPagination: only data of first pagination page is displayed

### ISSUE THREAD

**Issue by udos** [bootstrap-vue-next/bootstrap-vue-next#2356]
### Describe the bug

hello, there is a good chance that I'm completely missing something 😬...

I'm using an endpoint to GET the data and then assign the response to BTable prop **_items_** via `items.value=resp.data` (which is an array of objects)

I tried to "fake" this behaviour in the stackblitz example by using a watcher.

like there, I see only the retrieved data of the first page (when clicking on the other pages of BPagination...

looking at the vue debugger in dev tools and inspecting the BTable object, I see the retrieved data in "items"...

any ideas/suggestions what's wrong here?

thx 🙏

### Reproduction

https://stackblitz.com/edit/github-pah63p?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
```html
<b-table
    :items="items"
    :per-page="perPage"
    :current-page="currentPage"
    small
  />
```
=>
```html
<b-table
    :items="items"
    small
  />
```
You're using it as if you're using the provider prop (instead of items).

**Comment by VividLemon** [comment]
To be clear, what you're doing is manually paginating AND using automatic pagination

**Comment by udos** [comment]
thank you so much 🙏
I had a feeling that the problem was sitting in front of the computer... 🙄

note:
but I got "inspired" by the docs 😬:

- https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/pagination.html#overview

```js
<template>
  <BContainer>
    <BRow>
      <BCol>
        <div class="overflow-auto">
          <b-pagination
            v-model="currentPage"
            :total-rows="rows"
            :per-page="perPage"
            aria-controls="my-table"
          />

          <p class="mt-3">Current Page: {{ currentPage }}</p>

          <b-table
            id="my-table"
            :items="items"
            :per-page="perPage"
            :current-page="currentPage"
            small
          /></div
      ></BCol>
    </BRow>
  </BContainer>
</template>

<script setup lang="ts">
import {computed, ref} from 'vue'

const perPage = ref(3)
const currentPage = ref(1)
const items = ref([
  {id: 1, first_name: 'Fred', last_name: 'Flintstone'},
  {id: 2, first_name: 'Wilma', last_name: 'Flintstone'},
  {id: 3, first_name: 'Barney', last_name: 'Rubble'},
  {id: 4, first_name: 'Betty', last_name: 'Rubble'},
  {id: 5, first_name: 'Pebbles', last_name: 'Flintstone'},
  {id: 6, first_name: 'Bamm Bamm', last_name: 'Rubble'},
  {id: 7, first_name: 'The Great', last_name: 'Gazzoo'},
  {id: 8, first_name: 'Rockhead', last_name: 'Slate'},
  {id: 9, first_name: 'Pearl', last_name: 'Slaghoople'},
])
const rows = computed(() => items.value.length)
</script>
```
