### ISSUE TITLE
Module '"bootstrap-vue-next"' has no exported member 'BootstrapVueNextResolver'.ts(2305)

### ISSUE THREAD

**Issue by cakadi190** [bootstrap-vue-next/bootstrap-vue-next#2357]
### Describe the bug

I just found a little bug in the typescript for vite.config.ts that when I import BootstrapVueNextResolver with inertia adonisjs or laravel breeze but there are no types available. What is the solution?

![image](https://github.com/user-attachments/assets/ab6503ab-fd1e-473f-b799-ac12e3c29ec8)

Here my bun version
```
cakadi190's cakadi-porto/ via  18.20.4                                                              RAM:15/31GB ┋ 17ms
⮞  bun -v
1.1.28
cakadi190's cakadi-porto/ via  18.20.4                                                              RAM:14/31GB ┋ 40ms
⮞
```
But when i try with npm package manager, it works. No type issues on typescript. Please help to fix it to the next update.
![image](https://github.com/user-attachments/assets/c57bcb75-afbb-4513-a69a-de06ce189946)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-2xbcrn?file=README.md

### Used Package Manager

bun

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
A better reproduction would be needed. It's likely a configuration issue on your end that doesn't require our input -- the https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/1a03b9b4c089ad80797f22200d02a1f6310714d2/packages/bootstrap-vue-next/package.json#L13 is as correct as it can be
