### ISSUE TITLE
Multiple warnings in docs

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#2360]
### Describe the bug

With the .26 release, I started seeing a large number of the following error when running the docs site in dev mode:

```
reactivity.esm-bundler.js:9  [Vue warn] Set operation on key "value" failed: target is readonly. RefImpl {dep: Dep, __v_isRef: true, __v_isShallow: true, _rawValue: null, _value: null}
```

[vue-warnings.log](https://github.com/user-attachments/files/17820638/vue-warnings.log)

Looking at #2353, it appears there are issues with name conflicts in `useTemplateRef` causing warnings. But I can't find anything in the vue docs to back this up. What I do see is that the reference that is created shouldn't conflict with other references, but in #2353, we're changing the symbol in the template.

In any case - I tried changing the element refs in `BOffcanvas.vue` to avoid collisions, and it removed several of the warnings.

```
const elementRef = useTemplateRef<HTMLElement>('offcanvas-element')
const fallbackFocusElement = useTemplateRef<HTMLElement>('fallback-focus-element')
```
But, I'm not even sure how to track down the ones where `_rawValue === null`. Do we have to 'fix' every place that we call `useTemplateRef` to make the names unique? We've got a lot of places where we're referencing `element`, so that won't be a small chore, but doable. I just wouldn't want to tackle that without understanding what is actually going on.

Also, this appears to only happen with SSR. A simple app that uses an `BOverlay` doesn't repro.

@mbabker - any thoughts? Can you point me at anything that describes why the changes you made in #2353 work?

### Reproduction

All of the docs pages

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mbabker** [comment]
There are probably other fixes similar to what I did in #2353 needed.  When looking for info when I filed #2337, it seems like the root cause is the template ref having the same name as the script variable.  Because of the way Vue handles template references, it tries to automatically assign the reference to something with the same variable name (in BModal I see a `fallbackFocusElement` and a `const fallbackFocusElement = useTemplateRef('fallbackFocusElement')` as an example), and https://github.com/vuejs/core/issues/11795 leads me to believe that's the wrong use of the `useTemplateRef` helper.

**Comment by dwgray** [comment]
Thanks @mbabker - If I'm reading the vue core information correctly [vuejs/core#11795](https://github.com/vuejs/core/issues/11795) is closed as fixed by [bc63df0](https://github.com/vuejs/core/commit/bc63df01992fdbf0b6749ad234153725697ed896), which shows up in the changelog as fixed in [3.5.1](https://github.com/vuejs/core/blob/minor/CHANGELOG.md#351-2024-09-04)

So I don't think the right answer is to go an change all our names. We should figure out why we're either not seeing the fix or why the fix isn't working in our case. 

@VividLemon, @xvaara any thoughts? Are you seeing these warnings on your local machines or am I doing something weird? I see the pnpm-lock.yaml is showing vue as 3.5.13 and I'm also showing that version number in vue tools, so I think I've correctly pulled down the most recent version that should have this fix.

**Comment by VividLemon** [comment]
Check again

**Comment by dwgray** [comment]
Okay, I take it this means you're not seeing the issue?

I'm attempting as clean a build as I can, so I created a clone directly from the main branch of the main fork.

Here's what I did:
- git clone https://github.com/bootstrap-vue-next/bootstrap-vue-next.git bsvn
- cd bsvn
- pnpm install
- pnmp dev
- open `http://localhost:8000/bootstrap-vue-next/` in a browser

I get the same errors I attached above. Other than global caching of corrupt or outdated packages, I can't think of anything else that would cause this to fail on my machine and not yours, but as I've said before this is not my native environment, so please let me know if you have any ideas.

P.S. Just tried the above on a different machine and get the same results, so I'm completely stumped...

**Comment by MorningLightMountain713** [comment]
I am also seeing these errors

**Comment by xvaara** [comment]
@VividLemon this is the reason I sais we shouldn't change to useTemplateRef without a reason to do so. 

My understanding of this is that it complains in dev mode. Of the ref:ed element isn't rendered at the first load then vue needs to set the ref to the element. If the `ref="foo"` matches `const foo` then vue tries to set the const foo to the element with ref="foo", and useTemplateRef does it a diffrerent a little bit more complex way. 

So we need to change the ref="x" to something to avoid changing the variables. My suggestion is that we add _ to the begining of them, common convention for "internal variables".

**Comment by xvaara** [comment]
@dwgray can you test the pr if it fixes all the errors for you?

**Comment by dwgray** [comment]
Thanks, @xvaara, that resolves the warnings I'm seeing, and the solution makes sense to me.
