### ISSUE TITLE
BTabs Lazy attribute causes recursion

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#2364]
### Describe the bug

I'm filling out the docs for the `BTabs` component and am running into an issue when setting the `lazy` attribute.

I'm getting the message and the tabs and content aren't rendering:

```
Uncaught (in promise) Maximum recursive updates exceeded in component <BTabs>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
```

This is the source (basically straight from BSV):
```vue
  <BTabs content-class="mt-3">
    <!-- This tabs content will always be mounted -->
    <BTab title="Regular tab"><BAlert show>I'm always mounted</BAlert></BTab>

    <!-- This tabs content will not be mounted until the tab is shown -->
    <!-- and will be un-mounted when hidden -->
    <BTab title="Lazy tab" lazy><BAlert show>I'm lazy mounted!</BAlert></BTab>
  </BTabs>
```

This doesn't repro in stackblitz or when pasted into App.vue in the BSVN sources, so I suspect the has something to do with SSR? If someone can point me at a straightforward way to repro in SSR mode, I'd be happy to give that a try - do we have something in playground that will let me do that? 

### Reproduction

See above

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
@dwgray it's probably some prop or functionality that we aren't safeguarding correctly from the weirdness, so can you share all the code to me somewhere?

**Comment by dwgray** [comment]
> I'll poke around a little more to see if I can come up with a more concise test case or potential solution, but I'm pretty tight time today...

@xvaara - here is a smaller repro for case (2) above:

Against my clean install of BSVN - main fork, main branch, I can put this in App.vue:

```vue
<template>
  <BTabs content-class="mt-3">
    <!-- This tabs content will always be mounted -->
    <BTab title="Regular tab"><BAlert show>I'm always mounted</BAlert></BTab>

    <!-- This tabs content will not be mounted until the tab is shown -->
    <!-- and will be un-mounted when hidden -->
    <BTab title="Lazy tab" lazy><BAlert show>I'm lazy mounted!</BAlert></BTab>
  </BTabs>
</template>

<script setup lang="ts">
// You can use this file as a development spot to test your changes
// Please do not commit this file
import {BTab, BTabs} from './components'
</script>
```
And I see this:
![image](https://github.com/user-attachments/assets/f2e0ee98-f579-4fd8-ad31-e22c8d75a389)

No errors in the console but the tab bodies don't show up...

**Comment by xvaara** [comment]
@dwgray BAlert doesn't have show prop

**Comment by xvaara** [comment]
@dwgray is the error coming in when you do a hmr (a file save and automatic reload in the browser for the components)?

in TabsCustomLinks.vue you are using a function as value to a prop. They "really" aren't reactive and are causing the problem with hmr. That example is also quite bad example, since we already have activeNavItemClass and inactiveNavItemClass and should add (in)activeNavLinkClass props. 

You can have a computed for example creating an array that has the classes:
```js
const linkClass = computed(() =>
  Array.from(Array(3).keys()).map((idx) =>
    tabIndex.value === idx ? ['bg-primary', 'text-light'] : ['bg-light', 'text-info']
  )
)
```

the function works, but not with hmr.

**Comment by dwgray** [comment]
Thanks, @xvaara - That was indeed what was causing the errors on the page. The other thing that was happening was that I did not read my own migration notes on [`BAlert`](http://localhost:8000/bootstrap-vue-next/docs/migration-guide.html#balert).

Both of these were because I'm converting the BSV examples in the old docs. I'll take a closer look for differences before I call for help next tim.
