### ISSUE TITLE
Regression: BModal's background is now "flashing" when the BModal opens

### ISSUE THREAD

**Issue by tbl0605** [bootstrap-vue-next/bootstrap-vue-next#2365]
### Describe the bug

Hi,
I have the same problem again as described [here](https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2260#issuecomment-2407680345).

When I open a BModal with version 0.26.1, I have the background that "flashes" briefly.
It is hard to notice on a white page, but very visible on a page with many components (and colors).

### Reproduction
1. Go to https://stackblitz.com/edit/github-rzxbjv-mnhfku
2. Click on the "Open Modal" button, you'll see that background color briefly switches between two colors

Note that with version 0.25.13, the problem doesn't occur: https://stackblitz.com/edit/github-rzxbjv-gqgmmn

### Reproduction

https://stackblitz.com/edit/github-rzxbjv-mnhfku

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xvaara** [comment]
I just filmed with my iphone slowmotion video. Yes, it goes black for 1 frame. That's an overside on my part. Didn't notice it on my high refresh monitor, but clearly annoying on a display with slower pixels. Bootstrap css has some weirdness that we have to account for.

**Comment by tbl0605** [comment]
@xvaara,
thank you for the fix :)
