### ISSUE TITLE
How to do v-b-popover.hover.html after update to 0.26.x?

### ISSUE THREAD

**Issue by mediaessenz** [bootstrap-vue-next/bootstrap-vue-next#2374]
Until version 0.25.x it was possible to do something like this:
```
<i class="bi bi-question-circle"
   v-b-popover.hover.html="{variant:'dark', title:'Dummy', content:'<strong>Attention:<strong> whatever...'}">
</i>
```
Since 0.26.x this produces an html encoded output.

How can this be done under 0.26.x as well?

**Comment by xvaara** [comment]
Use a component.

**Comment by VividLemon** [comment]
Yes, the intended solution here is to use the component form with explicit `v-html` for safety
