### ISSUE TITLE
useModal doesn't hide the modal changing v-model

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#2376]
### Describe the bug

BVN 0.26.2

while ok is prevented changing BModal modelValue programmatically doesn't close the  modal

see also #2028 

### Reproduction

https://stackblitz.com/edit/github-ydzoyh?file=src%2FApp.vue

### Used Package Manager

npm

**Comment by VividLemon** [comment]
Note: 

```html
<template>
  <div>
    <b-button @click="visible = true">Open Modal</b-button>

    <b-modal v-model="visible" no-close-on-backdrop @ok.prevent="ok">
      content {{ visible }}
    </b-modal>
  </div>
</template>
<script setup lang="ts">
import { nextTick } from 'vue';
const visible = defineModel<boolean>();

const ok = () => {
  nextTick(() => {
    visible.value = false;
  });
};
</script>

```
If you add a nexttick, the modelValue is updated. So this means that there's an internal value not being updated.

**Comment by makroxyz** [comment]
I've about 100 modals in my project which stops to close. Hope this is a
minor fix on the way

Il ven 22 nov 2024, 18:57 Issayah ***@***.***> ha scritto:

**Comment by makroxyz** [comment]
Since old BV I always did in that way

```vue
<template>
  <div>
    <b-button @click="visible = true">Open Modal {{ visible }}</b-button>

    <b-modal v-model="visible" no-close-on-backdrop @ok="ok"> content </b-modal>
  </div>
</template>
<script setup lang="ts">
const visible = defineModel<boolean>();

const ok = (e: Event) => {
  // if axios submit, or inertiajs form submit with success then visible.value = false
};
</script>
```

**Comment by xvaara** [comment]
@makroxyz I might have fixed this for you. Test 0.26.4, uploading to npm right now...

**Comment by makroxyz** [comment]
Thank you, I'll try tomorrow morning!

Il mar 26 nov 2024, 19:08 Jukka Raimovaara ***@***.***> ha
scritto:

**Comment by xvaara** [comment]
@makroxyz any updates?

**Comment by makroxyz** [comment]
Sorry, I was really busy at work.
tried latest version... It works fine! Thanks

Il ven 29 nov 2024, 14:52 Jukka Raimovaara ***@***.***> ha
scritto:
