### ISSUE TITLE
useShowHide `visible` attribute not behaving as documented

### ISSUE THREAD

**Issue by dwgray** [bootstrap-vue-next/bootstrap-vue-next#2385]
### Describe the bug

I'm working on updating the migration guide to reflect #1821 . Based on the description in `showhide-props.ts`, I would expect that a component with just `visible` would show on initial render (and with just `show` it would animate). `show` works as documented, but `visible` doesn't - see the example.

@xvaara Let me know I'm misunderstanding the intent of the documentation.

### Reproduction

https://stackblitz.com/edit/github-yymg1c?file=src%2FApp.vue

### Used Package Manager

pnpm

**Comment by xvaara** [comment]
@dwgray I'm quite sure I missed that I broke that feature at some point. There were so many moving parts, forgot to test each of them after each change. It works when you toggle visible after the first render. I'll fix it.
