### ISSUE TITLE
Regression in v0.26.4: Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times

### ISSUE THREAD

**Issue by tbl0605** [bootstrap-vue-next/bootstrap-vue-next#2393]
### Describe the bug

Hello,
since version 0.26.4, I get the following error logged in the console, every time I navigate to a new page (my application is now totally broken):
```
Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    updateTabbableNodes2 focus-trap.esm.js:409
    activate focus-trap.esm.js:863
    activate useFocusTrap.mjs:11
    useActivatedFocusTrap useActivatedFocusTrap.ts:67
    callWithErrorHandling chunk-GRYGDNWY.js:2300
    callWithAsyncErrorHandling chunk-GRYGDNWY.js:2307
    call chunk-GRYGDNWY.js:8310
    job chunk-GRYGDNWY.js:2029
    callWithErrorHandling chunk-GRYGDNWY.js:2300
    flushJobs chunk-GRYGDNWY.js:2508
    promise callback*queueFlush chunk-GRYGDNWY.js:2422
    queueJob chunk-GRYGDNWY.js:2417
    scheduler chunk-GRYGDNWY.js:8322
    scheduler chunk-GRYGDNWY.js:2046
    trigger chunk-GRYGDNWY.js:546
    endBatch chunk-GRYGDNWY.js:604
    notify chunk-GRYGDNWY.js:864
    trigger chunk-GRYGDNWY.js:838
    set value chunk-GRYGDNWY.js:1710
    useShowHide useShowHide.ts:345
    setTimeout handler*useShowHide/</</</</< useShowHide.ts:344
    useShowHide useShowHide.ts:342
    useShowHide useShowHide.ts:341
    useShowHide useShowHide.ts:340
    useShowHide useShowHide.ts:339
    callWithErrorHandling chunk-GRYGDNWY.js:2300
    callWithAsyncErrorHandling chunk-GRYGDNWY.js:2307
    call chunk-GRYGDNWY.js:8310
    job chunk-GRYGDNWY.js:2029
    callWithErrorHandling chunk-GRYGDNWY.js:2300
    flushJobs chunk-GRYGDNWY.js:2508
    promise callback*queueFlush chunk-GRYGDNWY.js:2422
    queueJob chunk-GRYGDNWY.js:2417
    scheduler chunk-GRYGDNWY.js:8322
    scheduler chunk-GRYGDNWY.js:2046
    trigger chunk-GRYGDNWY.js:546
    endBatch chunk-GRYGDNWY.js:604
    notify chunk-GRYGDNWY.js:864
    trigger chunk-GRYGDNWY.js:838
    set value chunk-GRYGDNWY.js:1710
    onEnter useShowHide.ts:283
    onEnter useShowHide.ts:281
    onEnter useShowHide.ts:280
    callHook2 chunk-GRYGDNWY.js:10644
    makeEnterHook chunk-GRYGDNWY.js:10704
    callWithErrorHandling chunk-GRYGDNWY.js:2300
    callWithAsyncErrorHandling chunk-GRYGDNWY.js:2307
    callHook3 chunk-GRYGDNWY.js:3398
    callAsyncHook chunk-GRYGDNWY.js:3407
    enter chunk-GRYGDNWY.js:3466
    mountElement chunk-GRYGDNWY.js:7017
    flushPostFlushCbs chunk-GRYGDNWY.js:2485
    render2 chunk-GRYGDNWY.js:8112
    mount chunk-GRYGDNWY.js:6055
    mount chunk-GRYGDNWY.js:12256
    <anonymous> main.js:57
    promise callback* main.js:56
```
I'll try to add a reproduction in the next few days, I'm unfortunately very busy at the moment, but I thought it would be useful to file a bug report as soon as possible.

@xvaara,
this probably has to do with your recent `useShowHide` changes.

Thierry.

### Reproduction

-

### Used Package Manager

pnpm

**Comment by tbl0605** [comment]
Ok, sorry, it seems that this is fixed in version v0.26.5 which has been released in the meantime ^^
Sorry for the inconvenience ^^

And thank you for your great work!

Thierry.

**Comment by xvaara** [comment]
Yes, sorry about that. It seems vue has a different behaviour in the production build, so we were triggering the transition even without show:ing the component.

**Comment by acanthis** [comment]
When trying to show a modal window via useModalController() I get the same error

`show?.({
     component: FieldsSettingsModal,
});`
    
`Your focus-trap must have at least one container with at least one tabbable node in it at all times`

**Comment by xvaara** [comment]
@acanthis can you share the a reproduction or the content of FliedsSettingsModal in the linked issue?

**Comment by xvaara** [comment]
@acanthis works for me: https://stackblitz.com/edit/github-ydzoyh-kebbye?file=src%2FApp.vue,src%2Fcomponents%2FComp.vue

It might be something in your other code. Comment on the linked issue if you can get that stackblitz to error out like your code.

**Comment by acanthis** [comment]
@xvaara 
> Это может быть что-то в вашем другом коде. Прокомментируйте **связанную проблему,** если вы можете заставить этот stackblitz выдавать ошибку, как ваш код.

This code doesn't work for me. Moreover, the **__BVID__modal-container** container is filled with the correct HTML code, the background is darkened, but I don't see the window itself. And in the console there is an error: _Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times_

I don't understand yet why this is happening

**Comment by acanthis** [comment]
@xvaara 

I found the reason for this behavior. It turns out that I disabled the import of bootstrap-vue-next.css styles. After connecting the style, everything worked as it should.
Thanks for your help.
Sorry, the ticket can be closed.

**Comment by oliver681** [comment]
Yeah, thank you @acanthis!

@xvaara 
I had the same problem. I was importing `~bootstrap-vue-next/src/styles/styles.scss` to my project`s SCSS, which doesn't include the modal styles. Is the scss file not meant to be used?

I saw that the modal styles are defined on the [BModal](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/a32c8fa937d9747103721a71653d85c793983ad6/packages/bootstrap-vue-next/src/components/BModal/BModal.vue#L441) component. Somehow they still weren't applied when using it..
