### ISSUE TITLE
[Vue warn]: Failed to resolve directive: b-modal

### ISSUE THREAD

**Issue by elrosi** [bootstrap-vue-next/bootstrap-vue-next#2405]
Hello,

In my project, I wanted to use bootstrap-vue-next specifically the BModal component. 

With the following implementation, after opening and closing the modal window, the Chrome console displays the warning:
 **[Vue warn]: Failed to resolve directive: b-modal**

```
<BButton @click="modal = !modal"
         :class="`btn btn-flex btn-outline btn-color-gray-700 btn-active-color-primary bg-body h-40px fs-7 fw-bold`"
         v-b-modal.modal-scrollable
><i class="bi bi-card-list fs-4"></i> {{ $t('label.add_part') }}</BButton>

<BModal
            v-model="modal"          
            :id="`modal-scrollable`"
            :title="`Add Budget Part`"
            :fullscreen="false"
            :headerCloseLabel="'x'"
            :bodyScrolling="true"
            :hide-footer="true"
            :autoFocus="true">
        <p class="my-4" v-for="i in 3" :key="i">
            Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in,
            egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
        </p>
    </BModal>
```

Can you advise me where I am making a mistake?
Thank you for any help.

- OS: Windows 11
- Package Version: 0.26.7
- Vue: 3.5.13
- Bootstrap: 5.3.3
- Npm: 10.8.2

**Comment by xvaara** [comment]
You don't need the directive, the v-model should work just fine.

You probably haven't installed the directives, they aren't installed as default since they aren't the recommended way. They have so many caveats in using them.
