### ISSUE TITLE
Bug: BPagination needs totalRows and perPage configured BEFORE v-model?

### ISSUE THREAD

**Issue by ltickett** [bootstrap-vue-next/bootstrap-vue-next#2414]
### Describe the bug

When I navigate to a Vue app with a page number in the querystring I'm having a bit of a nightmare :)

At the point the app is mounted, an API call has not yet been made so we don't have totalRows. 
We do have perPage and the current page (i.e. v-model).

Unfortunately, the value bound to v-model is ignored when totalRows gets updated.

To force BPagination to display the currently selected page I have to `await nextTick();` then reset v-model.

Additionally, the component emits `@update:model-value` and `@page-click` with a page number of 0 at some point, which I have to ignore.

Am I taking a mad approach- is there a more obvious way?

I'm disinclined to fake totalRows and set it to 1,000,000 or something while the page loads?

Thanks in advance!

### Reproduction

https://stackblitz.com/edit/github-klmeuo?file=src%2FApp.vue

### Used Package Manager

npm

**Comment by ltickett** [comment]
Thanks @dwgray that sounds like a good fix BUT I don't think it'll work.

I just updated the StackBlitz to better explain- but here's the flow:

- Init the component with v-model=1, total-rows=1, per-page=50
- Renders as expected...
- API call returns data
- Update total-rows=1000, per-page=50, and v-model=3
- Component does not update and still shows page 1 as selected
- Force a cycle with `await nextTick()` then set v-model=3 again
- Component correctly shows page 3 as selected

**Comment by dwgray** [comment]
Thanks @ltickett , we definitely have some reactivitey weirdness around updating the model and the pagination information (page-size, toatl-rows). I'll take a closer look as soon as I've got a few cycles for this and see what I can do.

**Comment by VividLemon** [comment]
What's happening is that the watcher (that resets the value back to starting at one if you're out of bounds) is being executed after you've updated your variable, but in the same batch. We could have the watcher execute synchronously, but this isn't the best solution.

Surprisingly, this is a fair use of nextTick. You should probably just prefer to use nextTick

**Comment by dwgray** [comment]
> What's happening is that the watcher (that resets the value back to starting at one if you're out of bounds) is being executed after you've updated your variable, but in the same batch. We could have the watcher execute synchronously, but this isn't the best solution.
> 
> Surprisingly, this is a fair use of nextTick. You should probably just prefer to use nextTick

I think the change I made in #2414 makes our code more robust and should solve @ltickett's problem

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2416

**Comment by VividLemon** [comment]
https://opencollective.com/bootstrap-vue-next/contributions/812851

Tyvm!

**Comment by ltickett** [comment]
Least I could do. Really appreciate your responsiveness- I know how challenging it can be to maintain something like this.

Next time perhaps i'll have the confidence to contribute directly :)

**Comment by ltickett** [comment]
p.s. if you're interested here's the project i'm using bootstrap-vue-next in https://gitlab.com/gitlab-org/developer-relations/contributor-success/contributors-gitlab-com // https://contributors.gitlab.com/

You probably know how much we love open source at GitLab ❤️

**Comment by VividLemon** [comment]
> p.s. if you're interested here's the project i'm using bootstrap-vue-next in https://gitlab.com/gitlab-org/developer-relations/contributor-success/contributors-gitlab-com // https://contributors.gitlab.com/
> 
> You probably know how much we love open source at GitLab ❤️ 

Ive read in RFCs that upgrading to Vue 3 has been quite the challenge for you

**Comment by ltickett** [comment]
Our monolith is pretty crazy. I haven't been too close to the Vue3 migration, but I know we're at least running our test suite for both Vue2 and Vue3 now which should at least ensure any new components introduced are Vue3 compatible.

I'm lucky to be working on this standalone project using Vue3 from the beginning 👍

**Comment by VividLemon** [comment]
Tbh it would be incredibly useful to have someone working through a migration, or real project, while also maintaining the library of choice. Practically though most companies don't want to pay for that lol. The limited experience I've had with updating the simplelogin extension brought some great ideas for the lib
