### ISSUE TITLE
ScrollSpy does not support nested elements.

### ISSUE THREAD

**Issue by Matthew-Berends-WorkSafe** [bootstrap-vue-next/bootstrap-vue-next#2420]
### Describe the bug

ScrollSpy does not support nested elements.
"Item-2" will not activate as it sits in another element.

```
        <div id="scrollspy-nested">
          <h4 id="item-1">Section one heading</h4>
          <p>{{ text }}</p>
          <div>
            <h4 id="item-2">Section two heading does not highlight</h4>
          </div>
          <p>{{ text }}</p>
          <h4 id="item-3">
            Section three heading
          </h4>
          <p>{{ text }}</p>
          <h4 id="item-4">Section four heading</h4>
          <p>{{ text }}</p>
        </div>

```

### Reproduction

https://stackblitz.com/edit/github-fvmk8h?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

yarn

**Comment by xvaara** [comment]
The contentQuery is quite strict by default, add contentQuery: '[id]' to the scrollSpy options to make id wider. or maybe h4[id] might be a good compromise
