### ISSUE TITLE
Tooltip breaks BButtonGroup

### ISSUE THREAD

**Issue by jongbonga** [bootstrap-vue-next/bootstrap-vue-next#2428]
### Describe the bug

when adding a tooltip on the last button in a BButtonGroup, the border-radius of the button disappear.

![Screenshot 2024-12-07 at 7 50 02 PM](https://github.com/user-attachments/assets/81d3b1ad-f4bf-46e2-a09a-cb7575350b5d)

### Reproduction

https://stackblitz.com/edit/github-hspdt1-whaprfe9?file=src%2FApp.vue

### Used Package Manager

npm

**Comment by xvaara** [comment]
move the tooltip to the body with body modifier. `v-b-tooltip.body="title"`
