### ISSUE TITLE
BLink / useLink warnings / maybe errors

### ISSUE THREAD

**Issue by xvaara** [bootstrap-vue-next/bootstrap-vue-next#2429]
### Describe the bug

![Screenshot 2024-12-08 at 11 01 57](https://github.com/user-attachments/assets/3639f60c-4779-4520-8e63-3c0b0f93b223)

### Reproduction

just add     <BLink to="/">home</BLink> to the App.vue in our codebase

### Used Package Manager

pnpm

**Comment by jongbonga** [comment]
I get this error after I updated to `0.26.9`
![Screenshot 2024-12-08 at 2 20 15 PM](https://github.com/user-attachments/assets/2611696c-6f16-4f6d-a1be-b625d8840ab5)
