### ISSUE TITLE
Add peer dependencies for types generation

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#2442]
### Clear and concise description of the problem

vue router, vueuse, etc types aren't being bundled. 

### Suggested solution

Either we have to bundle types or add them as optional peer dependencies. Otherwise the typescript doesn't always work. @xvaara @dwgray  Which is better?

**Comment by dwgray** [comment]
I don't know offhand, but I did a bit of reading today which makes me lean towards optional peer dependency.
- Bundling an explicit version with BSVN seems pretty heavy-handed
- While we're not in a plugin/provider scenario (which is what most of the stuff I'm seeing on peer dependencies is about - e.g. https://nodejs.org/en/blog/npm/peer-dependencies/), it seems like that's a reasonable proxy for our case.
- FWIW: Copilot suggested peerDependencies in this case :-)
