### ISSUE TITLE
Nuxt BLink `to` navigation is full reloading page

### ISSUE THREAD

**Issue by VividLemon** [bootstrap-vue-next/bootstrap-vue-next#2445]
### Describe the bug

Nuxt BLink `to` navigation is full reloading page

```html
  <BLink to="/about"> Click me </BLink>
```

### Reproduction

ab

### Used Package Manager

pnpm

**Comment by darthf1** [comment]
`0.26.10` is not affected. So I guess its https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2438?

**Comment by darthf1** [comment]
Is it possible this is not fully resolved? I updated to `0.26.14` but the reloading was still happening for me. Let me know what information you need from me to debug. I'm not sure if page reloading is producible on stackblitz?

**Comment by ptdev** [comment]
Hi,

For us `BNavItem :to` and `BDropdownItem :to` are also doing full page loads with latest `0.26.14` 😕

**Comment by VividLemon** [comment]
> Hi,
> 
> For us `BNavItem :to` and `BDropdownItem :to` are also doing full page loads with latest `0.26.14` 😕
> 
> On our case, adding `"@bootstrap-vue-next/nuxt": "0.26.8"` to our resolutions/overrides seems to solve it. Issue apparently starts with `0.26.9`



> Is it possible this is not fully resolved? I updated to `0.26.14` but the full reloading was still happening for me. Let me know what information you need from me to debug. I'm not sure if page reloading is producible on stackblitz?

```html
      <BRow>
        <BCol>
          <BLink
            :to="{ path: '/about' }"
            prefetched-class="link-underline-danger"
            variant="info"
          >
            About with prefetch underline class
          </BLink>
        </BCol>
      </BRow>
      <BRow>
      <BCol>
        Nav items
        <BNavItem :to="{path: '/about'}">About</BNavItem>
        <BNavItem to="/">Home</BNavItem>
      </BCol></BRow>
      <BRow>
        <BCol>
          dropdown
          <BDropdown>
            <BDropdownItem to="/">Home</BDropdownItem>
            <BDropdownItem to="/about">About</BDropdownItem>
          </BDropdown>
        </BCol>
      </BRow>
```

All of these examples are working for me on the nuxt playground. Make a reproduction if you manage to find something more concrete please

**Comment by ptdev** [comment]
Hey,

Sorry for not posting the repro earlier, here it is now:

https://stackblitz.com/edit/nuxt-starter-mou6rk?file=package.json,app.vue

Thanks for checking it out :+1:

**Comment by VividLemon** [comment]
It worked on my machine ™️ 

https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2465
