### ISSUE TITLE
Floating Input Group is broken

### ISSUE THREAD

**Issue by memen45** [bootstrap-vue-next/bootstrap-vue-next#2452]
### Describe the bug

The floating labels for input groups is broken (used to work). 

Broken example: https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-group.html#floating-labels

Working example from the original bootstrap: https://getbootstrap.com/docs/5.3/forms/floating-labels/

Any idea why it is broken and how it can be fixed?

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-group.html#floating-labels

### Used Package Manager

pnpm

**Comment by ptdev** [comment]
Hi,

Not sure if it's the same issue but it's probably related.

We're getting some console errors as well hinting at some issue with input-group.

See the following error:

<img width="880" alt="Screenshot 2024-12-13 at 10 50 37" src="https://github.com/user-attachments/assets/3ae033e0-ecda-42b9-947f-ae743d656085" />

It appears as there is some issue trying to load BFormInput. This happens even after clearing node_modules, lock files etc and installing all from scratch.
