### ISSUE TITLE
Toasts only work in script setup mode

### ISSUE THREAD

**Issue by autoantwort** [bootstrap-vue-next/bootstrap-vue-next#2453]
### Describe the bug

I use the options api in my project and not the "new" composition api. It seems that there toasts does not work anymore. 

### Reproduction

https://stackblitz.com/edit/github-9wwkztyv?file=src%2FApp.vue

### Used Package Manager

npm

**Comment by VividLemon** [comment]
That's not valid syntax for options api

```html
<script lang="ts">
import { useToastController } from 'bootstrap-vue-next';

export default {
  setup() {
    const { show } = useToastController();
    return {show}
  }
};
</script>
```

**Comment by quantumdot** [comment]
Sorry to reopen, but I have a use case for showing toasts outside of a component. This was previously possible with `bootstrap-vue` but now seems impossible with `bootsrap-vue-next`.

In my case, an app with electron, vue, and bootstrap-vue-next, a user can select a file to be opened, and I want to show a toast with a status message to let the user know the app is working on their request. The request to open a file may not come from a component; it could possibly come from an IPC message. Therefore, the load file function is located outside of a component, in more of a command repository pattern.

This was previously possible with  `bootstrap-vue`:
```
app.$bvToast.toast(body, {
    id: 'loading-toast',
    title: 'Loading Data',
    variant: 'info',
    toaster: 'b-toaster-bottom-right',
});
```

But now with `bootsrap-vue-next` an error is thrown when trying to create the toast:
```
const {create} = useToastController()
create({
    id: 'loading-toast',
    title: 'Loading Data',
    variant: 'info',
    isStatus: true,
    body: "Loading data, please wait...",
});
```
```
> [Vue warn]: inject() can only be used inside setup() or functional components.
> Uncaught TypeError: Cannot read properties of undefined (reading 'create')
```

**Comment by MorningLightMountain713** [comment]
+1

**Comment by VividLemon** [comment]
> Sorry to reopen, but I have a use case for showing toasts outside of a component. This was previously possible with `bootstrap-vue` but now seems impossible with `bootsrap-vue-next`.
> 
> In my case, an app with electron, vue, and bootstrap-vue-next, a user can select a file to be opened, and I want to show a toast with a status message to let the user know the app is working on their request. The request to open a file may not come from a component; it could possibly come from an IPC message. Therefore, the load file function is located outside of a component, in more of a command repository pattern.
> 
> This was previously possible with `bootstrap-vue`:
> 
> ```
> app.$bvToast.toast(body, {
>     id: 'loading-toast',
>     title: 'Loading Data',
>     variant: 'info',
>     toaster: 'b-toaster-bottom-right',
> });
> ```
> 
> But now with `bootsrap-vue-next` an error is thrown when trying to create the toast:
> 
> ```
> const {create} = useToastController()
> create({
>     id: 'loading-toast',
>     title: 'Loading Data',
>     variant: 'info',
>     isStatus: true,
>     body: "Loading data, please wait...",
> });
> ```
> 
> ```
> > [Vue warn]: inject() can only be used inside setup() or functional components.
> > Uncaught TypeError: Cannot read properties of undefined (reading 'create')
> ```

You would need to pass the message to a component to have the component handle it. Perhaps you could find another way, but this is simply a Vue limitation.
