### ISSUE TITLE
Warning when using "to" attribute and v-b-tooltip directive for b-button

### ISSUE THREAD

**Issue by tghkuma** [bootstrap-vue-next/bootstrap-vue-next#295]
```
    :
    <b-button
        v-b-tooltip
        title="user"
        to="/user"
    >test</b-button>
    :
```

JS Console
```
[Vue warn]: Runtime directive used on component with non-element root node. The directives will not function as intended. 
  at <RouterLink key=0 to="/user" href="/user"  ... > 
  at <BLink class="btn btn-secondary" aria-disabled="false" aria-pressed=null  ... > 
  at <BButton title="user" to="/user" > 
  at <Dashboard onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: Proxy, <handler>: {…} }
 > key="/dashboard" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <App> 
  at <NuxtRoot>
  ```

**Comment by tghkuma** [comment]
It was a problem of b-link of child component of b-button

The tooltip is not displayed in b-link.
It is displayed as router-link.

```
    <b-link
        v-b-tooltip
        title="user"
        to="/user"
    >test</b-link>
```

JS Console
```
[Vue warn]: Runtime directive used on component with non-element root node. The directives will not function as intended. 
  at <RouterLink key=0 to="/user" href="/user"  ... > 
  at <BLink title="user" to="/user" > 
  at <Dashboard onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/dashboard" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <App> 
  at <NuxtRoot>
```

**Comment by xvaara** [comment]
@VividLemon for this to work we'd need to wrap BLink in a span. Directives aren't supported on multiroot components / fragments. Should we have a tooltip booleanis on the BLink to have a tooltip on it based on title value?

**Comment by VividLemon** [comment]
> @VividLemon for this to work we'd need to wrap BLink in a span. Directives aren't supported on multiroot components / fragments. Should we have a tooltip booleanis on the BLink to have a tooltip on it based on title value?

What purpose does blink have to require multiple root nodes? Could it simply not be refactored to require one node? From my looking briefly at the component, I believe it could be simplified

**Comment by phlegx** [comment]
Hi! I get the same warning using `v-b-toggle` with `b-link`.

**Comment by VividLemon** [comment]
Wrapping any item in a div or span will solve the issue temporarily until I can get a better solution -- I will likely be able to find a solution, but the alternative is that it's "permanent" (very unlikely)
