### ISSUE TITLE
b-table #head(), #cell()

### ISSUE THREAD

**Issue by KOVex13** [bootstrap-vue-next/bootstrap-vue-next#375]
Default fall-back scoped slot 'head()' or 'foot()' to format any header or footer cells dont work. And also cell().
p.s. without param - field key.

**Comment by cmora-pe** [comment]
I backup this request. As stated in the original b-table docs, ..."You can use the default fall-back scoped slot 'cell()' to format any cells that do not have an explicit scoped slot provided."
[docs](https://bootstrap-vue.org/docs/components/table#custom-data-rendering)

In the same way, head() and foot() does the generic for footers and headers: "You can use a default fall-back scoped slot 'head()' or 'foot()' to format any header or footer cells that do not have an explicit scoped slot provided."
[docs](https://bootstrap-vue.org/docs/components/table#header-and-footer-custom-rendering-via-scoped-slots)

IMHO, it's just a matter of adding a couple of lines to BTable.vue. In the original code, the following changes may do the work :

line 77:
```
            const slotName = `head(${field.key})`
            let thContent = field.label
            if (slots[slotName]) {
              thContent = slots[slotName]?.({
                label: field.label,
              })
            } else if (slots['head()']) {
              thContent = slots['head()']?.({
                label: field.label,
              })
            } 
```
or, as an improvement for the callback, also add the full field description in the slot call:

```
            const slotName = `head(${field.key})`
            let thContent = field.label
            if (slots[slotName]) {
              thContent = slots[slotName]?.({
                label: field.label,
                field: field,
              })
            } else if (slots['head()']) {
              thContent = slots['head()']?.({
                label: field.label,
                field: field,
              })
            } 
```

The footer stuff is more of the same

**Comment by carlos-mora** [comment]
ALternative change:
```
            let slotName = `head(${field.key})`
            let thContent = field.label
            if (!slots[slotName]) {
              slotName = 'head()'
            }

            if (slots[slotName]) {
              thContent = slots[slotName]?.({
                label: field.label,
                // this ones to fullfill original bootstrapVue slot specs
                column: field.key,
                field: field,
              })
            }
```

**Comment by VividLemon** [comment]
Pretty sure this is fixed
