### ISSUE TITLE
BTable scoped slots not matching

### ISSUE THREAD

**Issue by carlos-mora** [bootstrap-vue-next/bootstrap-vue-next#391]
The header slot only receives the 'label' attribute of the field, missing all the rest. I confirmed that reading the component code.
the ideal situation is to have the same scope BootstrapVue has, [acording to the docs](https://bootstrap-vue.org/docs/components/table#comp-ref-b-table-slots).
<html>
<body>

Property | Type | Description
-- | -- | --
clearSelected | Function | Unselect all rows (applicable if the table is in selectable mode)
column | String | The field's key value
field | Object | The field's normalized definition object (from the fields prop)
isFoot | Boolean | Will be true if the slot is being rendered in the table footer
label | String | The field's label value
selectAllRows | Function | Select all rows (applicable if the table is in selectable mode)

</body>
</html>
Obviously the selectable related properties are irrelevant as far as we don't implement that.

**Comment by graemedewe** [comment]
I'm also having this issue, I had to build my own replacement `<b-table>` component to be able to use `<template #head(name)="{field}">` is there a plan to add it? I see a few issues have been raised regarding it with no work around

**Comment by VividLemon** [comment]
If you've had time to build a replacement, why not make a PR to fix it :thinking:

**Comment by graemedewe** [comment]
> If you've had time to build a replacement, why not make a PR to fix it 🤔

I can do I wasn't sure what the plan was as there were a few issue threads on the matter, I'm away for a week I can look to do that on my return

**Comment by mbutricodeloitte** [comment]
Hi, has this issue been resolved?
it appears to me that the scoped slots are still not working.

Thank you very much

**Comment by VividLemon** [comment]
This seems like it's been fixed but if there is something missing, open a new ticket with more specificity
