### ISSUE TITLE
Toast usage clarification

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue-next/bootstrap-vue-next#563]
**What you are trying to do**
Showing a close button on a toast having set only `body`, similar to https://getbootstrap.com/docs/5.2/components/toasts/#custom-content

**What you have already tried**
```
toast.show({ body: msg }, {pos: 'bottom-center'}) // docs say close button should show by default
toast.show({ body: msg, noCloseButton: false }, {pos: 'bottom-center'}) // docs mention `no-close-button`, but that's not a valid object property? Source code has `noCloseButton`
toast.show({ body: msg }, {pos: 'bottom-center', noCloseButton: false}) // not clear where Component reference -> properties should be passed, first or second param? Or on `b-container` ?
```
https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html#toasts-on-demand

Thanks

**Comment by aceofwings** [comment]
have to look into this.

**Comment by VividLemon** [comment]
The docs referenced appear to be for the BToast/BToast.vue component, while the style appears to be using the BToast/plugin.ts `useToast`. At this moment, I don't know how to fix

**Comment by mariusa** [comment]
Bump as toasts don't work anymore after
https://github.com/cdmoro/bootstrap-vue-3/commit/c91801dee1e9264588d88d8998288d13b3a64402
@VividLemon 

The docs still explain the old way of using toasts; "Show toast" doesn't work anymore
https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html#toasts-on-demand

Even playgroup still has the old way:
https://github.com/cdmoro/bootstrap-vue-3/blob/main/apps/playground/src/App.vue
`<b-container id="container" ref="container" :toast="{root: true}" class="mt-4" fluid="sm">`

**Comment by VividLemon** [comment]
Ngl I didn't think that stuff on the container even worked so I removed it.

**Comment by mariusa** [comment]
They did work...

Would you please add that back and make a new release?

**Comment by VividLemon** [comment]
> They did work...
> 
> Would you please add that back and make a new release?

https://github.com/cdmoro/bootstrap-vue-3/pull/806

**Comment by mariusa** [comment]
Thanks, it's working again!

**Comment by xmatthias** [comment]
is the new release not available on the documentation, or is there something else broken with toasts?

trying the [toasts doc page](https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html#variants) doesn't render ANY toast...

**Comment by VividLemon** [comment]
> is the new release not available on the documentation, or is there something else broken with toasts?
> 
> trying the [toasts doc page](https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html#variants) doesn't render ANY toast...

Toast broken

**Comment by batmanhit** [comment]
Toast is still not working with `useToast` and is there any expectations on fixing this?

**Comment by aceofwings** [comment]
Did a quick PR simplifying the toast functionality. With server side rendering users were reporting errors with the injection key return an undefined controller. The toast functionality should be up and running. Tests to come in the next few days.
