### ISSUE TITLE
Input value not updated reactively 

### ISSUE THREAD

**Issue by RuBaWa** [bootstrap-vue-next/bootstrap-vue-next#652]
I`'ve build a input formatter for mac adresses with b-form-input. Therefore i use a wrapper component which converts input, emit result to a parent und updates the input by prop value, recived from the parent. 

I know, i can do the same thing with "formatter", by i also need it for other things, so generally it should work.

The input value is not updated by v-model, if i update it with computed getter/setter. The value is passed to the input component, but the visible value of the input is not updated.

Here i build up an example, but with fake props:
https://codesandbox.io/s/bootstrap-vue-3-input-format-by-v-model-iqbxqq

I expect, that the value is reactively passed down to the input.

**Environment (please complete the following information):**
 - bootstrap-vue-3: 0.3.2

**Comment by VividLemon** [comment]
So, the issue is not that both props are getting the same value, but the value **inside** the input field is not updating?
![image](https://user-images.githubusercontent.com/31498096/189673705-ccacd2fc-e23d-40f3-9c11-e76ff758c00d.png)

**Comment by RuBaWa** [comment]
Yes, its only for demonstration, that in real example events are triggered correctly and props get the right value. Only the input field value is not updated.

With formatter prop everything is working fine. I've recently migrated from bootstrap-vue and transfer all logic to new components. With old framework everything works like exspected. Maybe with new "formatter" prop behavior have changed?

**Comment by VividLemon** [comment]
You said that you didn't want to user the formatter prop here, so I'm not sure what you are looking for with 
>Maybe with new "formatter" prop behavior have changed?

This issue is a bit complicated. The logic is pulled into a composable, which abstracts some things. It's going to take a bit of time to fully figure out.

**Comment by RuBaWa** [comment]
I can use formatter, since i get any edge cases. But it would be nice, if reactivity at form values works as exspected.

Thank you for your great work.

**Comment by VividLemon** [comment]
Fixed 0.15
