### ISSUE TITLE
BTable emptyFilteredText not implemented

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#664]
BTable is now near to be usable for production!!! Good job!

what is missing now is ```empty``` slot and "old" props to define the default empty slot like: 
```empty-filtered-text```, ```empty-text```, ```empty-filtered-html``` and ```empty-html```

**Comment by devhus** [comment]
I've left them out since never needed to use them. However, I will work on it soon, Thanks for sharing the information.

**Comment by makroxyz** [comment]
> It was added in this PR #672, I did not add `empty-html`, or`empty-filtered-html` props because there is no real benefit from it. I might be mistaken about these props since i don't really know what they are for.

I agree... with ```empty``` slot ```empty-html``` or ```empty-filtered-html``` probably could be dropped.
Anyway in these props you can write custom html for empty table (no data) and empty filtered table with (no data after filter applying).
They are the same as ```empty-text``` and ```empty-filtered-text``` but you can set some HTML instead plain text.

**Comment by devhus** [comment]
> > It was added in this PR #672, I did not add `empty-html`, or`empty-filtered-html` props because there is no real benefit from it. I might be mistaken about these props since i don't really know what they are for.
> 
> I agree... with `empty` slot `empty-html` or `empty-filtered-html` probably could be dropped. Anyway in these props you can write custom html for empty table (no data) and empty filtered table with (no data after filter applying). They are the same as `empty-text` and `empty-filtered-text` but you can set some HTML instead plain text.

I see, sounds like useless props since you can write the HTML in the slot anyways
