### ISSUE TITLE
BTable api-url property and items using provider function

### ISSUE THREAD

**Issue by makroxyz** [bootstrap-vue-next/bootstrap-vue-next#673]
The "old" bootstrap-vue BTable has also this feature [provider function](https://bootstrap-vue.org/docs/components/table#using-items-provider-functions).

I think it should be implemented if possibile. In this case also busy property should be a v-model.

**Comment by Kyriakos-Michael** [comment]
Agree, that the provider function is extremely helpful, especially for a Pagination implementation from APIs.

**Comment by devhus** [comment]
@makroxyz  @Kyriakos-Michael hopefully that covers it https://github.com/cdmoro/bootstrap-vue-3/pull/678. Please, give it a try, and let me know if there is anything else needed

**Comment by mediaessenz** [comment]
I tried the provided example in #678, but it doesn't seem to work properly.
If the items object is an empty array at the beginning (which is mostly the case if using a provider function, the table output stays empty, even if the provider function returns an array of objects. It doesn't matter if I return a promise, or the array directly.
