### ISSUE TITLE
b-breadcrumb error

### ISSUE THREAD

**Issue by MyungGyu** [bootstrap-vue-next/bootstrap-vue-next#745]
**Describe the bug**

The `key` for `v-for` should not be an index.

**To Reproduce**

**Expected behavior**
`item` instead of `index`

**Screenshots**
![image](https://user-images.githubusercontent.com/34330511/195255959-7688a104-13ac-43d0-830b-b24fe0f2fdd8.png)

**Environment (please complete the following information):**
 - OS: Window10

**Additional context**

**Comment by VividLemon** [comment]
And what's the problem

**Comment by MyungGyu** [comment]
> And what's the problem

The href is not changed because the DOM is not updated.

**Comment by VividLemon** [comment]
I don't think this is the issue. I suggest making a reproduction.

**Comment by MyungGyu** [comment]
All right. Thank you.

**Comment by MyungGyu** [comment]
> > All right. Thank you.
> 
> I'm curious on why you decided to close the issue? A reproduction would be very helpful to narrow down the issue. To figure out if it is indeed a :key issue, or something else. A reproduction means I can meaningfully write a test, and ensure that the bug never resurfaces.

sorry.. I'm not good at English. I didn't know the meaning of `reproduction`.

### my code

```vue
<template>
  <BBreadcrumb :items="computedBreadcrumbItems"></BBreadcrumb>
</template>

<script setup>
... imports

const route = useRoute();
const computedBreadcrumbItems = computed(() => {
  return route
    .matched
    .filter((match) => match.name)
    .map(({ name: text, path: to }) => ({ text, to }))
});
</script>
```

If the route of the route is changed, only `text` is changed and `href` is not changed.

So I tried two things.

first
In BBreadcrumbs.vue(bootstrap-vue-3)
```vue
<!-- :key="i" => :key="item"  -->
<b-breadcrumb-item v-for="(item, i) in breadcrumbItemObjects" :key="item" v-bind="item">
  {{ item.text }}
</b-breadcrumb-item>
```

second
In My Code
```vue
<!-- Use key -->
<BBreadcrumb :items="computedBreadcrumbItems" :key="computedBreadcrumbItems"></BBreadcrumb>
```

Was it the answer to the reproduction? Thank you.

**Comment by MyungGyu** [comment]
I am sending you the attached `code sandbox` because the `reproduction` I gave you is not enough.

https://codesandbox.io/s/thirsty-chandrasekhar-33mktq?file=/src/App.vue

### Try the following procedure.
#### step 1.
![image](https://user-images.githubusercontent.com/34330511/195738443-d03d0f51-90f0-47e2-8907-1ea617eadcbe.png)

#### step 2.
![image](https://user-images.githubusercontent.com/34330511/195738639-c8955a06-e856-4867-8dc2-ee6a8b25f5ab.png)

Click 'About First'.

Check Breadcrumb Trail(href => /about)

#### step 3.
![image](https://user-images.githubusercontent.com/34330511/195738743-1e8ad017-6806-446d-a062-046620992cd2.png)

Click 'Home Second'

Check Breadcrumb Trail(href => /about)  => expected behavior : /home

**Comment by VividLemon** [comment]
Thank you, this is very odd behavior. I'll try to find a solution tomorrow.

**Comment by MyungGyu** [comment]
Thank you!

**Comment by VividLemon** [comment]
I'll need to revisit this in a future release. From my dev environment, using my uncommitted changes, everything is working as intended. So, it's possible I had already fixed this unintentionally.
