### ISSUE TITLE
const toast = useToast() breaks my app

### ISSUE THREAD

**Issue by dagnelies** [bootstrap-vue-next/bootstrap-vue-next#749]
These two lines break my app.

 ```ts
import {useToast} from 'bootstrap-vue-3'
const toast = useToast()
```

*Just by including it, the whole view is not even rendered anymore!* ...and I did not even trigger a toast yet. It took me quite a while to figure out it was the culprit.

Here is cryptic error in the console:
```
TypeError: Cannot read properties of undefined (reading 'getOrCreateViewModel')
    at Ga (bootstrap-vue-3.js?v=637cd6a0:7597:21)
```

I don't know why the source maps are not activated in dev mode, I'll look into it later.

Edit: looks similar to the second part of #283

**Comment by VividLemon** [comment]
This is like the fifth toast related topic this week. Getting kind of tired stating that I'm working on it lmao. 

I thought about enabling sourcemaps. 🤔 But I don't know if the effect would cascade down to the end user.

**Comment by dagnelies** [comment]
PS: demo is broken too: https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html

**Comment by dagnelies** [comment]
It would be nice to disable the "stale bot" and keep bugs open until resolved.

**Comment by dagnelies** [comment]
thanks

**Comment by forchel** [comment]
I've got the same problem. If I use `useToast()` within a component, it works as expected. But if I use `useToast()` from within another function, the App is broken with the following exception:

[plugin:vite:import-analysis] Missing "./dist/components/BToast/plugin" specifier in "bootstrap-vue-next" package
