### ISSUE TITLE
b-table provider not working for page two

### ISSUE THREAD

**Issue by leoralph** [bootstrap-vue-next/bootstrap-vue-next#855]
**Describe the bug**
When a b-table page changes, the table doesn't render anything, even if the provider is returning correct data

**To Reproduce**
1. Create a b-table with a provider, and pagination.
2. The first page will load normally, but every other page wont load
**Expected behavior**

**Screenshots**
![First page, works normally](https://user-images.githubusercontent.com/86016347/209407455-faa01c6b-c2a8-48af-aa6b-b021d6074a51.png)
First page, works normally

![image](https://user-images.githubusercontent.com/86016347/209407523-bbe12531-e3f2-45dc-8c42-ce308629c3d0.png)
Second page, nothing shows

```vue
<template>
    <b-table :fields="['id']" :provider="myProvider" :current-page="currentPage" :per-page="perPage"></b-table>
    <b-pagination :current-page="currentPage" :total-rows="totalRows" v-model="currentPage"></b-pagination>
</template>

<script>
export default {
    data() {
        return {
            currentPage: 1,
            perPage: 10,
            totalRows: 100,
        };
    },
    methods: {
        myProvider(context) {
            let values = [];

            for (let i = 0; i < context.perPage; i++) {
                values.push({ id: i });
            }

            return values;
        },
    },
};
</script>

```
Example code, generating items as the page changes

**Environment (please complete the following information):**
 - OS: Ubuntu-22.04 (WSL2)
 - Version 0.4.15

**Comment by VividLemon** [comment]
Btable will be fixed eventually. There are about 4-5 components waiting to be fixed up first. BTable will see a major rewrite to make it clean, more performant, and most likely more features. I'd like to get it the ability to sort by multiple columns... Anyways, your issue here is not being forgotten.
