### ISSUE TITLE
form-input type="number" acting strange

### ISSUE THREAD

**Issue by xmatthias** [bootstrap-vue-next/bootstrap-vue-next#933]
**Describe the bug.**
When using a number input with tied v-model, the input cursor suddenly jumps all the way to the left when the last decimal is deleted - causing unwanted / accidental input in almost all cases.

**To Reproduce.** Steps to reproduce the behavior:

```
<template>
  <b-container>
    <b-row>
      <b-form-input id="price-input" v-model="numberInput" type="number" />
    </b-row>
  </b-container>
</template>

<script setup lang="ts">
import {ref} from 'vue'
const numberInput = ref(356.78)
</script>

```

**Expected behavior.** 
The cursor remains where it was - allowing to either delete the decimal point manually, or to insert new decimals.

**Screenshots.** 

![Peek 2023-02-15 20-21](https://user-images.githubusercontent.com/5024695/219131182-f5284253-c297-4521-b65f-2449b3f94f58.gif)

**Environment (please complete the following information):**

- OS: [e.g. Windows 11, Linux Mint] linux / chromium 
- Package Version: [e.g. 0.2.6] 3c5c024555f35064373ea44a017ffb51fa41ea7e (running from main branch - but 
- Npm/Yarn/Pnpm Version: [e.g. pnpm@7.18.2]

**Comment by VividLemon** [comment]
Very weird

**Comment by VividLemon** [comment]
Seems like its been fixed sometime previously

**Comment by xmatthias** [comment]
Interesting indeed, i did re-validate this only about a month ago and it was still valid there - so it must've been one of the very recent changes

it's fixed though - that's all that matters :+1:
