### ISSUE TITLE
<b-table> stacked prop does not work.

### ISSUE THREAD

**Issue by sky-code** [bootstrap-vue-next/bootstrap-vue-next#935]
Setting stacked prop on <b-table> to any value has zero effect on layout/behavior, property just ignored/not implemented, is there any plans to support this feature soon?

Environment (please complete the following information):
"bootstrap-vue-next": "0.7.3",
"nuxt": "3.2.2"

**Comment by sky-code** [comment]
Looks like `bootstrap-vue-next/src/styles/styles.scss` is not imported when bootstrap-vue-next installed like described in this guide https://bootstrap-vue.github.io/bootstrap-vue-next/getting-started/#installation-nuxt-js-3

**Comment by sky-code** [comment]
BTable not giving `data-label` attribute any value when `stacked` property set, because of this correct styles not applied.
https://github.com/bootstrap-vue/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/components/BTable/BTable.vue#L95

**Comment by VividLemon** [comment]
I have a few things to do first before I can overhaul the table. I have to review a large PR, and do a few other things after that. The table is a large component, and will likely be one of the last to be overhauled

**Comment by VividLemon** [comment]
Working in latest versions
