### ISSUE TITLE
BTable fields don't work with nested objects for keys

### ISSUE THREAD

**Issue by NNeto** [bootstrap-vue-next/bootstrap-vue-next#957]
**Describe the bug.**
In BootstrapVue we can do something like this:
```
fields: [
  { key: "user.name", label: "User", sortable: true },
  { key: "user.role", label: "Role", sortable: true },
],
```
with items like this:
```
items: [
  { id: 0, title: "AAAA", qty: "0", user: { name: "John", role: "admin" } },
]
```
But this doesn't work in BootstrapVueNext. The column becomes empty.

**To Reproduce.**

1. Put an attribute of a nested object of items as key in fields
2. The column in the table will be empty

Here is a codesandbox with the BootstrapVue and working example:
https://codesandbox.io/s/c5858k

Here is another codesandbox, with the same example but failing field in BootstrapVueNext:
https://codesandbox.io/s/5650c9

**Expected behavior.**
The column should be filled in with the value of the path specified at the key in the fields.

**Environment:**

- OS: Fedora Linux 35
- Package Version: 0.7.3
- Npm/Yarn/Pnpm Version: pnpm@7.28.0

**Comment by xvaara** [comment]
For now you can flatten the object. For your example this would be fitting: https://www.30secondsofcode.org/js/s/flatten-object

**Comment by makroxyz** [comment]
This is an important feature, hope it will be implemented soon

**Comment by VividLemon** [comment]
Seems to be working now
