### ISSUE TITLE
BTable items loosing reactivity

### ISSUE THREAD

**Issue by NNeto** [bootstrap-vue-next/bootstrap-vue-next#958]
**Describe the bug.**
Trying to manipulate the item data within the cell scoped slot has no effect on the objects passed to the `:items` prop, as it does in BootstrapVue.

**To Reproduce.**

Here is a codesandbox with an working example with BootstrapVue: https://codesandbox.io/s/xbqh3m

1. Click on the "+1" buttons or change the value on the select inputs
2. Check that the values change in the `pre` tag.

Here is a codesandbox with the same code but with BootstrapVueNext: https://codesandbox.io/s/q6n4h0

1. Click on the "+1" buttons or change the value on the select inputs
2. Check that the items value stays at `0` or `null`.

**Expected behavior.**
As in BootstrapVue, the values in the variable passed to the `:items` prop should react to the changes in the cell scoped slot.

**Environment:**

- OS: Fedora Linux 35
- Package Version: 0.7.3
- Npm/Yarn/Pnpm Version: pnpm@7.28.0

**Comment by NNeto** [comment]
> Sorting makes deepClone of the items and removes reactivity. with :sort-internal="false" the reactivity works. @VividLemon Should we remove cloning, or put skip-cloning prop to table? Removing might open it own can of worms.
> 
> for now you can use a hacky way around this:
> 
> ```
> <button @click="items.find(i => i.id === data.item.id).qty++">+1</button>
> ```

Yeah, I'm using `@update:modelValue` in the case of the select input, but all of this are hacky and defeat the purpose of reactivity, while in BootstrapVue 2 it works beautifully.

**Comment by devhus** [comment]
Will be improved in https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1262 PR

**Comment by VividLemon** [comment]
I feel like this behavior is weird, I don't think mutation of the data should be allowed (though there wouldn't be an alternative, so it's fine)... But regardless, it seems to be working
