### ISSUE TITLE
BTable does not provide refresh mechanism as stated in the documentation 

### ISSUE THREAD

**Issue by diyan-gochev-at-ft-dot-com** [bootstrap-vue-next/bootstrap-vue-next#960]
The current BTable implementation does not provide refresh mechanism. 

The documentation states: 
`Force refreshing of table data
You may also trigger the refresh of the provider function by emitting the event refresh::table on $root with the single argument being the id of your b-table. You must have a unique ID on your table for this to work.

this.$root.$emit('bv::refresh::table', 'my-table')
Or by calling the refresh() method on the table reference

<div>
  <b-table ref="table" ... ></b-table>
</div>
this.$refs.table.refresh()`

But does not work.

**Comment by diyan-gochev-at-ft-dot-com** [comment]
One solution would be to expose callItemsProvider method

**Comment by carlos-mora** [comment]
The obvious purpose of callItemsProvider is that, call the Provider to fetch data no matter what the reason is, and we need a way of telling the component the data is no longer valid, so there should be a method called invalidateData() or sth like that, that, eventually, would trigger callItemsProvider or whatever the context demands.
Single concern. my 2 cts.

**Comment by diyan-gochev-at-ft-dot-com** [comment]
> The obvious purpose of callItemsProvider is that, call the Provider to fetch data no matter what the reason is, and we need a way of telling the component the data is no longer valid, so there should be a method called invalidateData() or sth like that, that, eventually, would trigger callItemsProvider or whatever the context demands. Single concern. my 2 cts.

Totally agree. @VividLemon for us, this is a show-stopper (critical).

**Comment by VividLemon** [comment]
Use the exposed 'refresh' method. This is staying open as I will revisit this during the BTable overhaul.

**Comment by VividLemon** [comment]
> Use the exposed 'refresh' method

> bv::refresh::table

There is no such event structure in Vue 3. Use the exposed method.
