### ISSUE TITLE
BTableProviderContext isn't exported by the root import

### ISSUE THREAD

**Issue by dpash** [bootstrap-vue-next/bootstrap-vue-next#967]
If you want to use `BTableProviderContext` you need to import directly from the relevant file in the `dist` directory as it's not included in `dist/types/exports/index.d.ts` :

    import {BTableProviderContext} from "bootstrap-vue-next/src/types/components";

However, due to the use of `exports` in `package.json`, vite complains with:

    ✘ [ERROR] [plugin vite:dep-scan] Missing "./dist/types/components" specifier in "bootstrap-vue-next" package
    
        script:/var/www/html/resources/js/components/report_requests/ReportRequestList.vue?id=0:86:7:
          86 │ import "bootstrap-vue-next/dist/types/components"
             ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     
      This error came from the "onResolve" callback registered here:
    
        node_modules/esbuild/lib/main.js:1287:20:
          1287 │       let promise = setup({

**Comment by VividLemon** [comment]
fixed 0.15
