### ISSUE TITLE
[0.8.6] B-TABLE: Attr "data-label" on <TD> missing

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#993]
hi,

i'm using version 0.7.3

the "data label" attribute is missing from the td tag in the b-table cells. it would be great if that were available again, because then you can see the column names again in the stacked mode of the table. is important for mobile phones and tablets. Adding attributes with tdAttr does not work because data-label is not a member of the tdAttr interface. Furthermore, the attributes are missing from the td-tag: "aria-colindex" and role="cell"

- OS: [e.g. Windows 10]
- Package Version: [0.7.3]
- Npm Version: [npm@9.2.0]

**Comment by VividLemon** [comment]
https://github.com/bootstrap-vue/bootstrap-vue-next/issues/981#issue-1642028049

**Comment by ndavenia** [comment]
waiting the fix a workaround is to put tdAttr: { "data-label": "the label" } inside each field of fields on b-table

**Comment by VividLemon** [comment]
The purpose of mentioning https://github.com/bootstrap-vue/bootstrap-vue-next/issues/993#issuecomment-1493326803 was to have conversations over to there as to not lose information.

**Comment by susanne99** [comment]
not yet solved

**Comment by VividLemon** [comment]
I don't understand what the data-label attribute is for. I can't see it mentioned on Bootstrap-vue, or getBootstrap.com. The tdAttr/thAttr has been changed to be any Record (in uncommitted versions atm)

So, I'm going to request that a reproduction is made while also marking it stale. If it stays stale for an extend period of time, I will remove it

**Comment by VividLemon** [comment]
Apparently it does something in stacked mode :thinking: That's weird. I also see that the BTd & BTh fields declare "stackedHeading", which adds it to the "data-label"... But given this, I'm not sure what the expected syntax is (beyond the `tdAttr: {'data-label': 'the label'}` fix)

**Comment by VividLemon** [comment]
Fixed in 0.15
