### ISSUE TITLE
Docs aren't working

### ISSUE THREAD

**Issue by eris-vn** [bootstrap-vue-next/bootstrap-vue-next#999]
![image](https://user-images.githubusercontent.com/69683870/229719876-23e68a93-0b8c-477a-8777-079020ba3611.png)

**Comment by akhi-ninja** [comment]
I do face same issue , is there any other documentation page available ?

**Comment by VividLemon** [comment]
Clone the repository then open the docs locally. I understand it's a hassle. The docs were built with Vuepress, and lately it's been having issues.

At this point I refuse to fix the problems with Vuepress, and have already started moving towards building them with Nuxt, considering the new availability under 0.8 (Though it was always planned to transition)

**Comment by jiwonman** [comment]
Where is that document located in the repository?

**Comment by VividLemon** [comment]
Run pnpm dev at the root and it will open all available projects. Otherwise `pnpm dev --filter docs` works as well

**Comment by GWillS163** [comment]
> ![image](https://user-images.githubusercontent.com/69683870/229719876-23e68a93-0b8c-477a-8777-079020ba3611.png)
> 

My project be affected two days too. is it has offline-version or github-version docs? 😭

**Comment by VividLemon** [comment]
> > ![image](https://user-images.githubusercontent.com/69683870/229719876-23e68a93-0b8c-477a-8777-079020ba3611.png)
> 
> My project be affected two days too. is there has offline-version or repo-version docs? 😭

https://github.com/bootstrap-vue/bootstrap-vue-next/issues/999#issuecomment-1496247870

**Comment by jaireth** [comment]
Seems I could view the docs directly here:
https://github.com/bootstrap-vue/bootstrap-vue-next/tree/main/apps/docs/docs/getting-started

Didn't have to clone anything.

**Comment by GWillS163** [comment]
> Seems I could view the docs directly here: https://github.com/bootstrap-vue/bootstrap-vue-next/tree/main/apps/docs/docs/getting-started
> 
> Didn't have to clone anything.

You, bro, you're my hreo! it's almost usefull for temporaliy!

**Comment by susanne99** [comment]
does anyone understand the problem. somehow i have a strange feeling sometimes.
in an emergency, restart the web server :)

**Comment by roman-1983** [comment]
Still not working :/

**Comment by IARI** [comment]
Is this issue very hard to fix?

**Comment by VividLemon** [comment]
> Is this issue very hard to fix?

There are multiple issues. Which are you referring to? 

This is my todo list, assuming anyone wants to fix some of the issues. Some of them I will need to do myself no matter what. If anyone wants to fix them, pick the easier ones.

[TODO.md](https://github.com/bootstrap-vue/bootstrap-vue-next/files/11413008/TODO.md)

**Comment by VividLemon** [comment]
Also if you're one of those weird programmers that use light mode, switch to dark
![image](https://user-images.githubusercontent.com/31498096/236639184-be713920-0cd0-4159-9c92-680c00a268f6.png)
![image](https://user-images.githubusercontent.com/31498096/236639186-edbac63b-a95c-4a88-a421-5ab9ce15f402.png)

**Comment by VividLemon** [comment]
The docs are working, but there are still some things to either fix or add, overall I'm going to close this because they _are working_
